### PR TITLE
Update FTLDNS from dev

### PR DESCRIPTION
**Pull request by PromoFaux**
Internal

### CODE REVIEW

**Comment by PromoFaux** [comment]
This can now be merged to `FTLDNS` as it was pending 68d7337 and a6e4b0f

**Comment by DL6ER** [comment]
I approve this PR via comment as, for some unknown reason, I cannot use any of GitHubs green buttons (except the comment button) at the moment.

Note that this depends on also merging https://github.com/pi-hole/AdminLTE/compare/FTLDNS...devel for adding front end support of the most recently merged LOCALDNSPORT PR. (yes, I also cannot open a new PR so I assume it is a problem with GitHub's frontend)

**Comment by DL6ER** [comment]
I approve this PR via comment as, for some unknown reason, I cannot use any of GitHubs green buttons (except the comment button) at the moment.

Note that this depends on also merging https://github.com/pi-hole/AdminLTE/compare/FTLDNS...devel for adding front end support of the most recently merged LOCALDNSPORT PR. (yes, I also cannot open a new PR so I assume it is a problem with GitHub's frontend)

**Comment by DL6ER** [comment]
I approve this PR via comment as, for some unknown reason, I cannot use any of GitHubs green buttons (except the comment button) at the moment.

Note that this depends on also merging https://github.com/pi-hole/AdminLTE/compare/FTLDNS...devel for adding front end support of the most recently merged LOCALDNSPORT PR. (yes, I also cannot open a new PR so I assume it is a problem with GitHub's frontend)

**Comment by DL6ER** [comment]
This PR depends on https://github.com/pi-hole/AdminLTE/pull/747 being merged at the same time (see also dependency on FTLDNS therein)

**Pull request merged**
