### PR TITLE
Change log flush time to 00:00

### PR DESCRIPTION
**Pull request by PromoFaux**
Rather than flush logs nightly at 23:58, do it at midnight. This will stop the weird little bit at the end of the graph.

@pi-hole/gravity

### CODE REVIEW

**Comment by PromoFaux** [comment]
Approved

**Comment by Mcat12** [comment]
Approved

**Comment by dschaper** [comment]
:shipit:

**Comment by dschaper** [comment]
Whiskey Tango? Why does it need PA again? Does PA not play well with GitHub requiring the branch to be updated? I guess we have to approve it and then wait until PA goes green, then update the branch. Hopefully that wont reset the 'purity' flag for PA...

**Comment by PromoFaux** [comment]
Didn't you do something in the yaml that meant it reset if there were new commits?

**Comment by PromoFaux** [comment]
https://github.com/pi-hole/pi-hole/blob/master/.pullapprove.yml#L4

**Comment by dschaper** [comment]
Yeah, but I assumed that it would be intelligent enough to catch that it was just an update and not a new commit. Guess it's not...

**Comment by PromoFaux** [comment]
@jacobsalmela @Mcat12 @brantje If one of you could approve this PR, that'd be great!

**Comment by PromoFaux** [comment]
Wait.
This is going to get messy
I'll close and re-pull, it needs an update again!

**Pull request closed without merging**
