### PR TITLE
Change comment to hash

### PR DESCRIPTION
**Pull request by dschaper**
Fixes #563.

Changes proposed in this pull request:

Modify comment indicator in dhcpcd.conf

@pi-hole/gravity

Change format of comment to hash/octothorpe to clearly delineate that it's a comment. Looks better than `:::` which causes confusion.

### CODE REVIEW

**Comment by dschaper** [comment]
@bitterypaul We can continue the comment issue discussion here, and we won't lose track of it.

**Comment by dschaper** [comment]
Approved

**Comment by Mcat12** [comment]
Approved

**Comment by dschaper** [comment]
No addition to changelog - file under misc bugfixes.

**Pull request merged**
