### PR TITLE
Updates lighttpd config to allow a persistent port change on IPv6

### PR DESCRIPTION
**Pull request by mtzfederico**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
It allows changing the web server port without it getting reset in updates

**How does this PR accomplish the above?:**
It moves where the external.conf file for lighttpd is included in lighttpd.conf

**What documentation changes (if any) are needed to support this PR?:**
To show how to change the web server port.
You need to add `server.port := <newPort>` to `/etc/lighttpd/external.conf`

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by PromoFaux** [comment]
Hi there, thanks for the submission.

Per the contribution guide, all pull requests must be made based on, and against the `development` branch:
 
image

Secondly, could you please explain how moving these lines further up in the file allows for the port to be specified in `external.conf`. ?

**Comment by mtzfederico** [comment]
Yes, It is mostly for ipv6 since in lighttpd.conf the ipv6 port is set to server.port before external.conf is imported, and external. conf is the preferred way to change the lighttpd settings since it doesn't reset on updates.


sorry, I forgot to make the merge request to the development branch (It's my first time contributing to an open-source project), should I modify the merge request?

**Comment by PromoFaux** [comment]
So, for IPv4, this change would not make a difference?

It's also worth noting that we are starting to actively develop v6.0 of Pi-hole, which will do away with `lighttpd` all together. As such, it's likely that the only v5.x releases any time soon will be for bug fixes. 

I wont close this just yet, rather I'll leave it to others to chime in

---

And congrats on making your first pull request! Took me [three attempts](https://github.com/pi-hole/pi-hole/pulls?page=13&q=is%3Apr+author%3Apromofaux) to get my first one merged, and now... here I am. So don't be too rejected if we don't accept this :)

**Comment by PromoFaux** [comment]
After a little internal discussion on this, I see how this works now. It seems that the `:=` (replace/overwrite earlier value) syntax is only supported since `lighttpd` `1.4.46`

Unfortunately on Debian/Raspbian Stretch the supported version of `lighttpd` is `1.4.45` - so not all users are able to benefit from it. 

However it is interesting to note that anyone that _does_ have `lighttpd >= 1.4.46` is able to use this _currently_ to overwrite the `server.port` for IPv4... So now I can see the value in your PR, being able to also set it for IPv6.

**Comment by janvonde** [comment]
Merging would be cool anyway. This would allow me to install Apache and use it as reverse proxy on my raspbian pi-hole system, too :)

**Review by PromoFaux — APPROVED** [review]

**Pull request merged**
