### PR TITLE
added sleep before gravity for slower hardware 

### PR DESCRIPTION
**Pull request by technicalpyro**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

_{5}_

---
_{attempt to sleep for 15s to allow dnsmasq to fully start before calling gravity 
use case is pi2B or lower with anything more than 900K domains}_

users with faster hardware will still be slept as im not sure how to code this on a per use case 

ALSO no clue why the hotfix is showing in this PR but if someone with the ability could delete that from it i would appreciate it 
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by dschaper** [comment]
We're actually debating this right now on how to handle the problem with `dnsmasq` and having this timing verified in a real use case scenario is very helpful. WaLLy was working on something similar so I'll ping him to check this out. @WaLLy3K 

Thanks! (And it's showing a merge conflict, looks like it's a difference in the echo style, we've moved from the older `:::` format to a new checkbox format. I'll tweak the code in the pull to resolve the conflict, but you'll need to pull that change in to your branch.)

**Comment by technicalpyro** [comment]
yeah i made some mistakes when i forked this morning to make the pull request in my experience if we wait 10-15s before calling gravity it allows dnsmasq to finish its startup unless something elaborate that checks the dnsmasq status before running gravity is coded i think this really is the most simple solution

**Comment by WaLLy3K** [comment]
While the issue that this attempts to resolve is a very valid problem, your proposed solution is a bit ham-fisted as it only affects a specific minority of users while creating a huge delay for others running default blocklists.

As Dan said, this is something I'm already attempting to resolve - via [this section of code](https://github.com/pi-hole/pi-hole/blob/tweak/gravity/gravity.sh#L71).

**Comment by DL6ER** [comment]
Will be resolved by #1631 in a more elegant way (users on fast hardware or with small blocking lists won't have to wait an extra 15 seconds)

**Pull request closed without merging**
