### PR TITLE
Malformed wildcard blocking doesn't crash awk.

### LINKED ISSUE #3173: Faulty regex causes issues with pihole -q and consumes all memory until it's killed
This has been [brought up at the v5.0 beta discourse forum](https://discourse.pi-hole.net/t/faulty-regex-consumes-all-memory-and-causes-issues-with-pihole-q/28710/20). Please see there for more details and screenshots.

Using a faulty regex like 

`(\.|^)*\.services\.generalmagic\.com`

causes issues when executing `pihole -q` resulting in dramatically memory increase until the init system kills the process. The output lists

`/opt/pihole/query.sh: line 37: 21500 Killed                  awk 'NR==FNR{regexps[$0];next}{for (r in regexps)if($0 ~ r)print r}' <(echo "${lists}") <(echo "${domain}") 2> /dev/null`

Background: There is no validation of regex by pihole that it will ever match a domain. 

Expected behavior: I don’t think pihole should have a full-grown regex validator (In terms of ‘This is what the regex means’) but maybe a simple syntax checker ('This is not a valid regex und will never match any domain.) - especially as a non-valid regex can break pihole’s scripts. Or pihole should be more robust against faulty regex.

### PR DESCRIPTION
**Pull request by dschaper**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**
Fixes #3173 

This allows for users to enter non-canonical values in the white/blacklist entry display. `*.host.domain.com` is valid to use as a wildcard type entry. 

**How does this PR accomplish the above?:**

Use bash regex in place of `awk` for matching. 

**What documentation changes (if any) are needed to support this PR?:**
None.

## _Please squash merge this. I didn't squash the commits as there are people on the branch and I did not want to break them._

### CODE REVIEW

**Comment by dschaper** [comment]
https://discourse.pi-hole.net/t/faulty-regex-consumes-all-memory-and-causes-issues-with-pihole-q/28710/103

Looks to be working as intended now.

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/faulty-regex-consumes-all-memory-and-causes-issues-with-pihole-q/28710/108

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-becomes-unresponsive-during-pihole-d-and-q/28152/32

**Comment by dschaper** [comment]
http://mywiki.wooledge.org/BashGuide/Patterns

>Bash uses the Extended Regular Expression (ERE) dialect.

I think `awk` was not chosen for a specific reason, it's what mmotti was comfortable with. He's reviewed these changes.

**Pull request merged**
