### PR TITLE
Simplify interaction between Chronometer and FTL

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

## 10

---

Use `nc` instead of `bash` builtin functions (which have proven to be problematic in certain situations). There is a number of automatic changes caused by my text editor (removed lonely spaces at line ends).

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by WaLLy3K** [comment]
Minimum viable code test:
```
#!/usr/bin/env bash
calc(){ awk "BEGIN {print $*}" 2> /dev/null; }

pihole-FTL-Old() {
  ftl_port=$(cat /var/run/pihole-FTL.port 2> /dev/null)
  if [[ -n "$ftl_port" ]]; then
    # Open connection to FTL
    exec 3<>"/dev/tcp/localhost/$ftl_port"

    # Test if connection is open
    if { "true" >&3; } 2> /dev/null; then
      # Send command to FTL
      echo -e ">$1" >&3

      # Read input
      read -r -t 1 LINE <&3
      until [[ ! $? ]] || [[ "$LINE" == *"EOM"* ]]; do
         echo "$LINE" >&1
         read -r -t 1 LINE <&3
      done

      # Close connection
      exec 3>&-
      exec 3<&-
   fi
  else
    echo "FTL offline"
  fi
}

pihole-FTL-New() {
  ftl_port=$(cat /var/run/pihole-FTL.port 2> /dev/null)
  if [[ -n "$ftl_port" ]]; then
    # Get data from FTL
    C=0
    readarray -t LINE <<< "$(echo ">$1" | nc -w 1 127.0.0.1 "${ftl_port}")"
    if [[ "${#LINE[@]}" -ge "1" && ! "${LINE[0]}" == "" ]]; then
      until [[ "${LINE[$C]}" == *"EOM"* || "${LINE[$C]}" == "" ]]; do
        echo "${LINE[$C]}"
        let C+=1
      done
    else
      echo -e "FTL offline"
    fi
  else
    echo -e "FTL offline"
  fi
}

run_start=$(date +%s.%N)
printf "Start: %.2fs\n" $(calc "$(date +%s.%N) - $run_start")
pihole-FTL-Old "stats"
printf "Runtime for old FTL code: %.2fs\n" $(calc "$(date +%s.%N) - $run_start")

run_start=$(date +%s.%N)
pihole-FTL-New "stats"
printf "Runtime for new FTL code: %.2fs\n" $(calc "$(date +%s.%N) - $run_start")
```

Output returns:
```
>stats output
Runtime for old FTL code: 0.02s
>stats output
Runtime for new FTL code: 2.03s
```

That's taking way too long to generate - are you seeing the same run times on your end?

**Comment by DL6ER** [comment]
```
pi@raspberrypi:~ $ time pihole-FTL-Old version
version v2.9.1-9-g60bf275
tag v2.9.1
branch development
date 2017-06-19 20:10:38 +0200

real	0m0.252s
user	0m0.000s
sys	0m0.000s

pi@raspberrypi:~ $ time pihole-FTL-New version
version v2.9.1-9-g60bf275
tag v2.9.1
branch development
date 2017-06-19 20:10:38 +0200

real	0m0.521s
user	0m0.000s
sys	0m0.010s
```

**Comment by DL6ER** [comment]
A more scientific approach: I ran the timing shown above 25 times for either of the two commands and computed the statistics. I see:

## New
Average: 0.28s +/- 0.04s
Max: 0.53s
Min: 0.24s

## Old
Average: 0.31s +/- 0.10s
Max: 0.74s
Min: 0.23s

**Comment by WaLLy3K** [comment]
I'm just not seeing that kind of swiftness when I try and run the proposed code, which is a bit confusing:

```
#!/usr/bin/env bash
calc(){ awk "BEGIN {print $*}" 2> /dev/null; }

ftlFunc() {
  ftl_port=$(cat /var/run/pihole-FTL.port 2> /dev/null)
  if [[ -n "$ftl_port" ]]; then
    # Get data from FTL
    C=0
    readarray -t LINE <<< "$(echo ">$1" | nc -w 1 127.0.0.1 "${ftl_port}")"
    if [[ "${#LINE[@]}" -ge "1" && ! "${LINE[0]}" == "" ]]; then
      until [[ "${LINE[$C]}" == *"EOM"* || "${LINE[$C]}" == "" ]]; do
        echo "${LINE[$C]}"
        let C+=1
      done
    else
      echo -e "FTL offline"
    fi
  else
    echo -e "FTL offline"
  fi
}

run_start=$(date +%s.%N)
ftlFunc version
printf "Runtime for new FTL code: %.2fs\n" $(calc "$(date +%s.%N) - $run_start")
```

```
version v2.9.3
tag v2.9.3
branch (no branch)
date 2017-06-21 20:19:49 +0200
Runtime for new FTL code: 2.02s
```

**Comment by DL6ER** [comment]
@WaLLy3K Any updats on this? Have you tried running the code the same way I did (define functions, run them through `time` instead of measuring the time like you did)?

**Comment by DL6ER** [comment]
Going to merge `development` now. Hopefully that resolves the test issues.

**Comment by WaLLy3K** [comment]
Running `time ftlFunc version`:
```
version v2.9.4
tag v2.9.4
branch (no branch)
date 2017-06-22 23:33:48 +0200

real    0m2.016s
user    0m0.000s
sys     0m0.000s
```

Old code completes in 0m0.008s.

**Comment by WaLLy3K** [comment]
Unless there's something *really* wrong with my setup (hey, always a possibility!), I'd consider closing this until we can find code that runs (almost) as quickly as what we already have.

As far as Chrono and my personal opinion goes, I absolutely do not mind that the code is *longer*, I just care that it's *faster*. People could be setting a Chrono refresh of 1 second (when as-is with #1518, the first-run of the code is roughly 0.5-0.6s), and we need to be able to retrieve data from `FTL` as quick as possible.

**Comment by DL6ER** [comment]
@WaLLy3K Okay.

**Pull request closed without merging**
