### PR TITLE
pihole.cron reduce duplication

### PR DESCRIPTION
**Pull request by diginc**
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**
- [x] 10 (very familiar)

---
No need to inline the path change repeatedly.  Cron supports this style.

### CODE REVIEW

**Comment by PromoFaux** [comment]
Code looks sound.

Approved

**Comment by PromoFaux** [comment]
Added change notes to draft release

**Comment by DL6ER** [comment]
I was not even aware that this is possible with `cron`. Great!

**Comment by DL6ER** [comment]
Reverted by #1039 
Release v2.10.2 #1041

**Pull request merged**
