### PR TITLE
Start changes to new code style for repository. Revise basic installer.sh spacing.

### PR DESCRIPTION
**Pull request by dschaper**
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**
Change default spacing to 4 spaces, set tabs as space. Initial implementation, only changes `basic install.sh`. Further script revisions will address other scripts/utilities after this major PR change.

**How does this PR accomplish the above?:**
Re-indent `basic install.sh` and change the `.editorconfig` to use 4 spaces, tabs as space.

**What documentation changes (if any) are needed to support this PR?:**
No changes needed to documentation.

### CODE REVIEW

**Comment by dschaper** [comment]
Tagging as WIP for the moment, will remove label when it is clear to merge. No changes are scheduled for this PR, just waiting on a few other PRs that may be affected by the changes in style.

**Comment by dschaper** [comment]
WIP removed, good for approval.

**Comment by diginc** [comment]
RE: [Loops](https://google.github.io/styleguide/shell.xml?showone=Loops#Loops)

```
 if [[ foo ]]; then
# VS
 if [[ foo ]] ; then
```

I saw a couple examples of spaces before the semicolon in basic install.  There's no written rule about the space before the semicolon as far as I see but their examples all seem to favor no space before semicolon.

**Comment by dschaper** [comment]
We'll take care of the formatting for code in a different PR.

**Comment by dschaper** [comment]
This is holding up other PRs, there's not much in the way of code to review, it's almost all just an adjustment in spaces and indenting.

**Pull request merged**
