### PR TITLE
Fixed locale issue, do not parse for string.

### PR DESCRIPTION
**Pull request by dschaper**
Signed-off-by: Dan Schaper <dan.schaper@pi-hole.net>

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
Remove string parsing from function that caused locales different than EN to fail.

**How does this PR accomplish the above?:**

Use `git ls-remote` command.

**What documentation changes (if any) are needed to support this PR?:**

None

### CODE REVIEW

**Comment by dschaper** [comment]
Fix #2296

**Comment by dschaper** [comment]
Response from old command, we test on `tracked` and there's no match.
```
LANGUAGE=de_DE.UTF-8 git remote show origin | grep 'tracked' | sed 's/tracked//;s/ //g'
>
```

New code should be `locale` agnostic.
```
LANGUAGE=de_DE.UTF-8 git remote show origin
* Remote-Repository origin
  URL zum Abholen: https://github.com/pi-hole/pi-hole.git
  URL zum Versenden: https://github.com/pi-hole/pi-hole.git
  Hauptbranch: master
  Remote-Branches:
    FTLDNS                                         gefolgt
    FTLDNS-pihole-r                                gefolgt
    FTLDNS-systemd                                 gefolgt
    adamFTLDNS                                     gefolgt
    adlist-default-query                           gefolgt
```

New code, does not check for static string.
```
LANGUAGE=de_DE.UTF-8 git ls-remote --head --quiet | cut -d'/' -f3- -
FTLDNS
FTLDNS-pihole-r
FTLDNS-systemd
adamFTLDNS
adlist-default-query
adlist-default-query-1
development
experiment/RemoveDnsmasq
feature/style_guide
fix/debug-ipaddr
```

**Comment by dschaper** [comment]
Existing output
```
pihole checkout core
  Please note that changing branches severely alters your Pi-hole subsystems
  Features that work on the master branch, may not on a development branch
  This feature is NOT supported unless a Pi-hole developer explicitly asks!
  Have you read and understood this? [y/N] y

  [✓] Fetching branches from https://github.com/pi-hole/pi-hole.git
  [i] 31 branches available for Pi-hole Core

  [i] Requested branch "" is not available
  [i] Available branches for Core are:
      - FTLDNS
      - FTLDNS-pihole-r
      - FTLDNS-systemd
      - adamFTLDNS
      - adlist-default-query
      - adlist-default-query-1
   ...
```

New code
```
pihole checkout core
  Please note that changing branches severely alters your Pi-hole subsystems
  Features that work on the master branch, may not on a development branch
  This feature is NOT supported unless a Pi-hole developer explicitly asks!
  Have you read and understood this? [y/N] y

  [✓] Fetching branches from https://github.com/pi-hole/pi-hole.git
  [i] 31 branches available for Pi-hole Core

  [i] Requested branch "" is not available
  [i] Available branches for Core are:
      - FTLDNS
      - FTLDNS-pihole-r
      - FTLDNS-systemd
      - adamFTLDNS
      - adlist-default-query
      - adlist-default-query-1
   ...
```

**Comment by PromoFaux** [comment]
Tested and working fine this end. Green to go!

**Pull request merged**
