### PR TITLE
Update basic-install.sh

### PR DESCRIPTION
**Pull request by certuna**
Added DNS64 server configurations for Google and Cloudflare, for use on single stack IPv6 networks.

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by dschaper** [comment]
Hello, thanks for the submission.

Normally we'd ask that you follow the Contributor's Guide that you acknowledge you read, but in this case that's not necessary. We are not adding or changing the default DNS servers, nor would we be adding IPv6 only DNS servers.

**Comment by certuna** [comment]
At the moment there are already IPv6 DNS servers (for use on dual stacked networks), I'm only adding the ones that do DNS64 (for use on single stack IPv6 networks)

**Comment by dschaper** [comment]
Doesn't change my stance or the state of this PR.

**Comment by certuna** [comment]
So everyone on a single stacked IPv6 network will have to set this up manually?

**Comment by dschaper** [comment]
Yes.

**Pull request closed without merging**
