### PR TITLE
Check if tty exist before we get screen size

### PR DESCRIPTION
**Pull request by bolausson**
This change fixes issue #145 "stty: standard input: Inappropriate ioctl for device "
It checks if a real terminal exist, if not it sets the screen size to a fixed value.
This helps to avoid nasty and unnecessary logs when running "pihole -up" via e.g. cron.

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
This change fixes issue #145 "stty: standard input: Inappropriate ioctl for device "

**How does this PR accomplish the above?:**
It checks if a real terminal exist, if not it sets the screen size to a fixed value.

**What documentation changes (if any) are needed to support this PR?:**
No changes to the documentation are required

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by Mcat12** [comment]
Thanks for the PR! However, there are some changes that have to be made:
1. Fill in the PR template. I've added it back for you
2. Base your branch on development and point the PR to development (this will fix the build failure as well)
3. Sign off your commits: https://docs.pi-hole.net/guides/github/how-to-signoff/

**Comment by bolausson** [comment]
> Thanks for the PR! However, there are some changes that have to be made:
> 
> 1. Fill in the PR template. I've added it back for you
> 2. Base your branch on development and point the PR to development (this will fix the build failure as well)
> 3. Sign off your commits: https://github.com/pi-hole/pi-hole/pull/2859/checks?check_run_id=177170212

Hej,

I checked all the boxes and added comments.
But I don't know how I can change my PR to point against development and how (or where I exactly should sign it off) -Could you give me some guidance?

Cheers,
Bjoern

**Comment by Mcat12** [comment]
I've updated the PR to point to development, but you need to rebase your branch onto development. If you don't know how to do this, there are lots of guides available on the internet.

The link I shared previously shows you exactly how to sign off your commits. If you cannot access it, this link also has the instructions: https://docs.pi-hole.net/guides/github/how-to-signoff/

**Comment by bolausson** [comment]
> I've updated the PR to point to development, but you need to rebase your branch onto development. If you don't know how to do this, there are lots of guides available on the internet.
> 
> The link I shared previously shows you exactly how to sign off your commits. If you cannot access it, this link also has the instructions: https://docs.pi-hole.net/guides/github/how-to-signoff/

Guys, sorry, the patch took me 1 minute, and I am now trying to figure out how to "rebase" my branch for 1h... just close the request and maybe someone else is going to submit a PR the right way...

Cheers,
Bjoern

**Comment by PromoFaux** [comment]
@bolausson, easiest thing to do sometimes is just start again :) I've been doing this for years and still don't get the rebase command!

Process should be similar to the following:

- Fork the Pi-hole repository to your account.
- Clone it to your workstation
- On your local copy, make a branch based from development (`git checkout -b mynewbranch development`)
- make your changes
- commit (with signoff as explained above)
- push back to your repository
- create new PR based on your changes

That way, you get the proper accreditation for your work when it is merged to the main Pi-hole repository.

This is a great resource for learning about `git`, if you are less familiar with it!

https://learngitbranching.js.org/

**Comment by bolausson** [comment]
> @bolausson, easiest thing to do sometimes is just start again :) I've been doing this for years and still don't get the rebase command!
> 
> Process should be similar to the following:
> 
> * Fork the Pi-hole repository to your account.
> * Clone it to your workstation
> * On your local copy, make a branch based from development (`git checkout -b mynewbranch development`)
> * make your changes
> * commit (with signoff as explained above)
> * push back to your repository
> * create new PR based on your changes
> 
> That way, you get the proper accreditation for your work when it is merged to the main Pi-hole repository.
> 
> This is a great resource for learning about `git`, if you are less familiar with it!
> 
> https://learngitbranching.js.org/

I'll start over :)

**Comment by PromoFaux** [comment]
Great stuff. I will close out this PR for now... Looking forward to your next one :)

**Pull request closed without merging**
