### PR TITLE
Add a "Reviewed by Hound" badge

### PR DESCRIPTION
**Pull request by salbertson**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [ ] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---

Is Codacy still used? Should I remove the broken badge and image?

screenshot 2018-11-15 22 01 33

### CODE REVIEW

**Comment by dschaper** [comment]
Thanks, I haven't had time to set up Hound for Shellcheck linting of the code.

**Comment by dschaper** [comment]
We'll be using another service instead of Hound for our needs. Thanks for the PR though.

**Comment by salbertson** [comment]
Thanks for the update @dschaper. What did you end up using instead?

**Comment by dschaper** [comment]
For this core repo that is mostly shell script with some PHP and Python unit tests we're using CodeFactor.

**Comment by salbertson** [comment]
Thanks @dschaper. Just fyi, Hound uses [ShellCheck](http://help.houndci.com/configuration/shellcheck) and [Flake8](http://help.houndci.com/configuration/flake8) to review shell script and Python, plus we just released [PHP support](https://github.com/houndci/hound/issues/313#issuecomment-440537534) using PHP_CodeSniffer. Anyway, thanks again for the update.

**Pull request closed without merging**
