### PR TITLE
Fix list: User same wildcard regex that the UI use

### PR DESCRIPTION
**Pull request by andras-tim**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
Same and working whitelist/blacklist handling that UI has.

**How does this PR accomplish the above?:**
* As you can see in the code, I swapped the parts of the regex group to fit with the UI's.

**What documentation changes (if any) are needed to support this PR?:**
I don't think this is necessary now.

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by andras-tim** [comment]
**With the latest docker release** (`pihole/pihole:v5.3.4`) you can add the same domain twice if you use the **wildcard** option on the UI and the `--wild` or `--white-wild` option w/ CLI.

1. Exactly, if I want to add **foo.bar** to whitelist as wildcarded domain...

    * the UI will create: `(\.|^)foo\.bar$`
    * the CLI (`pihole --white-wild foo.bar`) will create: `(^|\.)foo\.bar$`

    _(so, I will have two regexes for one purpose)_

1. And of course the CLI is consistent w/ itself, so (`pihole --white-wild -d foo.bar`) will remove the `(^|\.)foo\.bar$` only.

**With my fix**, the CLI add wildcard records as the UI do, so in `(\.|^)<DOMAIN>$` form.

_(of course, my first idea was I make the `list.sh` be smarter to be able to handle both formats, but the current code requires more refactor that I wanted to do now)_

**Comment by dschaper** [comment]
That's an OR grouping, so the order really doesn't matter?

**Comment by andras-tim** [comment]
> That's an OR grouping, so the order really doesn't matter?

Both interfaces extend the same SQLite table with different regexes. These regexes are in OR condition (as you exclude two different domains, e.g. foo.com and bar.com)

**Review by dschaper — APPROVED** [review]

**Comment by andras-tim** [comment]
Thank you!

**Comment by dschaper** [comment]
Thank you for making the submission!

**Pull request merged**
