### PR TITLE
Remove problem list, sends in Unicode - Not adware

### LINKED ISSUE #816: binary files in gravity.list
some times gravity.list will end up being truncated. with a binary file matches error.    i belive this to be due to https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt.    taking the output file from that list  tells me its gzipped      i belive the solution to this is adding --compressed to curl   not sure if it hurts to do this on all of the lists but adding    
            "ransomwaretracker.abuse.ch")
                cmd_ext="--compressed"
            ;;
in gravity_spinup semes to have cured this but only time will tell as this is a random error

### PR DESCRIPTION
**Pull request by dschaper**
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**By submitting this pull request, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

- [x] 10 (very familiar)

---
Remove problematic adlist from sources, does not block ads, is a Command and Control blocker, small number of domains and presents list in Unicode on occasion, breaking system. Cull.

Fixes #816

### CODE REVIEW

**Comment by Mcat12** [comment]
Approved

**Comment by PromoFaux** [comment]
Approved

Note for future users wondering why their list has suddendly dropped by 2,258 (ish) domains. This is why.

**Comment by PromoFaux** [comment]
Wow, that list has really grown, When it was first added it was only an additional 174 domains.

**Comment by dschaper** [comment]
They're all random subdomains, not many domains...

**Comment by dschaper** [comment]
:+1:

**Pull request merged**
