### PR TITLE
Hotfix/readme

### PR DESCRIPTION
**Pull request by dschaper**
Fixes #[INTERNAL] .

Changes proposed in this pull request:

- Hotfix README.md with development cherry-picks.

(Merges commits already in development. Cherry-picked for README.md update on Master branch.)

@pi-hole/gravity

### CODE REVIEW

**Comment by dschaper** [comment]
Approved

**Comment by Mcat12** [comment]
Approved

**Comment by PromoFaux** [comment]
Approved

**Comment by PromoFaux** [comment]
Revoked approval.. just realised it's on master branch.

**Comment by dschaper** [comment]
Closing, will process with next Master push.

**Pull request closed without merging**
