### PR TITLE
Changes as in #253, but with less commits to keep the repo tidy

### PR DESCRIPTION
**Pull request by PromoFaux**

### CODE REVIEW

**Comment by PromoFaux** [comment]
@Mcat12 @DonLexos @dschaper 

`curl -L https://raw.githubusercontent.com/pi-hole/pi-hole/Bugfix/InstallScriptFix/automated%20install/basic-install.sh | bash`

**Comment by DonLexos** [comment]
Want me to test this on a fresh upgraded Jessie installation?

**Comment by PromoFaux** [comment]
Yes please. And then I'm going for a cigarette and a cup of tea!

**Comment by Mcat12** [comment]
I have 38 updates... D: Updating...

**Comment by PromoFaux** [comment]
But did the script cut out and not give the service start errors?

**Comment by Mcat12** [comment]
Yep

**Comment by DonLexos** [comment]
I already did that update manually, I am running the script and it takes a bit since this is a vanilla installation, will post the output when done :-)

**Comment by DonLexos** [comment]
All done (successsfully!)
```
pi@pi-hole:~ $ curl -L https://raw.githubusercontent.com/pi-hole/pi-hole/Bugfix/InstallScriptFix/automated%20install/basic-install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16691  100 16691    0     0  26192      0 --:--:-- --:--:-- --:--:-- 26202
:::
::: sudo will be used for the install.
::: Using interface: eth0
::: Using IPv4 on 192.168.1.11/24
::: IPv6 will NOT be used.
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your pi is up to date! Continuing with pi-hole installation...
:::
::: Checking dependencies:
:::    Checking for dnsutils... Not found! Installing... done!
:::    Checking for bc... Not found! Installing... done!
:::    Checking for toilet... Not found! Installing... done!
:::    Checking for figlet... Not found! Installing... done!
:::    Checking for dnsmasq... Not found! Installing... done!
:::    Checking for lighttpd... Not found! Installing... done!
:::    Checking for php5-common... Not found! Installing... done!
:::    Checking for php5-cgi... Not found! Installing... done!
:::    Checking for php5... Not found! Installing... done!
:::    Checking for git... Not found! Installing... done!
:::    Checking for curl... already installed!
:::    Checking for unzip... already installed!
:::    Checking for wget... already installed!
:::
::: Stopping services. done.
:::
::: Checking for existing base files...
:::    Checking /etc/.pihole is a repo... not found!!
:::    Cloning https://github.com/pi-hole/pi-hole.git into /etc/.pihole.. done!
:::
::: Checking for existing web interface...
:::    Checking /var/www/html/admin is a repo... not found!!
:::    Cloning https://github.com/pi-hole/AdminLTE.git into /var/www/html/admin.. done!
:::
::: Installing scripts... done.
:::
::: Installing configs... done.
:::
::: Creating log file and changing owner to dnsmasq... done!
:::
::: Installing pihole custom index page... done!
:::
::: Installing latest Cron script... done!
:::
::: Preparing to run gravity.sh to refresh hosts...
::: Running gravity.sh
:::
:::
::: sudo will be used.
::: Neutrino emissions detected...
:::
::: Getting adaway.org list... List updated, transport successful!
::: Getting adblock.gjtech.net list... List updated, transport successful!
::: Getting hosts-file.net list... List updated, transport successful!
::: Getting www.malwaredomainlist.com list... List updated, transport successful!
::: Getting pgl.yoyo.org list... List updated, transport successful!
::: Getting someonewhocares.org list... List updated, transport successful!
::: Getting winhelp2002.mvps.org list... List updated, transport successful!
::: Getting mirror1.malwaredomains.com list... List updated, transport successful!
:::
::: Aggregating list of domains.. done!
::: Formatting list of domains to remove comments... done!
::: 97705 domains being pulled in by gravity...
::: Removing duplicate domains... done!
::: 88587 unique domains trapped in the event horizon.
::: Formatting domains into a HOSTS file...
:::
::: Adding 8 ad list sources to the whitelist... done!
::: Running whitelist script to update HOSTS file... 8 domains whitelisted!
::: Running blacklist script to update HOSTS file... 0 domains blacklisted!
:::
::: Refresh lists in dnsmasq.. done!
pi@pi-hole:~ $
```

**Comment by PromoFaux** [comment]
Thank **** for that!

**Comment by Mcat12** [comment]
I'm only 7% done updating... This might take awhile.

**Comment by DonLexos** [comment]
Admin interface is working, whitelist.sh is working, I see no ads anymore .. all working as far as I can tell :-) Good work!!

**Comment by PromoFaux** [comment]
We have confirmation that:

1. It exits the script if there are upgrades to do
2. It installs correctly once upgrades are done.

I'm just booting a fresh pi for a final sanity check, but other than that, I'm good to merge to master.

All those in favour?

**Comment by Mcat12** [comment]
Maybe wait until my pi finishes updating. :D

**Comment by DonLexos** [comment]
What @Mcat12 said might be a good idea, that way it all steps have been tested with latest commit. From what I can tell after the upgrade it runs fine.

**Comment by PromoFaux** [comment]
Anyone else get this on a fresh pi?

image

**Comment by DonLexos** [comment]
Thats odd, the SSL from git is not accepted? I did not get that, tested it and ran the script again, no error here.

**Comment by PromoFaux** [comment]
Reflashing...

**Comment by DonLexos** [comment]
Try again first

**Comment by PromoFaux** [comment]
Same thing, hence reflashing in case I did something wrong

**Comment by DonLexos** [comment]
Could be a temp error, I get `Could not resolve host: github.com` errors sometimes.

**Comment by PromoFaux** [comment]
I'm not certain, but it might have had something to do with connecting over SSH with the same session from before I flashed...

**Comment by PromoFaux** [comment]
Once this is merged I will do a PSA post on /r/pihole and /r/raspberry_pi

**Comment by DonLexos** [comment]
Well it said certificate is not yet valid, MAYBE the SSL is signed to be valid from 28-01-2016 0:00 but in a different timezone and your Pi is still on Jan 27th?

**Comment by Mcat12** [comment]
65% done.

**Comment by PromoFaux** [comment]
Yep, was my fault, didn't accept the certificate on connecting over SSH

**Comment by PromoFaux** [comment]
Exit 1  still doesn't stop the splash screen, but the message is clear at least.

image

**Comment by DonLexos** [comment]
Question though
I checked git status in `/etc/pihole` and got nothing, then I read
`:::    Cloning https://github.com/pi-hole/pi-hole.git into /etc/.pihole.. done!`

The git file is places in `/etc/.pihole/`, is that intended?

**Comment by Mcat12** [comment]
Yes, then the specific files are pulled from there.

**Comment by PromoFaux** [comment]
That's intended.

**Comment by DonLexos** [comment]
Ok I am learning how github and git works exactly, just thought I mention it before you merge it into master :)

**Comment by Mcat12** [comment]
It ran fine.

**Comment by PromoFaux** [comment]
Do we need to force an apt-get upgrade? Should we just recommend they run it after pi has installed?

**Comment by PromoFaux** [comment]
As far as I'm concerned, we only need the up to date package lists to get the dependencies.

and it would stop me from trying to work out the splash screen /service error bug...

**Comment by PromoFaux** [comment]
try this `curl -L https://gist.githubusercontent.com/PromoFaux/74577036e3cb00ce2681/raw/b1c707c0a20c4f46a15216291a4b567e51509d53/install.sh | bash`

(have been playing about with a gist, instead of committing just to test)

**Comment by PromoFaux** [comment]
Can confirm the above change works on a fresh pi.

@Mcat12 or @DonLexos can you give one final test, please? Sorry for messing you about

**Comment by PromoFaux** [comment]
Freshly baked pi install testing with above commit:
image

**Comment by PromoFaux** [comment]
The rest of the script finished installing OK
image

I'm going to make an executive decision and push this live. I'll announce on the subreddit what went wrong, and how users can fix.

**Comment by Mcat12** [comment]
Just got back from eating. I'll test it one more time, but I think it's pretty solid.

**Comment by PromoFaux** [comment]
Already pulled, but tests are appreciated! I'll wait 10 mins before pushing to master

**Comment by Mcat12** [comment]
What url do you want us to curl? https://raw.githubusercontent.com/pi-hole/pi-hole/development/automated%20install/basic-install.sh

**Comment by PromoFaux** [comment]
`curl -L https://gist.githubusercontent.com/PromoFaux/74577036e3cb00ce2681/raw/b1c707c0a20c4f46a15216291a4b567e51509d53/install.sh | bash`

**Comment by DonLexos** [comment]
Sorry I missed this, I am in the CET timezone, your update was at 1 AM and I was long gone. I'll be at work during the day but happy to test anything tonight if you need some help

**Comment by PromoFaux** [comment]
:) Only an hour ahead of me! But totally understandable. I ran a couple of tests myself, provided the evidence that the fix works, and pushed to master! All good. Thanks for your help last night anyway. I think I'll use you as my go-to test guy :+1:

**Comment by DonLexos** [comment]
Haha .. well after playing around yesterday and ending up with a working installation again I decided it would be wise to do something off-screen for a bit before today started (filled with all kinds of screens again). I should get an extra pi to play on, right now I wreck my DNS1 the whole time and I see banners everywhere ;-) 

I am happy to test (new) stuff when it's necessary so give me a shout when you need something :-)

**Comment by Mcat12** [comment]
Oh, I guess I forgot to report that it worked fine.

**Pull request merged**
