### PR TITLE
Added removal of pihole user to the uninstall.sh

### PR DESCRIPTION
**Pull request by zbholman**
**By submitting this pull request, I confirm the following (please check boxes, eg [X])Failure to fill the template will close your PR:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

- [] 1 (very unfamiliar)
- [X] 2
- [] 3
- [] 4
- [] 5
- [] 6
- [] 7
- [] 8
- [] 9
- [] 10 (very familiar)

---
Added remove of pihole user to uninstall.sh
# If the pihole user exists, then remove
	if id "pihole" >/dev/null 2>&1; then
        	echo "::: Removing pihole user..."
		${SUDO} userdel -r pihole
	fi

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

Not sure if I should have created a variable for the username or if the echo is necessary. And this is my first time doing a pull request, hopefully it works out lol.

### CODE REVIEW

**Comment by PromoFaux** [comment]
Approved.

(Note to self: `uninstall.sh` needs to be updated to remove refs to `${SUDO}` and the root check in a future update.)

**Comment by PromoFaux** [comment]
Whoops, hold up...

**Comment by PromoFaux** [comment]
@zbholman Please ensure pull requests are based on the `development` branch as per [the contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md#technical-requirements) (which you ticked up above to say you'd read 😉)

**Comment by PromoFaux** [comment]
Approved.

**Comment by Mcat12** [comment]
Approved

**Comment by zbholman** [comment]
@PromoFaux Oops, I'll be sure to do that next time haha. Lesson learned

**Pull request merged**
