### PR TITLE
Be able to disable the DHCP domain name

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 10

---

Setting the DHCP domain name to `none` prevents it from being used at all.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by Mcat12** [comment]
Approved

**Comment by DL6ER** [comment]
screenshot at 2017-01-18 14-23-03

**Comment by ssbgnes** [comment]
Sorry, I'm noob here. Could you help me? Was this solution applied? I need to get DHCP without domain name on my Pi-hole v5.2.4 installed but the web interface does not allow it. How can I do it? Thanks

**Comment by ssbgnes** [comment]
Sorry, Im noob here. Could anyone help me, please? Was this solution apply? I need to get a DHCP without domain name on my Pi-hole (v5.2.4), but this is not allowed on web interface. How could I do it? Thanks.

**Comment by duden00b** [comment]
Sorry, Im noob here. Could anyone help me, please? Was this solution apply? I need to get a DHCP without domain name on my Pi-hole (v5.2.4), but this is not allowed on web interface. How could I do it? Thanks.

**Comment by PromoFaux** [comment]
Please open a help request on https://discourse.pi-hole.net

also:
>Setting the DHCP domain name to none prevents it from being used at all.

**Pull request merged**
