### PR TITLE
Change white/blacklist to allow/blocklist

### PR DESCRIPTION
**Pull request by StefanHolmes**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [ ] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*
A change in language to eliminate any potential negative connotation caused by use of 'blacklist' versus 'whitelist'.

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*
Hand review all instances and replacing with 'allowlist' and 'blocklist'.

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*
Potentially just an acknowledgement of the change.

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by PromoFaux** [comment]
Per contribution guidelines, all Pull requests must be based on and submitted against the `development` branch.

**Comment by PromoFaux** [comment]
Also, just as a note on this, a find and replace is not going to work for this, there are interworking systems that would need to be tested thoroughly to ensure the changes work throughout the whole system.

**Comment by yubiuser** [comment]
I would not use "blocklist" but rather "denylist" or so, because "blocklist(s)" was the term used by pihole <v5.0 for what is now called "adlist(s)". This might confuse users to mix up lists of domains (usually found online) with a self-maintained list of (few additionally) blocked domains.

**Comment by axi0m** [comment]
I'd just like to say that I support this PR. 👍

**Comment by simonschaufi** [comment]
Another suggestion: Exclude list

**Comment by HyperCriSiS** [comment]
Seriously, this is ridiculous....

**Comment by itpropro** [comment]
Are there any updates on this? 
In the meantime, most governments as well as nearly all security tools have moved away from the wording, as it is clearly coming from the era of mass enslavement and forced deportation of Africans. And as the "main" branch has become the default, "allowlists" and "blocklists" have become a default, too (and fitting the main purpose of pi-hole much better anyway).
It would be great if this could be revisited, as the amount of work is minimal, no one has any disadvantages and we would avoid alienation and a lot of negative associations that come with the terms "black-" and "whitelisting". 
Especially as pi-hole is a project that many people come to, that don't have any technical background and are thereby no impacted by working with these terms for years, the wording is important.

**Comment by yubiuser** [comment]
This is changed already in the upcoming v6 version.

**Comment by itpropro** [comment]
> This is changed already in the upcoming v6 version.

Did not know this, thank you!

**Comment by Peterkal2112** [comment]
# Additional Arguments for Restoring "Whitelist" and "Blacklist" in Pi-hole

## Introduction

Beyond the technical and usability concerns already discussed, it is important to address the broader implications of renaming "Whitelist" and "Blacklist" to "Allow List" and "Deny List." This document presents additional arguments focusing on the **unintended consequences of politicizing neutral technical terminology** and the logical inconsistencies behind the change.

## The Danger of Seeing Racism Where None Exists

### 1. **Introducing Unnecessary Division into Neutral Technical Concepts**
   - "Whitelist" and "Blacklist" are terms with well-defined meanings in technology, security, and network management, having nothing to do with race.
   - By attributing racial implications to these terms, an **unwarranted controversy** is introduced where none previously existed.
   - This approach fosters division rather than unity, as it forces users and developers into ideological debates instead of focusing on improving software.

### 2. **Politicization of Software Development Harms Technical Progress**
   - The purpose of software development is to create efficient, functional, and user-friendly tools.
   - When social or ideological concerns dictate naming conventions, it **shifts focus away from usability and functionality.**
   - Developers should prioritize logical and practical reasons for changes rather than attempting to address external social issues through arbitrary language adjustments.

### 3. **Language Evolution Should Be Driven by Practicality, Not Ideology**
   - Technical terminology evolves organically based on efficiency and widespread usage.
   - Forcing changes to terminology based on social movements rather than practical necessity disrupts continuity and creates unnecessary learning curves for users.
   - If a term needs to change, it should be because of **clear and objective improvements,** not ideological motivations.

## Applying Social Reasoning to a Non-Social Context Is Misguided

### 4. **Technical Terms Have Distinct Meanings That Do Not Imply Human Characteristics**
   - In computing, "whitelist" means **allowing** and "blacklist" means **blocking**—these are simple functional descriptions.
   - The usage of "white" and "black" in this context stems from physics (e.g., **white light contains all colors, black is the absence of light**), not social constructs.
   - Assuming that these words must carry racial connotations ignores their technical origins and **imposes an unrelated framework onto a neutral domain.**

### 5. **Misguided Changes Lead to a Slippery Slope of Endless Renaming**
   - If "Whitelist" and "Blacklist" are renamed due to perceived social concerns, where does it stop?
   - Other well-established technical terms like "Master/Slave" have already been targeted for renaming despite their clear functional meanings in computing.
   - This cycle of renaming risks creating **endless disruptions without clear benefits**, as future terms may be reinterpreted through ideological lenses and deemed problematic.

## Conclusion

The renaming of "Whitelist" and "Blacklist" in Pi-hole is an example of unnecessary interference in technical terminology based on social or ideological reasoning. This change does not enhance software functionality but instead creates confusion, disrupts user experience, and distracts from meaningful development.

Restoring the original terms is not about politics—it is about maintaining clarity, efficiency, and neutrality in software development. The focus should remain on **technical excellence, not ideological debates.**

**Comment by HyperCriSiS** [comment]
This is really well written. Even the last one should understand it with this text.
Thank you for ending this insanity!

**Comment by tekneek** [comment]
Is there any evidence the new way has actually confused anyone?

**Comment by HyperCriSiS** [comment]
> Is there any evidence the new way has actually confused anyone?

It is not even about confusion, it is about completely unnecessary changes that just produce work and don't help anybody.
Not even a bit. It was just purely ideology.

**Comment by dschaper** [comment]
We're not doing this here.

**Pull request closed without merging**
