### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by deathbybandaid**
**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'development' branch!}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#git-commit---signoff))

---

**What does this PR aim to accomplish?:**

Just a typo found on the README.md file

Signed-off-by: deathbybandaid sam@deathbybandaid.net

### CODE REVIEW

**Comment by Mcat12** [comment]
Either add in the DCO to the commit or to the PR.

**Comment by deathbybandaid** [comment]
sorry 'bout that!

**Comment by deathbybandaid** [comment]
Note to self: a quick edit from Github's live-editor will not let me do the DCO signoff

**Comment by deathbybandaid** [comment]
I'm apparently on the struggle-bus, and will return after I have had some coffee

**Comment by dschaper** [comment]
If you do changes though the web interface it will squawk at you. It wants the name and email you have on file with GitHub, or if you do the web interface it sometimes uses the anonymous email address. It's not an update thing, if you make 3 commits and only the last commit is valid DCO the test still fails from the previous commits. Just make an edit to your PR message and add the Signed Off By line to that and we can bypass the check and merge anyways.

**Comment by deathbybandaid** [comment]
added to the PR message

**Pull request merged**
