### PR TITLE
debugPihole.sh, uninstall.sh bug fixes and improvements, script cleanup

### PR DESCRIPTION
**Pull request by nate-ubiquisoft**
- Added debugPihole.sh to generate a debug file to assist in troubleshooting
- Refactored uninstall.sh to be more robust and customize the uninstall process
- Lots of general bash scripting improvements to make PiHole more robust and forwards-backwards compatible with bash versions.

@pihole/gravity

### CODE REVIEW

**Comment by PromoFaux** [comment]
@nate-ubiquisoft does this have the changes as per requirements in the previous PR?

**Comment by nate-ubiquisoft** [comment]
@PromoFaux Yes this includes all of my changes to the old PR for ScriptCleanup and PiholeDebug. I *havent* tested since the rebase and merge as I am at the office but everything passed shellcheck.net with no issues.

**Comment by PromoFaux** [comment]
Once i've got myself sorted here, I'll clone it and test.

**Comment by PromoFaux** [comment]
Finicky change request..... ;)

image

The first prompt needs to be changed from `[y/n]` to `[y/n]: ` (make sure not to miss the space at the end :)

**Comment by PromoFaux** [comment]
Oh, sorry, didn't notice eariler, change `DONE!` to ` done!` (space at beginning) to match install script

**Comment by PromoFaux** [comment]
Almost there! 

image

`/n` to `\n` :)

**Comment by PromoFaux** [comment]
Not sure how I feel about [this line](https://github.com/nate-ubiquisoft/pi-hole/blob/development/automated%20install/uninstall.sh#L110)

Let's say the user does not remove the `lighttpd` dependency, you've now killed off the config directory! 

What this line _should_ do is replace `/etc/lighttpd/lighttpd.conf` with `/etc/lighttpd/lighttpd.conf.orig` (if the directory exists)

**Comment by PromoFaux** [comment]
We'll get there!

And then to work out where the conflicts are.. but that can be a job for tomorrow.

**Comment by PromoFaux** [comment]
OK, this is looking better. Uninstall is not leaving any artifacts in `/usr/local/bin`, for a start, which is good!

I think this is ready for merge. Will run some final tests after dinner first though.

**Comment by PromoFaux** [comment]
@nate-ubiquisoft 

- `piholeDebug.sh` could do with a couple of tweaks, nothing major. If there is no `adlists.list` output something like `:::     adlists.default in use`.
- Needs to be made executable with the same permissions as the rest of the script

**Comment by PromoFaux** [comment]
Also, it may just be my setup, but stick a `$SUDO` ahead of `ifconfig` on [this line](https://github.com/nate-ubiquisoft/pi-hole/blob/development/advanced/Scripts/piholeDebug.sh#L121)

**Comment by PromoFaux** [comment]
do `compareWhitelist` and `compareBlacklist` actually do anything? Not seeing anything in the output...

**Comment by nate-ubiquisoft** [comment]
They will only show matches between the whitelist/blacklist files and gravity.list. The whitelist check also is used to ensure that the nslookup test does not use a whitelisted domain from gravity.list

**Comment by PromoFaux** [comment]
latest errors!

```bash
::: Aggregating list of domains... done!
::: Formatting list of domains to remove comments.... done!
::: 125897 domains being pulled in by gravity...
::: Removing duplicate domains.... done!
::: 101402 unique domains trapped in the event horizon.
::: Formatting domains into a HOSTS file...
:::
::: Adding 9 adlist sources to the whitelist... done!
::: Running whitelist script to update HOSTS file.... [|]  /usr/local/bin/whitelist.sh: line 123: /etc/pihole/whitelist.txt: Permission denied                                                                                          7 domains whitelisted!
::: Running blacklist script to update HOSTS file.... [|]  /usr/local/bin/blacklist.sh: line 118: /etc/pihole/blacklist.txt: Permission denied
/usr/local/bin/blacklist.sh: line 123: /etc/pihole/blacklist.txt: Permission denied                                                                                                                                                     0 domains blacklisted!
:::
::: Cleaning up un-needed files... done!
:::
::: Refresh lists in dnsmasq... done!
::: Restarting services... done.
:::
::: Installation Complete! Configure your devices to use the Pi-hole as their DNS server using:
:::     192.168.216.235/23
:::     fe80::223:aeff:fe1c:8004
:::
::: If you set a new IP address, you should restart the Pi.
:::
::: The install log is located at: /etc/pihole/install.log
adam@adamwdebian:/etc/.pihole$ ll /etc/pihole/
total 12336
-rw-rw-rw- 1 root root    2514 Apr  1 13:40 adlists.default
-rw-rw-rw- 1 adam adam       0 Apr  1 13:19 blacklist.txt
-rw-rw-rw- 1 adam adam 8716530 Apr  1 13:40 gravity.list
-rw-r--r-- 1 adam adam    3583 Apr  1 13:40 install.log
-rw-rw-rw- 1 adam adam  860134 Apr  1 13:40 list.0.raw.githubusercontent.com.domains
-rw-rw-rw- 1 adam adam   23846 Apr  1 13:40 list.1.adblock.gjtech.net.domains
-rw-rw-rw- 1 adam adam  333287 Apr  1 13:40 list.2.mirror1.malwaredomains.com.domains
-rw-rw-rw- 1 adam adam  656185 Apr  1 13:40 list.3.sysctl.org.domains
-rw-rw-rw- 1 adam adam    8266 Apr  1 13:40 list.4.zeustracker.abuse.ch.domains
-rw-rw-rw- 1 adam adam     613 Apr  1 13:40 list.5.s3.amazonaws.com.domains
-rw-rw-rw- 1 adam adam   43642 Apr  1 13:40 list.6.s3.amazonaws.com.domains
-rw-rw-rw- 1 adam adam 1821935 Apr  1 13:40 list.7.hosts-file.net.domains
-rw-rw-rw- 1 adam adam  133964 Apr  1 13:40 list.8.raw.githubusercontent.com.domains
-rw-rw-rw- 1 adam adam     136 Apr  1 13:26 whitelist.txt
adam@adamwdebian:/etc/.pihole$ whitelist.sh some.domain
::: Adding some.domain to whitelist.txt... done!
/usr/local/bin/whitelist.sh: line 123: /etc/pihole/whitelist.txt: Permission denied
:::
::: Modifying HOSTS file to whitelist 0 domains... done!
:::
::: Refresh lists in dnsmasq... done!
```

**Comment by PromoFaux** [comment]
May be the changes in 7b8fa3b

**Comment by nate-ubiquisoft** [comment]
@PromoFaux No I was getting those errors before I made that change. That change does show that somewhere the permissions for /etc/pihole are being re-set as I set the owner to root:root, and you can see that it is owned by adam:adam in you output above

**Comment by PromoFaux** [comment]
In which case it will be in `gravity.sh`

**Comment by PromoFaux** [comment]
Found it. 

`whitelist.sh` line 123
`blacklist.sh` line 118

Add back in the removed `cat` calls.

**Pull request merged**
