### PR TITLE
Only re-block whitelist deletions if in adlists

### LINKED ISSUE #581: Inconsistent Behavior with Whitelist from Admin GUI
##### Expected Behaviour:

In the admin gui, when a domain is removed from the whitelist, it is removed from /etc/pihole/whitelist.txt _and not added to gravity.list_. 
##### Actual Behaviour:

In the admin gui, when a domain is removed from the whitelist, it is removed from /etc/pihole/whitelist.txt _and also added to gravity.list_. 
##### Steps to reproduce this issue:

Add a domain to whitelist
Confirm domain is added to end of /etc/pihole/whitelist.txt on container
Remove domain from whitelist via red garbage can icon on the right
Domain is removed from list in the GUI
Domain is no longer in whitelist.txt
However, domain is added to end of gravity.list (?!), causing the domain to be "pi-holed"

Refer to here for further notes:
https://github.com/diginc/docker-pi-hole/issues/23
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/36156074-inconsistent-behavior-with-whitelist-from-admin-gui?utm_campaign=plugin&utm_content=tracker%2F3011939&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F3011939&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by diginc**
Fixes #581 and maybe others.

Changes proposed in this pull request:

- Prevent blocking benign/untracked domains deleted off whitelist
- Searches /etc/pihole/*.domain files for a previous block on the domain being un-whitelisted before re-blocking
- Change the wording to be a little clearer what un-whitelisting a adList blocked domain does (re-block)
- 2 Spaces instead of tabs

@pi-hole/gravity

Manual tests

```
root@b55bcecd295b:/etc/pihole# export test='zv1.november-lax.com'; pihole -w $test ; pihole -w -d $test ;
::: You are root.
::: Adding zv1.november-lax.com to /etc/pihole/whitelist.txt... done!
:::
::: Modifying HOSTS file to whitelist 9 domains... done!
:::
::: Refresh lists in dnsmasq... done!
::: You are root.
:::
::: Modifying HOSTS file to un-whitelist domains...
:::    AdLists contain zv1.november-lax.com, re-adding block
:::        Restoring block for zv1.november-lax.com on IPv4 done!
:::    Removing zv1.november-lax.com from /etc/pihole/whitelist.txt... done!
:::
::: Refresh lists in dnsmasq... done!
```

```
root@b55bcecd295b:/etc/pihole# export test='w.diginc.us'; pihole -w $test ; pihole -w -d $test ;
::: You are root.
::: Adding w.diginc.us to /etc/pihole/whitelist.txt... done!
:::
::: Modifying HOSTS file to whitelist 9 domains... done!
:::
::: Refresh lists in dnsmasq... done!
::: You are root.
:::
::: Modifying HOSTS file to un-whitelist domains...
:::    Removing w.diginc.us from /etc/pihole/whitelist.txt... done!
:::
::: Refresh lists in dnsmasq... done!

```

### CODE REVIEW

**Comment by PromoFaux** [comment]
Looks good here... Approved.

**Comment by PromoFaux** [comment]
Approved!

(Apparently you need to start the comment with that)

**Comment by dschaper** [comment]
:+1:

**Comment by Mcat12** [comment]
Approved

**Pull request merged**
