### PR TITLE
Re-order debug log

### PR DESCRIPTION
**Pull request by yubiuser**
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
Re-orders the components of the debug log into more logical groups.

old: https://tricorder.pi-hole.net/LmUi3gRu/
new: https://tricorder.pi-hole.net/8ngM2ToL/

### CODE REVIEW

**Comment by yubiuser** [comment]
@pi-hole/debug Happy to get your opinion on that.

**Comment by yubiuser** [comment]
> E.g. it might be beneficial to see all lighttpd stuff in one place for one user's debug log, where it might be more interesting to have all log files grouped together for the next, regardless of which software produced it.

Auto-sorting depending on the issue to solve would be the next step ;-)

Thanks for the feedback.

**Comment by DL6ER** [comment]
Looking at the most recent , I don't *really* see much of a difference. Maybe because I'm used to looking either at everything from top to bottom or only opening the debug log to look at one specific thing so I have no pronounced feeling for the order in there. That being said, your changed debug log also doesn't appear any worse at all.

**Comment by DL6ER** [comment]
@yubiuser Do you still want this added? The feedback seems a bit sparse, I expressed my view already above.

**Comment by yubiuser** [comment]
As the major theme was "it is Ok as it is now" I'm fine with closing it. Can be revived if needed.

**Pull request closed without merging**
