### PR TITLE
Remove misplaced start of string expression

### LINKED ISSUE #1191: Certain domains can no longer be blocked
@r0ckarong commented on [Sun Jan 29 2017](https://github.com/pi-hole/AdminLTE/issues/379)

**In raising this issue, I confirm the following (please check boxes, eg [X] - no spaces) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

0

---
**[BUG | ISSUE] Expected Behaviour:**
Entries in the Query log can be black-/whitelisted by pushing the button or using the "pihole -b/-w" commands. 

**[BUG | ISSUE] Actual Behaviour:**
Certain (sub)domain names can not be added. Once added to lists they can only be removed by editing the list files manually.

**[BUG | ISSUE] Steps to reproduce:**
Skim Query Log.
Click on blacklist button for entry like "r1---sn-4g5e6nls.gvt1.com".
"Failure! Something went wrong.::: r2---sn-4g5edne7.gvt1.com is not a valid argument or domain name"

workspace 1_001

---

@DL6ER commented on [Sun Jan 29 2017](https://github.com/pi-hole/AdminLTE/issues/379#issuecomment-275908622)

We changed the validation scheme in the recent version. I'll test with the domain you provided. You can meanwhile white-/blacklist them by editing the files in `/etc/pihole/` manually and run `pihole -g` afterwards.

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 10

---

Remove misplaced start of string expression. Fixes #1191

https://regex101.com/r/Cd8j8q/5

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by Mcat12** [comment]
According to Regex101 we would be adding `sn-4g5e6nls.gvt1.com` instead of `r1---sn-4g5e6nls.gvt1.com`

**Comment by Mcat12** [comment]
Also, this would add `test.js` if `https://example.com/test.js` was input: https://regex101.com/r/x7t4uW/1

**Comment by dschaper** [comment]
What are some domains we do and do not want to pass this section so I can start writing some tests to check it?

**Comment by Mcat12** [comment]
Invalid:
```
https://example.com/test.js
http://example.com
example.com(testing)?something=else
```
Valid:
```
example.com
sub.example.net
r1---sn-4g5e6nls.gvt1.com
```

**Comment by DL6ER** [comment]
Updated regex:
- allow any number of direct successively placed `-` (previous regex allowed only one at a time, but did not enforce that)
- test whole string, do not do separate tests for each detected work (which lead to accepting `test.js` if `https://example.com/test.js` was the input)

https://regex101.com/r/Cd8j8q/6

**Comment by dschaper** [comment]
Thanks for the pointers. And do we need to do anything with the domains that pass the tests? Do they results need to be stored anywhere, or do we just return a valid/invalid result?

**Comment by DL6ER** [comment]
Valid/Invalid is sufficient, we'd have to debug them externally anyways.

**Comment by dschaper** [comment]
Okay, when I'm done on site I'll start to craft up some function tests.

**Comment by Mcat12** [comment]
Approved

**Pull request merged**
