### PR TITLE
Issue 309

### LINKED ISSUE #309: REQUEST: DNS Servers
add level 3 DNS servers: 4.2.2.1, 4.2.2.2. also add the ability to key in your own dns servers during install

### PR DESCRIPTION
**Pull request by fayetted**
Add ability to specify own DNS servers during install.

Fixes #309 and #320

### CODE REVIEW

**Comment by fayetted** [comment]
I'm not sure why there are a couple of commits in here that are not related to the DNS change.  It appears from the diff to be a single line in the README.md file but I was unable to clean it up.  Not sure exactly what I need to do.

**Comment by PromoFaux** [comment]
Thanks. Just FYI, no need to create a new issue for each pull request. We're more than happy to discuss things in the PR.

Those are from where I merged the development branch into @slamanna212 's branch

**Comment by PromoFaux** [comment]
Which I probably didn't need to do. I'm still trying to get the hang of git myself!

**Comment by fayetted** [comment]
@PromoFaux did I do that?

**Comment by PromoFaux** [comment]
I misread this as a new issue and not a PR. No worries! I'll check over the code

**Comment by fayetted** [comment]
Ok, cool.  Thought I screwed something up again.

**Comment by dschaper** [comment]
There's nothing you can do in Git that can't be undone or fixed, it's really really hard to break anything beyond a quick revert or rebase. (Of course, screw ups are retained in the log for everyone to look at, but you can squash those sometimes too...)

**Comment by PromoFaux** [comment]
NEVER DELETE HISTORY. LET THE WORLD SEE OUR SHAME.

**Comment by PromoFaux** [comment]
@fayetted 

Something has gone wrong with your additions. `01-pihole.conf` is not being updated at the `server=` lines. I have tested @slamanna212 's and it worked fine, so it's something you've changed :)

**Comment by PromoFaux** [comment]
Fixed and merged into slamanna212-development to be reviewed by the rest of the team. Thanks @fayetted and @slamanna212

**Pull request closed without merging**
