### PR TITLE
Added - Readme Windows Tray App

### PR DESCRIPTION
**Pull request by goldbattle**
Changes proposed in this pull request:
* Updated the readme to include a windows tray application I wrote
* Thought some people might find it interesting
* Link - https://github.com/goldbattle/copernicus

Sorry about the first PR, should have known better. Thanks!
@pi-hole/gravity

### CODE REVIEW

**Comment by Mcat12** [comment]
Approved (Merge in the latest changes)

**Comment by dschaper** [comment]
Approved (with updates from development merged in please @goldbattle)

**Comment by jacobsalmela** [comment]
Approve

**Comment by dschaper** [comment]
@goldbattle We can merge this PR as soon as you pull the latest changes from development into your branch and then push your PR branch again.

**Comment by goldbattle** [comment]
Thanks!

**Pull request merged**
