### PR TITLE
add parameter to set filename for teleporter

### PR DESCRIPTION
**Pull request by lschloetterer**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/contributing/).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*

Make it possible to write pihole -a -t myname.tar.gz to configure the filename however you want.
Using only pihole -a -t still gives you the same auto-generated filename as before.

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*

Check if parameter is given and use it for the redirect.

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*

Add second option for the teleporter command with a filename parameter

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by DL6ER** [comment]
Please add a comment about the possibility to specify a custom filename to the `helpFunc` in the same file.

**Comment by lschloetterer** [comment]
Like this? You could probably use something like `teleporter [filename]` too, but it's not like this for the other commands.

**Comment by PromoFaux** [comment]
> Like this?

This is fine for me, maybe we could go as far as adding something like `e.g pihole teleporter myfilename.tar.gz`

Another thought, maybe we should make the `tar.gz` just happen by default, so the usage would be `pihole teleporter myfile`

**Comment by rdwebdesign** [comment]
Every test will fail to CentOS 8 (EOL).

**Comment by lschloetterer** [comment]
> maybe we could go as far as adding something like e.g pihole teleporter myfilename.tar.gz

Done.

> maybe we should make the tar.gz just happen by default

I'm not too much a fan of this idea, as it would break for example `pihole -a -t $(mktemp)`. Also when using tar it doesn't add it automatically either.

> Every test will fail for CentOS 8 (EOL).

I'm not sure why this is, the only thing I changed after the first commit which passed was text

**Comment by yubiuser** [comment]
> I'm not sure why this is, the only thing I changed after the first commit which passed was text

This is kind of an issue on our side. CentOS 8 is end of file and the test container we used was unable to install software from an now old centos repo. This was fixed now as we switched to CentOS Steam (https://github.com/pi-hole/pi-hole/pull/4596)

**Comment by lschloetterer** [comment]
> This was fixed now as we switched to CentOS Steam (https://github.com/pi-hole/pi-hole/pull/4596)

Ah I see, the checks are now passing again 👍

**Review by PromoFaux — APPROVED** [review]

**Pull request merged**
