### PR TITLE
proposed gravity function renames

### PR DESCRIPTION
**Pull request by PromoFaux**
**By submitting this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#git-commit---signoff))

---

**What does this PR aim to accomplish?:**

After some brief internal discussion, we decided to make the function names within `gravity.sh` make a bit more sense. The Black hole/Star Trek theming is fun, but can be a bit of a block for new contributors. Renaming the functions should make it easier to work out what each function does without having to remember it's name.

This PR does not change any of the actual text output during a run of `pihole -g`.

**How does this PR accomplish the above?:**

Functions renamed, and references updated.

**What documentation changes (if any) are needed to support this PR?:**

N/A ( I think)

### CODE REVIEW

**Comment by dschaper** [comment]
I thought the same thing about the prefix, but it would help contributors to know what script is being called or affected by the function. If it goes to a library of functions then the specificity would be nice to differentiate the functions.

**Comment by PromoFaux** [comment]
Yeah, that was my thinking with leaving the `gravity_` in. If the script is sourced, then it will make more sense using the functions from another script.

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-v3-3-released-its-extra-special/7159/1

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-v3-3-released-its-extra-special/7159/1

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-v3-3-released-its-extra-special/7159/1

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-v3-3-released-its-extra-special/7159/1

**Comment by PromoFaux** [comment]
ALRIGHT @pralor CHILL OUT.

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-v3-3-released-its-extra-special/7159/1

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-v3-3-released-its-extra-special/7159/1

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-v3-3-released-its-extra-special/7159/1

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-v3-3-released-its-extra-special/7159/1

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-v3-3-released-its-extra-special/7159/1

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-v3-3-released-its-extra-special/7159/1

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-v3-3-released-its-extra-special/7159/1

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-v3-3-released-its-extra-special/7159/1

**Pull request merged**
