### PR TITLE
Improve debug log generation

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**

Improve debug log to contain more useful details.

**How does this PR accomplish the above?:**

- Print content of all directories that are relevant for Pi-hole. Only print contents for special files (not all)
- Print content of /etc/dnsmasq.conf 
- Do not include older debug logs in new debug logs (may confuse readers) 
- Print content of all files in `/etc/dnsmasq.d/`

**What documentation changes (if any) are needed to support this PR?:**

None

### CODE REVIEW

**Comment by dschaper** [comment]
https://tricorder.pi-hole.net/m04fkwfkoi/

I think there's a lot more information there than we want to have.

**Comment by jfb-pihole** [comment]
I don’t think we need the contents of /etc/pihole, the lighttpd access log, /var/log. The new setup variables section appears to duplicate what we already have.

**Comment by DL6ER** [comment]
The role of `REQUIRED_FILES` changed. We can just remove and add files here and we'll only get the content for files listed there. The content of `/etc/pihole` is directly related to Pi-hole, so I'd like to keep it. No arguments about removing the access log. It can be helpful, but most of the time it will not, I agree.

Concerning `/var/log`, I'm not sure why a full directory listing is a bad idea. However, I'll swap that with only doing the head and tail on the two relevant log lines.

**Comment by Bucking-Horn** [comment]
From my limited personal mod experience, I agree with jfb:
I've to try hard to remember issues involving the _list_ of files in `/etc/pihole/`or `/var/log/` or the content of lighttpd's access log.; I think I never came across any of those personally.

Related to `/etc/pihole/`, I would keep `install.log` contents, and I'd probably be interested in database integrity for both db files (e.g. from `sudo sqlite3 pihole-FTL.db "PRAGMA integrity_check"`).

Related to `/var/log/`, I sometimes find myself suggesting to look for recent voltage issues in syslog as sort of a general precaution (e.g. `grep -ni 'voltage' /var/log/syslog.*`), but most requests to look at log contents are probably related to specific individual support, often requiring specific configuration of logging parameters beforehand, so likely too specific to be included. 
I'm happy with the current heads/tails for `pihole.log` and `pihole-FTL.log`. On occasions, I find myself wishing it would always include the stats (i.e. the section following `Imported xx queries from the long-term database`); I usually ask OPs for nc API call results then (e.g. `echo ">stats >quit" | nc localhost 4711`).

Related to `/etc/dnsmasq.d/`, I'd like to see the content for all Pi-hole generated files (currently, the `04-` isn't included).
In addition, I'd probably prefer to see only the list of files in that directory rather than explicit contents.  In some instances, the latter could produce thousands of lines with hostnames (e.g. see https://discourse.pi-hole.net/t/whitelist-is-not-allowing-access-to-things-that-are-on-adlists/36496/31). I think that knowing potentially conflicting files do exist will already prove helpful.

**Comment by jfb-pihole** [comment]
From both a user standpoint and a tech support standpoint, I don't see any need to show the directory contents of /var/log.  This is fairly standard across Linux distributions and there is rarely anything of interest there to troubleshoot a Pi-hole problem.  If needed, it's a simple request to the user to show a command output for further troubleshooting.  In the specific case on one of my Pi-hole installs, there is quite a list of stuff in /var/log and that's a lot to wade through in exchange for no usable information:
```
ls -lha /var/log
total 5.0M
drwxr-xr-x 12 root        root     4.0K Nov 18 00:00 .
drwxr-xr-x 12 root        root     4.0K Aug  5  2018 ..
-rw-r--r--  1 root        root        0 Oct 26 00:00 alternatives.log
-rw-r--r--  1 root        root      112 Oct 25 12:35 alternatives.log.1
-rw-r--r--  1 root        root      169 May 24  2019 alternatives.log.10.gz
-rw-r--r--  1 root        root      228 Apr 14  2019 alternatives.log.11.gz
-rw-r--r--  1 root        root      338 Mar 31  2019 alternatives.log.12.gz
-rw-r--r--  1 root        root      317 Aug  5 02:23 alternatives.log.2.gz
-rw-r--r--  1 root        root      211 Jul  8 21:13 alternatives.log.3.gz
-rw-r--r--  1 root        root      275 Feb 19  2020 alternatives.log.4.gz
-rw-r--r--  1 root        root      244 Oct 29  2019 alternatives.log.5.gz
-rw-r--r--  1 root        root      250 Sep 22  2019 alternatives.log.6.gz
-rw-r--r--  1 root        root      171 Aug 20  2019 alternatives.log.7.gz
-rw-r--r--  1 root        root     4.4K Aug  6  2019 alternatives.log.8.gz
-rw-r--r--  1 root        root      394 Jun 30  2019 alternatives.log.9.gz
drwxr-xr-x  2 root        root     4.0K Nov 14 20:27 apt
-rw-r-----  1 root        adm      160K Nov 18 09:40 auth.log
-rw-r-----  1 root        adm      302K Nov 15 00:00 auth.log.1
-rw-r-----  1 root        adm       19K Nov  8 00:00 auth.log.2.gz
-rw-r-----  1 root        adm       20K Nov  1 00:00 auth.log.3.gz
-rw-r-----  1 root        adm       20K Oct 25 00:00 auth.log.4.gz
-rw-r--r--  1 root        root     180K Nov 17 12:31 boot.log
-rw-r--r--  1 root        root        0 Jun 26  2018 bootstrap.log
-rw-rw----  1 root        utmp        0 Nov  1 00:00 btmp
-rw-rw----  1 root        utmp      384 Oct  7 10:57 btmp.1
-rw-r-----  1 root        adm      1.1M Nov 18 09:45 daemon.log
-rw-r-----  1 root        adm      130K Nov 15 00:00 daemon.log.1
-rw-r-----  1 root        adm      8.7K Nov  8 00:00 daemon.log.2.gz
-rw-r-----  1 root        adm      9.5K Nov  1 00:00 daemon.log.3.gz
-rw-r-----  1 root        adm      8.7K Oct 25 00:00 daemon.log.4.gz
-rw-r-----  1 root        adm      4.2K Nov 17 12:31 debug
-rw-r-----  1 root        adm       303 Nov 14 20:33 debug.1
-rw-r-----  1 root        adm       105 Nov  5 16:45 debug.2.gz
-rw-r-----  1 root        adm       126 Oct 30 12:23 debug.3.gz
-rw-r-----  1 root        adm       126 Oct 22 10:44 debug.4.gz
-rw-r--r--  1 root        root     4.6K Jun  8 21:42 dns-test.txt
-rw-r--r--  1 root        root     1.1K Nov 14 20:27 dpkg.log
-rw-r--r--  1 root        root      24K Oct 25 12:35 dpkg.log.1
-rw-r--r--  1 root        root      319 Mar 22  2020 dpkg.log.10.gz
-rw-r--r--  1 root        root     6.1K Feb 27  2020 dpkg.log.11.gz
-rw-r--r--  1 root        root      523 Jan 30  2020 dpkg.log.12.gz
-rw-r--r--  1 root        root     1.4K Sep 17 12:40 dpkg.log.2.gz
-rw-r--r--  1 root        root     2.6K Aug 15 14:29 dpkg.log.3.gz
-rw-r--r--  1 root        root     1.2K Jul 14 10:36 dpkg.log.4.gz
-rw-r--r--  1 root        root      424 Jun  9 06:25 dpkg.log.5.gz
-rw-r--r--  1 root        root     3.4K May 29 10:30 dpkg.log.6.gz
-rw-r--r--  1 root        root      577 Apr 24  2020 dpkg.log.7.gz
-rw-r--r--  1 root        root     1.9K Apr 22  2020 dpkg.log.8.gz
-rw-r--r--  1 root        root      571 Apr  7  2020 dpkg.log.9.gz
drwxr-s---  2 Debian-exim adm      4.0K Nov 18 00:00 exim4
-rw-r--r--  1 root        root      24K Sep 17 12:36 faillog
-rw-r--r--  1 root        root     3.3K Apr 22  2020 fontconfig.log
-rw-r-----  1 root        adm         0 Nov 18 00:00 kern.log
-rw-r-----  1 root        adm       85K Nov 17 12:31 kern.log.1
-rw-r-----  1 root        adm      7.0K Sep 21 10:48 kern.log.2.gz
-rw-r-----  1 root        adm      7.0K Sep 19 11:15 kern.log.3.gz
-rw-r-----  1 root        adm      7.0K Jun  3 11:59 kern.log.4.gz
-rw-rw-r--  1 root        utmp     286K Nov 18 09:34 lastlog
drwx--x--x  2 root        root     4.0K Nov 17 12:18 lightdm
drwxr-x---  2 www-data    www-data 4.0K Nov 15 00:00 lighttpd
-rw-r-----  1 root        adm         0 Sep 24 00:00 mail.err
-rw-r-----  1 root        adm       268 Sep 23 09:31 mail.err.1
-rw-r-----  1 root        adm         0 Sep 24 00:00 mail.info
-rw-r-----  1 root        adm       268 Sep 23 09:31 mail.info.1
-rw-r-----  1 root        adm         0 Sep 24 00:00 mail.log
-rw-r-----  1 root        adm       268 Sep 23 09:31 mail.log.1
-rw-r-----  1 root        adm         0 Sep 24 00:00 mail.warn
-rw-r-----  1 root        adm       268 Sep 23 09:31 mail.warn.1
-rw-r-----  1 root        adm       88K Nov 18 00:00 messages
-rw-r-----  1 root        adm      1.2K Nov 15 00:00 messages.1
-rw-r-----  1 root        adm       181 Nov  8 00:00 messages.2.gz
-rw-r-----  1 root        adm       181 Nov  1 00:00 messages.3.gz
-rw-r-----  1 root        adm       179 Oct 25 00:00 messages.4.gz
drwxr-xr-x  2 ntp         ntp      4.0K Mar 21  2019 ntpstats
drwxr-xr-x  2 root        root     4.0K Feb 20  2019 openvpn
drwxr-xr-x  2 pihole      pihole   4.0K Aug  5  2018 pihole
-rw-r--r--  1 root        pihole    33K Oct 29 19:37 pihole_debug.log
-rw-r--r--  1 root        root      24K Feb  4  2019 pihole_debug-sanitized.log
-rw-r--r--  1 pihole      pihole    783 Nov 18 09:00 pihole-FTL.log
-rw-r--r--  1 pihole      pihole    23K Nov 18 00:00 pihole-FTL.log.1
-rw-r--r--  1 pihole      pihole    446 Nov 17 00:00 pihole-FTL.log.2.gz
-rw-r--r--  1 pihole      pihole   2.7K Nov 16 00:00 pihole-FTL.log.3.gz
-rw-r--r--  1 pihole      pihole   286K Nov 18 09:46 pihole.log
-rw-r--r--  1 pihole      pihole   357K Nov 18 00:00 pihole.log.1
-rw-r--r--  1 pihole      pihole    38K Nov 17 12:11 pihole.log.2.gz
-rw-r--r--  1 pihole      pihole    72K Nov 17 00:00 pihole.log.3.gz
-rw-r--r--  1 pihole      pihole    84K Nov 16 00:00 pihole.log.4.gz
-rw-r--r--  1 pihole      pihole   3.7K Nov 15 00:00 pihole.log.5.gz
-rw-r--r--  1 root        root     1.4K Nov 15 04:09 pihole_updateGravity.log
drwx------  2 root        root     4.0K Aug  6  2019 private
drwxr-x---  2 root        adm      4.0K Mar  5  2018 samba
-rw-r-----  1 root        adm      477K Nov 18 09:45 syslog
-rw-r-----  1 root        adm      732K Nov 18 00:00 syslog.1
-rw-r-----  1 root        adm      4.0K Nov 17 00:00 syslog.2.gz
-rw-r-----  1 root        adm      4.8K Nov 16 00:00 syslog.3.gz
-rw-r-----  1 root        adm      5.1K Nov 15 00:00 syslog.4.gz
-rw-r-----  1 root        adm      3.8K Nov 14 00:00 syslog.5.gz
-rw-r-----  1 root        adm      3.9K Nov 13 00:00 syslog.6.gz
-rw-r-----  1 root        adm      3.8K Nov 12 00:00 syslog.7.gz
-rw-r-----  1 root        adm         0 Nov 18 00:00 user.log
-rw-r-----  1 root        adm      7.0K Nov 17 12:31 user.log.1
-rw-r-----  1 root        adm       546 Sep 21 10:48 user.log.2.gz
-rw-r-----  1 root        adm       535 Sep 19 11:15 user.log.3.gz
-rw-r-----  1 root        adm       18K Jun  3 11:59 user.log.4.gz
drwxr-xr-x  2 root        root     4.0K Nov 17 12:11 wicd
-rw-rw-r--  1 root        utmp     339K Nov 18 09:34 wtmp
-rw-rw-r--  1 root        utmp     8.3K Aug  1  2019 wtmp.1
-rw-r--r--  1 root        root     4.4K Nov 17 12:18 Xorg.0.log
-rw-r--r--  1 root        root     4.4K Nov 17 12:18 Xorg.0.log.old
```

Similar for the install log contents - unless a user has specific problems, we don't need this, and if they do, we can ask for it.  I can't think of two times I have asked for this after reviewing about a thousand debug logs.

I would like the addition of the 24 hour query history - this is frequently a follow up question.  It sometimes appears in the output of the pihole-FTL.log, but not always.

I read over a hundred debug logs a month, I would estimate.  The simpler and more concise we keep this, the more users we can assist.

**Comment by dschaper** [comment]
My reason for not wanting `/var/log` is that it contains files we have no business looking at. 

The debugger has some sanitizing functions written for it to remove data that isn't directly related to Pi-hole and the reason (I think) that it's been widely accepted is that it only looks for what we need and nothing more. We only have that data for 48 hours but I don't want to have access or storage of anything not absolutely necessary. 

Privacy is priority for me. Even if that privacy causes more work in the long run.

**Comment by DL6ER** [comment]
Just to make this clear for anyone else looking at this: My changes would not include any content of any file inside `/var/log`. There mere listing of the files (`ls /var/log`) didn't seem like something touching privacy aspects. I may be wrong about this.

The changes requested require basically redoing this from scratch rather than unwinding most of the changes in here. I'll start with a new PR once I'm ready. Thanks for your feedback. I'll use it in the next debugger improvements iteration.

---

One slight note: @Bucking-Horn I'm not sure `sudo sqlite3 pihole-FTL.db "PRAGMA integrity_check"` has the intended effect. It may show if there is corruption in the headers of the database (and in the table schema). While it does scan the index registers, it doesn't do a full walk of the tree so it may miss some errors that are only apparent when reading from these tables. In addition, it is a very slow procedure (checking if all pointers actually correspond to valid leaf nodes, verifying the freelist, and a few more steps). For instance, it just took 15 seconds on my database on a proper HP (Ubuntu) server (no Raspberry hardware). SO I'm not dismissing this lightly, but I'm still saying no :-)

**Pull request closed without merging**
