### PR TITLE
Grouped common dependencies of distros

### PR DESCRIPTION
**Pull request by WouterServaes**
**What does this PR aim to accomplish?:**

It groups the common dependencies into variables

**How does this PR accomplish the above?:**

It groups the common dependencies for development branch packages, removes these from the original variables. This also add the new variable to the argument list of the install dependent package calls

**Link documentation PRs if any are needed to support this PR:**

No documentation changes required

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x ] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Review by yubiuser — DISMISSED** [review]

**Comment by WouterServaes** [comment]
The common dependencies should also be uninstalled in the uninstall script

**Review by yubiuser — APPROVED** [review]

**Comment by yubiuser** [comment]
The uninstaller needs some attention...

**Comment by yubiuser** [comment]
@WouterServaes 

This repo requires all commits to be signed before they can be merged.

https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by WouterServaes** [comment]
Sorry for wasting your time and thank you for taking the time to review this.

**Comment by yubiuser** [comment]
Thanks for your PR.

**Pull request merged**
