### PR TITLE
Pi-hole beta releases

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'development' branch!}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#git-commit---signoff))

---

**What does this PR aim to accomplish?:**

We are investigating if we can use GitHub's Pre-Releases for "beta" releases.

Pre-releases allow users to begin using new features and functionality before they're officially launched. As we polish the final release, feedback from beta-testing users will ensure the release works flawless for as many use cases as possible when the project moves to a general release.
Pre-releases are ready to be used to run Pi-hole in controlled environments - most importantly all users should be aware of the pre-release nature - but they should not be used in full production situations.

While users can already now participate in `alpha` testing by checking out the `development` branches, this is more like a rolling release, it is changed all of the time and it breaks every now and then.

However, a `beta` release would be a pre-release where we have done all testing from our side already. Hence, the risk for failures is very small but given the diversity of user installations, we have long outgrown the ability to test each and every configuration on any imaginable device ourselves. Beta-users can do this as they are aware of the fact that there may be some minor glitches in the release and help us improving the release before we go for a general release. They profit from getting new features early on and having the chance to improve/modify new features as they think would be best.

### CODE REVIEW

**Comment by dschaper** [comment]
I think another idea is to use something similar to what I've seen on other repositories. When we are in between releases, periodically grab a snapshot of development when it's stable and tag a release candidate. Then we could Pre-Release on GitHub with that tag.

**Comment by unclehowell** [comment]
How can you install pihole without going through the whiptail menu? I tried to use a python keystroke generator to simulate me hitting enter 9 times, but I'm sure there must be an easier solution. One script exists on GitHub but its outdated

**Comment by dschaper** [comment]
Open an issue, don't post on random Pull Requests that have nothing to do with what you need.

**Comment by Mcat12** [comment]
Closing this as the web PR was also closed.

**Pull request closed without merging**
