### PR TITLE
QueryFunc() rewrite

### LINKED ISSUE #1330: Potential optimizations for queryFunc()
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

5

---
**[ISSUE] Expected Behaviour:**
When using `pihole -q`, returning results for manually blacklisted (or wildcard listed) should be fast. 

**[ISSUE] Actual Behaviour:**
Returning results for manually blacklisted sites are slow, as [`queryFunc()`](https://github.com/pi-hole/pi-hole/blob/de6aaf18abf414f297abd09f30e767a37341bc37/pihole#L109) scans `/etc/pihole/list.*` before everything else.

**[ISSUE] Steps to reproduce:**
Manually blacklist a site (either exact or wildcard), and run `pihole -q`

**Extra thoughts:**
While developing my block page, I've been considering *first* checking `/etc/pihole/blacklist.txt` and `/etc/dnsmasq.d/03-pihole-wildcard.conf` via PHP to increase the speed in which the block page loads, but I think it'd be better to provide a fix rather than a workaround.

This appears to achieve the result I'm looking for:

```
queryFunc() {
  domain="${2}"
  method="${3}"
  
  # Scan for possible wildcard matches
  if [ -e "${wildcardlist}" ]; then
    local wildcards=($(processWildcards "${domain}"))
    for wdomain in ${wildcards[@]}; do
      result=$(scanList "\/${domain}\/" ${wildcardlist})
      # Remove empty lines before couting number of results
      count=$(sed '/^\s*$/d' <<< "$result" | wc -l)
      if [[ ${count} > 0 ]]; then
        echo "::: Wildcard blocking ${domain} (${count} results)"
        echo "${result}"
        echo ""
        exit 0
      fi
    done
  fi
  
  lists=(/etc/pihole/blacklist.txt /etc/pihole/list.*)
  for list in ${lists[@]}; do
    if [ -e "${list}" ]; then
      result=$(scanList ${domain} ${list} ${method})
      # Remove empty lines before couting number of results
      count=$(sed '/^\s*$/d' <<< "$result" | wc -l)
      echo "::: ${list} (${count} results)"
      if [[ ${count} > 0 ]]; then
        echo "${result}"
        [ ${list} = "/etc/pihole/blacklist.txt" ] && exit 0
      fi
      echo ""
    else
      echo "::: ${list} does not exist"
      echo ""
    fi
  done

  exit 0
}
```

The idea is to search wildcards and `blacklist.txt` first (running `exit 0` after a match so that `/admin/scripts/pi-hole/php/queryads.php` can return the final result faster), before scanning `list.*` files.

As I don't have a full understanding of the Pi-hole codebase (and therefore any potential ramifications this may incur), I feel it'd be better to raise this as an issue to be discussed, rather than a pull request.

**Differences in loading time:**
[Current `queryFunc()`](https://github.com/pi-hole/pi-hole/blob/de6aaf18abf414f297abd09f30e767a37341bc37/pihole#L109):
* test.com: 1.98s/1.96s/1.98s
* lb.usemaxserver.de (Manually blacklisted):  1.67s/1.66s/1.64s
* gas.com (Wildcard blacklisted): 1.95s/1.94s/1.96s

Above `queryFunc()`:
* test.com: 1.97s/1.97s/1.98s
* lb.usemaxserver.de (Manually blacklisted): 0.22s/0.22s/0.22s
* gas.com (Wildcard blacklisted): 0.15s/0.15s/0.15s

Above `queryFunc()`, changing `/etc/pihole/list.*` to read `/etc/pihole/list.*.domains` (Bypassing preEventHorizon):
* test.com: 1.75s/1.73s/1.75s
* lb.usemaxserver.de (Manually blacklisted): Unchanged
* gas.com (Wildcard blacklisted): Unchanged

### PR DESCRIPTION
**Pull request by WaLLy3K**
**By submitting this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

5

---
With these changes, running `pihole -q doubleclick.com` (searching over 1.6m blocked domains between 55 lists) is returned in 0.628s on a Pi 3B. This has the benefit of bringing the page load time of the block page (parsing the exact results of `doubleclick.com` from `queryads.php` serverside) to a mere 0.22s instead of 1.98s.

PR resolves #1330

### CODE REVIEW

**Comment by PromoFaux** [comment]
Something doesn't seem right with the `exact` flag...

```
pi@pihole:/etc/.pihole$ pihole -q www.doubleclick.net
/etc/pihole/list.0.raw.githubusercontent.com.domains:0.0.0.0 www.doubleclick.net
/etc/pihole/list.2.sysctl.org.domains:127.0.0.1  www.doubleclick.net
/etc/pihole/list.6.hosts-file.net.domains:127.0.0.1     www.doubleclick.net
/etc/pihole/list.6.hosts-file.net.domains:127.0.0.1     www.doubleclick.net.my
pi@pihole:/etc/.pihole$ pihole -q www.doubleclick.net -exact
::: No exact results found for www.doubleclick.net

```

**Comment by PromoFaux** [comment]
Approved pending fix of `-exact` flag

**Comment by WaLLy3K** [comment]
Good find! All the lists I pull are a domains only format, and therefore, I should have stopped to think why `/s` was there in the first place.

Thanks.

**Comment by PromoFaux** [comment]
Approved.

(Though I might frig about with the output format at a later date!)

**Pull request merged**
