### PR TITLE
use py3 instead py2

### PR DESCRIPTION
**Pull request by jnozsc**
Signed-off-by: jnozsc <jnozsc@gmail.com>

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
replace usage of python2

**How does this PR accomplish the above?:**
use python3

**What documentation changes (if any) are needed to support this PR?:**
NA

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by dschaper** [comment]
This looks good to me, just not sure if this needs to be in release/v5.0 or development.

**Comment by dschaper** [comment]
Would 3.4 or 3.6 work as well? I don't see anything that would prevent those. Travis defaults to 3.6 so I'm comfortable with their tooling to work with that version.

**Comment by jnozsc** [comment]
I recommend to use the latest version, python3.8, so that people don't have to upgrade from py3.x to py3.y in any time next year. It is just personal preference.

https://devguide.python.org/#status-of-python-branches

About python 3.4 or python 3.6 compatibly. I think it should work with any python 3 version. But I do notice some packages will/is drop(ing) 3.4 support since it has already EOL (check the link above)

**Comment by dschaper** [comment]
I'd like 3.6. The reason being that if we say 3.8 then we are making a contract to support any features that may be in 3.8. Ubuntu 18 ships with 3.6, travis is default 3.6 (though you can change that of course). I'd prefer to have it be the lowest possible version required so the largest number of people can contribute to it.

**Comment by jnozsc** [comment]
ok, fixed in https://github.com/pi-hole/pi-hole/pull/3153/commits/49fc2650f985816d93098bea1d3d83ca02da6e4d

**Comment by dschaper** [comment]
@PromoFaux Any preference on the branch this should merge in to?

**Comment by PromoFaux** [comment]
Either is fine I think. The knot python we have is in the tests, so it's not actually going to affect anything in userland, and no real rush to get it "released"

**Comment by dschaper** [comment]
For safety sake I think `development` would be better. Release 5 is very close and I don't want to throw something in there that may cause unintended issues.

jnozsc, can you send this to `development` instead of `release/v5.0` and I'll merge it.

**Comment by jnozsc** [comment]
changed. thanks all

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-5-1-released/35577/1

**Pull request merged**
