### PR TITLE
[WIP] PHP7 on CentOS7

### PR DESCRIPTION
**Pull request by bcambl**
**By submitting this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#git-commit---signoff))

---

**What does this PR aim to accomplish?:**

PHP 7 on CentOS 7 via Software Collections

**How does this PR accomplish the above?:**

CentOS 7 ships with PHP 5.4 which is EOL. 
This PR will install PHP 7 via Software Collections

**What documentation changes (if any) are needed to support this PR?:**

Fedora/CentOS Support:
 - CentOS 7.x (x86_64)
 - Fedora 26/27 (ARM/x86_64) (note: Fedora 25 is EOL as of December 12th, 2017)

WIP - Additional commits are expected for code and comment corrections.

### CODE REVIEW

**Comment by Mcat12** [comment]
Is this still WIP?

**Comment by bcambl** [comment]
I still need to make a small change.. but I am tempted to just archive based on [Pi-hole Web Interface: The Next Generation](https://pi-hole.net/2018/01/13/pi-hole-web-interface-the-next-generation/).

These changes would only be **required** if it is decided to drop support for PHP 5.4.
There is some value to users who appreciate using supported language versions, but we could likely leave out this additional complexity if we plan to drop PHP in the future.

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/1st-install-doesnt-work/7268/3

**Comment by bcambl** [comment]
Archiving. May re-open in the future if required.

**Comment by theooze** [comment]
w/o the check for a working php7 install from the IUS or SCL repo (or elsewhere), the pihole updater installs the php 5.4 rpms which don't need to be installed.

**Pull request closed without merging**
