### PR TITLE
Filtering harmful queries

### PR DESCRIPTION
**Pull request by ysfemritte**
**By submitting this pull request, I confirm the following:** 
*Please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented on my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by dschaper** [comment]
Can you explain what this change is, what it does, why it's needed?

**Comment by PromoFaux** [comment]
Looking over the code, I'm now wondering why the debug script does not use the upstream servers that the user has chosen (by sourcing `setupVars.conf`)

Did we choose to hardcode for a reason?

**Comment by dschaper** [comment]
Just picking an endpoint that is known to be up and working. If the user selected remote is down then a false positive failure could happen to make the user think it's a local problem when in fact it's a remote problem. We've had the discussion before I think and I guess nothing came of it.

**Comment by PromoFaux** [comment]
I guess at least with `8.8.8.8` we can pretty much guarantee that it will be working for everyone (except [sometimes in turkey](https://en.wikipedia.org/wiki/Google_Public_DNS#Censorship_in_Turkey), but that's a bigger issue than Pi-hole 😏)

That in mind, I don't massively see any benefit of changing to `9.9.9.9` as an alternative (unless it was added as an additional check in cases where no route can be found `8.8.8.8`). At that rate, might as well stick in `1.1.1.1` too. Where do we stop??

**Pull request closed without merging**
