### PR TITLE
Fix 725 and 653

### LINKED ISSUE #725: Ubuntu 16.04 - Errors on missing php5 packages on install / upgrade.
Ubuntu server LTS 16.04 does not provide repositories for php5. Instead, it's possible to use the packages `php-common`, `php-cgi` and `php` which point at php7-*

##### Expected Behaviour:
Pi-hole should be able to support depending on either `php5-*` or `php-*`, depending on the platform.

##### Actual Behaviour:
Pi-hole logs errors during installation/upgrade stage. Pi-hole admin interface is not usable after installation unless php is manually installed.

##### Steps to reproduce this issue:
1. Install Ubuntu Server 16.04 LTS
2. Install pi-hole.
3. Read install.log

```
::: Checking Pi-Hole dependencies:
:::    Checking for dnsutils... already installed!
:::    Checking for bc... already installed!
:::    Checking for dnsmasq... already installed!
:::    Checking for lighttpd... already installed!
:::    Checking for php5-common... Not found! Installing.... [/]  E: Package 'php5-common' has no installation candidate
 done!
:::    Checking for php5-cgi... Not found! Installing.... [/]  E: Package 'php5-cgi' has no installation candidate
 done!
:::    Checking for php5... Not found! Installing.... [/]  E: Package 'php5' has no installation candidate
 done!
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/37994119-ubuntu-16-04-errors-on-missing-php5-packages-on-install-upgrade?utm_campaign=plugin&utm_content=tracker%2F3011939&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F3011939&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by PromoFaux**
Fixes #725 and #653   .

Changes proposed in this pull request:

- Check if php5 is available in apt-cache, if so install it, else just install php

@pi-hole/gravity

### CODE REVIEW

**Comment by PromoFaux** [comment]
Approved

**Comment by dschaper** [comment]
:+1:

**Comment by PromoFaux** [comment]
Should also close #567

**Comment by jacobsalmela** [comment]
Approved

**Pull request merged**
