### PR TITLE
remove static routers

### PR DESCRIPTION
**Pull request by shawaj**
remove static routers declaration as it breaks the ability to move the same device between different hardware routers if they use a different ip address

Signed-off-by: Aaron Shaw <shawaj@gmail.com>

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*

Fix issues with moving routers due to the setting of static routers

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*

By removing the line

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*

None

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by dschaper** [comment]
@shawaj I'm not going to break every other Pi-hole install to fix an issue with your now unauthorized kit.

**Comment by PromoFaux** [comment]
Same answer, for the same submisson: https://github.com/pi-hole/pi-hole/pull/3093#issuecomment-577318137

**Comment by shawaj** [comment]
@dschaper "this will break a whole lot of things" - which things are they?

**Comment by dschaper** [comment]
IP networking, something very essential to DNS servers.

**Comment by PromoFaux** [comment]
To be a little more specific, it's the equivalent of the `gateway` option in a windows network setup.

Without that, the Pi (or any device Pi-hole is installed on) will not know where to route any network traffic... so, one could say it is essential.

**Comment by shawaj** [comment]
@PromoFaux sure - but that doesn't need to be statically set on the pi (nor does the IP). It would make more sense to do this from the router IMHO.

I know you all hate me, for whatever reason, but just trying to help.

**Comment by dschaper** [comment]
It's a DNS server, do you propose that it has a dynamic address that moves and renders all clients broken??

**Comment by PromoFaux** [comment]
If I have a server with a statically assigned IP address (on the server, not using DHCP reservation) then I would not be in the least surprised that I would need to update the networking configuration on the server if I moved it onto a different network / bought a new router that had a different LAN configuration. 

That said, every time I have changed  my router, I just configure that to match that of my "old" network. Much simpler.

**Comment by shawaj** [comment]
@dschaper please put down your guns for a minute. As always, I am only trying to help and you are just being utterly hostile in return.

I never said a dynamic address. I just said it would be better to set it on the router, not the Pi

@PromoFaux  get what you are saying, and totally fair enough - i just thought that from a users perspective it makes it easier if they don't have to dig into terminal commands and can just update it via the router GUI (which most routers have these days) - difference of opinion I guess.

Also - as a side note - it is perhaps worth covering this in the Wiki somewhere. I appreciate it is an edge case, but it is likely to come up again at some point in the future when someone gets a new router and their Pi-hole stops working and they can't work out why.

**Comment by dschaper** [comment]
Router GUIs vary vastly and have very different feature sets. Some don't do DHCP, some do and don't allow for any kind of modification, some allow full use. Relying on users setting routers would create a huge load of support requests asking for us to set their routers for them. We answer every user question asked so that would grind Pi-hole development to a halt. 

And yes, I am very disappointed to have to read https://twitter.com/shawaj2/status/1218615426768195584

**Comment by shawaj** [comment]
@dschaper fair enough, aprreciate your resources are limited. I obviously have never been unlucky enough to have had a router that doesn't allow you to set static IPs!

Is your wiki editable? I would be more than happy to add something explaining the situation in #2723 saying that if people change their router and it has a default address that is different to what they originally set they may have to run the setup again.

Appreciate you might not want me to though, hence asking in advance.

Re the tweet - happy to delete all tweets in our little tiff the other day, if you are happy to do the same. I will follow up via email on that though so as not to litter your GitHub with this stuff.

**Comment by dschaper** [comment]
The wiki is deprecated, all documentation is done on the pi-hole/docs repository. I have no issues with a PR on that adding more information.

As to tweets, no, I prefer to keep the public record public. I have nothing to hide of my comments.

**Comment by shawaj** [comment]
@dschaper - ok will write something and submit it 👍

I have nothing to hide of my comments either so will leave them then.

**Comment by alasdairdc** [comment]
@dschaper Out of interest would you be willing to accept this in alternate form, e.g. only if a specific switch / option `standalone` has been issued as an argument on the command or as part of a whiptail menu?  /u/deatharse noticed the issue of the default routes being clobbered when installed on a pinephone as a standalone [Pinephone + UBPorts + Pi-hole](https://www.reddit.com/r/PINE64official/comments/f3edb1/pinephone_ubports_pihole/fhkr9os)

**Comment by dschaper** [comment]
Take a look at the https://github.com/pi-hole/pi-hole/tree/release/v5.0 branch and see if that has improved the situation. We've already removed the localhost DNS server configuration. I'm not sure about adding in more switches but we've talked about making the installer capable of parsing options passed during install. Whiptails just get mashed through without anyone really reading it.

I'm more inclined to just remove the whole IP addressing system and have users configure it themselves.

**Comment by alasdairdc** [comment]
I agree not messing around with the network settings at all of the device Pi-Hole is installed on would be best.

**Pull request closed without merging**
