### PR TITLE
[RELEASE] Pi-hole Core 2.12.1

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 10

---

[RELEASE] Pi-hole Core 2.12.1

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by dschaper** [comment]
Approved

**Comment by PromoFaux** [comment]
Approved

**Comment by Mcat12** [comment]
Approved

**Comment by jacobsalmela** [comment]
Approved

**Comment by jpgpi250** [comment]
DL6ER, could you please explain why you are adding #su # to the logrotate configuration file. Eager to learn. Has this been tested on a pi (raspbian jessie lite) as I noticed the remark "required for ubuntu". If needed, I can test this, given instructions, I've noticed you also changed something in the installation script, for this to work, but don't really understand. Thanks for your effort.

**Comment by PromoFaux** [comment]
Approved

Confirmed not broken on Debian.

@jpgpi250 You can alway try out the bleeding-edge by switching to the development branch in your local repos, though be aware that things are likely to break at any time!

```bash
sudo rm -rf /etc/.pihole
sudo rm -rf /var/www/html/admin
sudo git clone https://github.com/pi-hole/pi-hole.git /etc/.pihole
sudo git clone https://github.com/pi-hole/adminLTE.git /var/www/html/admin

cd /etc/.pihole
git checkout development

cd /var/www/html/admin
git checkout devel

pihole -r (choose repair here)
```

The footer versions on the web admin should read : `Pi-hole Version vDev (development, v2.12-14-gda05491) Web Interface Version vDev (devel, v2.3.1-111-g2e44c68)` for this version

**Comment by dschaper** [comment]
Approved

**Comment by DL6ER** [comment]
@jpgpi250 I'm sorry, I seem to have overlooked your response.

It has been tested on all supported OSes. However, last time we skipped Ubuntu 16.04.1 because we successfully tested Ubuntu 16.10. However, now it turned out that Ubuntu 16.04.1 needs a specific for of the config file, which works also in all other tested OSes (including Raspbian, of course).

As you have already seen I have inserted `# su #` in the `logrotate` template script.
What happens at installation/update is now the following (I will guide you to the corresponding code lines so it is easier to follow):
1. The `logrotate` script is first copied to its new destination `/etc/pihole/logrotate` [here](https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L943)
2. The user and group of the directory `/var/log` is determined and stored in a variable [here](https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L950)
3. The comment you have seen `# su #` is replaced by `su user:group` which has been determined in step 2 [here](https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L952)
4. If the user / group cannot be detected (for whatever reason), step 3 is skipped. However, that shoould not be harmful, since then `# su #` will still be there and a comment should not hurt anyone.

**Pull request merged**
