### PR TITLE
Upsteam DNS enhancement

### PR DESCRIPTION
**Pull request by ChadBHowell**
The purpose of these commits is to do the following:

1) Bring the dnsmasq.conf changes to be inline with how config files are modified on current Debian type systems by using the "*.d" directory. This allows for a cleaner distro upgrade path and avoids stomping our config changes during dnsmasq upgrades.

2) Allow the user to choose between Google and DynDNS upstream servers during the install. This will later be extended to allow the user to enter custom upstream DNS servers as well.

### CODE REVIEW

**Comment by PromoFaux** [comment]
Hey @ChadBHowell , are these the same changes as proposed in your previous pull for this?

**Comment by PromoFaux** [comment]
I'll get @dschaper to look over this, as he was dealing with it before...

**Comment by ChadBHowell** [comment]
Yes.  These are the same changes with a little fix up here and there.  I was new to github and didn't know squat and had to start over using branches.  I have closed the old pull request as it was based on an older dev branch.  Sorry for any confusion.

**Comment by PromoFaux** [comment]
No no, it's all good! I was in the same boat as you last week.. :)

**Comment by ChadBHowell** [comment]
What part needs to be changed?  If you want, I can wait and rebase this when you merge #236 into the dev branch.  That way I can follow the style you set and also make the appropriate changes.  I still believe it is worth while to move dnsmasq.conf to the .d directory to be more inline with how Debian does stuff and protect our config from being squashed during dnsmasq upgrades.

**Comment by dschaper** [comment]
@ChadBHowell Let me take a look and see what we have, I'll be on and off for a bit, re-installing the OS on my main box. I agree with dropping the configs to `/etc/dnsmasq.d/01-pihole.conf` since that's canonical for Debian installs. We'll see what consensus we all come together on.

**Comment by jacobsalmela** [comment]
I second that motion.

**Comment by PromoFaux** [comment]
@ChadBHowell The latest commit you made needs to be changed back to `dnsmasq.conf`, but other than that... all good.

I've made a lot of changes to the install script, probably more to come, so it may be easier to rebase once I'm done.

**Comment by dschaper** [comment]
@ChadBHowell Hi Chad, I'll go ahead and pull this into a test branch in a bit. If anything comes up we'll let you know. There are changes being made to the install script as @PromoFaux mentioned, but we can work on getting everything settled and in the right directories. Thanks again for your submission!

**Comment by dschaper** [comment]
@ChadBHowell I hate to do this to you but can you pull the new master and rebase your changes off of the new master. There was a relatively big update to `basic-install.sh` that you need to pull in. That will help resolving the merge conflicts. Sorry about that.

**Comment by ChadBHowell** [comment]
Closing due to rebase on latest devel branch.  New PR #240.

**Pull request closed without merging**
