### PR TITLE
Update sort command in gravity.sh to use LANG=C

### PR DESCRIPTION
**Pull request by jauderho**
This significantly speeds up the sort command. Measured 6x decrease in time on a VM to process over 6 million entries. Similarly, 4x decrease in time to process the same number of entries on a Raspberry Pi 1.

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X ] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [ X] I have made only one major change in my proposed changes.
- [ X] I have commented my proposed changes within the code.
- [ X] I have tested my proposed changes, and have included unit tests where possible.
- [ X] I am willing to help maintain this change if there are issues with it later.
- [ X] I give this submission freely and claim no ownership.
- [ X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
Speed up the sort process

**How does this PR accomplish the above?:**
By setting LANG=C before the sort command, speedups of 4x-6x observed.

**What documentation changes (if any) are needed to support this PR?:**
No changes needed

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by dschaper** [comment]
Thanks for the submission. Please follow our contributors guide https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md. I see you have checked the box showing your understanding of it. 

Following that guide will be very helpful on this PR.

**Comment by jauderho** [comment]
Turns out that I had a problem with DCO. It's now fixed.

**Comment by dschaper** [comment]
Use the development branch is what I was trying to imply.

**Comment by dschaper** [comment]
```sh
dschaper@Mariner-10:~/Projects/Pi-hole/core$ git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
dschaper@Mariner-10:~/Projects/Pi-hole/core$ cat gravity.sh | grep "sort"
  sort -u "${piholeDir}/${parsedMatter}" > "${piholeDir}/${preEventHorizon}"
  comm -23 "${piholeDir}/${preEventHorizon}" <(sort "${whitelistFile}") > "${piholeDir}/${whitelistMatter}"
dschaper@Mariner-10:~/Projects/Pi-hole/core$ git checkout development
Switched to branch 'development'
Your branch is up to date with 'origin/development'.
dschaper@Mariner-10:~/Projects/Pi-hole/core$ cat gravity.sh | grep "sort"
dschaper@Mariner-10:~/Projects/Pi-hole/core$ 
```

**Comment by jauderho** [comment]
> Use the development branch is what I was trying to imply.

Ah. No worries. I'll resubmit.

**Comment by dschaper** [comment]
It's not in development. There's no need to resubmit.

**Pull request closed without merging**
