### PR TITLE
fix check box spacing

### PR DESCRIPTION
**Pull request by jacobsalmela**
**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [x] 10 (very familiar)

**[FEATURE REQUEST | QUESTION | OTHER]:**

I have seen several issues/PRs with the extra space.  removing the
extra whitespace might help to keep the formatting when being submitted.

### CODE REVIEW

**Comment by dschaper** [comment]
Much better!

**Comment by dschaper** [comment]
:+1:

**Comment by jacobsalmela** [comment]
Oops.  I should fill out the template myself...

**Comment by dschaper** [comment]
And approve it, won't merge without author approval.

**Comment by jacobsalmela** [comment]
Gotta try to get the free T-shirt...

**Comment by jacobsalmela** [comment]
Approved

**Comment by PromoFaux** [comment]
Approved

**Pull request merged**
