### PR TITLE
Remove Deprecated cameleon list

### LINKED ISSUE #3249: CAMELEON hosts file is deprecated
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

10

---
**Expected behaviour:**

No deprecated lists are suggested during Pi-hole's installation.

**Actual behaviour:**

On the [CAMELEON website](https://sysctl.org/cameleon/), the hosts files are listed as deprecated and no longer updated. I downloaded the UNIX format hosts file to check: `# Last updated : 2018-03-17`.
I know this list is quite reputable, but I still wanted to let you know, especially with the CNAME blocking change that's coming in Pi-hole 5.0.

**Steps to reproduce:**

1. Go to the CAMELEON website.
2. Observe that hosts files are listed as deprecated.
3. Download the hosts files.
4. Check the dates of last update are more than two years old.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A

**Troubleshooting undertaken, and/or other relevant information:**

I can submit a PR, should I get a green light to do so. 😄

### PR DESCRIPTION
**Pull request by PromoFaux**
**By submitting this pull request, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**

Removes a list that is no longer maintained from the "defaults"

closes #3249

### CODE REVIEW

**Comment by DL6ER** [comment]
Further information: This list has last been updated on `2018-03-17` according to the first line in that file.

With this list:
> Number of gravity domains: 105269 (**92111 unique domains**)

Without it: 
> Number of gravity domains: 82035 (**81935 unique domains**)

**Comment by dschaper** [comment]
Can we get a diff of the domains that are no longer and see if they even exist anymore? Would be interesting to find the number of NXDOMAINs and the true impact of the list removal.

**Comment by DL6ER** [comment]
Get ID of cameleon table:
```sql
SELECT id FROM adlist WHERE address = 'http://sysctl.org/cameleon/hosts';
3
```

Computer some numbers (see comments):
```sql
SELECT COUNT(DISTINCT domain) FROM gravity;
91969 # Number of distinct domains on gravity with the cameleon list

SELECT COUNT(DISTINCT domain) FROM gravity WHERE adlist_id != 3;
81845 # Number of distinct domains on gravity without the cameleon list

SELECT COUNT(DISTINCT domain) FROM gravity WHERE adlist_id = 3;
20567 # Number of distinct domains on this list

SELECT COUNT(DISTINCT domain) FROM gravity WHERE domain NOT IN (SELECT DISTINCT domain FROM gravity WHERE adlist_id != 3);
10124 # Number of domains only on this list and not in any of the other lists
# This number can also be computed from 91969 - 81845 = 10124
```

We see that almost exactly 50% (49,2%) of the domains on the cameleon list are also already contained in the other lists Pi-hole offers in the installer.

Get the diff list:
```bash
time sqlite3 /etc/pihole/gravity.db "SELECT DISTINCT domain FROM gravity WHERE domain NOT IN (SELECT DISTINCT domain FROM gravity WHERE adlist_id != 3);" > domaindiff.list

real    0m1,058s
user    0m1,047s
sys     0m0,010s
```

Run a small bash script on it:
```bash
#!/bin/bash
file="domaindiff.list"
while IFS= read -r domain
do
  result="$(dig "$domain" @8.8.8.8 | sed '/status:/!d;s/.*status: //g;s/,.*//g')"
  echo "${domain}: ${result}"
done < "$file"
```

and we get (out of the 50% of domains which are NOT contained in the other lists):
- NOERROR (domain exists): 8156
- NXDOMAIN: 1278
- SERVFAIL (Google DNS refused to answer the query): 687

**Comment by DL6ER** [comment]
Just for completeness, when using CF (1.1.1.1) as upstream, the numbers are:
- NOERROR 8696
- NXDOMAIN 1277
- SERVFAIL 151

**Comment by DRS1978** [comment]
Hello there?

Em dom., 30 de nov. de 2025, 05:47, Pralor-bot ***@***.***>
escreveu:

**Pull request merged**
