### PR TITLE
Exit init script with error result code if FTL fails to start

### PR DESCRIPTION
**Pull request by dschaper**
- **What does this PR aim to accomplish?:**

Exit init script with error result code if FTL fails to start

- **How does this PR accomplish the above?:**

Exits init script with non-zero result code if FTL fails to start.

- **What documentation changes (if any) are needed to support this PR?:**

Nothing.

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
- [x] I have read the above and my PR is ready for review. _Check this box to confirm_

### CODE REVIEW

**Comment by yubiuser** [comment]
Should we add `set -e` as well?

**Comment by dschaper** [comment]
I wouldn't add that to an init script.

**Review by yubiuser — APPROVED** [review]

**Comment by dschaper** [comment]
@DL6ER Since you 'own' this part of the code.

**Review by DL6ER — APPROVED** [review]
Seems reasonable.

However, it can only catch very early-on issues happening before daemonization (where `init.d` losses track of the process).

**Comment by yubiuser** [comment]
It's early enough to catch the most common error

```
rockpi@rockpi-4b:~$ sudo /etc/init.d/pihole-FTL start
Not running


dnsmasq: failed to create listening socket for port 53: Address already in use
rockpi@rockpi-4b:~$ echo $?
2
```

**Pull request merged**
