### PR TITLE
Do not account for refactor anymore

### PR DESCRIPTION
**Pull request by yubiuser**
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [ ] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
For discussion.

Removes old code. The installer contained a section which has been introduced to account for renaming variables in the past. This section was introduced [5 years ago](https://github.com/pi-hole/pi-hole/commit/82e7de2aaad483d22c2dab6750d1cc04c049d3ed) with an addition [3 years ago](https://github.com/pi-hole/pi-hole/pull/2115). 
I would argue that users that did not update their Pi-hole in the last 3 years have more severe issues than a broken update script.

The section stats:

> At some point in the future this list can be pruned...

This future might be now

### CODE REVIEW

**Review by DL6ER — APPROVED** [review]
> This future might be now

Yes. The required changes were for v2.10 and v4.0

**Comment by PromoFaux** [comment]
Just a thought, do we still need the `^INSTALL_WEB_SERVER=` logic?

**Comment by yubiuser** [comment]
I don't think so. It is a leftover from https://github.com/pi-hole/pi-hole/pull/2115 (v4.0) when `INSTALL_WEB` was split into `INSTALL_WEB_SERVER` and `INSTALL_WEB_INTEFACE`

**Review by PromoFaux — APPROVED** [review]
Yep, OK - makes sense after reading through the linked pulls. Thanks

**Pull request merged**
