### PR TITLE
Fix IPv6 support when Pi-hole is a router

### LINKED ISSUE #4505: no ipv6 internet access when pi-hole is the router caused by ra-param=*,0,0
### Versions

- Pi-hole:  v5.7
- AdminLTE:  v5.9
- FTL:  v5.12.1

### Platform

- OS and version:  Raspbian Buster

- Platform:  Raspberry Pi 4

### Expected behavior

clients have access to the internet over ipv6

### Actual behavior / bug

clients do not have internet access

### Steps to reproduce

1. Check `Enable IPv6 support (SLAAC + RA)`

## Debug Token

- URL:  https://tricorder.pi-hole.net/zoO4Fa20/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

The problem is caused by `ra-param=*,0,0` in `/etc/dnsmasq.d/02-pihole-dhcp.conf`, which prevents the router from advertising a route. Due to not advertising a route, clients on the subnet have no internet access. `ra-param=*,0,0` appears to be intended behavior to prevent pi-hole from advertising itself as the router when there is already a router present. However, it makes ipv6 completely unusable when pi-hole itself is the router.

### PR DESCRIPTION
**Pull request by Omoeba**
Signed-off-by: Omoeba <38597972+Omoeba@users.noreply.github.com>

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/contributing/).

---
**What does this PR aim to accomplish?:**
- Close #4505 
- This will break any setups where Pi-hole is set to advertise IPv6 prefixes but is _**not**_ the router. However, that is likely a rare configuration.
- A possible alternative is a new `IS_ROUTER` option in `/etc/pihole/pihole-FTL.conf` that changes this behavior if it is set to `true`

**How does this PR accomplish the above?:**
- Remove `ra-param=*,0,0` so Pi-hole will correctly advertise itself as the router

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*
- A note stating that `Enable IPv6 support (SLAAC + RA)` requires Pi-hole to be the router

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by MichaIng** [comment]
> This will break any setups where Pi-hole is set to advertise IPv6 prefixes but is _not_ the router. However, that is likely a rare configuration.

Hmm, actually I would have guessed the other way round: Common setups I see are Pi-hole on a Raspberry Pi (which cannot easily serve as gateway) being the DHCP server + IPv6/RA/SLAAC but not the gateway/router. However, thinking about it now, can Pi-hole, without being the router, actually know which GUA prefix to advertise? Otherwise client's won't be able to do public requests with their LLA addresses 🤔. However, obviously in the past it did not break something, so it would be more sensitive to not break existing setups with an update but instead add another checkbox right below the `IPv6 (SLAAC + RA)` one where it is directly related to.

**Comment by DL6ER** [comment]
>  However, thinking about it now, can Pi-hole, without being the router, actually know which GUA prefix to advertise?

Sure, the router advertises the useable GUA prefix periodically within the network. The Pi-hole uses itself to derive the main interface's address from where Pi-hole takes it (using the address, applying the subnet to isolate the prefix).

**Comment by DL6ER** [comment]
This set of IPv6 options has been carefully designed to work in the vast majority of cases for a large number of devices (Android, iOS, Linux, MacOS, Windows, and also some IPv6-aware Arduino library). This was non-trivial and I'd like it to stay as is.

Our typical advise is to use the "IPv6-support" checkbox on the web interface (leading to the addition of the lines you modified) only if you really want it to be set up like that. If you have any demand in changing it, simply untick the box and add all the parameters you want in a custom config file in `/etc/dnsmasq.d`

**Comment by MichaIng** [comment]
> Sure, the router advertises the useable GUA prefix periodically within the network.

But if the router keeps sending RAs, what purpose do the Pi-hole RAs then serve? And one then needs to (be able to) configure the router RAs to not provide conflicting info, especially DNS name servers. Basically all that is wanted is a GUA prefix and the gateway IP, both with the router knows best about while Pi-hole can only duplicate this info 🤔.

**Comment by dschaper** [comment]
I've resolved a merge conflict that involved a line not modified by this PR. 

@Omoeba can you please verify that this change did not affect your intent with this PR?

**Comment by Omoeba** [comment]
Everything looks good, thank you!

**Comment by dschaper** [comment]
@DL6ER something to look over when you have a chance please.

**Comment by DL6ER** [comment]
@MichaIng Sorry, I missed your last reply. Yes, the intention is nothing else than to duplicate the information at hand (prefix + gateway) and append ourselves as DNS server.

Neither having `enable-ra` (also commented right now) nor `ra-params` causes Pi-hole to not send out any `RA`s at all. As I haven't seen a home-network that is not at least dual-stack in the past years, it should be fine to assume that the client's will find a way to communicate with the Pi-hole using DHCP (IPv4). It is not important to use IPv6 internally to query the DNS server so if this is causing issues, I'm fine with removing this.

**Review by DL6ER — APPROVED** [review]

**Comment by MichaIng** [comment]
Isn't it fragile when the router sends out RAs without Pi-hole as DNS and Pi-hole sends out the same RAs just with itself added as DNS? I mean are clients then not using or bypassing Pi-hole for DNS queries via IPv6 just based on the has RA they received (and adjusted DNS entries accordingly)?

And isn't `ra-param=*,0,0` now breaking the most common setup (according to my observations) where the Pi-hole server is not the router, i.e. if I understand correctly, Pi-hole will now always advertise itself as default gateway, so if it isn't the router, any non-LAN IPv6 request from any client will then fail.

If so, then at least the OP suggested docs change is mandatory, so users know that Pi-hole must be the router/gateway when IPv6 support is enabled.

**Comment by DL6ER** [comment]
> Isn't it fragile when the router sends out RAs without Pi-hole as DNS and Pi-hole sends out the same RAs just with itself added as DNS? I mean are clients then not using or bypassing Pi-hole for DNS queries via IPv6 just based on the has RA they received last (and adjusted DNS entries accordingly)?

No, RAs are not designed by "the last". The RA from the router may simply not contains a DNS server - but this doesn't mean there is none. The RA sent by Pi-hole later just adds this extra bit of information, there is no ambiguity here.

> And isn't removing `ra-param=*,0,0` now breaking the most common setup (according to my observations) where the Pi-hole server is not the router, i.e. if I understand correctly, Pi-hole will now always advertise itself as default gateway, so if it isn't the router, any non-LAN IPv6 request from any client will then fail.

No, Pi-hole will simply stop sending any RAs at all.

**Comment by yubiuser** [comment]
This PR did not introduce a way to remove `ra-param=*,0,0` from any existing installation where it is set already. Do we need one?

@Omoeba 
> A note stating that Enable IPv6 support (SLAAC + RA) requires Pi-hole to be the router

Are you going to PR a change to the web interface to include that info?

**Comment by DL6ER** [comment]
@yubiuser I don't think the statement

> A note stating that Enable IPv6 support (SLAAC + RA) requires Pi-hole to be the router

is correct. Yes, the router lifetime of the RAs sent by Pi-hole isn't zero any more and, hence, we say we have valid routes, but then, however, we send none if Pi-hole isn't the router. Such RAs *should* not be considered useful as default router if Pi-hole isn't the router.

Note that the router lifetime is independent from the DNS server record lifetime which is a separate field:
RA-ra-param-DNS-lifetime

---

@MichaIng I don't know if you got notified about [my edit above](https://github.com/pi-hole/pi-hole/pull/4508#issuecomment-1147490442). If not, please have another look, if yes, sorry for the additional noise :-)

**Pull request merged**
