### PR TITLE
sed cmd to replace crlf if they exist in setupVars

### PR DESCRIPTION
**Pull request by jlagermann**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by jlagermann** [comment]
This could be added before "source ${setupVars}" (line 2548) or in the "accountForRefactor" function. If "accountForRefactor" will go away in the future, I would leave it where it is.
This could save hours of troubleshooting when the setupVars has crlf. The symptoms are a partial failure. The only functions that fail are Boolean matches, for example "INSTALL_WEB_SERVER=true" does not match true with a crlf after it. Collecting other information, like IP addresses and domains, will still work even followed by a crlf.

**Comment by jlagermann** [comment]
added gpg

**Comment by PromoFaux** [comment]
Hi there, thanks for the submission!

I'm afraid I'm going to have to reject it at this moment in time, please make your changes again, but this time base them on the `development` branch, and submit the PR to target `development` (as per the contribution guide)

```
git checkout development
git checkout -b mybranchname
[make changes and commit them to mybranchname]
```

Sorry to be a pain, but we need people to follow the processes. Thanks again for contributing!

**Comment by jlagermann** [comment]
I don't mind the correction, infact, I appreciate it!  I want to do this
correctly.

I'm trying to figure out how to do it with VS Code.  I maintain my own
gitlab environment (https://gitlab.lagermann.net) and it just works for
me.  Interfacing with github seems to have a few more steps I'm missing.


Thank you,

James Lagermann
636-575-7249

**Comment by jlagermann** [comment]
Okay, I've tried everything I can think of.  I can clone/fork/branch or
anything else you can think of to my github or gitlab but nothing seems to
work with pi-holes.  I keep getting permission denied.

If I try to fork the development branch directly on github, it forks the
master.

If I clone the master branch with VS Code,
then checkout development,
then create a branch jlagermann
then checkout jlagermann
I cannot commit to it, permission denied.

The only thing that works is publishing the branch to my own repo.

I would like to contribute you the project but at this point, I might just
fork it and keep my improvements to myself.


Thank you,

James Lagermann
636-575-7249

**Comment by dschaper** [comment]
The process would be to:

1. Fork https://github.com/pi-hole/pi-hole/ to a repo under your namespace. It looks like you've done that with https://github.com/jlagermann/pi-hole

2. Clone https://github.com/jlagermann/pi-hole

3. Checkout the development branch with your clone of https://github.com/jlagermann/pi-hole

4. Create your topic branch, based on the development branch code.

5. Make your changes, push the topic branch to your repo.

6. Open a Pull Request to merge your repo's branch in to our repo.

**Pull request closed without merging**
