### PR TITLE
Chrono uptime close #325

### LINKED ISSUE #325: Add uptime -p to chronometer.sh
Quick feature request:
Add simple uptime -p under the current uptime line.

Along the same lines, uptime and average load would be nice on the admin UI

I dont think this is enough to make a pull request over but I could.

``` bash
		clear
		# Displays a colorful Pi-hole logo
		toilet -f small -F gay Pi-hole
		echo "        $(ifconfig eth0 | awk '/inet addr/ {print $2}' | cut -d':' -f2)"
		echo ""
		uptime | cut -d' ' -f11-
		uptime -p
		echo "-------------------------------"
```

### PR DESCRIPTION
**Pull request by Hippyjake**
adds pretty uptime to chronometer.sh

### CODE REVIEW

**Comment by PromoFaux** [comment]
Tested Working OK.

**Comment by Morlok8k** [comment]
i'd use `uptime | awk -F'( |,|:)+' '{print $6,$7",",$8,"hours,",$9,"minutes."}'` instead, so it works on all pi's.

**Comment by dschaper** [comment]
Can you submit a PR with the updated code for us to evaluate? Thanks!

**Comment by Morlok8k** [comment]
yes, i can.  I'm running raspbian wheezy (fully up to date, though), by the way.

**Pull request merged**
