### PR TITLE
Pi-hole v2.5.3

### PR DESCRIPTION
**Pull request by PromoFaux**
Ready for merging

Pull Request for tracking changes to development branch

### CODE REVIEW

**Comment by PromoFaux** [comment]
OK, I think this is ready. Releasing in 3...2...

**Comment by DonLexos** [comment]
Yes very, and all the complication will probably make sense as soon as I have the complete overview, but now it means I can hint on (small) fixes and where to make them, but cannot simply do it myself (which would be less time consuming for everyone). Will get there eventually ;-)

**Comment by Hippyjake** [comment]
Installs like a charm. The web interface is very cool, but the version number did not change.

**Comment by PromoFaux** [comment]
Are you sure?? 

It has changed on mine.. 

image

**Comment by DonLexos** [comment]
I played with the developer branch so on my initial upgrade it skipped the admin since there were files there that were different. I wiped the admin, ran the installer again and got `Pi-hole Version v2.5.3 Web Interface Version v1.1.0` so it should work I believe. You sure you installed it in the last 10 or so minutes, the release was done really really recently.

**Comment by PromoFaux** [comment]
It may be because @Mcat12 didn't tag the release until after I released pi-hole. The files are correct.

I believe that the version number is pulled from the latest release page of the github repo.

**Comment by Mcat12** [comment]
The version number is pulled from the git repo. There will be a quick minor release to fix the images in the query log. (Caused by trying to host everything needed, but I missed something)

**Comment by Hippyjake** [comment]
selection_006

**Comment by Hippyjake** [comment]
Ran updateDashboard.sh an the version is 1.1.1 :)

**Comment by PromoFaux** [comment]
Ah! Excellent. May have just not caught up yet. Enjoy!

**Pull request merged**
