### PR TITLE
Backend additions for aufit log feature

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 10

---

See https://github.com/pi-hole/AdminLTE/pull/479

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by PromoFaux** [comment]
Approved

**Comment by PromoFaux** [comment]
Although, there needs to be a way to remove items, too.

**Comment by DL6ER** [comment]
I will add a `Undo` button that will remove the very last line that was added to the audit file. I see no point in being able to reset the list via the web interface - you can still do that very easily by hand over SSH. but let's see if anyone really needs that.

**Comment by PromoFaux** [comment]
Why not one for each? In the same way that you can remove individual entries from the black and whitelists....

**Comment by DL6ER** [comment]
Pushing this feature back to a future release, since I don't want this to be a blocker (some things are still being actively discussed)

**Comment by Mcat12** [comment]
Aligned this PR's milestone with its corresponding web PR's milestone (v3.2)

**Pull request merged**
