### PR TITLE
Redirect to admin panel when accessing 'http://pi.hole/'

### PR DESCRIPTION
**Pull request by raincoats**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

2

---
If someone tries to access 'http://pi.hole/', it will take them to the "Website blocked" page. Very confusing if you don't know to go to 'http://pi.hole/admin/'. This just redirects them to the admin panel.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by dschaper** [comment]
I believe that has already been addressed the latest release. Check here and see if this is the same resolution to the problem: https://github.com/pi-hole/pi-hole/blob/master/advanced/lighttpd.conf.debian#L73

**Comment by raincoats** [comment]
Oh well there's my issue, I'm not using the lighttpd that gets installed, I'm using nginx.

**Comment by DL6ER** [comment]
HTTP response code **302 Found** is usually used for pages that have only moved temporarily (like due to maintance). This is not the case as the dashboard will actually always only be available under `admin/`, so I'd suggest response code **301 Moved Permanently**

I remember having read that in Nginx, you should always only accomplish redirects with the built-in `rewrite` directive. A quick look into the `man` page suggests something like

```
server {
    [... something else ...]
    rewrite ^/$ http://pi.hole/admin permanent;
    [... something more ...]
}
```

I cannot test this, since I have no Nginx running, but it should be easy for you to test this yourself.

**Comment by DL6ER** [comment]
This solution should work across a number a different web servers. Please change your code to respond with code 301 (`Moved permanently`) instead of 302 (`Found`), like this:
```
if ($serverName === 'pi.hole')
{
	header("Location: admin/", true, 301);                                     
}
```

**Comment by raincoats** [comment]
You're right, to be honest I never gave the 301/302 codes much thought. I've gone ahead and made the change to my code (I think? Clumsy with git, worse with pull requests).

**Comment by DL6ER** [comment]
Approved

**Comment by dschaper** [comment]
Do we want to merge this now, or wait until after 3.0?

**Comment by DL6ER** [comment]
I vote for merging it now.

**Comment by dschaper** [comment]
Okay, sounds good, I just didn't know if this would conflict with anything that's currently staged.

**Pull request merged**
