### PR TITLE
Added piholeDebug.sh script for advanced debugging

### PR DESCRIPTION
**Pull request by nate-ubiquisoft**
Roadmap item #2 .

Changes proposed in this pull request:

- Added script to produce a debugging log file to be shared with developers for troubleshooting purposes.

@pihole/gravity

Script piholeDebug.sh added to /usr/local/bin to generate a detailed log file for debugging/troubleshooting.

### CODE REVIEW

**Comment by Mcat12** [comment]
What would an example output look like?

**Comment by Mcat12** [comment]
Also, make sure to change the description of the file in the license header.

**Comment by nate-ubiquisoft** [comment]
@Mcat12 Whoops, missed the description in the header there. I just pushed that change.
The format for the log is as follows:

1. - IP Addresses of this Pi
2. - Gateway check (check if Pi has internet)
3. - Dnsmasq.conf file dumped
4. - Hosts file dumped
5. - Whitelist.txt file dumped
6. - Blacklist.txt file dumped
7. - Adlists.list file dumped
8. - Tail -f /var/log/pihole.log dumped until interrupt with displayed instructions for user
9. - Interrupt catch to write remaining files to debug log (item 10)
10. - Gravity.list file dumped

There are checks for all files existing with relevant error handling being displayed to user as well as logged in pihole_debug.log
Are there any other files/items needing to be logged for you diagnostic purposes? I didn't want to start incorporating external packages which would be needed for more detailed network information.

**Comment by ChadBHowell** [comment]
You will need to dump /etc/dnsmasq.d/01-pihole.conf too.

**Comment by nate-ubiquisoft** [comment]
Okay I'll dump that as new (10.) and move Gravity.list to the bottom, since it is so long. I also refactored a version which copies each file to /tmp/pihole_debug/ then tars them with a tail -f file from pihole.log so that we don't get their entire pihole.log file, just the sites they are having trouble with.

**Comment by nate-ubiquisoft** [comment]
Updated format:
- IP Addresses of this Pi
- Gateway check (check if Pi has internet)
- Dnsmasq.conf file dumped
- Hosts file dumped
- Whitelist.txt file dumped
- Blacklist.txt file dumped
- Adlists.list file dumped
- Tail -f /var/log/pihole.log dumped until interrupt with displayed instructions for user
- Interrupt catch to write remaining files to debug log**
- 01-pihole.conf file dumped
- Gravity.list file dumped

**Comment by nate-ubiquisoft** [comment]
Just added the Pi 3B to the README.md since it hadn't been added yet and is probably the best device for running PiHole at the moment.

**Comment by PromoFaux** [comment]
Could you also add lighttpd.conf please?

**Comment by PromoFaux** [comment]
And maybe to keep the file size down,  either just a line count of gravity.list or the results of a grep against gravity.list for both the white and blacklist text files?

**Comment by nate-ubiquisoft** [comment]
@PromoFaux Acutally yes I have a few new changes not yet committed as I want to test them first thing tonight when I get home from FedEx.

- Line count of gravity.list rather than the file contents
- Removed comments from config files that are being written to make reading the file faster/easier
- Added `hostname` output
- Added a test for name resolution `nslookup doubleclick.com` to compare with `nslookup doubleclick.com 8.8.8.8`
- Added `lighttpd.conf` to debug.log
- Rearranged output of files to log for easier reading

**Comment by nate-ubiquisoft** [comment]
I am also working on a test for forwarding to assist with #396

**Comment by PromoFaux** [comment]
Super!  

As yes,  I forgot to mention removing commented lines from output files would be a good idea..  But you're one step ahead there! 

Testing `gravity.list` for domains in `whitelist.txt` and `blacklist.txt` would be useful for debugging,  too. Ideally the output would show domains in whitelist are also in gravity (exact match)  and domains in blacklist that are not in gravity.

Maybe worth grabbing a random domain from `gravity.list` for the name resolution part. The user,  for whatever reason,  May have `doubleclick.com` whitelisted.

**Comment by nate-ubiquisoft** [comment]
Good idea @PromoFaux. I will log any matches between whitelist || blacklist with gravity.list. I will use a the first, non-matched, entry in gravity.list for the nslookup test.

**Comment by PromoFaux** [comment]
Excellent! Just don't take the first one from `gravity.list` as that will always be `pihole.isworking.ok`

**Comment by nate-ubiquisoft** [comment]
Lol yes I saw that just now as I was adding these changes to my script.

**Comment by nate-ubiquisoft** [comment]
I still need to fully test my latest commit as well as finish the testNslookup function but I have the parsing of blacklist.txt and whitelist.txt against gravity.list working! I also added the hostname output in this commit.

**Comment by Mcat12** [comment]
It might be best for future expansion of the debug log to output a zip of different logs. So in the zip, there would be a cloned gravity.list, results of connectivity checks, config files (with comments cut), etc. Then they just send us the zip, keeping it still one file.

**Comment by dschaper** [comment]
You mean a gzip tarball right ;)

**Comment by Mcat12** [comment]
Whatever works. :) a zip might be a bit more universal though.

**Comment by dschaper** [comment]
Just giving you a hard time :) But if we could get the stuff tar'd at least it should be good. Not sure if they would have any benefit being gzip'd in addition to collecting them into a ball...

**Comment by nate-ubiquisoft** [comment]
Do you guys have any hosted servers? I was actually going to do the whole tar/zip of the files rather than writing to a single log file but I figured it would be more lightweight and easier for the users to send a single text file rather than a compressed archive. If you have a hosted server I can setup a chrooted sftp and create another debug script (pihole_advanced_debug.sh) that will build and compress the archive of all necessary logs then automatically sftp it to your server.

**Comment by dschaper** [comment]
@nate-ubiquisoft I have an OpenVZ VPS that is able for use, and I can spin up a DO droplet if you need. Just let me know what way is the best. I'm teaching myself Docker on the OpenVZ CentOS with Alpine so we can do some other things that we can discuss offline. I'd be happy to give you full access to whatever you need. You know how to contact me, so let me know. (I'm bouncing around to a bunch of different places this week so I'll get to you when I get a moment, installing PFSense, RouterOS, bridged xDSL and a EoC turn up, lol...)

**Comment by nate-ubiquisoft** [comment]
@dschaper I can look into setting that up for the next release. I was hoping you guys could merge in this pull request so all the users can run my debug script. It is finalized and ready for release and VERY thoroughly tested on three different networks.

**Comment by dschaper** [comment]
All merge to master goes for team review first from devel branch. I haven't
had a bit to review but if others okay then override me...

Dan Schaper via GS3

**Comment by nate-ubiquisoft** [comment]
Sounds good. I didn't mean to start making all these changes on master but I honestly didn't expect you guys to be as open and welcoming as changes as you have been. All new work I do will be in separate branches to merge into dev before going to production. 
On another note (if I am not overstepping my boundaries) I think that a restructure of the Pi-Hole branching structure would be beneficial to development.
I do development for FedEx Worldwide AirOps and our most recent project we have setup a full-proof Git branching structure to allow for release development, production deployment, point releases, and bug fixes.

Branch the next large release from master as PiHole-x.x.x-Release then branch any feature/bug fix development tasks off of that then merge them back in to the Release. Then when a release goes to production, it is merged into master and tagged. The tag can be used to generate a point release branch for production critical bug fixes that are then merged immediately back into master upon completion. This allows new Release branches to then fast-forward on the next pull to get the bug fixes merged into master.

**Comment by dschaper** [comment]
@nate-ubiquisoft Check your email, need to talk for a sec...

**Comment by PromoFaux** [comment]
Closing as requested

**Pull request closed without merging**
