### PR TITLE
Pi-hole Core v4.3.2

### LINKED ISSUE #1877: Pihole -up with no network showing update available for FTL
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).
---
See https://discourse.pi-hole.net/t/pihole-up-with-no-network-gives-ftl-update-available/6155

> When running pihole -up on ubuntu server 64bit 16.04.3 in virtualbox and network disable, update says Pi-hole core is up to date and FTL needs updating, Web interface check is missing

### LINKED ISSUE #2843: Dead default blocklist link
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

3

---
**Expected behaviour:**

Blocklist showing a list of hosts to block

**Actual behaviour:**

URL Shows ?php
echo "# ZeuS Tracker has been discontinued on Jul 8th, 2019";
exit();
?

**Steps to reproduce:**

Go to https://zeustracker.abuse.ch/byebye.php?download=domainblocklist

`{Steps of what you have done to fix this}`

Saw reddit post https://old.reddit.com/r/pihole/comments/ccfxom/one_of_default_blocklists_is_dead_another_outdated/

Checked URL https://zeustracker.abuse.ch/byebye.php?download=domainblocklist
 Site shows
?php
echo "# ZeuS Tracker has been discontinued on Jul 8th, 2019";
exit();
?

### LINKED ISSUE #2860: Installscript fails with "pihole: command not found"
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

No "command not found" errors

**Actual behaviour:**

Using Vagrant on CentOS7 (both host and box), I run into the fact that the webinstaller cannot find pihole, although it exists at that place. Perhaps bash is calling it wrong.

**Steps to reproduce:**

```
[..]
  [✓] DNS service is running
  [i] Pi-hole blocking will be enabled
/usr/local/bin/pihole: line 293: pihole: command not found
[vagrant@pihole ~]$ /usr/local/bin/pihole
Usage: pihole [options]
```

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/eq6nvrkf0j

### LINKED ISSUE #2863: gravity.sh bad handling of CNAME results from dig, when domain is blocked
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behaviour:**

Successfully download a list from a blocked domain.

**Actual behaviour:**

It fails all the time. I need to whitelist the domain before, then it works.
`dig 8.8.8.8` response with a CNAME
This causing a bad curl request, which will fail.

> Ah, I see it. The dig to 8.8.8.8 is returning a string (looks like a CNAME) instead of a bare IP address.

Also:
> Looks like our browser string is out of date now as well, they are complaining about the id as deprecated.

More Info here:
https://discourse.pi-hole.net/t/update-gravity-doesnt-work-for-lists-when-domain-is-on-blocked-list/22121/25

**Steps to reproduce:**

https://discourse.pi-hole.net/t/update-gravity-doesnt-work-for-lists-when-domain-is-on-blocked-list/22121/25

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/8twqcy8mbv

**Troubleshooting undertaken, and/or other relevant information:**

https://discourse.pi-hole.net/t/update-gravity-doesnt-work-for-lists-when-domain-is-on-blocked-list/22121/25

### LINKED ISSUE #2869: pihole-FTL fails to restart on Debian 10 (Buster)
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`2`

---
**Expected behaviour:**

I am aware that Debian 10 (Buster) is not yet officially supported, but I expect pihole-FTL to support it in the future and found this issue.

**Actual behaviour:**

On Debian 10, `pihole-FTL` has a tendency to fail to restart (using `pihole restartdns` or `pihole -r`), logging that port 53 is already in use despite it not being so.

**Steps to reproduce:**

1. Clean installation of Debian 10 (x86_64).
2. Install Pi-hole
3. `pihole restartdns`

[Demo video](https://youtu.be/bfbHbJTvwQE)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`https://tricorder.pi-hole.net/3y7w56odsy`

**Troubleshooting undertaken, and/or other relevant information:**

By contrast, `systemctl restart pihole-FTL` (almost) always seems to work.

### PR DESCRIPTION
**Pull request by dschaper**
Release on v4.3.2 of the core Pi-hole application. 

Simplify restarting code for "pihole restartdns" #2873 (Fixes #2869)
Remove the ZeusTracker blocklist from the defaults #2846 (Fixes #2843)
Fix for 404 error when browsing to pi.hole (without /admin) #2826
Fedora 30 tests #2833
quick fix for when dig also returns a CNAME #2865 (Fixes #2863)
Create FUNDING.yml #2774
Fix pihole -up showing FTL update when network is down #2820 (Fixes #1877)
Improve PID detection in pihole-FTL.service #2767
Fix uninstall causing 403 errors and not removing packages #2808
Fix pihole manpage to match code. #2822
Fix error when getting latest FTL tag #2882
Call 'pihole' with full path in install and cronjobs. #2886 (Fixes #2860)
Add dhcp-ignore-names option when enabling DHCP service #2768 - From v4.2
Restore 'pihole -q' hosts format support and improve matching in edge cases #2891

### CODE REVIEW

**Comment by dschaper** [comment]
Force-push for DCO correction of user submission.

**Comment by dschaper** [comment]
One more PR to be pushed to this branch in the next day or so to cover full paths to binary/script calls.

**Comment by dschaper** [comment]
I'd like to get #2891 in this and then I think everything is buttoned up.

**Comment by onedr0p** [comment]
LGTM :)

**Pull request merged**
