### PR TITLE
Optionally include lighttpd-mod-deflate since it is no longer provide…

### PR DESCRIPTION
**Pull request by lightswitch05**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*

If the package `lighttpd-mod-deflate` exists, Include it as a dependency for Pihole Web. Right now, Pihole fails on Debian Bullseye due to the missing deflate module for lighttpd. This PR includes the module as a dependency to correct that failure - but only if the package exists.

Failure:

> 2021-06-30 22:36:39: plugin.c.195) dlopen() failed for: /usr/lib/lighttpd/mod_deflate.so /usr/lib/lighttpd/mod_deflate.so: cannot open shared object file: No such file or directory
> 2021-06-30 22:36:39: server.c.1238) loading plugins finally failed
> Stopping lighttpd
> lighttpd: no process found

Debian Bullseye is in 'Hard Freeze' status, with a 'Full Freeze' status planned for 2021-07-17. As far as I can determine, this is the only required change to get things working on Bullseye. I did testing of this change through Docker using the down-stream docker-pihole project.

Interesting enough, if you search for the error message, you'll come across the Pihole discourse, talking about the same error, except with the Kali distribution. Which of course is unsupported, but shares the same solution:

* [Installation aborts at lighttpd restart](https://discourse.pi-hole.net/t/installation-aborts-at-lighttpd-restart/45912/2)
* [Mod_deflate.so module is missing from lighttpd?](https://discourse.pi-hole.net/t/mod-deflate-so-module-is-missing-from-lighttpd/42781/3)

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*

If the package `lighttpd-mod-deflate` exists, Include it as a dependency for Pihole Web.

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*
 
None that I know of? As far as I can tell, the uninstall script sources from this same variable, so it should work fine I believe?

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by MichaIng** [comment]
Makes sense to have a function for this.

I checked the packages availability: https://packages.debian.org/lighttpd-mod-deflate
- It is a a virtual package on Buster and Stretch backports as well, provided by `lighttpd` itself, where `apt-cache show lighttpd-mod-deflate` will then return `true`, so that it is added to the array.
- As `dpkg-query -W` does not list "provided" packages, the installer will always mark it for being installed.
- APT resolves such "provided" virtual packages automatically, in this case with `lighttpd`, which will hence be "installed" on every Pi-hole update, regardless whether it is actually installed already.
- That is not a problem, but looks a bit strange for users when `lighttpd-mod-deflate` is shown as required, not installed, resulting in an APT call which again shows nothing more than "all already up-to-date" (by meaning), surrounded by the horizontal dashes and all that.

But a bigger actual issue is the following on Buster, where the package is not only provided by the base repository `lighttpd` but also available via backports:
```
2021-07-07 13:27:54 root@VM-Buster:~# apt-cache show lighttpd-mod-deflate
Package: lighttpd-mod-deflate
Source: lighttpd
Version: 1.4.59-1~bpo10+1
Installed-Size: 39
Maintainer: Debian lighttpd maintainers <team+lighttpd@tracker.debian.org>
Architecture: amd64
Replaces: lighttpd (<< 1.4.56~rc7-0+exp2)
Depends: lighttpd (= 1.4.59-1~bpo10+1), libbrotli1 (>= 0.6.0), libc6 (>= 2.14), zlib1g (>= 1:1.1.4)
Breaks: lighttpd (<< 1.4.56~rc7-0+exp2)
Description: HTTP response compression module for lighttpd
Description-md5: 8944796df0c20715cd6384c5fc447619
Homepage: https://www.lighttpd.net/
Section: httpd
Priority: optional
Filename: pool/main/l/lighttpd/lighttpd-mod-deflate_1.4.59-1~bpo10+1_amd64.deb
Size: 9720
SHA256: 32c7a5f4c00f51310501905c6e3b83cf8171c8010d3eb55089feaf7667fd0dfa

2021-07-07 13:28:11 root@VM-Buster:~# apt install lighttpd-mod-deflate
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 lighttpd-mod-deflate : Depends: lighttpd (= 1.4.59-1~bpo10+1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
So the package is not resolved via `lighttpd` from the main repository, which "provides" it, but via backports (if part of `sources.list`). But dependencies are denied to be pulled from backports, with not explicitly defined (e.g. `-t buster-backports`). So currently this PR will break the installer on most Debian systems. On Raspbian/Raspberry Pi OS (32-bit) no backports exist, but on Debian/Raspberry Pi OS (64-bit).

**Comment by lightswitch05** [comment]
> So the package is not resolved via lighttpd from the main repository, which "provides" it, but via backports (if part of sources.list). But dependencies are denied to be pulled from backports, with not explicitly defined (e.g. -t buster-backports).

🤯🤯🤯

**Comment by lightswitch05** [comment]
> Is deflate transfer compression really something important for the Pi-hole admin panel?

I'm good with with dropping, it cannot be said that I didn't try my best to keep support for it. Perhaps someone with more systems experience could find a clean solution.

My only concern is about migrations. Do we need to worry about removing the compression configuration for lighttpd, or can we safely assume anyone with that configuration will already have the correct packages available? Specifically thinking about docker usage, it might be a problem.

**Comment by MichaIng** [comment]
> My only concern is about migrations. Do we need to worry about removing the compression configuration for lighttpd

But where is this compression configuration? The module is not loaded by the default Lighttpd config, installed by the Pi-hole installer on Debian systems: https://github.com/pi-hole/pi-hole/blob/master/advanced/lighttpd.conf.debian
If someone added this manually, then I think the error message is clear enough, as the states exactly the config line which fails. Also, a distro upgrade is something that requires some manual config updates in most cases. I remember this `use-ipv6.pl` file included, which changed its name/path from Stretch to Buster. There will be maybe cases/reports about it, but trying to work around all such migration issues potentially causes more issues than it solves.

**Comment by lightswitch05** [comment]
Yes, its `mod_compress` - which is deprecated and replaced by `mod_deflate`

**Comment by MichaIng** [comment]
Ah that is true, see it now being internally replaced and loaded automatically.

Hmm, so as the Lighttpd config is re-installed on every Pi-hole update, generally it is possible to remove the `mod_compress` module to fix installs on Bullseye and newer Ubuntu. If someone upgrades the distribution before next Pi-hole release, (s)he will run into the error regardless whether we implement the module dependency or remove it from the config. And both solutions will fix it for fresh Pi-hole installs on those distros and when upgrading the distro after next Pi-hole update.

So the final question is whether keeping transfer compression is with the effort to do this conditional package install 🤔. As the package check turned out to be complicated here, the distribution version could be checked instead. But users might have manually added/removed the backports repository or changed priorities, so it remains unreliable or complicated to know for sure whether `apt-get install lighttpd` will pull a version with or without included `mod_deflate`.

Another approach is to force the install of dependencies, as the deflate module is a recommendation for `lighttpd` packages where it's not included: https://packages.debian.org/buster-backports/lighttpd
But currently the installer uses `--no-install-recommends` to explicitly avoid that (reasonably) while there is no option to force it, and it can be disabled via `apt.conf` > `APT::Install-Recommends "false";`. I think this can be passed to a single `apt-get` call as well, but then lighttpd would need to be installed in a separate call to only force recommends there... Still complicated and somehow fragile when package metadata changes 🤔.

**Comment by lightswitch05** [comment]
> Lighttpd config is re-installed on every Pi-hole update

Also, looks like the lighttpd config isn't exposed by default in docker - so that shouldn't be a problem. People are allowed to mount `/etc/lighttpd` to make their own local configurations, but it isn't part of the standard setup. If people are making configuration changes, then its own them to maintain it.

Not that I really get a vote, but I vote for the removal of compression considering the issue keeping support for it.

* Most use cases the removal will not be missed
* A reverse proxy can add compression easily
* The configuration can easily be changed to add it back
* Perhaps someone who really misses it can read all this in the future and submit a PR that adds it back in a clean way that we are unable to discover at the moment

**Comment by MichaIng** [comment]
Thanks for checking with the Docker implementation. I usually forget this 👍.

**Comment by PromoFaux** [comment]
> * The configuration can easily be changed to add it back

Although they would need to do it with an `external.conf` (or whatever the file is called)

> but I vote for the removal of compression considering the issue keeping support for it.

I inclined to agree here

> Not that I really get a vote,

Maybe not officially, but you certainly have the ear of those that do 🙂

**Comment by MichaIng** [comment]
Is there a way to filter the output of `apt-cache show` or `apt-cache dumpavail` by priority? If so, that would be generally a good addition to the package checks as (only) those with priorities >= 500 would install just fine as dependencies are nearly assured to share the same priority then :thinking:.

**Pull request closed without merging**
