### PR TITLE
Fix handling of wildcard help text

### LINKED ISSUE #1304: [TYPO] Commandline pihole -wild
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{5}_

---
**[BUG] Expected Behaviour:**
 ```pihole -wild -l``` show usage syntax for the option

**[BUG | ISSUE] Actual Behaviour:**
```::: Usage: pihole -b domain1 [domain2 ...]``` where ```-b``` should have been ```-wild```

**[BUG] Steps to reproduce:**

use the CLI command ```pihole -wild``` on system that was installed without the admin web interface.

### PR DESCRIPTION
**Pull request by r0ckarong**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

_4_

---
Fixed handling of the "-wild" parameter for the list, rewrote help texts to handle word properly.
Fixes #1304 

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by dschaper** [comment]
This looks okay, but would be a breaking change that users would have to be informed of.

**Comment by r0ckarong** [comment]
Can I rework this to make it easier to integrate?

**Comment by WaLLy3K** [comment]
Does [`7d17c65`](https://github.com/pi-hole/pi-hole/pull/1317/commits/7d17c652f3e241c745b50ace547910fe59038231) fix what you're looking to achieve?

```
pihole -wild -h
Usage: pihole -wild [options] <domain> <domain2 ...>
Example: 'pihole -wild site.com', or 'pihole -wild site1.com site2.com'
Wildcard blacklist one or more domains

Options:
  -wild, --wildcard   Block all subdomains of specified domain
  -d, --delmode       Remove domain(s) from the wildcard blacklist
  -nr, --noreload     Update wildcard blacklist without refreshing dnsmasq
  -q, --quiet         Make output less verbose
  -h, --help          Show this help dialog
  -l, --list          Display all your wildcard blacklisted domains
```

If so, I approve of the change.

**Comment by WaLLy3K** [comment]
Ping @r0ckarong

**Comment by r0ckarong** [comment]
Yes this is what I was trying to achieve. If this is going into the mainline dev branch anyway this PR can be closed.

**Comment by WaLLy3K** [comment]
No need to close this, it's got the changes needed ready to go (and you get the credit of finding the issue! :smile:)

Approved

**Comment by dschaper** [comment]
Hold merge on this, discussing the changes and how to resolve, will try a block but not sure if that will work.

**Pull request merged**
