### PR TITLE
Retrieve local repos on repair

### PR DESCRIPTION
**Pull request by WaLLy3K**
**By submitting this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

4

---

**[BUG] Expected Behaviour:**

When running `pihole -r` for a repair, `/etc/.pihole` and `/var/www/html/admin` should be updated.

**[BUG] Actual Behaviour:**
```
::: You are root.
::: Repair option selected.
::: Verifying free disk space...
[]
:::    Checking for whiptail... installed!
::: --reconfigure passed to install script. Not downloading/updating local repos
:::    Checking for bc... installed!
```

**[BUG] Steps to reproduce:**

`pihole -r`, and select repair.

**PR fixes:**

* Change conditional to check for repair
* Change wording of Update/Reconfigure message
* Fixed indenting

### CODE REVIEW

**Comment by Mcat12** [comment]
Wouldn't this turn repair into running an update? Not updating the repos is useful for when you switch branches.

**Comment by PromoFaux** [comment]
maybe a git reset --hard?

**Comment by WaLLy3K** [comment]
Thinking about the code that was already there, I'd say you're right @Mcat12. As @PromoFaux, `git reset --hard` would be necessary to revert any changes, and then maybe of these two solutions:

* Repair becomes an "update and repair"
* Repair attempts to clone the current locally operating version

**Comment by PromoFaux** [comment]
When I first implemented the repair option, the thinking was that nobody should really be editing files in the `.pihole` directory, but they may have messed things up elsewhere. Really it's only purpose was to redistribute the correct files to where they should be.

I use it when I'm doing experimental development, edit into the repo directory, and then install. Though, that said, I'm now using Dom's symlink script, so I will use the repair option less frequently.

Is it used by the `pihole checkout` function? I'd look but I'm on mobile and lazy!

**Comment by WaLLy3K** [comment]
It looks like `git reset --hard` is the right tool for the job here!

**Comment by technicalpyro** [comment]
not sure if this is a result of this commit or something else going on but this is what is returned when trying to update 
```
::: --reconfigure passed to install script. Resetting changes to local repos
fatal: Not a git repository (or any of the parent directories): .git
Unable to complete update, contact Pi-hole
```

**Pull request merged**
