### PR TITLE
Add wpad vulnerability fix as suggested by dnsmasq.conf.example

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**

Add `wpad` vulnerability fix as suggested by `dnsmasq.conf.example`
See https://www.kb.cert.org/vuls/id/598349 for further information

**How does this PR accomplish the above?:**

Add config lines that instruct our DHCP server to ignore when clients announce themselves with hostname `wpad`.

**What documentation changes (if any) are needed to support this PR?:**

Unclear, probably none.

### CODE REVIEW

**Comment by AlexJamesHaines** [comment]
Does this mean that I can now remove the following entry from my blocklist:

wpad.mylocal.domain

**Comment by EWouters** [comment]
This seems to cause my dnsmasq to crash when starting.
It only starts when i comment the line `dhcp-name-match=set:wpad-ignore,wpad` in `/etc/dnsmasq.d/01-pihole.conf`.

[https://tricorder.pi-hole.net/fc30tdif6q](https://tricorder.pi-hole.net/fc30tdif6q)

**Comment by dschaper** [comment]
It requires `pihole-FTL` or `dnsmasq` > 2.80. If you are running this please open an issue.

**Comment by Fedora-Core** [comment]
Please update the status of the Pi-hole project at 
[ https://www.kb.cert.org/vuls/id/598349](url)

As of today the status is still **vulnerable** 
and is noted with absent **Vendor has issued information**

Greetings,
 F-C

**Comment by DL6ER** [comment]
> https://www.kb.cert.org/vuls/id/598349/

I already wrote them that the issue has been fixed by v4.2 on January 1. I will contact them again to see why they haven't updated it so far.

**Pull request merged**
