### PR TITLE
Add "-ni" to all sqlite3 invocations

### LINKED ISSUE #4650: gravity.sh error caused by ~/.sqliterc
### Versions
Pi-hole version is v5.9 (Latest: v5.9)
AdminLTE version is v5.11 (Latest: v5.11)
FTL version is v5.14 (Latest: v5.14)

### Platform
Debian 11.2 in LXC on Proxmox 7

### Expected behavior

`pihole updateGravity` runs without issues

### Actual behavior / bug

`pihole updateGravity` fails with
```
  [i] Target: address
  [✗] Invalid Target

  [i] Target: ----------------------------------------------------------------
  [✗] Status: ---------------------------------------------------------------- ()
  [✗] List download failed: no cached list available
```

### Steps to reproduce

The cause is an existing .sqliterc in the pihole users $home.

1. Create .sqliterc in pihole users $home with content `.headers on`
2. execute `pihole updateGravity`

### Additional context

I did not find good documentation on how to prevent sqlite3 from loading ~/.sqliterc, but it can be overridden using `--init` parameter.
`sqlite3 --init /dev/null` worked for me (ex. on line 380 in gravity.sh).

### PR DESCRIPTION
**Pull request by DL6ER**
# What does this implement/fix?

This PR fixes #4650 for Pi-hole v6.0 by adding `-ni` to all `pihole-FTL sqlite3` invocations. This PR was created fully-automatically using search-and-replace like

Screenshot from 2023-12-09 23-04-36
Screenshot from 2023-12-09 23-04-52

---

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

### CODE REVIEW

**Comment by yubiuser** [comment]
Errors at

```
sqlite3: Error: unknown option: -ni
```

**Comment by DL6ER** [comment]
Are you using the latest `development-v6` binaries?

**Comment by yubiuser** [comment]
The CI tests complain.

**Comment by DL6ER** [comment]
Binary build have finished, tests succeeded

**Review by yubiuser — APPROVED** [review]
Before

```
*** [ DIAGNOSING ]: Name resolution (IPv4) using a random blocked domain and a known ad-serving domain
-- Loading resources from /root/.sqliterc
[✗] Failed to resolve domain
bob430.web3000.com on lo (127.0.0.1)
[✗] Failed to resolve domain
bob430.web3000.com on end0 (10.0.1.24)
[✓] No IPv4 address available on wlan0
[✓] doubleclick.com is 142.251.36.206 via a remote, public DNS server (8.8.8.8)

*** [ DIAGNOSING ]: Name resolution (IPv6) using a random blocked domain and a known ad-serving domain
-- Loading resources from /root/.sqliterc
[✗] Failed to resolve domain
bob829.web3000.com on lo (::1)
[✗] Failed to resolve domain
bob829.web3000.com on end0 (fe80::dd1b:451d:132:4316)
[✓] No IPv6 address available on wlan0
[✗] Failed to resolve doubleclick.com via a remote, public DNS server (2001:4860:4860::8888)
```

After

```
*** [ DIAGNOSING ]: Name resolution (IPv4) using a random blocked domain and a known ad-serving domain
[✓] tracking.hittail.com is NOERROR on lo (127.0.0.1)
[✓] tracking.hittail.com is NOERROR on end0 (10.0.1.24)
[✓] No IPv4 address available on wlan0
[✓] doubleclick.com is 142.251.36.206 via a remote, public DNS server (8.8.8.8)

*** [ DIAGNOSING ]: Name resolution (IPv6) using a random blocked domain and a known ad-serving domain
[✓] marketing.visitvancouverusa.com is NOERROR on lo (::1)
[✗] Failed to resolve marketing.visitvancouverusa.com on end0 (fe80::dd1b:451d:132:4316)
[✓] No IPv6 address available on wlan0
[✗] Failed to resolve doubleclick.com via a remote, public DNS server (2001:4860:4860::8888)

```

**Pull request merged**
