### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by CrAlMo**
fix link splash screen

### CODE REVIEW

**Comment by dschaper** [comment]
This may or may not be helpful, but since you completely ignored the template I guess we'll never know?

**Review by PS113 — APPROVED** [review]

**Review by PS113 — APPROVED** [review]

**Review by PS113 — APPROVED** [review]

**Review by PS113 — APPROVED** [review]
€

**Comment by PS113** [comment]
> fix link splash screen

**Review by PS113 — APPROVED** [review]
**@__**

**Review by PS113 — APPROVED** [review]

**Review by PS113 — APPROVED** [review]

**Comment by MichaIng** [comment]
This is wrong. The path must be absolute, as blocking page (and 404 page) can show this with every request path, depending only on the path of the blocked ad or the nonexistent resource, while the admin panel is only available at absolute `/admin`. To be more tolerant for webservers with no automatic directory expansion, it could be made `/admin/`, or even `/admin/index.php`, when do autoindex is set, but both is default on all webservers and systems I dealt with.

**Pull request closed without merging**
