### PR TITLE
Fixed the splashpage not appearing properly on non-root directories

### PR DESCRIPTION
**Pull request by The-SamminAter**
Before, when visiting an invalid non-`/var/www/html/` path page, such as `$serverName/a/a`, the `Did you mean to go to the admin panel?` page didn't show up correctly, as the file paths on lines 66, 67, and 70 didn't start with a `/`. In the example, instead of loading in `$serverName/pihole/blockingpage.css`, it would attempt to load $serverName/a/pihole/blockingpage.css`.

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [ ] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*
This PR aims to fix the `Did you mean to go to the admin panel?` not appearing properly on non-root directories.

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*
This PR accomplishes that by adding a `/` to the beginning of the file paths on lines 66, 67, and 70.

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*
None, as far as I'm aware of.

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by dschaper** [comment]
Please review https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md#technical-requirements for the proper branches to base commits on, and to base PRs against.

**Comment by dschaper** [comment]
Only `http://pi.hole/` should redirect to `http://pi.hole/admin/`. Any other URLs prompting to redirect will break if users are still utilizing block pages.

**Comment by The-SamminAter** [comment]
I'm afraid I've never 

> Please review https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md#technical-requirements for the proper branches to base commits on, and to base PRs against.

Apologies, should I delete this pull request, make the changes on that branch, and then make a new pull request?

**Comment by dschaper** [comment]
> I'm afraid I've never

It's the first tick box that you checked as having read and understood.

I don't know if this PR would be accepted, @pi-hole/web-approvers should weigh in before going through rebasing your commits on `development` and changing the PR base branch to `development'.

**Comment by The-SamminAter** [comment]
> > I'm afraid I've never
> 
> It's the first tick box that you checked as having read and understood.
> 
> I don't know if this PR would be accepted, @pi-hole/web-approvers should weigh in before going through rebasing your commits on `development` and changing the PR base branch to `development'.

Sorry, didn't realize that I commented that, I meant to say "I'm afraid I've never signed off before, so I'm afraid it didn't work properly." I also didn't notice the clarification about using the development branch, so should I delete this PR and make a new, correctly done one?

**Comment by The-SamminAter** [comment]
I'm just going to delete this pull request, and make an issue (about the issue), and say what I did to fix the issue.

**Pull request closed without merging**
