### PR TITLE
Fix/install deps exit

### PR DESCRIPTION
**Pull request by dschaper**
**By submitting this pull request, I confirm the following _Failure to fill the template will close your PR_:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

- [x] 10 (very familiar)

---
Use debconf (OS dependency) to install packages, should cover every Debian/Ubuntu and derivatives. 

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by dschaper** [comment]
This installer will pull down the Master branch, so if you get an error with setupvars, check to see if `gravity.sh` is trying to use the new or old variable names. (Should not be an issue once 2.10 is released.)

**Comment by DL6ER** [comment]
Worked for me on Ubuntu

**Comment by DL6ER** [comment]
Testing with Fedora droplet
```
::: Checking dnf for upgraded packages....Failed to set locale, defaulting to C
 done!
```

```
::: User 'pihole' doesn't exist. Creating...

:::	Warning: 'lighty-enable-mod' utility not found. Please ensure fastcgi is enabled if you experience issues.
:::
::: Installing scripts from /etc/.pihole... done.
```

```
::: SELinux Detected
:::	Checking for SELinux policy development packages...Failed to set locale, defaulting to C
 installed!
:::	Enabling httpd server side includes (SSI).. Success
```

Web UI not working.

**Comment by DL6ER** [comment]
Adding to my last comment: I think there are some permission issues going on here.

**Comment by DL6ER** [comment]
But this is no problem of the current PR

Approved

**Pull request merged**
