### PR TITLE
Use inclusive language

### PR DESCRIPTION
**Pull request by mayrs**
- **What does this PR aim to accomplish?:**

Removes references to racially-charged jargon from the code for more neutral and inclusive language. [Read more](https://www.zdnet.com/article/linux-team-approves-new-terminology-bans-terms-like-blacklist-and-slave/).

- **How does this PR accomplish the above?:**

1. Prefer the terms `allowlist` and `denylist` over `whitelist` and `blacklist`.
2. Affects part of the commands but not all: `-w` and `-b` stay for now as `-a` and `-d` are already taken. Could be done in a later step.

- **What documentation changes (if any) are needed to support this PR?:**

The following changes to the documentation will be needed (simple search & replace tasks).

* Replace string `white-` with `allow-`
* Replace string `White-` with `Allow-`
* Replace string `whitelist` with `allowlist`
* Replace string `Whitelist` with `Allowlist`
* Replace string `black-` with `deny-`
* Replace string `Black-` with `Deny-`
* Replace string `blacklist` with `denylist`
* Replace string `Blacklist` with `Denylist`

Some anchors will have to be changed.

Some commands did change, too.

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
- [x] I have read the above and my PR is ready for review. _Check this box to confirm_

### CODE REVIEW

**Comment by yubiuser** [comment]
You can't just simply search & replace the names. There are interworkings at place. E.g. You need to add a new database migration step, otherwise update will break for everyone. 
Additionally, you also need to modify the web and ftl repo to make this work.

**Comment by DL6ER** [comment]
I agree with what @yubiuser said. After merging this PR, no Pi-hole could continue to operate.

**Comment by mayrs** [comment]
@yubiuser, @DL6ER, I agree with both of you. I will set this to blocked and work on it a more as I haven't thought about migration. If someone is interested in helping, feel free to suggest next steps.

**Comment by rdwebdesign** [comment]
This change is complex because it needs to be done in 4 repositories at the same time (pi-hole, AdminLTE, FTL and Docs). It cannot be done in a hurry (and I think it will be too much work to be done by a single person).

There is already a [Feature Request on Discourse Forum](https://discourse.pi-hole.net/t/change-blacklist-and-whitelist-terminology/31657/99). You can discuss the issue there.

**Comment by DL6ER** [comment]
Before you invest any more time possibly in the wrong direction let me point you to branch `new/http` in the FTL repo where everything needed for a smooth migration had already been done. This is our candidate for Pi-hole v6.0. This will be a (massively) breaking change as existing API endpoints like `blacklist` will stop working for user scripts and that's not to be taken lightly.

I'm not sure if it is already the right time to do this now as the code is this repo is moving a lot and you'd have to always catch up on any of these changes until everything is ready for v6.0 . Hence, my suggestion would be to close this PR until we are ready for the v6.0 phase but I'll leave that to you - when you have the time to always update this branch when needed, that's fine, too, for me.

**Pull request closed without merging**
