### PR TITLE
Debug overhaul

### PR DESCRIPTION
**Pull request by dschaper**
**By submitting this pull request, I confirm the following _Failure to fill the template will close your PR_:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

- [x] 10 (very familiar)

---
Additional tweaks to debug script.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by dschaper** [comment]
Woo hoo!

**Comment by PromoFaux** [comment]
Some interesting outputs:

```
:::     Testing IPv4 interface
:::Addresses not found.:::
:::     Testing IPv4 interface
:::             IP addresses found
:::             Pinging default gateway: Gateway responded.
:::             Pinging Internet via IPv4: Query responded.
```

```
:::     A local copy of the Debug log can be found at : /var/log/pihole_debug.log
Use netcat.
```

```
:::::: Your debug token is : 0eg1yoo1rk:::
```

I'm guessing there are a few to many `:::`s in there somewhere! Also, not sure what's going on with teh `Testing IPv4` twice, and not finding it on the first time?

**Comment by DL6ER** [comment]
```
:::  IP Address Information
:::       IPv6 addresses located
:::       IPv4 addresses located
:::        Pinging default IPv4 gateway: Gateway responded.
:::        Pinging Internet via IPv4: Query responded.
:::
:::  Daemon Process Information
:::     Checking http port for lighttpd listener.
:::  Failure: IPv6 Port not in use
:::  Failure: IPv4 Port not in use
```
because my test Pi-hole is currently running on port 8080 (not `http`):

```
root@ubuntu-512mb-fra1-01: ~# lsof -i 4:http
root@ubuntu-512mb-fra1-01: ~# lsof -i 6:http
root@ubuntu-512mb-fra1-01: ~# lsof -i 4:http-alt
COMMAND    PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
lighttpd 19640 www-data    5u  IPv4 151341      0t0  TCP *:http-alt (LISTEN)
root@ubuntu-512mb-fra1-01: ~# lsof -i 6:http-alt
COMMAND    PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
lighttpd 19640 www-data    6u  IPv6 151342      0t0  TCP *:http-alt (LISTEN)
```

My debug token is `v8dcc0f5o5`

Also it puts the whole `error.log` from `lighttpd` into the log such that there is no `pihole.log` in the tricorder.

**Comment by dschaper** [comment]
```
:::	Checking for local repositories:
:::	Pi-hole Core Version: v2.10.2 (* master:739aaaf)
:::	Pi-hole WebUI Version: git repository not detected
***
***	1 Errors found
***		major -- WEBADMIN REPOSITORY DAMAGED
:::
```

**Comment by dschaper** [comment]
```
:::	Detecting existence of /etc/pihole/setupVars.conf
:::	not found!
***
***	1 Errors found
***		major -- SETUPVARS FILE MISSING
:::
:::	Checking for local repositories:
:::	Pi-hole Core Version: v2.10.2 (* master:739aaaf)
:::	Pi-hole WebUI Version: v2.2 (* master:83f19bc)
:::	SUCCESS: All repositories located.
!!!
!!!	 Please run "pihole -r" to generate required configuration file
!!!
```
or if all are missing:
```
:::	Detecting existence of /etc/pihole/setupVars.conf
:::
:::	Checking for local repositories:
:::	Pi-hole Core Version: git repository not detected 
:::	Pi-hole WebUI Version: v2.2 (* master:83f19bc)
***
***	1 Errors found
***		major -- CORE REPOSITORY MISSING
!!!
!!!	 Please re-install Pi-hole, you are missing the required source files.
!!!
```

**Comment by jacobsalmela** [comment]
I'm liking what you've done so far and we could always add in a URL to discourse.pi-hole.net if additional error information is needed.

As for lighttpd, we could just notify them it's on a non-standard port, since you can do run it on a different port now if you want.

**Comment by dschaper** [comment]
Completely forgot about the new port configuration, even though DL6ER pointed it out... I'll add that in to the daemon detection...

**Comment by PromoFaux** [comment]
@dschaper Is this ready for review/merge? Or is it still WIP?

**Comment by dschaper** [comment]
Still WIP, milestoned for 2.12

**Pull request closed without merging**
