### PR TITLE
Source setupVars in the updater before attempting to use it

### LINKED ISSUE #1347: "pihole -up" aborts on system w/o webinterface
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{5}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
"pihole -up" updates system where webinterface was opted not to be installed, without problems,

**[BUG | ISSUE] Actual Behaviour:**
me@rpiii:~ $ pihole -up
::: Checking for updates...
::: Pi-hole Core:   update available
::: Critical Error: Web Admin repo is missing from system!
::: Please re-run install script from https://github.com/pi-hole/pi-hole
me@rpiii:~ $ 

**[BUG | ISSUE] Steps to reproduce:**
run command "pihole -up"

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### PR DESCRIPTION
**Pull request by Mcat12**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

10

---

Fixes #1347
The `setupVars` variable exists from when the installer is sourced at the top of the file.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by PromoFaux** [comment]
Does it not get sourced when `basic_install.sh` is sourced?

**Comment by Mcat12** [comment]
No, only if `finalExports` is called.

**Comment by PromoFaux** [comment]
I was thinking it was somewhere else too, but on checking it's also only if `${useUpdateVars}` is true. Carry one!

**Comment by DL6ER** [comment]
Approved

**Pull request merged**
