### PR TITLE
Support pi hole behind a reverse proxy with ssl

### PR DESCRIPTION
**Pull request by TheNoim**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*
Pi-Hole behind a reverse proxy is possible use case. And if you configured your reverse proxy with ssl and pi hole does not use https for it style sheets, you get mixed content error. 

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*
The use of double slash always uses the clients protocol.

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*
-

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by dschaper** [comment]
Thank you for the submission but please follow the template completely and base your PR on the proper branch.

**Comment by TheNoim** [comment]
If I have time, I will resubmit this pull request with another branch name.

**Comment by dschaper** [comment]
I've updated the base branch for you this time, it's now based to development as the documentation describes instead of master.

**Comment by TheNoim** [comment]
Oh, sorry I miss understanded it. I thought the name of my branch `TheNoim:patch-1` was not ok. I was just too lazy to rename my origin branch and resubmit the pull request with the new branch. But if it is just the target branch, than it is ok.

**Comment by zmwangx** [comment]
I was just about to submit this, as I'm putting my web interface on a custom domain with TLS. Note that to use a custom domain one also needs to modify this line

https://github.com/pi-hole/pi-hole/blob/ba1e94d3d9cf1894e0b5adca3e92738d21897568/advanced/index.php#L60

to recognize the non-`pi.hole` domain. One either needs to hardcode it, or some configuration option needs to be offered. Since I'm not a PHP programmer, I'm not really sure how this kind of configuration is typically implemented in PHP.

**Pull request merged**
