### PR TITLE
Hotfix/cidr (Pi-hole 3.1.1)

### PR DESCRIPTION
**Pull request by PromoFaux**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have written tests and verified that they fail without my change.
- [x] I have squashed any insignificant commits.
- [x] This change has comments for package types, values, functions, and non-obvious lines of code.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership. It is compatible with the EUPL 1.2 license.
- [x] I have Signed Off all commits. (`git commit --signoff`)

***Please explain what you have done and wish to accomplish with this Pull Request***

1. What does this change do, exactly?
Cherry-picked the two CIDR fix commits from `development` into master to be released as a hotfix

2. Please link to the relevant issues.
various

3. Which documentation changes (if any) need to be made because of this PR?

### CODE REVIEW

**Comment by elaur** [comment]
This hotfix create another issue
`dnshole@pihole:~$ pihole -up
/opt/pihole/update.sh: line 29: /opt/pihole/COL_TABLE: No such file or directory
`

**Comment by PromoFaux** [comment]
WOW. Well spotted. I've pulled the release tag, and coding a fix as we speak.

**Comment by PromoFaux** [comment]
@elaur 

Can you please run this and see if it "works" `touch /etc/pihole/COL_TABLE && pihole -up`

There is nothing to update to yet, but I want to make sure those that have been affected have a way to update, cheers.

**Comment by elaur** [comment]
@PromoFaux is the same
`dnshole@pihole:~$ sudo touch /etc/pihole/COL_TABLE && pihole -up
/opt/pihole/update.sh: line 29: /opt/pihole/COL_TABLE: No such file or directory
dnshole@pihole:~$ `

**Comment by PromoFaux** [comment]
Apologies!

`touch /opt/pihole/COL_TABLE && pihole -up`

**Comment by elaur** [comment]
Now got this
`dnshole@pihole:/opt/pihole$ sudo touch /opt/pihole/COL_TABLE && pihole -up

::: Checking for updates...

/opt/pihole/update.sh: line 46: git rev-parse @{0}: command not found

/opt/pihole/update.sh: line 55: git rev-parse @{upstream}: command not found

::: Error: Local revision could not be obtained, ask Pi-hole support.

::: Additional debugging output:

On branch master

Your branch is behind 'origin/master' by 2 commits, and can be fast-forwarded.

  (use "git pull" to update your local branch)

nothing to commit, working directory clean

dnshole@pihole:/opt/pihole$ `

**Comment by PromoFaux** [comment]
OK @elaur This has all gone horribly wrong :)

Please run:
```
sudo rm -rf /etc/.pihole
sudo git clone https://github.com/pi-hole/pi-hole /etc/.pihole
pihole -r
```

That will get you back to 3.1 whilst we sort out this broken hotfix.

**Comment by PromoFaux** [comment]
Reopened this Pull request here: https://github.com/pi-hole/pi-hole/pull/1617

**Comment by elaur** [comment]
@PromoFaux , Thank you, now everything is back to normal, just reboted my vps and all work fine.

**Pull request merged**
