### PR TITLE
Dependancy cleanup

### PR DESCRIPTION
**Pull request by brontide**
**By submitting this pull request, I confirm the following (please check boxes, eg [X])Failure to fill the template will close your PR:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

- [X] 7

---

Testing has revealed two tiny issues.

- ping and lsof are debugging dependencies that are not default packages in minbase of debian.  Adding to dependency list.
- We have to decide between php and php5.  On debian sid both packages are available.  The logic should prefer the php metapackage over the the php5 package since it's likely to install a more modern php environment.

I will run it though the battery of test to make sure that this doesn't change any of my previous results.

### CODE REVIEW

**Comment by PromoFaux** [comment]
@brontide Could you please update from development? thanks

**Comment by brontide** [comment]
What did you do to development :-)

**Comment by dschaper** [comment]
Is this still WIP'd or ready for review? Looks good from what I'm seeing and would Approve as it is.

**Comment by brontide** [comment]
It's done, I just wanted to run it through the apt based tests I have, feel free to approve it since the changes really are so minor.

**Comment by dschaper** [comment]
Approved

**Comment by dschaper** [comment]
Approved

**Comment by Mcat12** [comment]
Approved

**Pull request merged**
