### PR TITLE
Revert "Include lighttpd-mod-deflate since it is no longer provided by default in Bullsye"

### PR DESCRIPTION
**Pull request by PromoFaux**
Reverts pi-hole/pi-hole#4212

A little premature. See comments on #4212

### CODE REVIEW

**Comment by PromoFaux** [comment]
This is one option.

The other option is to add in code to the install script that conditionally adds this package only if the detected OS is Debian 11 or Ubuntu 21.04

**Comment by dschaper** [comment]
Should probably revert this for now so we don't accidentally release the broken part. 

I don't know if checking for the detected OS is better or worse than checking if the package is available in the repos?

**Review by dschaper — APPROVED** [review]

**Comment by PromoFaux** [comment]
I'm just glad we have an early warning system in the nightly docker dev builds 😅

TBH, it's probably simpler (he says...) to add in a check on the core repo's test cases that checks per package repository?

**Comment by dschaper** [comment]
Maybe something that just calls `apt` and if the package exists, then add it. If not, then skip it.

@MichaIng Do you have anything like this that you use since DietPi is probably going to see the same issues with `lighttpd` if you change to the updated base OS?

**Comment by PromoFaux** [comment]
So far, adding these tests is doing the job on every distro except centos 7 (and I think that is due to remi for PHP):

```py
def test_package_manager_has_installer_deps(Pihole):
    ''' Confirms OS is able to install the required packages '''

    output = Pihole.run('''
    source /opt/pihole/basic-install.sh
    distro_check
    install_dependent_packages ${INSTALLER_DEPS[@]}
    ''')

    assert output.rc == 0


def test_package_manager_has_pihole_deps(Pihole):
    ''' Confirms OS is able to install the required packages '''

    output = Pihole.run('''
    source /opt/pihole/basic-install.sh
    distro_check
    install_dependent_packages ${PIHOLE_DEPS[@]}
    ''')

    assert output.rc == 0


def test_package_manager_has_web_deps(Pihole):
    ''' Confirms OS is able to install the required packages '''

    output = Pihole.run('''
    source /opt/pihole/basic-install.sh
    distro_check
    install_dependent_packages ${PIHOLE_WEB_DEPS[@]}
    ''')

    assert output.rc == 0
```

**Comment by MichaIng** [comment]
Pretty good to know that deflate is not part of the Lighttpd core package anymore. In our scripts we rely on the distro version for such to know whether the package is supposed to be available or not, but in case of Pi-hole this may get complicated when several distros are affected, backport repositories may or may not be enabled etc. Also I wonder if it's worth it to bother with that, as of Pi-hole v6? Also deflate is not required but may only speed up connections a little, which I wouldn't see so important for the Pi-hole admin panel. It's not a forum or blog where you expect much traffic and want visitors to get a smooth impression of your website, care about SEO or so.

But if so, there is the `apt-cache show <package>` method, already used in the installer. It is not 100% reliable, e.g. succeeds as well if another available package depends on `<package>` while that one itself may not be available, but the chances for that are pretty low.

**Pull request merged**
