### PR TITLE
Discourage PHP5 package usage #security

### PR DESCRIPTION
**Pull request by craigmayhew**
PHP5 stopped receiving security updates at the beginning of 2019 (20 months ago).

This PR suggests that we strongly discourage it's usage, for the sake of security.

### CODE REVIEW

**Comment by dschaper** [comment]
Again, exiting with a message of `Update to PHP7` is just going to give us a hundred support tickets saying "How do I update to PHP7????"

**Comment by craigmayhew** [comment]
As mentioned in the previous PR, I was opening it against the correct branch this time.

I will give this some thought, and if unable to find a way to explain the upgrade, I will change the PR to a warning message.

**Comment by dschaper** [comment]
The please mark it as a WIP until you are ready for it to be reviewed.

**Comment by craigmayhew** [comment]
Note there is some discussion at https://github.com/pi-hole/pi-hole/pull/3689#issuecomment-674558674 from the project team on php upgrade prompts. This may result in this PR being superfluous if the php5 code block is removed entirely or it is supplemented with a further upgrade prompt.

**Comment by MichaIng** [comment]
The php5 package code could indeed be removed since its a part that only affects APT-based distros, i.e. Debian and Ubuntu. All officially supported versions of those natively ship PHP7+: https://pkgs.org/search/?q=php-cgi

CentOS 7 indeed ships PHP5, but since its an rpm-based distro this part of the installer code is skipped, on those distros PHP5 and PHP7 packages are all named `php-`* without version string.
**EDIT: Ah I see PHP7 is installed on it as well: https://github.com/pi-hole/pi-hole/pull/3689#issuecomment-674558674**

But while currently Xenial and Jessie can still update Pi-hole to newest version (via env var), this change would indeed then require them to apply a 3rd party/custom package source. Ondrej's PPA would be the way to go, he is the official Debian PHP maintainer anyway, so no difference in build options/approach and such: https://deb.sury.org/
But he dropped support for Jessie, Xenial support is still there: http://ppa.launchpad.net/ondrej/php/ubuntu/dists/
So for Debian users I'm not sure where to cleanly get PHP7 packages from, and the installer requires APT-packages, hence no custom builds. For RPi1 and Zero Raspbian Jessie users it's even worse since those do not support regular Debian armhf (armv7l) builds.
But yeah, as long as the installer exits with a meaningful error message, its probably good to go forward and drop old compatibility code by times.

**Comment by craigmayhew** [comment]
If I understand correctly, some users of older systems might run into issues with installing PHP7. With that in mind I have left this PR with a soft warning message.

**Comment by MichaIng** [comment]
Probably better, at least as long there is no strong reason (like incompatible Pi-hole PHP scripts, or a nice feature that cannot be enabled). Unlikely, especially since Pi-hole v6 comes with its internal webserver (+PHP) anyway.

Btw, do we need to worry that https://github.com/symisc/PH7 didn't receive any commit for more then two years? 🤔

**Comment by DL6ER** [comment]
PHP5 will not be used on any recent systems, for older ones updating may not even be possible. As we'll (at some point) flip over to PH7, I'm going to close this PR. Thanks for your contribution nonetheless!

**Pull request closed without merging**
