### PR TITLE
Remove systemd service and optionally override configs on uninstall

### PR DESCRIPTION
**Pull request by MichaIng**
## Thank you for your contribution to the Pi-hole Community!

Please read the comments below to help us consider your Pull Request.

We are all volunteers and completing the process outlined will help us review your commits quicker.

**Please make sure you**

 1. Base your code and PRs against the repositories developmental branch.
 2. [Sign Off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits as we enforce the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
 3. [Sign](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all your commits as they must have verified signatures
 4. File a pull request for any change that requires changes to [our documentation](https://docs.pi-hole.net/) at our [documentation repo](https://github.com/pi-hole/docs) 

---

**What does this PR aim to accomplish?:**

Remove the FTL systemd service and override configs on uninstall.

**How does this PR accomplish the above?:**

`rm -(R)f` like other files and dirs.

**Link documentation PRs if any are needed to support this PR:**

None

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Review by yubiuser — APPROVED** [review]

**Comment by dschaper** [comment]
Is it a generally accepted practice to remove files that we didn't create like any user-created overrides?

**Comment by MichaIng** [comment]
IMO it is a reasonable cleanup step and as well a potential repair step when users did `systemctl edit pihole-FTL` and forgot about it, not knowing what or where the result of this is actually stored, and when this breaks a future Pi-hole version. But e.g. official Debian packages never do this cleanup, and I perfectly understand the arguments for this as well.

I'll follow whatever you agree with 🙂.

**Comment by yubiuser** [comment]
Why should we keep Pi-hole specific user-overrids when they decide to uninstall Pi-hole?

**Comment by dschaper** [comment]
> Why should we keep Pi-hole specific user-overrids when they decide to uninstall Pi-hole?

Do we know why they are uninstalling Pi-hole? Are they planning on reinstalling or trying to uninstall/reinstall as a troubleshooting option? 

I can see both sides of the argument but I'm hesitant to `rm -rf` a directory that we didn't create with file contents that we didn't create. The fact that apt package removal doesn't remove the files does weigh heavily in my mind.

**Comment by yubiuser** [comment]
> The fact that apt package removal doesn't remove the files does weigh heavily in my mind.

Convinced :-)

**Comment by MichaIng** [comment]
> trying to uninstall/reinstall as a troubleshooting option

That is the only reason I can think of, e.g. if `pihole -r` does not help. And a false/outdated override may be a good reason for a broken Pi-hole which cannot be repaired. That way the uninstall + fresh install path really does a fresh install in this regards and can solve a potentially related issue.

But of course, in theory people could store important files inside this directory, or large customisation of the systemd service, which they want to keep (even upon uninstall + new install) and have no backup of. So generally, the strict rule to never remove something which you did not create, makes sense. Although the Pi-hole uninstaller breaks this already with
```sh
    ${SUDO} rm -rf /var/log/*pihole* &> /dev/null
    ${SUDO} rm -rf /var/log/pihole/*pihole* &> /dev/null
    ${SUDO} rm -rf /etc/pihole/ &> /dev/null
    ${SUDO} rm -rf /etc/.pihole/ &> /dev/null
    ${SUDO} rm -rf /opt/pihole/ &> /dev/null
```
with the only difference that at least the directory itself was created by the installer. Debian packages have it easier with a defined file list.

On DietPi, we always remove systemd overrides on every software uninstall, we never received a complain about this, but I remember many cases where a forgotten override indeed caused issues, which AFAIK was the initial reason to consequently remove them. But there is of course no guarantee what this does remove an unwanted file and we do get a complain about this one day. I decided to rate the practical benefits higher until this happens 😉.

**Comment by dschaper** [comment]
> Although the Pi-hole uninstaller breaks this already with

The uninstaller has been broken for a long time and honestly never worked in the first place.

**Comment by MichaIng** [comment]
> The uninstaller has been broken for a long time and honestly never worked in the first place.

Ah, it is not so bad. The only thing I always wanted to bringt up a PR for is preventing users from purging essential system packages. It is rare, but every 2-3 months or so we face one breaking its network this way (purging `iproute2`) 😄.

Now I have an idea about the overrides, printing it with content may be a good alternative to at least bring it to admins attention, so they can remove it manually, if wanted.

**Review by yubiuser — APPROVED** [review]

**Pull request merged**
