### PR TITLE
Change dummy domain and show device's hostname in ping

### PR DESCRIPTION
**Pull request by Mcat12**
Changes proposed in this pull request:

- Allows users to access Pi-hole console with my.pi-hole.net instead of the IP address

It really just renames the dummy domain from Pi-Hole.IsWorking.OK to my.pi-hole.net

@pi-hole/gravity

### CODE REVIEW

**Comment by PromoFaux** [comment]
Might be worth changing this as per #373

**Comment by Mcat12** [comment]
These latest changes should also fix #373

**Comment by PromoFaux** [comment]
@Mcat12 is the web interface password whiptail dialog supposed to be in this PR?

Also, hella conflicted now i've pushed @nate-ubiquisoft's branch!

**Comment by Mcat12** [comment]
Um... No. I removed that after making the branch I think....

**Comment by PromoFaux** [comment]
huh. Just checked it out and ran the installer, and got a prompt to enter password :)

**Comment by Mcat12** [comment]
On dev?

**Comment by PromoFaux** [comment]
on this branch! `local-domain`

**Comment by Mcat12** [comment]
That is because this branch was created before I removed the password stuff.

**Comment by PromoFaux** [comment]
Ah,  you're going to need to rebase it anyway,  or we can cherry pick

**Comment by Mcat12** [comment]
What's actually easier (and recommended by Github in the "command line instructions") is to merge dev into local-domain, fix conflicts, and then merge local-domain into dev.

**Pull request merged**
