### PR TITLE
Typo/Linter fix

### PR DESCRIPTION
**Pull request by dschaper**
Fixes #INTERNAL .

Changes proposed in this pull request:

- Typo fixes

- Format linting

@pi-hole/gravity

Fix a few typo's, run through linter for format corrections.

### CODE REVIEW

**Comment by Mcat12** [comment]
Approved

**Comment by jacobsalmela** [comment]
Approved

**Comment by PromoFaux** [comment]
Approved

**Comment by PromoFaux** [comment]
No!

**Comment by PromoFaux** [comment]
Revoked

**Comment by PromoFaux** [comment]
PR to development please, so we don't have to update development from master.

**Pull request closed without merging**
