### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AstroGD**
I updated the README so that the root check of pihole on install will succeed. Otherwise there may bes some complications after the install and pihole may not be working correctly

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [] I have commented my proposed changes within the code. (I could not figure out how or what you exactly mean by that sorry - The only change is in line 27 - I changed the bash command to sudo bash)
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*
Make the root priviliege check not fail if anyone installs pihole through the steps in the README.

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*
Add sudo to the bash command in line 27

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*
-- NONE --

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by dschaper** [comment]
You don't need to do that, the installer will check to see if the proper privileges exits.

**Comment by AstroGD** [comment]
Yes the installer will but if there are not the required priveleges the installer will just run and maybe install some packages not or incorrectly

**Comment by dschaper** [comment]
You can't install a package without admin/root privs. No maybe about it.

**Comment by AstroGD** [comment]
I just installed pihole and everything seemed to be fine until i started using pihole and everything (dashboard and functionality) was corrupted. I also did not have the pihole command (command not found). After I reinstalled Pihole with sudo everything worked. My issue is that the command in your readme is without sudo and there is no install-prevention in pihole if there are no root permissions available. For beginners and inexperienced people this could be a very big issue and they could have huge issues installing pihole. I think this is unnecessary and it would be cool if even the docs would show the correct command or the pihole installation script would fail when there are no root permissions.

**Comment by dschaper** [comment]
You don't need to call it with `sudo`. See https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L2453 for effective id = 0 check.

**Comment by AstroGD** [comment]
Well it was not working when I installed Pihole...
It showed that it had no root privileges but continued with the installation anyway.
Thats why pihole broke after install for me

**Comment by PromoFaux** [comment]
@AstroGD , yeah that's correct... it will detect that you are not running as root, and then run it again as root, as seen on this line here not the ` | sudo bash` after it `curl`s the install script again

https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L2473

if `sudo` is not found on the users system, then it will not proceed any further.

Long and short: it is impossible for the installer to continue without root privileges

**Comment by AstroGD** [comment]
I saw the code and I don't now why but it seemed like it did in my case. Pihole finished the installation and afterwards the pihole command was not registered and there were files missing that caused the web-interface to throw errors. After installing pihole with sudo bash at the end of the command everything worked and pihole installed correctly. A notable difference was when pihole installed the dependencies. With root it took much longer and without it only came to like 20% progress and then abruptly cancelled and switched back to normal console output telling me that pihole installed successfully

**Comment by dschaper** [comment]
Then there's a bug to investigate. The solution is not to sledgehammer in `sudo` where it's not needed. As such please open an issue to investigate the bug. Closing this as it's not needed or useful.

**Comment by PromoFaux** [comment]
I'll be honest, it sounds like something "other" went wrong on the first install. Do you still have the output of the original install, perchance? Long shot I know!

If it is not too much effort, and you are installing on a Pi or something, perhaps it is worth flashing a fresh SD card and trying again from scratch to see if you can reproduce it. If so, open up a bug report and we'll look into it, but I can assure you I have run the installer without `sudo` 1000's of times, and it hasn't been an issue :)

Good luck , and thanks for the submission anyway, but as Dan said, it's not necessary

**Comment by AstroGD** [comment]
Sadly I dont have the output of the first install as I restartet my pi several times since then but if I have the time Ill try with a fresh install of raspbian again. If I can reproduce the issue I will open a pull request.

Thanks for the quick responses and your time, I appreciate that :)
Have a nice day ^^

**Pull request closed without merging**
