### PR TITLE
Don't fail when trying to detect OS architecture on RPM-based systems

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
Fix a crash when trying to detect the FTL architecture on rpm-based x86_64 systems.

**How does this PR accomplish the above?:**
There is a check which only works on `deb`-based systems. I modified the code to proceed correctly when `dpkg` is not available.

A crash is seen, e.g., here: https://github.com/pi-hole/FTL/issues/496#issuecomment-466367909

**What documentation changes (if any) are needed to support this PR?:**
None

### CODE REVIEW

**Comment by DL6ER** [comment]
@bcambl How'd this look like? In `uname`'s `mna` page,  see
```
       -m, --machine
              print the machine hardware name

       -i, --hardware-platform
              print the hardware platform (non-portable)
```
I'm a bit worried about this "non-portable"

**Comment by bcambl** [comment]
I would say it is more portable than a command that only exists on Debian family.

**Comment by bcambl** [comment]
> Print ‘unknown’ if this information is not available. Note this is non-portable (even across GNU/Linux distributions).

**Comment by bcambl** [comment]
>   -m, --machine            print the machine hardware name
>   -p, --processor          print the processor type (non-portable)
>   -i, --hardware-platform  print the hardware platform (non-portable)
> 
> 

_[bcambl@unknown ~]$ uname -m
x86_64
[bcambl@unknown ~]$ uname -p
x86_64
[bcambl@unknown ~]$ uname -i
x86_64
[bcambl@unknown ~]$_

**Comment by bcambl** [comment]
Also worth noting that the `arch` command ships along with the same package that provides `uname` (`coreutils`) and returns the same data as the _portable_ `uname -m`.

**Comment by bcambl** [comment]
Also we might want to test for both _i386_ and _i686_.

**Comment by DL6ER** [comment]
@bcambl I really don't know how it should look like for `rpm` systems, we've seen `i368` being returned from `dpkg` which is for what this `if` statement was designed for initially. `arch` reported a 64bit CPU for the user but the system was `i386` and even though the system might have been able to run 64bit binaries, the OS was lacking the 64bit libraries.

I think this strange behavior is what you'd expect if you install a 32bit OS on a 64bit CPU machine. We could drop support for this bizarre case but the more users you have, the more uncommon setups you see...

```bash
rpm -q --qf '%{ARCH}\n' glibc | grep x86_64 || echo "i386"
```
seems okay.

**Comment by bcambl** [comment]
Actually.. 32bit should never be installed on Fedora or CentOS any way.
FTL on Fedora 29+ and CentOS 7+ should be x86_64 or ARM only.

**Comment by DL6ER** [comment]
@bcambl So we can go back to my initial idea of
```
dpkg || true
```
to just skip the test for x86_64 without `dpkg`??

**Comment by bcambl** [comment]
I would say so. The last 32bit on the Fedora side was CentOS6 (unsupported).
My apologies for the run-around.. /facepalm

**Comment by Mcat12** [comment]
@DL6ER @bcambl In order to finish off this PR, it looks like the changes should be reverted back to the original `dpkg || true` idea?

**Comment by DL6ER** [comment]
I agree, I will hard-reset to https://github.com/pi-hole/pi-hole/pull/2646/commits/9867b7fccfdd95483680b34f5aa2636674016783 and force-push. This will provide a clean history while the comments in this PR will be preserved.

**Comment by DL6ER** [comment]
@Mcat12 I did as I promised to do. Please re-approve when you find the time to look at it.

**Pull request merged**
