### PR TITLE
Have the install script update the owner of admin files

### PR DESCRIPTION
**Pull request by celly**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [🐓] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [🐓] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [🐓] I have considered, and confirmed that this submission will be valuable to others.
- [🐓] I accept that this submission may not be used, and the pull request closed at the will of the This maintainer.
- [🐓] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

3.4

---

This updates permissions for the web-ui to be not root during install.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by dschaper** [comment]
Can you help us with some examples of how current code is causing a problem and how your proposed changes will improve on that situation? Thanks.

**Comment by celly** [comment]
@dschaper The current install script installs everything as root. So, it makes the owner of all the files in the admin interface is root. 

```sh
ls -lat /var/www/html/admin/

drwxr-xr-x 7 root     root      4096 Sep 21 21:34 .
-rw-r--r-- 1 root     root         8 Sep 21 21:34 pullapproval.yml
drwxr-xr-x 8 root     root      4096 Aug 15 15:58 .git
drwxrwxr-x 4 www-data www-data  4096 Jun 30 17:21 ..
drwxr-xr-x 3 root     root      4096 Jun 30 17:20 style
-rw-r--r-- 1 root     root      5926 Jun 30 17:20 api_FTL.php
-rw-r--r-- 1 root     root      6700 Jun 30 17:20 index.php
-rw-r--r-- 1 root     root     14164 Jun 30 17:20 LICENSE
-rw-r--r-- 1 root     root       648 Jun 30 17:20 .pullapprove.yml
-rw-r--r-- 1 root     root     36398 May  4 12:20 settings.php
-rw-r--r-- 1 root     root       903 May  4 12:20 taillog-FTL.php
-rw-r--r-- 1 root     root       895 May  4 12:20 taillog.php
-rw-r--r-- 1 root     root      2152 May  4 12:20 api.php
-rw-r--r-- 1 root     root      2745 May  4 12:20 api_PHP.php
-rw-r--r-- 1 root     root       846 May  4 12:20 CONTRIBUTING.md
-rw-r--r-- 1 root     root       949 May  4 12:20 debug.php
-rw-r--r-- 1 root     root      1230 May  4 12:20 gravity.php
-rw-r--r-- 1 root     root      9570 May  4 12:20 help.php
-rw-r--r-- 1 root     root      3291 May  4 12:20 list.php
-rw-r--r-- 1 root     root      4401 May  4 12:20 queries.php
-rw-r--r-- 1 root     root      1106 May  4 12:20 queryads.php
-rw-r--r-- 1 root     root      2038 May  4 12:20 README.md
drwxr-xr-x 4 root     root      4096 Jan  9  2017 scripts
drwxr-xr-x 2 root     root      4096 Jan  9  2017 img
drwxr-xr-x 2 root     root      4096 Jan  9  2017 .github
-rw-r--r-- 1 root     root        45 Jan  9  2017 .user.php.ini
-rw-r--r-- 1 root     root       153 Aug 21  2016 .gitignore
```

This isn't breaking anything right now. It's just bad practice, and could be dangerous.

**Comment by dschaper** [comment]
Thank you, I'm not sure if that changing the user/group to `pihole:pihole` will allow the web interface to access those files, since the contents of the directory are only readable by the user that owns the `/var/www/html` directory and `root`. Will test and see if changing to those users will stop the functioning of the web interface.

**Comment by celly** [comment]
Awesome. Thanks.

**Comment by Mcat12** [comment]
@celly It looks like this PR got lost in time. I will test to see if it works, but what security issues were you thinking about?

**Comment by celly** [comment]
@Mcat12 it is a bit less of a security issue, and more of just being dangerous. Any time you can have something not be owned by root, the better. 

That being said, taking a second look at this change, this does now give lighttpd process write access to these files. That could be seen as more dangerous to some, and the files should probably be owned by the pi/pihole user instead. However, that may cause issues for people who are not running this on a pi or using pihole-FTL.

If you want, we can close this for, and I can circle back to it in a bit when I have some more time.

**Comment by Mcat12** [comment]
Ok, closing for now. Also note that the new web interface + API will fix this issue by removing the external web server dependency.

**Pull request closed without merging**
