### PR TITLE
Script cleanup

### LINKED ISSUE #377: Uninstall script uinstalls PHP5 and all its dependencies without asking!
##### Expected Behaviour:
The uninstall script (curl -L uninstall.pi-hole.net | bash) should only uninstall packages that have been newly added by the install script (curl -L install.pi-hole.net | bash).

##### Actual Behaviour:
The uninstall script actually uninstalled & purged php5 and all(!) its dependencies which left my other sites / project on Ubuntu in limbo! 
(it should not make a difference if I use the scripts on a Pi or a Ubuntu Server....)

The apt log (which helped me to restore the server) looks like this: http://pastebin.com/Vnvi4HpS

### PR DESCRIPTION
**Pull request by nate-ubiquisoft**
Fixes #377  .
Massive cleanup of scripts, namely word splitting vulnerabilities, outdated scripting errors, and erroneous bash scripting.
Refactored uninstall.sh so a prompt is displayed with information on whether or not to allow apt-get purge to occur, damaging some OSes.

@pihole/gravity

### CODE REVIEW

**Comment by nate-ubiquisoft** [comment]
I already ran the uninstall.sh on my local pihole and had it keep the dependencies, which it did successfully while still removing all of pihole. The reinstall then from basic-install.sh worked flawlessly to get my back online behind the pihole.
 I ran each file through shellcheck.net when I was done and they are all squeaky clean

**Comment by Mcat12** [comment]
You should have branched the debug script, uninstall changes, and misc changes away from each other.

**Comment by nate-ubiquisoft** [comment]
Yea I know I need to refactor my branching. Ran into a weird issue with my local git repo that wouldnt let me switch branches but it was throwing no errors. Just the files wouldnt reflect the changes in each branch

**Comment by nate-ubiquisoft** [comment]
@Mcat12 Can you close/remove this pull request as well as my other, #394? I will refactor my branching and resubmit the pull requests to the correct branch.

**Comment by PromoFaux** [comment]
Closing as requested

**Pull request closed without merging**
