### PR TITLE
feat: Redirect automatically to admin page

### PR DESCRIPTION
**Pull request by ls4cfk**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by dschaper** [comment]
Anything you'd like to share as to what or why?

**Comment by ls4cfk** [comment]
When you visit the IP of pi-hole it automatically will be redirected to the admin page

**Comment by dschaper** [comment]
Why? That will break a lot of other functionality.

**Comment by MichaIng** [comment]
Little addition about why it is as it is now (hopefully still up to date and correctly understood by me 😅):
- When you use the blocking page, Pi-hole resolves blocked domains with the Pi-hole IP.
- A DNS resolver cannot change the request URL, only the host/domain, hence it cannot rewrite blocked requests to the blocking page explicitly.
- Instead the Lighttpd config rewrites the 404 handler to the Pi-hole blocking page and "hopes" that the request path does not really exist within the Pi-hole webroot, hence Lighttpd will answer with 404, redirecting to the blocking page, as desired.
- Of course the chance that a certain path exists in the Pi-hole webroot is quite low, but often you want/need to block a raw domain as well without a path in the request, if not for actual blocking reasons, probably at least for testing or you want to see the blocking page to add the domain to whitelist or such.
- I.e. you want to have "blocked.domain.org" in browser to show the blocking page instead of the Pi-hole admin panel. This is with current blocking page only possible if there is no index page in Pi-holes webroot and no rewrite in place like yours, that would prevent a 404.

Of course the above is only a problem if you really want to use the blocking page. If not, then AFAIK usual blocking method is to resolve the domain with `0.0.0.0`, where the Pi-hole index page or rewrite has no influence.

Not sure if there is another reason to decline redirect to Pi-hole admin page, but at least the benefit is marginal, since currently you just need to do one more click to link you from blocking page to admin panel.

**Pull request closed without merging**
