### PR TITLE
Include secondary upstream DNS for Quad9+Filter+ECS

### PR DESCRIPTION
**Pull request by tullo-x86**
### Adds the secondary DNS server IP for Quad9's filter+ECS resolver
Source: [Quad9 FAQ](https://www.quad9.net/faq/)

**By submitting this pull request, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code. _The change is in an uncommented block of envvars containing upstream IP addresses; there does not appear to be an appropriate place to leave a meaningful comment_
- [ ] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**
Completes the list of available upstream DNS resolvers hosted by Quad9.

**How does this PR accomplish the above?:**
Adds the missing IPv6 address for the backup resolver.

**What documentation changes (if any) are needed to support this PR?:**
Some screenshots of the configuration page may appear out of date after this change is deployed.

### CODE REVIEW

**Comment by dschaper** [comment]
Please rebase your changes on to the `development` branch. You can force push to this PR once you have done that to clear off the extra commits, or open a new PR with your changes made to a branch created off our development branch. No PRs should be opened against the `master` branch.

**Comment by tullo-x86** [comment]
That'll teach me to read the contributor's guide after 9 PM... >_>

**Review by PromoFaux — APPROVED** [review]
Fine with this change, as it is not adding another to the list - only adding a missing secondary to an existing entry

**Review by PromoFaux — CHANGES_REQUESTED** [review]
That said, the test is failing so let me look into that...

**Comment by PromoFaux** [comment]
Cherry-picked into #3851

**Pull request closed without merging**
