### PR TITLE
[Fix] Debian Dependency Installer Fault

### PR DESCRIPTION
**Pull request by dschaper**
**By submitting this pull request, I confirm the following (please check boxes, eg [X])Failure to fill the template will close your PR:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

- [x] 10 (very familiar)

---
Fix: Installing dependent packages will fault and fail in some installations. This is an attempt to fix that, or at least provide a more informative error response to the user.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by dschaper** [comment]
Cherry picked from #871

**Comment by dschaper** [comment]
```
::: Preparing to run gravity.sh to refresh hosts...
::: Running gravity.sh
:::
::: Neutrino emissions detected...
:::
::: No custom adlist file detected, reading from default file... done!
:::
::: Getting raw.githubusercontent.com list... List updated, transport successful!
::: Getting mirror1.malwaredomains.com list... List updated, transport successful!
::: Getting sysctl.org list... List updated, transport successful!
::: Getting zeustracker.abuse.ch list... List updated, transport successful!
::: Getting s3.amazonaws.com list... List updated, transport successful!
::: Getting s3.amazonaws.com list... List updated, transport successful!
::: Getting hosts-file.net list... List updated, transport successful!
::: Getting raw.githubusercontent.com list... List updated, transport successful!
::: 
::: Aggregating list of domains... done!
::: Formatting list of domains to remove comments.... done!
::: 129676 domains being pulled in by gravity...
::: Removing duplicate domains.... done!
::: 105552 unique domains trapped in the event horizon.
:::
::: Adding adlist sources to the whitelist... done!
::: Whitelisting 6 domains... done!
::: Nothing to blacklist!
::: Formatting domains into a HOSTS file...
::: No IP Values found! Please run 'pihole -r' and choose reconfigure to restore values
::: Restarting services...
:::
```

**Comment by dschaper** [comment]
Wheezy still complains, but Jessie and Ubu's all work with the progress bar.

**Comment by dschaper** [comment]
Needs extensive testing, only contains fixes for Debian and Ubuntu installs falling and crashing the installation script.

**Comment by Mcat12** [comment]
I tried installing on an empty Ubuntu DO VM and have the output: http://pastebin.com/eLDcKj5i

I noticed this line, although it's in gravity.sh:
`::: Formatting domains into a HOSTS file...::: No IP Values found! Please run 'pihole -r' and choose reconfigure to restore values`

**Comment by dschaper** [comment]
Okay, it's running in a subshell and not catching the `setupVars` file since that is written in another subshell. Once the script completes, all the shells are done with their writing and that file is populated.

**Comment by dschaper** [comment]
Did you get the progress bar or the plain installer?

**Comment by Mcat12** [comment]
When I ran `pihole -r` I got the progress bar.

**Comment by dschaper** [comment]
Okay, there's some cache-busting to do then... Thanks for the check.

**Comment by dschaper** [comment]
Development is so different that I'm closing this out and starting fresh with that updated code base. And will clean out the cherry picks to make sure CLA passes.

**Pull request closed without merging**
