### PR TITLE
Save custom IP

### LINKED ISSUE #471: gravity.sh overwrites custom IP settings in gravity.list
##### Expected Behaviour:
`gravity.sh` should preserve the customized IP (for example, an external IP) if one is in place instead of detecting it.

##### Actual Behaviour:
My pi-hole is on an external network with a private IP. During setup I specified its external IP. If `pihole -g` is run afterward, all the domains in `gravity.list` point to the internal IP (detected in `gravity.sh`), instead of the external IP specified during setup.

##### Steps to reproduce this issue:

1. Run pihole setup script and set a different IP than the one detected.
2. Domains in `gravity.list` point to the customized IP.
3. Run `pihole -g`.
4. Domains in `gravity.list` point to the detected IP.

### PR DESCRIPTION
**Pull request by jim-liu**
Fixes #471  .

Changes proposed in this pull request:

- Make `gravity.sh` preserve custom IP setting by not deleting `/tmp/piholeIP`.

- Make `whitelist.sh` use custom IP by reading `/tmp/piholeIP` if it exists.

@pi-hole/gravity

### CODE REVIEW

**Comment by Mcat12** [comment]
I think perhaps saving it to /etc/pihole/ would a more reliable way to store it, since tmp is a temporary place.

**Comment by jim-liu** [comment]
I agree, but I was trying to minimize the changes.

**Comment by Mcat12** [comment]
That's fine. We're OK with changes, since that's what a PR is for. ;)

**Comment by jim-liu** [comment]
Changed basic-install.sh so it saves $piholeIP to /etc/pihole/piholeIP, and changed gravity.sh, whitelist.sh and blacklist.sh to read the file if it exists.

**Comment by Mcat12** [comment]
I'm not getting any piholeIP file in my directory after installing...

**Comment by jim-liu** [comment]
You don't have a `/etc/pihole/piholeIP`?

**Comment by Mcat12** [comment]
After removing my pihole directory and running the install script off of your branch (with .pihole on your branch) it doesn't have piholeIP in it.

**Comment by jim-liu** [comment]
I don't know how to use the automated installer to test it (since it doesn't pull the development branch), so here's what I did:

1. Using the automated installer to install everything.
2. Create `/etc/pihole/piholeIP` with the VM's IP address.
3. Modify `gravity.sh`, `whitelist.sh` and `blacklist.sh` according to my commits.
4. Run `pihole -g` and notice the custom IP set in `/etc/pihole/piholeIP` is in effect.

If you could let me know how to test using the automated installer, I would run it again =)

**Comment by PromoFaux** [comment]
OK, i've pulled it into a seperate branch for you to try out. You should be able to test using the automated installed by following these steps:

```BASH
cd /etc/.pihole
sudo git fetch
sudo git checkout jim-liu-dev
./automated\ install/basic-install.sh
```

**Comment by jim-liu** [comment]
Thanks! I tested it again. If the detected value was accepted during install, `/etc/pihole/piholeIP` will not be created. If a custom IP was specified (even if it's the same as the detected), `/etc/pihole/piholeIP` will be created and used for generating `/etc/pihole/gravity.list`.

I don't think `/etc/pihole/piholeIP` is needed if the user just let the installer detect the IP, since all subsequent runs of `pihole -g` will detect IP address as well.

**Comment by PromoFaux** [comment]
I think it's probably worth creating the file anyway. I faced this issue myself a while back when I had an outgoing VPN connection on my pi as well as pihole. gravity would update with the IP address of `tun0` rather than `eth0` (Rather than code a fix for this, I just moved my VPN connection to a separate machine!)

**Comment by jim-liu** [comment]
Yeah that makes sense. Since the IP shouldn't change regardless of it's detected or custom set.

**Comment by PromoFaux** [comment]
added that to the `jim-liu-dev` if you want to test it.

**Comment by jim-liu** [comment]
Thanks! Just tested it - using all default values during installation. `piholeIP` was correctly saved.

**Comment by PromoFaux** [comment]
Super, If I get a chance later I will test it myself. Bit hectic in my real job recently!

**Comment by Mcat12** [comment]
Seems to work fine.

**Pull request merged**
