### PR TITLE
Script cleanup

### PR DESCRIPTION
**Pull request by nate-ubiquisoft**
This branch contains a variety of small patches to the bash scripts to improve stability across bash shells. Fixed issues:

- Unused variables cleaned up
- Double quotes added to prevent globbing/word splitting
- `read -a` replaced with `read -r` due to `-a` misinterpreting backslashes
- Double quotes around arrays to prevent re-splitting elements
- Removed erroneous `cat`s as they were not doing anything
- New Spinner that works across more shells

In addition to these fixes, `uninstall.sh` has been overhauled:

- Now removes /etc/.pihole git checkout
- Now removes all pihole log files
- Warn user about purging packages if not on raspbian or debian distro
 - If user accepts purging, packages are purged as before and relative package config files are removed
 - If the user does not accept, all pihole files are removed without purging any packages nor removing package related config files

I have run through 10 uninstall/reinstall cycles on my local pihole and everything is working fantastically. I have tested both cases of purging packages and reinstalling as well as not purging and reinstalling with success in both cases. 

@pihole/gravity

### CODE REVIEW

**Comment by Mcat12** [comment]
How about looping through each package that was newly installed by Pi-hole and asking if it should be removed?

**Comment by PromoFaux** [comment]
I think i have that in a PR already if you want some inspiration

**Comment by PromoFaux** [comment]
#288

**Comment by nate-ubiquisoft** [comment]
@Mcat1

> How about looping through each package that was newly installed by Pi-hole and asking if it should be removed?

Done

**Comment by Mcat12** [comment]
It would help for future expansion to loop through the dependencies instead of hardcoding them.

**Comment by PromoFaux** [comment]
Agreed with @mcat12.. See how I did it in  #288

**Comment by nate-ubiquisoft** [comment]
Okay I think this may be ready for UAT. It has been run close to 30 times now (basic-install.sh <> uninstall.sh) since my last commit and I have had no issues, but rather less as many issues as before. Scripts now handle just about every case of default files not being present and squelching stdout output. I also implemented a newer spinner which looks a bit nicer XD.

**Comment by PromoFaux** [comment]
Cool! I'll be back from visiting my parents tomorrow, and as it's a bank holiday I'll have plenty of time to test  it out! Thanks for the work.

**Comment by PromoFaux** [comment]
image

@nate-ubiquisoft Some requests for the uninstall script:

-  Add a `(y/n): ` to the end of the first question to match other prompts. 
-  Indent the line `::: Removing <blah>` with 4 extra spaces between `:` and `R`
-  Move the spinner /`DONE!` output back to the same line as `Removing <blah>...` (I think with a -n switch on echo?)

image

-  Did you get the above error when removing the `php5` dependencies? I'm wondering if removing `php5-common` also purges the other two packages?

image

-  Same thing here for the spinner/`DONE!` output. Needs to be on the same line.

Other than that, seems to do what it says it does! Now to try a reinstall...

**Comment by PromoFaux** [comment]
:S So running `uninstall.sh` and removing all dependencies seems to break a lot of things, that said, it could be the way my network is setup. 

`/etc/resolv.conf` contained only one `nameserver` entry.. which was the server's own IP!

``` bash
 bash install.sh
:::
::: sudo will be used for the install.
::: Using interface: eth0
::: Using IPv4 on 192.168.1.1/24
::: Using IPv6 on fe80::3aea:a7ff:fea1:646
::: Using Google DNS servers.
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: There are 177 updates availible for your pi!
::: We recommend you run 'sudo apt-get upgrade' after installing Pi-Hole!
:::
:::
::: Checking dependencies:
:::    Checking for dnsutils... Not found! Installing.... [/]  E: Failed to fetch http://security.debian.org/pool/updates/main/b/bind9/bind9-host_9.9.5.dfsg-9+deb8u6_amd64.deb  Could not resolve 'security.debian.org'

E: Failed to fetch http://security.debian.org/pool/updates/main/b/bind9/libisc95_9.9.5.dfsg-9+deb8u6_amd64.deb  Could not resolve 'security.debian.org'

E: Failed to fetch http://security.debian.org/pool/updates/main/b/bind9/libdns100_9.9.5.dfsg-9+deb8u6_amd64.deb  Could not resolve 'security.debian.org'

E: Failed to fetch http://security.debian.org/pool/updates/main/b/bind9/libisccfg90_9.9.5.dfsg-9+deb8u6_amd64.deb  Could not resolve 'security.debian.org'

E: Failed to fetch http://security.debian.org/pool/updates/main/b/bind9/libbind9-90_9.9.5.dfsg-9+deb8u6_amd64.deb  Could not resolve 'security.debian.org'

E: Failed to fetch http://security.debian.org/pool/updates/main/b/bind9/liblwres90_9.9.5.dfsg-9+deb8u6_amd64.deb  Could not resolve 'security.debian.org'

E: Failed to fetch http://security.debian.org/pool/updates/main/b/bind9/dnsutils_9.9.5.dfsg-9+deb8u6_amd64.deb  Could not resolve 'security.debian.org'

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?                                                                                                                                                   done!
:::    Checking for bc... Not found! Installing.... [/]  E: Failed to fetch http://ftp.uk.debian.org/debian/pool/main/b/bc/bc_1.06.95-9_amd64.deb  Could not resolve 'ftp.uk.debian.org'

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?                                                                                                                                                   done!
:::    Checking for toilet... Not found! Installing.... done!
:::    Checking for figlet... Not found! Installing.... done!
:::    Checking for dnsmasq... Not found! Installing.... done!
:::    Checking for lighttpd... Not found! Installing.... done!
:::    Checking for php5-common... Not found! Installing.... done!
:::    Checking for php5-cgi... Not found! Installing.... done!
:::    Checking for php5... Not found! Installing.... done!
:::    Checking for git... Not found! Installing.... [/]  E: Failed to fetch http://security.debian.org/pool/updates/main/g/git/git-man_2.1.4-2.1+deb8u2_all.deb  Could not resolve 'security.debian.org'

E: Failed to fetch http://security.debian.org/pool/updates/main/g/git/git_2.1.4-2.1+deb8u2_amd64.deb  Could not resolve 'security.debian.org'

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?                                                                                                                                                   done!
:::    Checking for curl... already installed!
:::    Checking for unzip... Not found! Installing.... done!
:::    Checking for wget... already installed!
:::
::: Stopping services... done.
::: Checking if user 'pihole' exists...
::: User 'pihole' already exists
:::
::: Checking for existing base files...
:::    Checking /etc/.pihole is a repo... not found!!
:::    Cloning https://github.com/pi-hole/pi-hole.git into /etc/.pihole...sudo: git: command not found
 done!
:::
::: Checking for existing web interface...
:::    Checking /var/www/html/admin is a repo... not found!!
:::    Cloning https://github.com/pi-hole/AdminLTE.git into /var/www/html/admin...sudo: git: command not found
 done!
:::
::: Installing scripts...cp: cannot stat ‘/etc/.pihole/gravity.sh’: No such file or directory
cp: cannot stat ‘/etc/.pihole/advanced/Scripts/chronometer.sh’: No such file or directory
cp: cannot stat ‘/etc/.pihole/advanced/Scripts/whitelist.sh’: No such file or directory
cp: cannot stat ‘/etc/.pihole/advanced/Scripts/blacklist.sh’: No such file or directory
cp: cannot stat ‘/etc/.pihole/advanced/Scripts/piholeLogFlush.sh’: No such file or directory
cp: cannot stat ‘/etc/.pihole/advanced/Scripts/updateDashboard.sh’: No such file or directory
chmod: cannot access ‘/usr/local/bin/gravity.sh’: No such file or directory
chmod: cannot access ‘/usr/local/bin/chronometer.sh’: No such file or directory
chmod: cannot access ‘/usr/local/bin/whitelist.sh’: No such file or directory
chmod: cannot access ‘/usr/local/bin/piholeLogFlush.sh’: No such file or directory
 done.
:::
::: Installing configs...
:::    Existing dnsmasq.conf found... it is not a pi-hole file, leaving alone!
:::    Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf...cp: cannot stat ‘/etc/.pihole/advanced/01-pihole.conf’: No such file or directory
 done.
sed: can't read /etc/dnsmasq.d/01-pihole.conf: No such file or directory
sed: can't read /etc/dnsmasq.d/01-pihole.conf: No such file or directory
sed: can't read /etc/dnsmasq.d/01-pihole.conf: No such file or directory
cp: cannot stat ‘/etc/.pihole/advanced/lighttpd.conf’: No such file or directory
:::
::: Creating log file and changing owner to dnsmasq... done!
:::
::: Installing pihole custom index page...cp: cannot stat ‘/etc/.pihole/advanced/index.html’: No such file or directory
::: done!
:::
::: Installing latest Cron script...cp: cannot stat ‘/etc/.pihole/advanced/pihole.cron’: No such file or directory
 done!
:::
::: Preparing to run gravity.sh to refresh hosts...
::: Running gravity.sh
install.sh: line 654: /usr/local/bin/gravity.sh: No such file or directory
::: Restarting services... done.
:::
::: Installation Complete! Configure your devices to use the Pi-hole as their DNS server using:
:::     192.168.1.1/24
:::     fe80::3aea:a7ff:fea1:646
:::
::: If you set a new IP address, you should restart the Pi.
:::
::: The install log is located at: /etc/pihole/install.log
```

**Comment by PromoFaux** [comment]
Adding a secondary name server fixed that, install script works again.

Might be worth adding a line to prompt user to change their DNS settings on their router/clients so they don't have issues resolving!

What would also be nice along the line is using `whiptail` in the uninstall script, so we could have checkboxes for the dependencies the user wishes to remove/keep. That's for another time.

Once you've made the changes mentioned above, I'll give it another test and then it can be merged.

Thanks again¬

**Comment by PromoFaux** [comment]
And to answer my own question: Yes.

image

**Comment by nate-ubiquisoft** [comment]
I moved the scripts from being copied to /usr/local/bin since we really shouldnt be copying them there. Instead they now go to /opt/pihole/ and are symlinked to /usr/local/bin. I am working on a single controller command called pihole which will have options to run all the different scripts so that users only need to use one command to do everything, rather than generic commands like uninstall.sh.

**Comment by Mcat12** [comment]
Maybe branch that off of this branch. These script changes can be merged first.

**Comment by nate-ubiquisoft** [comment]
Okay I'll work on this as I get free time this afternoon. My meeting at FedEx was cancelled this morning so I had some time to start on it. I've also got another branch off of my master which has all my latest changes that I am implementing UnboundDNS

**Comment by Mcat12** [comment]
Is that branching off master? Make sure to be doing that off development.

**Pull request closed without merging**
