### PR TITLE
Change the exemption issue label pinned to internal for stale issues

### PR DESCRIPTION
**Pull request by yubiuser**
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [ ] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/contributing/).

---
**What does this PR aim to accomplish?:**
Change the exemption issue label `pinned` to `internal` for stale issues. We don't use the label pinned, but internal

### CODE REVIEW

**Comment by PromoFaux** [comment]
Pinned, in this case, means that the issue is pinned to the top of the page, not a label.

We can add internal as an additional, though, for sure.

**Comment by yubiuser** [comment]
> Pinned, in this case, means that the issue is pinned to the top of the page, not a label.

Do you have any reference for this? I was looking for this, but the only case I found was after others explicitly added `pinned` as a label...

**Comment by PromoFaux** [comment]
Oh, no reference - all based on assumption.

**Comment by yubiuser** [comment]
Try searching for issues with `label:pinned` yields nothing, even one is currently pinned...

**Review by dschaper — APPROVED** [review]

**Review by PromoFaux — APPROVED** [review]

**Pull request merged**
