### PR TITLE
Added Link to blink1_pi-hole.py

### PR DESCRIPTION
**Pull request by elpatron68**
**By submitting this pull request, I confirm the following (please check boxes, eg [X])Failure to fill the template will close your PR:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

- [X] 1 (very unfamiliar)
---
readme.md: Added link to blink1_pi-hole.p_

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by PromoFaux** [comment]
Approved

**Comment by dschaper** [comment]
@elpatron68 Can we get you to fill out the full PR questions, It's a process we all need to go through.

**Comment by elpatron68** [comment]
@dschaper done, sorry for lazyness!

**Comment by dschaper** [comment]
Thank you, it may seem tedious for small pulls, but it does help us a ton.
Approved

**Comment by Mcat12** [comment]
Approved

**Pull request merged**
