### PR TITLE
Pi-hole version 2.9.2

### PR DESCRIPTION
**Pull request by PromoFaux**
@pi-hole/gravity

### CODE REVIEW

**Comment by PromoFaux** [comment]
Approved

**Comment by PromoFaux** [comment]
:shipit:

**Comment by PromoFaux** [comment]
Approved (again)

**Comment by dschaper** [comment]
:+1:

**Comment by PromoFaux** [comment]
Approved (again, again!)

**Comment by jacobsalmela** [comment]
Approved

**Comment by Mcat12** [comment]
Approved

**Pull request merged**
