### PR TITLE
Dns hostname fixes

### PR DESCRIPTION
**Pull request by bcambl**
Fixes #593 .

Changes proposed in this pull request:

- reinstate 8550b76 - add gateway to sysconfig interface file

- add primary and secondary dns to sysconfig interface file

- fix newline in configureSelinux stdout

- additional logic in gravity.sh to determine hostname

@pi-hole/gravity

### CODE REVIEW

**Comment by PromoFaux** [comment]
> reinstate 8550b76 - add gateway to sysconfig interface file

Yikes, that'll teach me to git pull before branching off!

**Comment by bcambl** [comment]
@PromoFaux ha ha! Yea, I paved my cubieboard and reinstalled pi-hole. 
I was wondering why I had no gateway.. I could recall fixing that a while ago!
No one can hide from git blame ;)

**Comment by dschaper** [comment]
@bcambl Can you update the branch with the newest development code? I'll approve once that is merged in...

**Comment by PromoFaux** [comment]
Oh! Sorry @bcambl I forgot about this soon after I commented on it :(

**Comment by bcambl** [comment]
@dschaper merged.

**Comment by dschaper** [comment]
:+1:

**Comment by PromoFaux** [comment]
:shipit:

**Comment by jacobsalmela** [comment]
Approved

**Comment by PromoFaux** [comment]
Hmmm, PullApprove is saying it's out of date still

**Pull request merged**
