### PR TITLE
Fix pipe to pihole tricorder

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**

Fix pipe to `pihole tricorder`

**How does this PR accomplish the above?:**

Change the upload mechanism to using `curl` as done in https://github.com/pi-hole/pi-hole/pull/4263 for the debug script.

**What documentation changes (if any) are needed to support this PR?:**

None

### CODE REVIEW

**Comment by dschaper** [comment]
I think we should still have the warnings/failure output there just in case.

**Comment by DL6ER** [comment]
I added a test similar to what we have in the debug script.

Instead of `--silent`, I added `--no-progress-bar` to get error output if something fails, e.g. when there is an issue with the connection:
Screenshot from 2021-08-30 20-21-54
or when the DNS server is down:
Screenshot from 2021-08-30 20-23-42

With `--silent` we'd always only see the last line, without knowing the reason for the failure:
Screenshot from 2021-08-30 20-21-54

**Comment by DL6ER** [comment]
And, finally, an example for a successful upload:
Screenshot from 2021-08-30 20-26-51

**Comment by dschaper** [comment]
Are those changes something to port to the debugger script?

**Review by dschaper — APPROVED** [review]

**Pull request merged**
