### PR TITLE
Adding docker+arm detection & FTL download

### PR DESCRIPTION
**Pull request by diginc**
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
Installs the new FTL binary flavor [armel-native](https://github.com/pi-hole/FTL/pull/657).

**How does this PR accomplish the above?:**
I confirmed a build of docker-pi-hole's docker falls into the 'Detected ARM architecture' block to know where to modify. Then if they have a /.dockerenv file then we know they're docker and not a bare metal raspberry pi.\

**What documentation changes (if any) are needed to support this PR?:**
Not useful, the docker-pi-hole build will consume this new installer logic.

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by PromoFaux** [comment]
I'm good with this, but as they touch a similar area of code, can we either:
 - wait until #3003 is merged in
 - cherry pick this commit into #3003 
 - rebase this branch on `fix/tbd`

**Comment by dschaper** [comment]
#3003 should be in today to tomorrow at the latest.

**Comment by PromoFaux** [comment]
Pretty sure the merge conflict resolution is just taking from the top and deleting the bottom, but if someone else could give it a check over, I'd appreciate it, too :)

**Comment by PromoFaux** [comment]
image

**Comment by xBelladonna** [comment]
Not to poke my head in where it doesn't belong but I had a look through and it seems like the resolution is to take the top and delete the bottom as well. That's what the actual commit does anyway
image

**Comment by dschaper** [comment]
xBelladonna is correct.

**Comment by PromoFaux** [comment]
Thank y'all

**Pull request merged**
