### PR TITLE
Remove local.list and openVPN traces

### PR DESCRIPTION
**Pull request by yubiuser**
**What does this PR aim to accomplish?:**

Remove `/etc/pihole/local.list`.
As far as I understood, it has been used previously (before local dns records) existed for additional local hosts. One use was to import openVPN hosts. As we don't do such a hand-holding for other VPN services, I think it's time to go.

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by dschaper** [comment]
@jfb-pihole Do you (or Buck) still advise people to use this file?

**Comment by PromoFaux** [comment]
paging @jfb-pihole @Bucking-Horn for comment

**Comment by Bucking-Horn** [comment]
I think I've stopped referring `local.list` after pihole-FTL introduced automatic handling of pi.hole with Pi-hole FTL v5.9 in 2021.

**Comment by yubiuser** [comment]
The corresponding FTL PR has been merged https://github.com/pi-hole/FTL/pull/1752

**Review by DL6ER — APPROVED** [review]

**Pull request merged**
