### PR TITLE
Improve lighttpd configuration on modern Fedora

### PR DESCRIPTION
**Pull request by cryptomilk**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**

lighthttpd doesn't have a single configuration file, but it provides several files which can be modified to enable the required stuff. We should do it to keep the file structure and documentation if someone tries to understand what is configured and wants to change it. Also this can just be turned on for newer Debian versions too.

Instead of overwriting the lighthttpd.conf it willl modify the different files for us and turn on what pi-hole requires. It will just copy vhost and config files which are special for pihole and edit those.

**What documentation changes (if any) are needed to support this PR?:**

There is no need for external.conf anymore. I dunno if this is being modified somewhere else, I didn't find a reference in the source code. However the pihole.conf should be modified instead!

### CODE REVIEW

**Comment by Mcat12** [comment]
I'm a little hesitant to add this change, as we are preparing to remove lighttpd and replace it with the API and new web interface.

If we do add this change, it should be for all distributions.

external.conf is a file that users can put settings in without fear of them getting wiped by a Pi-hole update. If this folder system is used, that file can be removed. That being said, there are some guides out there which would be made out of date with this change, such as the HTTPS guide on Discourse.

**Comment by cryptomilk** [comment]
This commit is the preparation for https://github.com/cryptomilk/pi-hole/tree/development-opensuse

**Comment by Mcat12** [comment]
We are not currently interested in adding support for any more package managers or major distributions, at least until we are finished improving the maintainability of the core code and installation mechanism.

**Comment by cryptomilk** [comment]
Which means I have to maintain a fork instead to keep it working.

**Comment by dschaper** [comment]
I'll be working on the installer, this might not be merged for a while but I'll definitely take it in to consideration while scaffolding things.

**Comment by cryptomilk** [comment]
Any news?

**Comment by cryptomilk** [comment]
Ping!

**Comment by PromoFaux** [comment]
What a difference a year makes, I'm going to ping @bcambl, our resident Fedora/Centos expert here and see if he has any comments...

**Comment by bcambl** [comment]
IMO any changes to how lighttpd is configured for Fedora/CentOS should also be done for the other supported distributions (Debian) to keep everything the same. I do prefer and use `conf.d` drop-in configs as much as I can with other projects to I am onboard with that concept.

I am not sure what the plan is with the replacement of lighttpd as mentioned above, so I will let someone else chime in on whether there is any value in adding additional complexity that would require more effort to troubleshoot.

**Comment by DL6ER** [comment]
I'm sorry for the delay in here. Before another years passes, is this intended to be brought up-to-date and ported to other distros as suggested by @bcambl ?

**Comment by dschaper** [comment]
https://discourse.pi-hole.net/t/centos-8-1-installation-seems-incomplete/38091/6 may be apropos for this as well.

**Comment by DL6ER** [comment]
This has not been dismissed at all and even when lighttpd is going to a rest, so, we're currently still using it and when this PR would be updated as requested, we can still merge it. Feel free to reopen this stale PR if you want to continue on this.

**Pull request closed without merging**
