### PR TITLE
[WIP] Group support on pi-hole cli

### PR DESCRIPTION
**Pull request by fcrespo82**
Hi folks. I love pi-hole and would like to help it with this feature that I think is lacking.

Recently I needed to add a regex based block on a group (I have groups for Adults and Children) but I really wanted to automate this (cronjob style).

Since the json api is more of a consumption rather that managing the pi-hole, I figured I could help and implement the cli changes necessary to achieve this.

Keep in mind this is only a discussion starter, not a complete PR, but with a simple change that would show the intention behind this PR.

Signed-off-by: Fernando Crespo <fernando82@gmail.com>

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [ ] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/contributing/).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*
Will add support to add/remove/list domains from a specific group on pi-hole 5.1

**How does this PR accomplish the above?:**
TODO

**What documentation changes (if any) are needed to support this PR?:**
TODO

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/whitelist-directly-for-groups/36002/4

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pihole-command-to-manage-groups/35877/3

**Comment by fcrespo82** [comment]
Hi folks. I would like to get this change back on track. Should I keep on?

Can someone help me understand how should I setup my dev system to test my changes properly.

I was using the root user to be able to access the gravity.db with write permission, but I was wondering if its ok to set the password of the user pihole to be able to login with it and test it properly.

Since I am here I'd like to ask if the maintainers have any other rules that I should follow.

**Comment by dschaper** [comment]
Checkout the `development` branch and make your changes based on that branch. Open your PRs against the `development` branch. I can't tell what changes you're trying to make since this PR has a bunch of master commits and things that shouldn't be here. 

You've indicated that you've read and understood the developers guide and that explains everything that I've said in the previous paragraph.

**Comment by fcrespo82** [comment]
Sorry about that. I made some mistakes in that branch... I'll try to fix it...

**Comment by fcrespo82** [comment]
I'll just close this one because it was pointing to master. I opened before I read the contribution guide..

**Pull request closed without merging**
