### PR TITLE
Drop Fedora 36 and add Fedora 39 to the test suite

### PR DESCRIPTION
**Pull request by yubiuser**
**What does this PR aim to accomplish?:**

Fedora 36 is EOL since May 2023 and today they shut down the metadata for repository for 'fedora-modular'. Our test suite will therefor always fail.
Fedora 39 was released today.

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by yubiuser** [comment]
Tests will fail until someone with write access adds Fedora 39 to `dev_supporedos.yaml`

**Comment by yubiuser** [comment]
@pi-hole/core-maintainers 

Fedora 36 tests are failing again for various `core` PRs. Any opinions about this PR?

**Comment by PromoFaux** [comment]
Fedora 37 now EOL, too. Do you want to address that in this PR? I'll update the dev TXT record

**Comment by yubiuser** [comment]
I also removed Fedora 37

**Comment by yubiuser** [comment]
Doc PR: https://github.com/pi-hole/docs/pull/989

**Review by PromoFaux — APPROVED** [review]

**Pull request merged**
