### PR TITLE
 Sanitize email address in case of security issues

### PR DESCRIPTION
**Pull request by bash-c**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [√ ] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [√ ] I have made only one major change in my proposed changes.
- [√ ] I have commented my proposed changes within the code.
- [√ ] I have tested my proposed changes, and have included unit tests where possible.
- [√ ] I am willing to help maintain this change if there are issues with it later.
- [√ ] I give this submission freely and claim no ownership.
- [√ ] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [√ ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*
- To sanitize email address before saving it.

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*
- None, I think

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by PromoFaux** [comment]
Thanks for the submission,

confirmed working :)

```
root@raspberrypi:/etc/.pihole# pihole -a email "test@test.com"
  [✓] Setting admin contact to test@test.com
root@raspberrypi:/etc/.pihole# pihole -a email "test at test dot com"
  [✗] Invalid email address
```

**Comment by pvogt09** [comment]
@PromoFaux: It seems like the regex is not sufficient to allow for gTLDs of nearly all kind that are longer than 4 characters, IDN domains and IP adresses, which are also valid.
I took some of the longest domains I found in the list on wikipedia and the umlaut domains from the german wikipedia below, where the regex fails.
[This](https://stackoverflow.com/questions/201323/how-to-validate-an-email-address-using-a-regular-expression) regex proposed on stackoverflow might be better suited, but I don't know ho to escape it right to make it work.

```bash
#!/bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'
# https://de.wikipedia.org/wiki/Internationalisierter_Domainname
# https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains
declare -a StringArray=(
	"test@test.com"
	'test at test dot com'
	"test@example.com"
	"test@com.example"
	"test@test.academy"
	"test@test.northwesternmutual"
	"test@test.vermögensberatung"
	"test@test.xn--vermgensberatung-pwb"
	"test@fußball.com"
	"test@xn--fuball-cta.com"
	"test@☃.com"
	"test@xn--n3h.com"
	"test@foo.âbcdéf.org"
	"test@foo.xn--bcdf-9na9b.org"
	"test@موقع.وزارة-الاتصالات.مصر"
	"test@xn--4gbrim.xn----ymcbaaajlc6dj7bxne2c.xn--wgbh1c"
	"test@deja.vu.com"
	"test@déjà.vu.com"
	"test@dömäin.com"
	"test@xn--dmin-moa0i.com"
	"test@dömäin.com"
	"test@xn--dmin-moa0i.com"
	"test@127.0.0.1"
	"test@localhost"
)
for val in "${StringArray[@]}"; do
	if [[ ! "${val}" =~ ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$ ]]; then
		echo -e "${RED}invalid email: ${val}${NC}"
	else
		echo -e "${GREEN}valid email:   ${val}${NC}"
	fi
done

exit 0
# https://stackoverflow.com/questions/201323/how-to-validate-an-email-address-using-a-regular-expression
# for val in "${StringArray[@]}"; do
# 	if [[ ! "${val}" =~ ^(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])$ ]]; then
# 		echo -e "${RED}invalid email: ${val}${NC}"
# 	else
# 		echo -e "${GREEN}valid email:   ${val}${NC}"
# 	fi
# done

```

**Comment by PromoFaux** [comment]
@pvogt09 - good point - I didn't test thoroughly enough.

Trying to make the regex you suggested work, but also failing on how to properly escape it :)

I've had more joy with this:

```
^[a-z0-9!#\$%&'*+/=?^_\`{|}~-]+(\.[a-z0-9!#$%&'*+/=?^_\`{|}~-]+)*@([a-z0-9]([a-z0-9-]*[a-z0-9])?\.)+[a-z0-9]([a-z0-9-]*[a-z0-9])?\$
```
image

**Comment by PromoFaux** [comment]
Above regex taken from https://stackoverflow.com/a/2138832/4065967

I have found from some research that the issue with validating email addresses with regex is that there is no perfect recipe.

**Comment by pvogt09** [comment]
Maybe it is a good idea to split the text up at the @-sign and do the parsing separately.
Also the IP form should be tested with the `valid_ip` function from `basic-install.sh` and it is also possible to use IPv6 "domain names" (may not be useful, but if it is validated, it can be done correctly from the beginning).
I would change the `+` for the subdomain part to `*` because that allows for hostnames solely and they are valid like in `test@localhost` i suppose.

Probably also the `checkDomain` function should be adapted accordingly and the subdomain maximum length of 63 characters and overall length of 255 characters could be introduced to the email check too, although I do not know if that is still valid and how it works for IDN domains.

The UTF-8 domains somehow do not work at all, but maybe that is not too much of an issue (at least for me), but should probably be kept in mind if someone runs into it. It might have something to do with multibyte characters, but I am not too familiar with that and how bash handles them.

```bash
#!/bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'
# Check an IP address to see if it is a valid one (from basic-install.sh)
valid_ip() {
    # Local, named variables
    local ip=${1}
    local stat=1

    # If the IP matches the format xxx.xxx.xxx.xxx,
    if [[ "${ip}" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        # Save the old Internal Field Separator in a variable
        OIFS=$IFS
        # and set the new one to a dot (period)
        IFS='.'
        # Put the IP into an array
        read -r -a ip <<< "${ip}"
        # Restore the IFS to what it was
        IFS=${OIFS}
        ## Evaluate each octet by checking if it's less than or equal to 255 (the max for each octet)
        [[ "${ip[0]}" -le 255 && "${ip[1]}" -le 255 \
        && "${ip[2]}" -le 255 && "${ip[3]}" -le 255 ]]
        # Save the exit code
        stat=$?
    fi
    # Return the exit code
    return "${stat}"
}

valid_email() {
	local email=${1}
	local stat=1
	local domain
	local name
	local split="^[^@]+@[^@]+\$"
	local regexname="^[a-z0-9!#\$%&'*+/=?^_\`{|}~-]+(\.[a-z0-9!#$%&'*+/=?^_\`{|}~-]+)*\$"
	local regexdomain="^([a-z0-9]([a-z0-9-]*[a-z0-9])?\.)*[a-z0-9]([a-z0-9-]*[a-z0-9])?\$"
	local regexipv4="^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\$"
	# regexipv6='^([0-9a-fA-F]{0,4}:){1,7}[0-9a-fA-F]{0,4}$'
	# https://stackoverflow.com/questions/53497/regular-expression-that-matches-valid-ipv6-addresses
	# allowed as per https://tools.ietf.org/html/rfc5321#section-4.1.3
	local regexipv6="^IPv6:(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))\$"
	local is_word=1
	local is_ipv4=1
	local is_ipv6=1
	if [[ "${email}" =~ ${split} ]]; then
		name="$(cut -d'@' -f1 <<<"${email}")"
		domain="$(cut -d'@' -f2 <<<"${email}")"
		if [[ "${name}" =~ ${regexname} ]]; then
			[[ "${domain}" =~ ${regexdomain} ]]
			is_word=$?
			valid_ip "${domain}"
			is_ipv4=$?
			[[ "${domain}" =~ ${regexipv6} ]]
			is_ipv6=$?
			if [[ is_word -eq 0 && "${domain}" =~ ${regexipv4} ]]; then
				is_word=is_ipv4
			fi
			[[ $is_word -eq 0 || $is_ipv4 -eq 0 || $is_ipv6 -eq 0 ]]
			stat=$?
		fi
	fi
	return "${stat}"
}
# https://de.wikipedia.org/wiki/Internationalisierter_Domainname
# https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains
declare -a StringArray=(
	"test@test.com"
	"test@tesT.com"
	"tesT@test.com"
	"test@example.com"
	"test@com.example"
	"test@test.academy"
	"test@test.northwesternmutual"
	"test@test.vermögensberatung"
	"test@test.xn--vermgensberatung-pwb"
	"test@fußball.com"
	"test@xn--fuball-cta.com"
	"test@☃.com"
	"test@xn--n3h.com"
	"test@foo.âbcdéf.org"
	"test@foo.xn--bcdf-9na9b.org"
	"test@موقع.وزارة-الاتصالات.مصر"
	"test@xn--4gbrim.xn----ymcbaaajlc6dj7bxne2c.xn--wgbh1c"
	"test@deja.vu.com"
	"test@déjà.vu.com"
	"test@dömäin.com"
	"test@xn--dmin-moa0i.com"
	"test@dömäin.com"
	"test@xn--dmin-moa0i.com"
	"test@127.0.0.1"
	"test@localhost"
	"test@IPv6:::1"
	"test@IPv6:2001:0db8:85a3:0000:0000:8a2e:0370:7334"
	"test@IPv6:2001:db8:85a3:0:0:8a2e:370:7334"
	"test@IPv6:2001:db8:85a3::8a2e:370:7334"
	"test@IPv6:0:0:0:0:0:0:0:1"
	"test@IPv6:::"
	"test@IPv6:ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff"
	"invalid"
	"test@localhost@a"
	'test at test dot com'
	"test@-test.com"
	"test@t/est.com"
	"test@355.0.0.1"
	"test@::1"
	"test@IPv6:zzff:ffff:ffff:ffff:ffff:ffff:ffff:ffff"
)

for val in "${StringArray[@]}"; do
	if valid_email "${val}"; then
		echo -e "${GREEN}valid email:   ${val}${NC}"
	else
		echo -e "${RED}invalid email: ${val}${NC}"
	fi
done
```

**Comment by PromoFaux** [comment]
Whew... Appreciate the effort put into that @pvogt09, however I think it is probably overly complex for our needs.

The new regex I suggested in #3255 should cover the majority of cases. The main purpose of this is to stop something that definitely isn't an email (e.g code injection) getting through from the web interface. 

It may just be that if a user wants to set their email address and they happen to be one of the edge-cases, they will need to set it manually in `/etc/pihole/setupVars.conf` 

I'm pretty certain the vast majority of users don't even set the email address, as I think it is only used on the block page, and that is not enabled by default.

**Comment by bash-c** [comment]
> Whew... Appreciate the effort put into that @pvogt09, however I think it is probably overly complex for our needs.
> 
> The new regex I suggested in #3255 should cover the majority of cases. The main purpose of this is to stop something that definitely isn't an email (e.g code injection) getting through from the web interface.
> 
> It may just be that if a user wants to set their email address and they happen to be one of the edge-cases, they will need to set it manually in `/etc/pihole/setupVars.conf`
> 
> I'm pretty certain the vast majority of users don't even set the email address, as I think it is only used on the block page, and that is not enabled by default.

I totally agree with this point :)

**Comment by pvogt09** [comment]
I am totally fine with your regex from #3255 (I was using it above anyway :)) exept for a change in the domain part from `+` to `*`:
```diff
- regex="...@([a-z0-9]([a-z0-9-]*[a-z0-9])?\.)+[a-z0-9]([a-z0-9-]*[a-z0-9])?\$"
+ regex="...@([a-z0-9]([a-z0-9-]*[a-z0-9])?\.)*[a-z0-9]([a-z0-9-]*[a-z0-9])?\$"
```
But moving the test to a separate function would be better because it can be unit tested this way (I can set up a pull request with the test cases above if requested).

**Pull request merged**
