### PR TITLE
Do not setcap FTL binary when systemd is used

### PR DESCRIPTION
**Pull request by MichaIng**
## Thank you for your contribution to the Pi-hole Community!

Please read the comments below to help us consider your Pull Request.

We are all volunteers and completing the process outlined will help us review your commits quicker.

**Please make sure you**

 1. Base your code and PRs against the repositories developmental branch.
 2. [Sign Off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits as we enforce the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
 3. [Sign](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all your commits as they must have verified signatures
 4. File a pull request for any change that requires changes to [our documentation](https://docs.pi-hole.net/) at our [documentation repo](https://github.com/pi-hole/docs) 

---

**What does this PR aim to accomplish?:**

Currently, if e.g. due to limited filesystem features, `setcap` fails to apply capabilities to FTL binary, the systemd unit is edited to start FTL as root user. This however is not required, since the systemd unit uses the `AmbientCapabilities=` setting to grant the required capabilities. If systemd is used, `setcap` could still be used for convenience, to allow users starting FTL as `pihole` (and theoretically other users) from console, e.g. for testing or debugging purpose. But it is not required for the systemd service to successfully start. For best security, this PR aims to skip it completely if systemd is used.

**How does this PR accomplish the above?:**

`setcap` is not applied if systemd is the init system and the systemd unit starts FTL as `pihole` user in every case.

**Link documentation PRs if any are needed to support this PR:**

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by PromoFaux** [comment]
Anything useful here? 

https://github.com/pi-hole/docker-pi-hole/blob/a787e29aad4604a42eee6f553fd6df6f08461b1e/src/s6/debian-root/usr/local/bin/bash_functions.sh#L33-L72

**Comment by MichaIng** [comment]
Not sure if `setcap` anyway applies all capabilities it can, still failing if it fails for one? Result would then be the same, compared to looping through all of them and applying those which are supported.

Also, we do not want to disable any Pi-hole feature which would work when started via systemd, only because they do not work when users can `sudo -u pihole pihole-FTL` from console. Same for the init.d service (which would then need to be adjusted for consistency), which currently also enables all features by running as root. So I see no reason for doing such checks, which are of course reasonable for the Pi-hole container.

**Comment by DL6ER** [comment]
@MichaIng Maybe you could join us on the Pi-hole chat server for discussing this more easily than over here. If we have the chance, I'd not only remove the dropping of the `root` user hack but remove the entirety of adding capabilities to the binary file. `systemd` is doing this at runtime and won't be affected by the file system, etc. We'd potentially be breaking systems from earlier than 2014 but that's absolutely fine since FTL is demanding a much more recent `glibc` already now making Pi-hole unusable  on way outdated systems anyway.

**Comment by MichaIng** [comment]
Edited the PR accordingly for best security practise. If there are really users stumbling over failing FTL starts from console because of missing caps, it can be reopened for discussion.

**Review by yubiuser — APPROVED** [review]

**Pull request merged**
