### PR TITLE
Fix errors on fresh installations while setting privacy levels and query logging due to absence of pihole.toml

### PR DESCRIPTION
**Pull request by yubiuser**
**What does this PR aim to accomplish?:**

Should fix an issue reported here: https://github.com/pi-hole/pi-hole/pull/5790#issuecomment-2422429230

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Review by DL6ER — APPROVED** [review]

**Comment by MichaIng** [comment]
@yubiuser
Just in case you plan to roll out v6 via `pihole checkout` or `pihole -up`. As this function does not exist in the v5 `utils.sh` yet, which is however loaded by the installer, if fails. Re-running the update/checkout then works, as the script then has been updated already. Chicken&Egg, probably easiest and safest is to reload `utils.sh` right after scripts have been updated? Or might it cause issues if an older local installer is incompatible with the newer `utils.sh`?

**Comment by yubiuser** [comment]
The `utils.sh` should be updated in`installScipts`

https://github.com/pi-hole/pi-hole/blob/76a6b420752520d5c5c158e25bc74f609a59cb7c/automated%20install/basic-install.sh#L1148

which is executed right before sourcing `utils.sh` in `installPihole`

https://github.com/pi-hole/pi-hole/blob/76a6b420752520d5c5c158e25bc74f609a59cb7c/automated%20install/basic-install.sh#L1604-L1611

Setting privacy level and query logging happens afterwards.

https://github.com/pi-hole/pi-hole/blob/76a6b420752520d5c5c158e25bc74f609a59cb7c/automated%20install/basic-install.sh#L2398-L2403

So this should be safe to use I think

**Comment by MichaIng** [comment]
Hmm, indeed seems so. I tried again:
```console
root@VM-Bookworm:~# curl -sSL https://install.pi-hole.net | bash
...
root@VM-Bookworm:~# pihole checkout dev
  Please note that changing branches severely alters your Pi-hole subsystems
  Features that work on the master branch, may not on a development branch
  This feature is NOT supported unless a Pi-hole developer explicitly asks!
  Have you read and understood this? [y/N] y

  [i] Shortcut "dev" detected - checking out development / devel branches...

  [i] Pi-hole Core
  [✓] Switching to branch: 'development' from 'refs/heads/master'
  [i] Already up to date.

  [i] Web interface
  [✓] Switching to branch: 'devel' from 'refs/heads/master'
  [i] Already up to date.
  [i] Running installer to upgrade your installation

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [i] SELinux not detected
  [✓] Update local cache of available packages

  [✓] Checking apt-get for upgraded packages... up to date!

  [i] Checking for / installing required dependencies for OS Check...
  [✓] Checking for grep
  [✓] Checking for dnsutils
  [i] Checking for binutils (will be installed)
  [i] Waiting for package manager to finish (up to 30 seconds)
  [i] Processing apt-get install(s) for: binutils, please wait...
----------------------------------------------------------------------
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package binutils-common:amd64.
(Reading database ... 19695 files and directories currently installed.)
Preparing to unpack .../0-binutils-common_2.40-2_amd64.deb ...
Unpacking binutils-common:amd64 (2.40-2) ...
Selecting previously unselected package libbinutils:amd64.
Preparing to unpack .../1-libbinutils_2.40-2_amd64.deb ...
Unpacking libbinutils:amd64 (2.40-2) ...
Selecting previously unselected package libctf-nobfd0:amd64.
Preparing to unpack .../2-libctf-nobfd0_2.40-2_amd64.deb ...
Unpacking libctf-nobfd0:amd64 (2.40-2) ...
Selecting previously unselected package libctf0:amd64.
Preparing to unpack .../3-libctf0_2.40-2_amd64.deb ...
Unpacking libctf0:amd64 (2.40-2) ...
Selecting previously unselected package libgprofng0:amd64.
Preparing to unpack .../4-libgprofng0_2.40-2_amd64.deb ...
Unpacking libgprofng0:amd64 (2.40-2) ...
Selecting previously unselected package libjansson4:amd64.
Preparing to unpack .../5-libjansson4_2.14-2_amd64.deb ...
Unpacking libjansson4:amd64 (2.14-2) ...
Selecting previously unselected package binutils-x86-64-linux-gnu.
Preparing to unpack .../6-binutils-x86-64-linux-gnu_2.40-2_amd64.deb ...
Unpacking binutils-x86-64-linux-gnu (2.40-2) ...
Selecting previously unselected package binutils.
Preparing to unpack .../7-binutils_2.40-2_amd64.deb ...
Unpacking binutils (2.40-2) ...
Setting up binutils-common:amd64 (2.40-2) ...
Setting up libctf-nobfd0:amd64 (2.40-2) ...
Setting up libjansson4:amd64 (2.14-2) ...
Setting up libbinutils:amd64 (2.40-2) ...
Setting up libctf0:amd64 (2.40-2) ...
Setting up libgprofng0:amd64 (2.40-2) ...
Setting up binutils-x86-64-linux-gnu (2.40-2) ...
Setting up binutils (2.40-2) ...
Processing triggers for libc-bin (2.36-9+deb12u9) ...
----------------------------------------------------------------------
  [✓] Supported OS detected
  [i] Checking for / installing required dependencies for this install script...
  [✓] Checking for git
  [✓] Checking for dialog
  [✓] Checking for ca-certificates
  [✓] Checking for iproute2

  [i] IPv4 address: 192.168.1.24/24
  [i] Found IPv6 GUA address
  [i] IPv6 address: 2003:e0:6f3e:501c:a00:27ff:fead:284e
  [i] Using upstream DNS: Google (ECS, DNSSEC) (8.8.8.8, 8.8.4.4)
  [i] Installing StevenBlack's Unified Hosts List
  [i] Query Logging on.
  [i] Using privacy level: 0
  [✓] Check for existing repository in /etc/.pihole
  [✓] Update repo in /etc/.pihole

  [✓] Check for existing repository in /var/www/html/admin
  [✓] Update repo in /var/www/html/admin

  [i] Checking for / installing required dependencies for Pi-hole software...
  [✓] Checking for curl
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for jq
  [✓] Checking for cron
  [✓] Checking for iputils-ping
  [✓] Checking for libcap2-bin
  [✓] Checking for dns-root-data
  [✓] Checking for libcap2
  [✓] Checking for netcat-openbsd
  [✓] Checking for procps
  [i] Checking for lshw (will be installed)
  [✓] Checking for bash-completion
  [i] Waiting for package manager to finish (up to 30 seconds)
  [i] Processing apt-get install(s) for: lshw, please wait...
----------------------------------------------------------------------
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package lshw.
(Reading database ... 20091 files and directories currently installed.)
Preparing to unpack .../lshw_02.19.git.2021.06.19.996aaad9c7-2+b1_amd64.deb ...
Unpacking lshw (02.19.git.2021.06.19.996aaad9c7-2+b1) ...
Setting up lshw (02.19.git.2021.06.19.996aaad9c7-2+b1) ...
----------------------------------------------------------------------
  [✓] Checking for user 'pihole'

  [i] FTL Checks...

  [✓] Detected x86_64 architecture
  [i] FTL binary already installed, verifying integrity...
  [✗] Remote binary is different, downloading...
  [✓] Downloading and Installing FTL
  [✓] Installing scripts from /etc/.pihole

  [i] Installing configs from /etc/.pihole...

  [✓] Installing latest Cron script

  [i] Installing latest logrotate script...
        [i] webserver.log added to logrotate file.
  [✓] Installing latest logrotate script
  [i] man not installed
  [i] Testing if systemd-resolved is enabled
  [i] Systemd-resolved is not enabled
  [i] Upgrading gravity database from version 15 to 16
  [i] Upgrading gravity database from version 16 to 17
  [i] Upgrading gravity database from version 17 to 18
  [i] Upgrading gravity database from version 18 to 19
  [i] Restarting services...
  [✓] Enabling pihole-FTL service to start on reboot...
  [✓] Restarting pihole-FTL service...
/etc/.pihole/automated install/basic-install.sh: line 2399: setFTLConfigValue: command not found
   Error: Unable to complete update, please contact support
```
But I also have no explanation for this, as the new `utils.sh` should have been installed and sourced before 🤔. I'll try to redo with `bash -x` when I find time.

**Comment by PromoFaux** [comment]
It's not something silly like `source`ing the file inside `installPihole` is only valid as long as we're inside that function, is it? Maybe it should be sourced in `main()`?

**Comment by PromoFaux** [comment]
Looks like it - came up against the same thing when testing #5785, moving the code per the following commit sorts it:

https://github.com/pi-hole/pi-hole/commit/8f1fce8f4bcc795bf721da21b242cdd6b7eab364#diff-595630a29a855f6d667a84ca0662042e826bf3ec56322ef61d4a6ef149147d23R1688

**Comment by MichaIng** [comment]
Hmm, seems so in this case, but it is actually not normal in `bash`:
```console
root@micha:~# cat test_source
test_var=success
test_func(){ echo success; }
root@micha:~# cat test_script
#!/bin/bash
func()
{
        source test_source
        echo "test_var: $test_var"
        echo "test_func(): $(test_func)"
}
func
echo "test_var: $test_var"
echo "test_func(): $(test_func)"
root@micha:~# bash test_script
test_var: success
test_var: success
```
So here, the variable and function remained set outside the function. Maybe because the output is piped, hence the function is not the main/controlling command, but `tee` is. ... yep, that is it:
```console
root@micha:~# cat test_script
#!/bin/bash
func()
{
        source test_source
        echo "test_var: $test_var"
        echo "test_func(): $(test_func)"
}
func | tee
echo "test_var: $test_var"
echo "test_func(): $(test_func)"
root@micha:~# bash test_script
test_var: success
test_func(): success
test_var:
test_script: line 10: test_func: command not found
test_func():
```
Same is true when declaring variables or functions directly within `func()` without sourcing. So when piping the output of any bash function, anything declared within this function is not available outside of it.

Now I remember a very similar issue, not about declared variables or functions, but also related to the fact that only the end of a pipe is the control command. We solved it with a weird redirect like this:
```sh
Run_DietPi_Update &> >(tee "$FP_LOG"); wait $!
```

**Comment by PromoFaux** [comment]
AFAICT, the functions from utils.sh are only used in the one place anyway, nowhere inside `installPihole` - so it's probably safe just to have it sourced outside

**Pull request merged**
