### PR TITLE
Update pihole-FTL.service

### PR DESCRIPTION
**Pull request by liberodark**
Better to use command -v

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by DL6ER** [comment]
@liberodark 

> Better to use command -v

Why?

**Comment by dschaper** [comment]
https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md#technical-requirements

Please follow that exactly.

**Comment by foreign-sub** [comment]
I guess he's referring to :

https://stackoverflow.com/a/37056347

Addressing a corner case where "which" would not be available as an external dependency

**Comment by liberodark** [comment]
Yes is better to use `command -v` and not `which`
That respect more the unix or posix compliance.
`which` is not installed all the time and is not a necessary app for a server.

Best Regards

**Comment by dschaper** [comment]
Thanks, please rebase the change on the `development` branch as per the guides and we can merge it.

**Comment by liberodark** [comment]
OK

**Pull request closed without merging**
