### PR TITLE
FTL integration

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 10

---

Clone, compile, and install `FTL`.

A log file is created:
```
pi@eden: ~# less /etc/pihole/FTL_build.log 
rm -f obj/*.o pihole-FTL
Making FTL version on branch master - 75a3085 (2017-02-06 12:36:02 +0100)
gcc -c -o obj/main.o main.c -I. -Wall -g
gcc -c -o obj/structs.o structs.c -I. -Wall -g
gcc -c -o obj/log.o log.c -I. -Wall -g
gcc -c -o obj/daemon.o daemon.c -I. -Wall -g
gcc -c -o obj/parser.o parser.c -I. -Wall -g
gcc -c -o obj/signals.o signals.c -I. -Wall -g
gcc -c -o obj/socket.o socket.c -I. -Wall -g
gcc -c -o obj/request.o request.c -I. -Wall -g
gcc -c -o obj/grep.o grep.c -I. -Wall -g
gcc -c -o obj/setupVars.o setupVars.c -I. -Wall -g
gcc -o pihole-FTL obj/main.o obj/structs.o obj/log.o obj/daemon.o obj/parser.o obj/signals.o obj/socket.o obj/request.o obj/grep.o obj/setupVars.o -I. -Wall -g 
install -m 0755 pihole-FTL /usr/local/bin
touch /var/log/pihole-FTL.log /var/run/pihole-FTL.pid /var/run/pihole-FTL.port
chmod 0666 /var/log/pihole-FTL.log /var/run/pihole-FTL.pid /var/run/pihole-FTL.port
```

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by PromoFaux** [comment]
Do we need to add a new dependency?

**Comment by DL6ER** [comment]
Excellent question. Everything should be there, but let me test that assumption on a droplet.

Including `build-essentials` cannot harm, but I don't know if a similar package exists for Fedora.

**Comment by DL6ER** [comment]
@PromoFaux Yes!

---

Installer:
```
::: Compiling FTL... grep: /etc/pihole/setupVars.conf: No such file or directory
```

FTL buildlog
```
cat /etc/pihole/FTL_build.log
./automated install/basic-install.sh: line 973: make: command not found
```

---

```
sudo apt-get install build-essential
```

---

Installer
```
::: Compiling FTL... done
::: Installing FTL... done
```

FTL buildlog
```
rm -f obj/*.o pihole-FTL
Making FTL version on branch master - b01d6b6 (2017-02-06 13:19:17 +0100)
gcc -c -o obj/main.o main.c -I. -Wall -g
gcc -c -o obj/structs.o structs.c -I. -Wall -g
gcc -c -o obj/log.o log.c -I. -Wall -g
gcc -c -o obj/daemon.o daemon.c -I. -Wall -g
gcc -c -o obj/parser.o parser.c -I. -Wall -g
gcc -c -o obj/signals.o signals.c -I. -Wall -g
gcc -c -o obj/socket.o socket.c -I. -Wall -g
gcc -c -o obj/request.o request.c -I. -Wall -g
gcc -c -o obj/grep.o grep.c -I. -Wall -g
gcc -c -o obj/setupVars.o setupVars.c -I. -Wall -g
gcc -c -o obj/args.o args.c -I. -Wall -g
gcc -o pihole-FTL obj/main.o obj/structs.o obj/log.o obj/daemon.o obj/parser.o obj/signals.o obj/socket.o obj/request.o obj/grep.o obj/setupVars.o obj/args.o -I. -Wall -g 
install -m 0755 pihole-FTL /usr/local/bin
touch /var/log/pihole-FTL.log /var/run/pihole-FTL.pid /var/run/pihole-FTL.port
chmod 0666 /var/log/pihole-FTL.log /var/run/pihole-FTL.pid /var/run/pihole-FTL.port
```

**Comment by diginc** [comment]
What are the technical advantages of building this client side vs continuous integration building and uploading it to github releases for download?

> build-essential

Ouch, right in my docker image size!  Here is what build-essentials or g++/make will do to my image size:

* diginc/pi-hole:alpine is 147MB uncompressed (after downloaded from hub)
  * installing g++ and make says it adds : `158 MiB in 27 packages`
  * 107% increase :anguished: 
* diginc/pi-hole:debian is 320MB
  * installing build essential says: `After this operation, 182 MB of additional disk space will be used.`
  * 56% increase :-1:
* average compression of my images by docker hub (soon to be moved to docker store) is around 40%, I don't want to upload there just to find the actual numbers of what the download will be.  The point is my download and uncompress times will increase by a not insignificant number.
* non docker raspberry pis will also have to download and install these requirements, increase the install time and OS footprint there too.

How big is the binary after compilation?  I'm guessing < 1MB.  please please please take the more efficient path here.  Build it once, distribute the built binaries instead.  

If build-essential takes 2 minutes to download + install for the average pi-hole client and a downloading the binary takes 2 seconds, think of that difference multiplied by the number of installs that'll happen...that's a lot of time.

**Comment by DL6ER** [comment]
No, you entirely misunderstood my point here. The reason why we don't want to simply grab a binary is that it does not work - not my unwillingness to do this - I invested over one week investigating how to do this best, because not having to compile on some unknown machine appears best.
We tried the recommended way for building a kernel for Raspberry Pi on an arbitrary Linux machine and that worked for a small test program. I was able to compile the binary using Travis CI and successfully download and run it on the Raspberry Pi.

Then, I enabled the very same procedure for `FTL`. The binaries have been created and uploaded successfully. However, the binary did not work on a Raspberry Pi 1 and Pi Zero, while they worked fine for a Raspberry Pi 3 (note that the cross compiled simple test program ran on all three devices). It entirely failed for my OrangePi Zero and NanoPi NEO. I complied `FTL` locally and the file size of the generated binary differs considerably. Who knows how many different variants are there for which I'd have to generate a customized binary.

The problem extends (I already said that I invested over one week): On the systems where the binary fails, it simply get's killed by `SIGSERV`. `gdb` does not help, since the binary is compiled with a too new version of the crosscompilers. I have found no way to either install the corresponding older version of the crosscompiler on Travis CI, nor to install a much more recent `gdb` on my Raspbian devices. I always end up with dozens of unfulfillable package dependencies, which will likely break the whole system. Hence, I had no possibility to track down *where* the binary fails exactly:
```
(gdb) run
Starting program: /home/pi/pi-hole-daemon/pihole-FTL-arm-linux-gnueabihf 

Program received signal SIGSEGV, Segmentation fault.
0x00058026 in ?? ()
(gdb) where
#0  0x00058026 in ?? ()
#1  0x00008e72 in _start ()
```

Before you say `valgrind`, let me tell you that it is of no help, either. There seems to be a rather severe bug with ARM which is only solved in a very recent version, which I - again - cannot install without tearing the whole system apart (like also including bleeding-edge versions of `libc`). I wouldn't even know if my system would behave the same after doing so many and such drastic changes.

**Comment by DL6ER** [comment]
Interestingly enough, none of the problems mentioned in my previous post, exist when I clone and compile the code directly on the target device. I agree that `build-essential` might not be the way to go, but I came from the point of presenting something that works. It is very likely that we don't need most of the stuff that `build-essential` installs, but I have the feeling that we cannot circumvent the need for locally compiling the source code - we will at least need `gcc`, `make` and a set of `...-dev` packages.

Further details would have to be worked out.

**Comment by DL6ER** [comment]
This code has become entirely obsolete as are now able to provide binaries for all systems we can test.

**Pull request closed without merging**
