### PR TITLE
Gentoo support

### PR DESCRIPTION
**Pull request by Graf-Euler**
**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#git-commit---signoff))

---

**What does this PR aim to accomplish?:**

Add support for Gentoo OS to Pi-hole, see [this feature request](https://discourse.pi-hole.net/t/add-gentoo-as-a-supported-os/2011).

**How does this PR accomplish the above?:**

Originally described [here](https://discourse.pi-hole.net/t/add-gentoo-as-a-supported-os/2011/7?u=graf_euler).
> 1. Added a gentoo section to the distro_check() function to fill the global variables accordingly.
> 2. As gentoo uses OpenRC init system as default, I added checks if the ‘service’-command is available before it is used (this also affects the pihole executable).
> 3. Added a lighttpd.conf.gentoo
> 4. For gentoo, the install-script does not install the dependencies! The script outputs the missing packages and requests the user to install them. This allows the user to review the use flags of the packages and review the comments of portage, since some packages require some further actions after installing them.

**What documentation changes (if any) are needed to support this PR?:**

Add Gentoo to supported OS

### CODE REVIEW

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/add-gentoo-as-a-supported-os/2011/10

**Comment by Mcat12** [comment]
We do not have an interest in supporting Gentoo at the moment, especially since it adds a lot more testing for little benefit (I have heard of less than 2 Gentoo users who want Pi-hole).

**Comment by mustang011** [comment]
Hello, I need to install pi-hole on gentoo.
Will anyone update patches with gentoo support to the latest pihole version available? RPI 4 1024MB RAM freezes, ddns stops working, and that’s not acceptable. I don’t want to install the pihole virtual machine from ubuntu. Please help.

**Comment by GieltjE** [comment]
If anyone is willing to help create and maintain a Gentoo port I'd be willing to help, just give me a message.

**Comment by JoeAndrew** [comment]
> If anyone is willing to help create and maintain a Gentoo port I'd be willing to help, just give me a message.

I will be happy to help, though I have little time

**Comment by GieltjE** [comment]
> I will be happy to help, though I have little time

Can we get in touch via dm somewhere?

**Pull request closed without merging**
