### PR TITLE
Standardize function declaration

### PR DESCRIPTION
**Pull request by airencracken**
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**By submitting this pull request, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

- [x] 1 (very unfamiliar)

---

There were no fewer than three styles of function declaration going
on in these files, so I attempted to standardize them to the typical

myfucn() {
}

style.

### CODE REVIEW

**Comment by dschaper** [comment]
Built by committee... Thanks for the PR, looks good.

**Comment by dschaper** [comment]
:+1:

**Comment by airencracken** [comment]
Whoops. Didn't mean to stack those commits.

**Comment by dschaper** [comment]
Yeah, try for two PR's just so we can cherry pick or revert in the unlikely case that we need to adjust things. (And any commits made after pullapprove resets the vote counter :) )

**Comment by PromoFaux** [comment]
I'm happy to keep these two commits lumped into the same PR if you are?

**Comment by dschaper** [comment]
It's good, as long as the commits are separate then we can work magic if need be.

**Comment by dschaper** [comment]
:+1:

**Comment by PromoFaux** [comment]
Approved

**Pull request merged**
