### PR TITLE
Update 01-pihole.conf

### PR DESCRIPTION
**Pull request by Potterli20**
add all-servers proxy-dnssec

## Thank you for your contribution to the Pi-hole Community!

Please read the comments below to help us consider your Pull Request.

We are all volunteers and completing the process outlined will help us review your commits quicker.

**Please make sure you**

 1. Base your code and PRs against the repositories developmental branch.
 2. [Sign Off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits as we enforce the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
 3. [Sign](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all your commits as they must have verified signatures
 4. File a pull request for any change that requires changes to [our documentation](https://docs.pi-hole.net/) at our [documentation repo](https://github.com/pi-hole/docs) 

---

**What does this PR aim to accomplish?:**

**How does this PR accomplish the above?:**

**Link documentation PRs if any are needed to support this PR:**

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by yubiuser** [comment]
A few remarks:

1) all PR should be based on and target `development` branch
2) you ignored the PR template completely
3) `all-servers` should not be set by default. Pi-hole determines the "fastest" upstream DNS server repeatedly (https://docs.pi-hole.net/ftldns/dns-resolver/#improve-detection-algorithm-for-determining-the-best-forward-destination) and using `all-servers` unlikely improved speed much but adds network load
4) Why do you need `proxy-dnssec`.
> In most cases, enabling DNSSEC validation within dnsmasq is a better option
https://thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html

___

If you want to make persistent changes, just add a new file to `/etc/dnsmasq.d/` with the desired options set. They will survive an update.

**Comment by dschaper** [comment]
This PR is not up to the standards that you acknowledge you understood when you (partially) filled out the template.

I'm not going to approve this unless there is some explanation on why these flags are necessary and applicable as the default settings for all Pi-hole installations. Word of warning, you'll need to make a convincing argument for why you feel this is so. I won't accept "because it works for me".

The very likely outcome of this is that it will be closed without merge and you can add these flags to `/etc/dnsmasq.d/50-my.conf` instead.

**Comment by rdwebdesign** [comment]
> In /etc/dnsmasq.d/, only the file of pihole is valid, other files are not valid.

What do you mean?

**Comment by dschaper** [comment]
> Even if I create another file called 02-dnsall.conf, it will not work.

Then you have an issue with your configuration or setup. The default Pi-hole configuration includes:

```bash
root@09184bcf19b7:/# cat /etc/dnsmasq.conf
conf-dir=/etc/dnsmasq.d
```
Which makes `/etc/dnsmasq.d` the configuration directory.

> This pr is either closed or merged, but I feel it is an optimization of file configuration.

It's going to be closed and if you are willing and able to answer my previous questions asking why you feel this is an optimization then we can look at it again. I already said that "works for me" is not a valid reason.

**Pull request closed without merging**
