### PR TITLE
Update basic-install.sh checking for 01-pihole.conf existence

### PR DESCRIPTION
**Pull request by quielb**
Signed-off-by: Barry Quiel <barry.quiel@gmail.com>

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
Allow for existing /etc/dnsmasq.d/01-pihole.conf that may come from external source such as docker volume mount or kubernetes ConfigMap.  Should allow for containers without persistent storage but configured externally during startup.

**How does this PR accomplish the above?:**
Check for existence of /etc/dnsmasq.d/01-pihole.conf.  If it doesn't exist then create it.

**What documentation changes (if any) are needed to support this PR?:**
None

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by dschaper** [comment]
`01-pihole.conf` is programmatically generated, I'm not sure this is a solution or potentially more problems when the file isn't what we expect it to bel.

**Comment by quielb** [comment]
> `01-pihole.conf` is programmatically generated, I'm not sure this is a solution or potentially more problems when the file isn't what we expect it to be.

It's not completely programmatically generated.  The base of the file comes from the local repo and there are few values modified based on ENV from docker or kube settings.

As far as not being expected, I really think that becomes an issue for the person who chooses not to use the base file provided.  I do think that because there is so much documentation out there for DNSmasq that having a syntactically correct file shouldn't be hard to create.  But it's kind of a you broke it you bought it situation.  For someone who is taking ownership of the config file, it should be there responsibility to make sure its correct.

**Comment by dschaper** [comment]
It's our responsibility to provide the support. And there will be support requests. 

The file is modified by the web interface, using a file we don't know the state of will break the application when we try to modify the file and it's not in the format we expect.

**Comment by dschaper** [comment]
And a side note: The Travis check won't pass since this is a PR based on the `master` branch code and currently pointed to merge to master. https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md#technical-requirements needs to be followed completely.

**Pull request closed without merging**
