### PR TITLE
Improve debugger database table printing

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**

Make the result of `pihole -d` for `Gravity.db` related stuff easier to read.

**How does this PR accomplish the above?:**

Change the SQL to:

- Improve distinctiveness of the domain type by added indentation, as in
    ```plain
    type
    ----
   0
     1
      2
       3
    ```
- Improve distinctiveness of the enabled flag by added indentation, as in
    ```plain
    enabled
    -------
       0
          1
    ```
- Include group ID in the very same table (comma separated if more than one group is associated to a given domain) to avoid printing the linked table as well.

**Previously**
```plain
*** [ DIAGNOSING ]: Domainlist (0/1 = exact white-/blacklist, 2/3 = regex white-/blacklist)
   id    type  domain                                                                                                enabled  date_added           date_modified        comment
   ----  ----  ----------------------------------------------------------------------------------------------------  -------  -------------------  -------------------  --------------------------------------------------
   59    0     hub.docker.com                                                                                        1        2020-01-29 22:29:30  2020-01-29 22:29:30 
   83    3     (\.|^)fbcdn\.net$                                                                                     1        2020-03-05 21:11:24  2020-03-05 21:11:24 
          
*** [ DIAGNOSING ]: Domainlist groups
   domainlist  group_id                    
   ----------  ----------
   59          0
   83          0
   83          1
   83          2
```

**New**
```plain
*** [ DIAGNOSING ]: Domainlist (0/1 = exact white-/blacklist, 2/3 = regex white-/blacklist)                                         
   id    type  enabled  group_ids     domain                                                                                                date_added           date_modified        comment
   ----  ----  -------  ------------  ----------------------------------------------------------------------------------------------------  -------------------  -------------------  --------------------------------------------------
   59    0           1  0             hub.docker.com                                                                                        2020-01-29 22:29:30  2020-01-29 22:29:30
   83       3        1  0,1,2         (\.|^)fbcdn\.net$                                                                                     2020-03-05 21:11:24  2020-03-05 21:11:24
```

**What documentation changes (if any) are needed to support this PR?:**

None

### CODE REVIEW

**Comment by dschaper** [comment]
I like the rearrangement of the columns. Is it possible to change the `0 1 2 3` to `EW` `EB` `RW` `RB` or something like that?

**Comment by dschaper** [comment]
And show enabled/disabled with a char like `*` for enabled and blank for disabled?

**Comment by DL6ER** [comment]
Pinging @jfb for his professional debugging opinion.

**Comment by jfb-pihole** [comment]
I would prefer as you have it for the 5.0 release, for a few reasons:

1.  The single digit code for the domainlist type is easier for me to scan quickly.  The numbers flow left to right.  The two digit letters don't scan as quickly.
2.  Same for the enabled/disabled indicator, although I can go either way with this.  When I scan a debug log, I look for changes, not specifically the value in the cell.  To my eye, it's a bit quicker to see the change in position between the 0 and the 1 than to see the absence or presence of the X.

My recommendation, leave as is for the 5.0 and we can revisit after we get some run time, and change as desired for 5.1 release.

**Pull request merged**
