### PR TITLE
Fix typo found by #3933

### LINKED ISSUE #3933: Typo in gravity sql
https://github.com/pi-hole/pi-hole/blob/0d8ece1be249fdc5993f01a45f8d0464257df819/advanced/Templates/gravity.db.sql#L76

### PR DESCRIPTION
**Pull request by mwoolweaver**
Signed-off-by: Michael Woolweaver <m.woolweaver@icloud.com>

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*

Fixes #3933
---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by dschaper** [comment]
Please follow the guide and use the `development` branch for all changes.

**Review by PromoFaux — APPROVED** [review]
I think this is OK to merge, but not sure if we now need to up the db schema version. paging @DL6ER for a secondary approval, as he will know the answer to that question for sure.

**Review by DL6ER — COMMENTED** [review]
Interesting that it worked at all and went unnoticed. Shouldn't require any further changes. However, I will not approve right now as I first want to test this locally (which I cannot at the moment).

**Comment by PromoFaux** [comment]
Yeah, it surprised me too. 

Looking closely at my gravity database it looks like so:

image

It appears that `sqlite3` has just gone "Oh, OK, we will just assume that the data type you wanted was `TEXT NOL`, even though we know that doesn't exist"

After some tinkering about, it appears you can put any old rubbish in as a data type and it will accept it, like so:

image


I think we should probably do a migration script, too to fix existing databases? Or does gravity not need that?

```sql
ALTER TABLE client RENAME TO tmpClient;

CREATE TABLE "client" (
	"id"	INTEGER,
	"ip"	TEXT NOT NULL UNIQUE,
	"date_added"	INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS int)),
	"date_modified"	INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS int)),
	"comment"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);

INSERT INTO client (id,ip,date_added,date_modified,"comment")
SELECT id,ip,date_added,date_modified,comment
FROM tmpClient
WHERE ip is NOT NULL; --in  case there is any bad data in the old table - ip will no longer be nullable

DROP TABLE tmpClient;
```

**Comment by PromoFaux** [comment]
I think the only thing affected by the typo is that we're missing the `NOT NULL` constraint. It hasn't fallen over because `sqlite3` uses a dynamic type system

More here for reading:
https://stackoverflow.com/a/8417411

**Comment by DL6ER** [comment]
I was aware of dynamic typing, the thing I was surprised about was that
```
"ip"	TEXT NOR NULL UNIQUE
```
was interpreted as (emphasis by spaces):
```
"ip"      TEXT NOL        NULL       UNIQUE
```

Where did the `NULL` go?

**Comment by PromoFaux** [comment]
Perhaps it's interpreted as "allow nulls"? 🤷‍♂️

**Comment by DL6ER** [comment]
If so, then this is a bug / unintended side-effect in SQLite3. Looking at the schema, the `NULL` should have been part of the typedef, or what would you say?

The only other valid occurrence of `NULL`  is when being headed by `DEFAULT` or `NOT`
Screenshot_2020-12-20 CREATE TABLE

I logged into a remote Pi-hole via SSH and did the same checks you did also there. No sign of a `NULL` anywhere, so it'll likely just be completely ignored:
```
sqlite> .header on
sqlite> .mode column

sqlite> pragma table_info('client');
cid         name        type        notnull     dflt_value  pk        
----------  ----------  ----------  ----------  ----------  ----------
0           id          INTEGER     0                       1         
1           ip          TEXT NOL    0                       0         

```

**Review by DL6ER — APPROVED** [review]

**Comment by DL6ER** [comment]
> I think we should probably do a migration script, too to fix existing databases? Or does gravity not need that?

The entire gravity database is regenerated on every `pihole -g` run. New databases will be created with the correct schema. Violating records (`ip == NULL`) should be skipped. They are meaningless, so that should be fine.

**Comment by PromoFaux** [comment]
Good enough for me.

**Comment by PromoFaux** [comment]
Have just pulled `development` locally and after a `pihole -g` it is fine:

```
CREATE TABLE client
(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        ip TEXT NOT NULL UNIQUE,
        date_added INTEGER NOT NULL DEFAULT (cast(strftime('%s', 'now') as int)),
        date_modified INTEGER NOT NULL DEFAULT (cast(strftime('%s', 'now') as int)),
        comment TEXT
);
```

(although it should be noted that my `client` table is empty there

**Pull request merged**
