### PR TITLE
Some verbiage change to outputs (plus a couple of comments)

### PR DESCRIPTION
**Pull request by PromoFaux**
### **What does this PR aim to accomplish?:**

Replaces some printed usages of white/blacklist with allow/deny as per other areas of the software.

Actually, thinking about it, we can probably pull out the legacy pre v5 file pointers/helpers now?

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
- [x] I have read the above and my PR is ready for review. _Check this box to confirm_

### CODE REVIEW

**Comment by PromoFaux** [comment]
🤔 

I didn't even touch these files. But can also fix later in this PR.


image

**Comment by PromoFaux** [comment]
The final commit is optional - but I think we can probably do away with this at this stage

**Comment by PromoFaux** [comment]
Reverted the final pre-v5.0 migration commit for now. Probably needs addressing as part of a larger patch later

**Review by DL6ER — APPROVED** [review]

**Comment by yubiuser** [comment]
> Reverted the final pre-v5.0 migration commit for now. Probably needs addressing as part of a larger patch later

If we remove those migration steps, users still on v4 won't be able to upgrade to v6 (as they have no chance to get to v5 first once v6 is is 'master' everywhere). I'm not sure how many users will be affected, the number might be rather small.

**Pull request merged**
