### PR TITLE
quick fix for when dig also returns a CNAME

### PR DESCRIPTION
**Pull request by ryrun**
Signed-off-by: Andreas <ryrun@online.de>

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [ ] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [ ] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
Fix for #2863

**How does this PR accomplish the above?:**
It filters the output of the dig command, so only the last line will be set to the variable. Which will be the ip, when also a CNAME is returned.

**What documentation changes (if any) are needed to support this PR?:**
None

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by dschaper** [comment]
Thanks! DCO failed because of a name/email check but you've provided enough so that I can manually set it to pass. (Commit sha: 63230cb, Author: Andreas, Committer: GitHub; Expected "Andreas ryrun@online.de", but got "ryrun ryrun@online.de".)

**Comment by dschaper** [comment]
Have you checked to see if this fix still works when the `dig` returns a non-CNAME response?

**Comment by ryrun** [comment]
Tricky part the DCO stuff xD Yep its working for me:

```
pi@raspberrypi:~ $ dig @8.8.8.8 -p 53 +short s3.amazonaws.com
s3-1.amazonaws.com.
52.216.134.69
pi@raspberrypi:~ $ dig @8.8.8.8 -p 53 +short s3.amazonaws.com | tail -1
52.216.184.133
pi@raspberrypi:~ $ dig @8.8.8.8 -p 53 +short mail.google.com
googlemail.l.google.com.
216.58.207.37
pi@raspberrypi:~ $ dig @8.8.8.8 -p 53 +short mail.google.com | tail -1
216.58.205.229
pi@raspberrypi:~ $ dig @8.8.8.8 -p 53 +short t-online.de
62.138.238.100
62.138.239.100
pi@raspberrypi:~ $ dig @8.8.8.8 -p 53 +short t-online.de | tail -1
62.138.239.100
pi@raspberrypi:~ $ dig @8.8.8.8 -p 53 +short google.de
172.217.22.35
pi@raspberrypi:~ $ dig @8.8.8.8 -p 53 +short google.de | tail -1
216.58.207.35
```

**Comment by Mcat12** [comment]
> ```
> pi@raspberrypi:~ $ dig @8.8.8.8 -p 53 +short google.de
> 172.217.22.35
> pi@raspberrypi:~ $ dig @8.8.8.8 -p 53 +short google.de | tail -1
> 216.58.207.35
> ```

This seems unexpected, but it works correctly when I did it manually. Perhaps the output was copied here incorrectly?

**Comment by ryrun** [comment]
You mean the different ips for the same domain? I think it depends on your location and which google servers are nearby. I'm in germany and doing this kind of request always give me different ip's of differnt google servers back.

```
pi@raspberrypi:~ $ dig @8.8.8.8 -p 53 +short google.de
216.58.210.3
pi@raspberrypi:~ $ dig @8.8.8.8 -p 53 +short google.de
172.217.22.35
pi@raspberrypi:~ $ dig @8.8.8.8 -p 53 +short google.de
172.217.22.35
pi@raspberrypi:~ $ dig @8.8.8.8 -p 53 +short google.de
216.58.210.3
pi@raspberrypi:~ $ dig @8.8.8.8 -p 53 +short google.de
216.58.210.3
```

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-4-3-2-release-notes/23852/1

**Pull request merged**
