### PR TITLE
Dont use bash keywords/programs as variable names

### PR DESCRIPTION
**Pull request by PromoFaux**
## **What does this PR aim to accomplish?:**

No functionality change here, just noticed as I was looking through the code that these two words were highlighted.

I guess they are reserved words. I don't think anything is actually affected, but feels like bad practice

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
- [x] I have read the above and my PR is ready for review. _Check this box to confirm_

### CODE REVIEW

**Comment by rdwebdesign** [comment]
I think we you need to do the same here:
https://github.com/pi-hole/pi-hole/blob/6c7a28a7b562bb8b3772e751efbac8861e7b43c5/gravity.sh#L720-L788

**Comment by PromoFaux** [comment]
Good spot. I tried to look for some more, but obviously missed one!

**Review by yubiuser — CHANGES_REQUESTED** [review]
https://github.com/pi-hole/pi-hole/blob/aefbe1f5b6225b7476fe08264c62da84aaa61fa0/advanced/Scripts/query.sh#L37

`query.sh` uses `type` as variable as well

**Comment by PromoFaux** [comment]
y'all and your eyes!

**Comment by yubiuser** [comment]
`Ctr+F`

**Review by yubiuser — APPROVED** [review]

**Pull request merged**
