### PR TITLE
WIP Sunset py27

### PR DESCRIPTION
**Pull request by jnozsc**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [ ] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by dschaper** [comment]
You need the code from the branch I linked to in your other PR. You will not pass the tests without it.

**Comment by dschaper** [comment]
I can PR it in to your repo if you'd like, but this is the change:

https://github.com/pi-hole/pi-hole/compare/development...fix/latettag_newline

**Comment by dschaper** [comment]
Sorry, had a major senior moment and brain left me. The best option at this point is to rebase on to https://github.com/pi-hole/pi-hole/tree/release/v5.0 as that has a number of fixes that haven't made it to development yet. I'll work on bringing development up to date in a bit, but use release/v5.0 please.

**Comment by jnozsc** [comment]
sorry for my bad rebase skill, I have to close this one and create another PR.

**Comment by dschaper** [comment]
Not a problem at all, thank you for sticking with it and not giving up!

**Pull request closed without merging**
