### PR TITLE
Remove double echos

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 10

---

Output on fresh installation is like:
```
::: Checking for existing repository...
:::    Cloning https://github.com/pi-hole/pi-hole.git into /etc/.pihole...:::    Cloning https://github.com/pi-hole/pi-hole.git into /etc/.pihole... done!
 done!
```

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by DL6ER** [comment]
`update_repo` and `make_repo` show the very same messages again, I.e. they are always shown twice currently

**Comment by dschaper** [comment]
@DL6ER Master doesn't have the `echo` lines? https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L164

**Comment by dschaper** [comment]
And, I see what you mean now. https://github.com/pi-hole/pi-hole/blob/development/automated%20install/basic-install.sh#L178 and https://github.com/pi-hole/pi-hole/blob/development/automated%20install/basic-install.sh#L140

**Comment by jacobsalmela** [comment]
Ahh OK.  I see now.  Thanks!

**Pull request merged**
