### PR TITLE
Add kernel information to chronometer

### PR DESCRIPTION
**Pull request by Perflyst**
Signed-off-by: Perflyst <mail@perflyst.de>

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**
Add kernel information to chronometer

### CODE REVIEW

**Comment by DL6ER** [comment]
How is this information relevant for what Pi-hole does (ad blocking)? I could *maybe* see an advantage in getting notified if there is a kernel update (or general updates) as this might bring in security fixes, but the static display of the architecture and kernel version is something where I do not see an advantage.

**Comment by dschaper** [comment]
I'll echo DL's comments. Is there an issue this ties to or any explanation of why this is necessary?

**Comment by Perflyst** [comment]
Chronometer shows already informations about the device. The kernel is an essential part of it so I find it useful to show it, to see which version runs on it.
Because you only have one display for the pihole output it is the best way to add kernel information to the chronometer.

**Comment by dschaper** [comment]
Based on the comments of the team I'm going to deny.

**Pull request closed without merging**
