### PR TITLE
Switch fedora and debian install check order

### PR DESCRIPTION
**Pull request by PromoFaux**
Address #660 

Changes proposed in this pull request:

- I've no way of testing this currently, but I think this is what @bcambl  was on about...!

@pi-hole/gravity

### CODE REVIEW

**Comment by Mcat12** [comment]
Approved (Also can't test, but the code looks good)

**Comment by dschaper** [comment]
:shipit: Looks fine in Droplet.

**Comment by bcambl** [comment]
Looks good. Thanks

**Comment by PromoFaux** [comment]
Approved

**Pull request merged**
