### PR TITLE
Cbh/bugfix/formatting

### PR DESCRIPTION
**Pull request by dschaper**
Alpha branch for #252. Please push any further changes to this branch.

### CODE REVIEW

**Comment by PromoFaux** [comment]
Should it not be CBH -> dev -> master? :)

**Comment by dschaper** [comment]
I'd like to have things tested out on their own bugfix  / feature branches before going to dev. I'd like to have dev as a branch for integration testing of multiple bugfixes / features and once it's passed that then head to master. I don't want to dump directly from PR to dev, it's not how I'd like to flow. This particular PR can probably bypass dev and go to master, it's pretty simple, just typographical changes.

**Comment by dschaper** [comment]
This should be ready for merge if there are no objections.

**Comment by PromoFaux** [comment]
Just going to give it a look over, make sure it doesn't break anything

**Comment by PromoFaux** [comment]
Looks good this side. I've pushed into the dev branch, too.

**Pull request merged**
