### PR TITLE
Replace `truncate` command with `echo " " >`

### LINKED ISSUE #221: Chrono LCD Query Stats Stop Pulling Or Recording When It Resets For the New Day
My stats as I just checked when I got home are:

Query: 1
Ads Blocked: 18 (1800%)

After browsing for 15min to sites I know have ads and ones with tons of ads it shows

Query: 1
Ads Blocked: 42 (4200%)

There is still something going on with permissions or the chrono script. It was fine yesterday, this happened once the script reset for the new day.

My laptop is going through the pi-hole so I know my traffic is not going someplace else.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30100614-chrono-lcd-query-stats-stop-pulling-or-recording-when-it-resets-for-the-new-day?utm_campaign=plugin&utm_content=tracker%2F3011939&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F3011939&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by PromoFaux**
Fixes #221  

See [here](https://www.reddit.com/r/pihole/comments/50naz8/queries_and_chronometer_still_wrong/d76t1ax?context=3) for details

@pi-hole/gravity

### CODE REVIEW

**Comment by PromoFaux** [comment]
:shipit:

**Comment by PromoFaux** [comment]
All credit to @gh0stshell for the fix

**Comment by jacobsalmela** [comment]
approved

**Comment by Mcat12** [comment]
Approved.

**Comment by dschaper** [comment]
Is it the space that is the fix, or can we use the logsafe `:> filename` to noop into the file?

**Comment by dschaper** [comment]
(And longer term, would it be better to add this as a logrotate snippet so that we could have a little more control over when the log is flipped... Will add as feature request.)

**Comment by PromoFaux** [comment]
Pass. I know that @gh0stshell tried several things to get it working and wound up with this. 

We know this works, will it cause any issues?

**Comment by dschaper** [comment]
Possibly if we write to the file at the same time it is being read, race condition that could bork. Rare, but the noop would pause for the read and wait until it has a sort of blocking access to that file, then dumps it.

**Comment by dschaper** [comment]
I guess it's good for now, and I'll add the FR for addition to logrotate. I see that the fix has been field tested so I'm comfortable with it.

**Comment by dschaper** [comment]
Approved

**Comment by PromoFaux** [comment]
Ah, that reminds me...

**Pull request merged**
