### PR TITLE
CLI function (checklogs) to check Pi-hole logs for given IOCs (domains/FQDNs, or IPs)

### PR DESCRIPTION
**Pull request by securechicken**
**By submitting this pull request, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
This PR implements a 'checklogs' command-line function (`pinhole checklogs`), which is aimed at checking Pi-hole FTL DB and DNS logs for a list of given domains/IPs, in order to determine if they have ever been queried by Pi-hole systems, regardless of the whole blocking logic. 

This is notably useful to investigate on (or check for) possible compromise, based on a list of network indicators of compromise (IOCs). This is also useful to quickly and programatically check if some domains have ever been queried, as far as Pi-hole can remember, without having to navigate the Web UI.

This has been proposed as some friends and I regularly rely on Pi-hole data (which are perfect) to check for possible past domains requests or known IPs resolutions; and we all had to manually query FTL DB, grep files, and/or write additional scripts to programatically do so.

**How does this PR accomplish the above?:**
This PR adds a dedicated script to implement the function, as well as a new command-line action in `pihole` to trigger the script execution (as done for existing CLI features). The script takes a path to a file (which contains a list of FQDNs/domains and IPs to be searched) as an argument.

The function is implemented by querying the FTL DB with `sqlite3`, and/or the `dnsmaq` generated DNS logs with `grep`. This function is not intrusive, as it does not requires additional files, DB, or setup actions to work; and simply relies on existing data and tools.

In order to ease tests, the checklogs function script can be used as a standalone one, out of the `pihole` command wrapper context.

Depending on PR adoption; this function could be wrapped in Web UI in the future, from the model of existing Tools > Query Lists page (queryads.php).

**What documentation changes (if any) are needed to support this PR?:**
Function is documented (detailed command line help + script comments). An entry would have to be added for `checklogs` action in [Pi-hole Web documentation](https://docs.pi-hole.net/core/pihole-command/), but could simply  be a copy of command-line help content.

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by jfb-pihole** [comment]
I'm not convinced this should be a core function of Pi-hole, but it may be helpful to some users.  My concern is the potential support load when the script doesn't complete properly - It may throw an error, but users will end up in our forums to resolve the problem.  And there is also the long term maintenance of this additional code - our developer team is quite small.

How do you handle the case where the user does not have their long term database in the default location?  You appear to have this hard-coded.  (PIHOLE_FTLDB="/etc/pihole/pihole-FTL.db")

This specific dnsmasq log (PIHOLE_LOGS="/var/log/pihole.log") will never hold more than 24 hours of data, and can contain as little as 1 minute of data, depending on when you access the log.  There may be as many of 5 previous days logs in the /var/log folder that do not appear to get searched. 

```
ls -lha /var/log/pihole.log*
-rw-r--r-- 1 pihole pihole 2.4M Jan 30 14:15 /var/log/pihole.log
-rw-r--r-- 1 pihole pihole 3.0M Jan 30 00:00 /var/log/pihole.log.1
-rw-r--r-- 1 pihole pihole 215K Jan 29 00:00 /var/log/pihole.log.2.gz
-rw-r--r-- 1 pihole pihole 305K Jan 28 00:00 /var/log/pihole.log.3.gz
-rw-r--r-- 1 pihole pihole 219K Jan 27 00:00 /var/log/pihole.log.4.gz
-rw-r--r-- 1 pihole pihole 178K Jan 26 00:00 /var/log/pihole.log.5.gz
```

This part seems backwards to me:  bad news that a result is found?  It seems that this is neither bad news or good news, it's just an answer.

```
   pbadnews "Uh oh, some IPs matched"
  else
    pgoodnews "No IPs were found in DNS logs"
```

**Comment by JusticeRage** [comment]
Definitely a feature I would be happy to have in the project. It is something I need to do on a regular basis.
Is there a way I can help get it merged?

**Comment by securechicken** [comment]
> I'm not convinced this should be a core function of Pi-hole, but it may be helpful to some users. 

I can't vet for all users, and this is up to maintainers; but some friends and I use Pi-hole for 2 things with equal importance: DNS blocking (annoying ads, trackers, malicious FQDNs), and DNS requests/resolution data conservation for the purpose of later searches. 

> My concern is the potential support load when the script doesn't complete properly - It may throw an error, but users will end up in our forums to resolve the problem. And there is also the long term maintenance of this additional code - our developer team is quite small.
> 

Can't estimate that, but there are not much possible errors (command line arguments - detailed help is available; FTL DB missing - DNS logs missing is just a warning, grep failed, sqlite3 query failed). And I can of course help maintaining this - if there are bugs, I'd like to fix them.

> How do you handle the case where the user does not have their long term database in the default location? You appear to have this hard-coded. (PIHOLE_FTLDB="/etc/pihole/pihole-FTL.db")
> 

Stated just above in comment. This is a default value, will be read in `pihole-FTL.conf` at start and overwritten by set `DBFILE` value if any.

> This specific dnsmasq log (PIHOLE_LOGS="/var/log/pihole.log") will never hold more than 24 hours of data, and can contain as little as 1 minute of data, depending on when you access the log. There may be as many of 5 previous days logs in the /var/log folder that do not appear to get searched.
> 

I personally tuned logrotate to hold way more than that. In any case, this value is also a default one, read from `dnsmasq.d\01-pihole.conf` later, is stared and passed to zcat, so all available rotated logs are also read (5 days of data in default logrorate config).
 
> This part seems backwards to me: bad news that a result is found? It seems that this is neither bad news or good news, it's just an answer.
> 

The main use case is searching for IOCs. So if you match a malicious FQDN or IP, it means one of your Pi-hole DNS clients at least tried to connect to a malicious endpoint (and then results will help you find which, what time, and which resolution). This IS bad news. But this could be changed with a mere warning, to allow for more general use cases.

**Comment by arieljt** [comment]
Searching for some similar solution to check my huge logs against a list of domains/IP I couldn't find anything beyond some examples to query the DB directly. I think the solution here naturally extends the functionality of pi-hole and would make it easier for other users looking to do the same.

**Comment by DL6ER** [comment]
I haven't had the time to look through your script properly. Given that it is > 500 lines (okay, a lot is comments and smaller helper functions), I should reserve some time for doing so. So far, I have few questions.

> This is notably useful to investigate on (or check for) possible compromise, based on a list of network indicators of compromise (IOCs).

Where to get them from?

> a list of given domains/IPs

Pi-hole stores only domains, not what they resolved to as this would unnecessarily make the database a lot larger. Admittedly, this information will be in `pihole.log` if logging is enabled. So is scanning for IPs limited to the most recent log data? Is this mentioned somewhere?

**Comment by JusticeRage** [comment]
> Where to get them from?

Whenever security research is published, there is usually a section at the end containing domains or IPs used by the attackers. You can find an example of those [here](https://securelist.com/holy-water-ongoing-targeted-water-holing-attack-in-asia/96311/) in the "Appendix – IOCs" paragraph - but really, it's an industry standard. There are also a number of commercial services that provide streams containing such indicators.

**Comment by securechicken** [comment]
> Given that it is > 500 lines (okay, a lot is comments and smaller helper functions), I should reserve some time for doing so
>

Seems fair!

> > This is notably useful to investigate on (or check for) possible compromise, based on a list of network indicators of compromise (IOCs).
> 
> Where to get them from?
> 

I agree with @JusticeRage. It will be natural and very common for anyone wishing to check for possible compromise, based on DNS logs. Input IOCs are just a list of domain names/FQDNs and/or IPs that are "known bad" in a given context. Depending on what you are looking for (the most frequent scenario is that you want to check if you have been targeted/compromised by a given recent attack), this could be an appendix in a public or private report, some raw lists in GitHub repositories (a directory-like crowd-sourced index here: https://github.com/sroberts/awesome-iocs), feeds of such "IOCs" that are published freely or to paid-subscribers as JSONs, or any suspicious domain that has been described as so in a social network post.

> > a list of given domains/IPs
> 
> Pi-hole stores only domains, not what they resolved to as this would unnecessarily make the database a lot larger. Admittedly, this information will be in `pihole.log` if logging is enabled. So is scanning for IPs limited to the most recent log data? Is this mentioned somewhere?

Command is primarily aimed at looking for domains/FQDNs hits, from FTL DB (and Pi-hole's DNS logs as an additional source to get more details where available), but some resolutions can also be found on Pi-hole's DNS logs, so I thought it would not hurt to use what is available. The command doc states what is looked for and where it is looked in. An additional warning on default very limited retention for DNS logs can be added in output messages if needed - but anyone can tune logs retention with Pi-hole's logrotate settings.

**Comment by DL6ER** [comment]
There are a few stickler complains on your code, e.g. https://github.com/pi-hole/pi-hole/pull/4026/files#annotation_903707644

We should discuss the point raised by @jfb-pihole, I'll ask for some more opinions.

> I'm not convinced this should be a core function of Pi-hole, but it may be helpful to some users. My concern is the potential support load when the script doesn't complete properly - It may throw an error, but users will end up in our forums to resolve the problem. And there is also the long term maintenance of this additional code - our developer team is quite small.

**Comment by securechicken** [comment]
> There are a few stickler complains on your code, e.g. https://github.com/pi-hole/pi-hole/pull/4026/files#annotation_903707644
> 
Fixed (rebase from development branch, with fixup on 1st commit).

> We should discuss the point raised by @jfb-pihole, I'll ask for some more opinions.
> 
Fair enough.

**Comment by yubiuser** [comment]
This script serves a very specific use case which the majority of Pi-hole users probably will never use. It's a perfect stand-alone tool and I don't see the value in adding it into Pi-hole directly (except of having received the blessing of the Pi-hole devs). Users who want to use it can run `./checklogs.sh` instead of `pihole checklogs`. 
On the downside of integrating it is the potential maintenance and support load.

**Comment by JusticeRage** [comment]
>This script serves a very specific use case which the majority of Pi-hole users probably will never use. 

> potential maintenance and support load

I feel that those two statements contradict themselves. Either only a limited number of people will ever use the feature, in which case it's unlikely it will generate crazy amounts of support requests, or a lot of people encounter problems with it which means that they are using it and that there's a real demand for it.

Which is it?

**Comment by dschaper** [comment]
> Which is it?

First, drop the attitude.

> I feel that those two statements contradict themselves.

The support burden comes from me and the other two developers having to adopt the code and maintain it and support it going forward. If this is the kind of response we're going to get from the community then I'm fine with rejecting this PR and letting the community take their demands directly to the PR author on their own repo.

**Comment by jfb-pihole** [comment]
I will restate my position on this.  This is an edge case, and does not contribute to the core function of Pi-hole as a domain blocker.  The purpose of this PR is to enable users to query Pi-hole logs against a list of domains, which is not within the scope of the Pi-hole software.  This PR is expanding Pi-hole to become a threat monitoring tool.

I agree that the proposed code has value, but I don't agree that it should become part of the Pi-hole code.

If we add a feature, users will use the feature and we will be required to support it.  This is similar in concept to the PADD software, which is a nice enhancement to Pi-hole, but is not part of the Pi-hole code, although the code is maintained by the Pi-hole team now.  Users have also written scripts that work alongside Pi-hole and are not embedded in Pi-hole code either (scripts to synchronize multiple Pi-hole installs, to determine which blocklists are being used regularly, etc.).  This proposed PR falls in the latter category.  It should be a separate user project, supported by those who wrote it and not embedded in the Pi-hole code.

**Comment by rasmuskapten** [comment]
Den tis 16 feb 2021 15:08Ivan Kwiatkowski <notifications@github.com> skrev:

**Comment by securechicken** [comment]
I'm absolutely fine publishing this as a standalone script, and I'm doing it now, while closing the PR (hope this is fine, I'm not familiar with such situation, reopen if not!), so that we do not make that pending more while taking contributors time.

It was actually a standalone script before the integration attempt and Pi-hole contributions guidelines conversion; but discussing the script with friends users, I understood that it would be simpler for most users to get it with Pi-hole and run it through standard `pinhole` CLI command, while giving it better chances of broader adoption (I deemed making simple IOCs checkup available to a broad user base from an already good product to be something good as well).

From my perspective, I do not feel that expected downsides around support and/or integration would be severe enough to prevail upon added functionality, but I'm a casual open-source contributor, not involved in Pi-hole project, and I initially needed this functionality; so surely can't assess right. I also do not agree that this is turning Pi-hole into a threat monitoring tool: I believe that a casual sqlite3/grep query helper on available at-rest data is far from that. It's certainly not introducing heavy or competing pipelines and continuous processes, it's not adding any data or requirements, and it is barely making a possible and useful casual task easier.
Yet, I perfectly understand (and agree with) maintainers deeming that anything as such should not be added to Pi-hole core, because it's not adding anything to core, not fitting with plans or in scope, or because it's simply something to add they don't feel good with.

If at any point you want that in, or efforts around such functionality, feel free to reach me back. Thanks for consideration in any case!

**Pull request closed without merging**
