### PR TITLE
Use autoremove feature of package manager for removing dependencies

### PR DESCRIPTION
**Pull request by WouterServaes**
**What does this PR aim to accomplish?:**

It adds the autoremove feature of the supported package managers for the installed dependencies, and adds an extra warning on packages that could not be auto removed.

**How does this PR accomplish the above?:**

It marks the newly installed dependencies as automatically installed through the package manager. During uninstallation these packages are automatically removed through the package manager autoremove feature. 

After the auto removal we still request if the user wants to remove the other packages, if so we again auto remove after the manual removal.

**Link documentation PRs if any are needed to support this PR:**

No documentation changes required. https://docs.pi-hole.net/main/uninstall/ is still ok

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x ] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by WouterServaes** [comment]
This implements https://github.com/pi-hole/pi-hole/issues/3929

**Comment by WouterServaes** [comment]
Force push due to missing signature

**Comment by WouterServaes** [comment]
I'll look into that also

**Comment by WouterServaes** [comment]
Commit [Added debian package for dependecy installation](https://github.com/pi-hole/pi-hole/pull/5782/commits/0eb6f76d0936bab540e9e10d77677aaf7641d5dc) uses a pihole-dependencies.deb file for installation. 

Uninstalling this package with `apt-get -y remove --purge --auto-remove pihole-dependencies` does NOT remove all installed packages. 

Following things were done on a clean Ubuntu docker

Installed the 81 required packages with  `apt-get install --no-install-recommends ./pi/pihole-dependencies.deb`:
```
adduser bash-completion bind9-dnsutils bind9-host bind9-libs binutils binutils-common binutils-x86-64-linux-gnu ca-certificates cron cron-daemon-common curl dialog dns-root-data dnsutils git git-man iproute2 iputils-ping jq libapparmor1 libargon2-1 libbinutils libbpf1 libbrotli1 libbsd0
  libcap2-bin libcryptsetup12 libctf-nobfd0 libctf0 libcurl3t64-gnutls libcurl4t64 libdevmapper1.02.1 libedit2 libelf1t64 liberror-perl libexpat1 libfdisk1 libgdbm-compat4t64 libgdbm6t64 libgprofng0 libgssapi-krb5-2 libicu74 libjansson4 libjq1 libjson-c5 libk5crypto3 libkeyutils1 libkmod2
  libkrb5-3 libkrb5support0 libldap2 liblmdb0 libmaxminddb0 libmnl0 libnghttp2-14 libonig5 libperl5.38t64 libpsl5t64 librtmp1 libsasl2-2 libsasl2-modules-db libsframe1 libssh-4 libssl3t64 libsystemd-shared libtirpc-common libtirpc3t64 libuv1t64 libxml2 libxtables12 lshw netcat-openbsd
  openssl perl perl-modules-5.38 psmisc sudo systemd systemd-dev unzip
```
Removed 76 packages with `apt-get remove --purge --auto-remove pihole-dependencies`
```
bind9-dnsutils* bind9-host* bind9-libs* binutils* binutils-common* binutils-x86-64-linux-gnu* cron* cron-daemon-common* curl* dialog* dns-root-data* dnsutils* git* git-man* iproute2* iputils-ping* jq* libapparmor1* libargon2-1* libbinutils* libbpf1* libbrotli1* libbsd0* libcap2-bin*
  libcryptsetup12* libctf-nobfd0* libctf0* libcurl3t64-gnutls* libcurl4t64* libdevmapper1.02.1* libedit2* libelf1t64* liberror-perl* libexpat1* libfdisk1* libgdbm-compat4t64* libgdbm6t64* libgprofng0* libgssapi-krb5-2* libicu74* libjansson4* libjq1* libjson-c5* libk5crypto3* libkeyutils1*
  libkmod2* libkrb5-3* libkrb5support0* libldap2* liblmdb0* libmaxminddb0* libmnl0* libnghttp2-14* libonig5* libperl5.38t64* libpsl5t64* librtmp1* libsasl2-2* libsasl2-modules-db* libsframe1* libssh-4* libsystemd-shared* libtirpc-common* libtirpc3t64* libuv1t64* libxml2* libxtables12*
  lshw* netcat-openbsd* perl* perl-modules-5.38* pihole-dependencies* sudo* systemd* systemd-dev* unzip*
```

The --auto-remove also fails when removing sudo (I'm doing this on a clean system w/o sudo)

The remaining 5 packages are still listed in `apt-mark showauto`:
```
adduser
bash-completion
ca-certificates
openssl
psmisc
```

I don't see how to remove these without explicitly asking the user, like how it is done now.

This is a work-in-progress commit, I'll look into this further, the installation tests will be fixed later.

**Comment by yubiuser** [comment]
I use a similar approach, but create the file on-the-fly.
https://github.com/pi-hole/pi-hole/pull/5785

Benefit is, that we avoid chicken-egg-situations when no `git` is installed and users can't download the repo and building the `*.deb` file

**Comment by WouterServaes** [comment]
Alright, that looks like a better approach yeah. I'll close this one

**Pull request closed without merging**
