### PR TITLE
removed relative ajax url

### PR DESCRIPTION
**Pull request by armin-nowacki**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

_3_

---
_removed relative ajax url_

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by Mcat12** [comment]
Why is this change necessary?

**Comment by DL6ER** [comment]
Is there anywhere some more information on why you would like to do this?

**Comment by armin-nowacki** [comment]
whenever i want to whitelist a page 
it sends the ajax data to the addomain with the following path
http://addomain.com//admin/scripts/pi-hole/php/add.php

**Comment by Mcat12** [comment]
You should be using http://pi.hole instead of the ad domain to access the web interface. Really, the web interface shouldn't be displaying if queried from the ad domain, because it would fail the Host check...

**Comment by armin-nowacki** [comment]
https://discourse.pi-hole.net/uploads/default/original/2X/4/46675a5b8cb7172e276443e5ed195be1c4b3e800.png

**Comment by Mcat12** [comment]
I see, what is the response?

**Comment by 1056454120** [comment]
so how can i whitelist a domain from the blocked page? when it sends the ajax request to addomain instead of pi.hole?

**Comment by Mcat12** [comment]
What is the response to that add.php request?

**Comment by 1056454120** [comment]
http://i.imgur.com/ke4dtKJ.png

**Comment by Mcat12** [comment]
Yes. I see what's going on now. It's requesting http://de.ign.com/ready-or-not/.../admin/scripts/pi-hole/php/add.php instead of http://de.ign.com/admin/scripts/pi-hole/php/add.php

Since Pi-hole redirects ad domains to itself, accessing the script via de.ign.com is the same as pi.hole in this case. The fix should be as simple as adding a `/` before `admin` on [this](https://github.com/pi-hole/pi-hole/blob/development/advanced/index.php#L188) line. If you want to make a PR for this, please read [the contributor's guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md) first.

**Comment by 1056454120** [comment]
yes thats what i meant sorry that ive closed the ticket was probably an accident

**Comment by Mcat12** [comment]
That's fine. Now you can open a new PR with a new branch based on what you learn from the contributor's guide.

**Pull request closed without merging**
