### PR TITLE
Update test to reflect currently supported OS

### PR DESCRIPTION
**Pull request by yubiuser**
- **What does this PR aim to accomplish?:**

Adjusts test to reflect supported OS. To be seen with https://github.com/pi-hole/docs/pull/728

Drop Debian 9, Ubuntu 16, ~~Ubuntu 21~~ and Fedora 33

- **What documentation changes (if any) are needed to support this PR?:**

https://github.com/pi-hole/docs/pull/728

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
- [x] I have read the above and my PR is ready for review. _Check this box to confirm_

### CODE REVIEW

**Comment by dschaper** [comment]
Can we keep Ubu21? I think it would be good to test against still.

**Comment by yubiuser** [comment]
Just adding back the test or also keep it in the list of "supported OS" in https://github.com/pi-hole/docs/pull/728

**Comment by yubiuser** [comment]
Test fail because DNS record of supported OS does not include Ubuntu 22 yet.

**Comment by dschaper** [comment]
I don't think we need to add them to the supported OS record, maybe we should?

We have a development txt record that can be updated to include Ubu22 for testing.

**Comment by PromoFaux** [comment]
Ah yeah, we should add it to the one at `dev-supportedos.pi-hole.net`. I don't remember what site I need to log into for that? I'll DM you @dschaper

**Comment by dschaper** [comment]
Tis managed by CI. I'll send you the info.

**Review by dschaper — APPROVED** [review]

**Pull request merged**
