### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by michi-zuri**
As requested.
See #3736

### CODE REVIEW

**Comment by PromoFaux** [comment]
Seems sane, but please sign off your commit so that the DCO bot passes... see here for instructions:

https://github.com/pi-hole/pi-hole/pull/3737/checks?check_run_id=1077567936

**Review by PromoFaux — APPROVED** [review]

**Comment by PromoFaux** [comment]
Thanks. I'll add this in because it is an innocuous change, but FYI, this can be avoided by using the built in `pi.hole` or typing the IP address directly. In either of those cases, the request will be redirected to `/admin` automagically. No harm in including `localhost` in that, though!

**Comment by michi-zuri** [comment]
Cool, thanks for approving. Since I'm tunneling port 80 of my pi to localhost:4653 (on my laptop) I didn't really have the option to use an ip address or pi.hole for the pi, otherwise I wouldn't need the tunnel in the first place. Next project is to figure out how to tunnel port 53 to localhost, but that seems more complicated with udp and all... Goal is to use pihole behind a NAT while on the road.

**Comment by PromoFaux** [comment]
VPN probably easier! https://docs.pi-hole.net/guides/vpn/overview/

If you want to get really fancy, something like this: https://www.reddit.com/r/pihole/comments/fy8zmu/pihole_traefik_dnsovertls/

**Pull request merged**
