### PR TITLE
[WIP] update chronometer.sh using web api with JSON

### PR DESCRIPTION
**Pull request by tuplink**
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**By submitting this pull request, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**
- [ x] 5

wasnt sure how to go about rebasing to devel   so here is a new PR   

OLD PR:https://github.com/pi-hole/pi-hole/pull/829

### CODE REVIEW

**Comment by tuplink** [comment]
i am not fluent in python i read somewhere that print() and python3 may function difrently

tested this on Python 2.7.12

**Comment by dschaper** [comment]
Yeah, print being a function call was changed in Python 3, so that is one of the buggy things that will catch you. You can `from future import print` in Python 2 to pull in that call if you'd like to develop on 2 and use 3 style prints. 

And formatting new style is pretty much the same: https://pyformat.info/

**Comment by tuplink** [comment]
works on   both
#python2 --version     Python 2.7.12
#python3 --version     Python 3.5.2

tested by replacing python   with python2/python3 

not sure if it looks right because im really not a python gooroo

**Comment by tuplink** [comment]
so i would like direction.   i have 3 working versions of this script.
1 requires jq
2 requires python
3 requires a small php script

what would you like to see?

**Comment by dschaper** [comment]
3 PR's with each one in a different request so we can see which is the best solution.

**Comment by tuplink** [comment]
ok so can you tell me how to make 3 branches in my local fork that are of pi-hole/development    or point me in the correct direction

**Comment by dschaper** [comment]
`git checkout -b newbranch origin/development`

**Comment by tuplink** [comment]
and that will not be based off of the changes i ahve already made in my development?

**Comment by dschaper** [comment]
Not as long as you pulled from our repo, origin should point to the Pi-hole repo and your would be sourcing development from the origin repo. `git remote show origin` in the local git repo should show the Pi-hole repo as `origin`.

**Comment by tuplink** [comment]
moved to three PRs
[Python](https://github.com/pi-hole/pi-hole/pull/854)
[JQ](https://github.com/pi-hole/pi-hole/pull/855)
[PHP](https://github.com/pi-hole/pi-hole/pull/856)

**Comment by tuplink** [comment]
Closed after linking new PRs

**Pull request closed without merging**
