### PR TITLE
Fixing code for running pihole under docker in different port

### PR DESCRIPTION
**Pull request by diegoweb**
See https://github.com/pi-hole/pi-hole/issues/2195#issuecomment-486854023 for explanation

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*
https://github.com/pi-hole/pi-hole/issues/2195#issuecomment-486854023

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*
If pi-hole is running under docker, if you change default exposed port 80 to any other, it gives you an error when you visit HOST_IP:PORT.

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*
Not necessary.

Sorry if anything is not properly documented, my english is not very good for technical stuff.

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by dschaper** [comment]
Is this a situation that happens when you run docker with `-p 1234:80` mapping or are you changing port 80 in the image to something else?

**Comment by dschaper** [comment]
- Submit Pull Requests to the development branch only.
- Before Submitting your Pull Request, merge development with your new branch and fix any conflicts. (Make sure you don't break anything in development!)

**Comment by diegoweb** [comment]
Yup @dschaper when you run pihole with -p 1234:80

**Comment by dschaper** [comment]
@diginc Can you look this over please?

**Comment by diginc** [comment]
Seems fine to me.  Has it been tested on bare metal install in addition to docker?

**Comment by Hades32** [comment]
I tried this change by modifying the file directly in the latest docker image and it didn't help.

**Comment by diegoweb** [comment]
Still working great in the latest version
chrome_10-12-2019_10-31-15

But I have to modify the file every pihole update.
chrome_10-12-2019_10-33-09

**Comment by dschaper** [comment]
If you rebase to `development` instead of `master` then the required tests will be more likely to pass.

**Comment by mschoettle** [comment]
Can someone try `$_SERVER["SERVER_NAME"]`? That gives the actual host name instead of the IP address. *HOST* which is there currently returns `hostname:port`. I created pull request #3067 which addresses problems when changing hostname and/or port where I used *SERVER_NAME*.

**Comment by DL6ER** [comment]
Closing due to inactivity

**Pull request closed without merging**
