### PR TITLE
Diagnostic script

### PR DESCRIPTION
**Pull request by fayetted**
Script checks
 1. Google public DNS nameservers, ensure they resolve to public IP's
 2. Two random sites from the whitelist, ensure they are public IP's
 3. Two random sites from the adlist, ensure they resolve to the Pi-Hole IP
 4. Two random sites from the blacklist, ensure they resolve to the Pi-Hole IP

Addresses Feature request #100

### CODE REVIEW

**Comment by PromoFaux** [comment]
Just taken a look over this script...

A couple of things:
In this screenshot, you can see that the sites listed in `gravity.list` are showing as resolving a public IP address, however when pinging them (from any device on my network) I get an internal IP address (as expected)

image

Another thing I noticed is on [this line](https://github.com/fayetted/pi-hole/blob/66e3a005d8d7c138423ebc367023735111e1e1e8/advanced/Scripts/check-functionality.sh#L18) there is a localrange IP address hard-coded... what is that, please? It appears to be the root of the `$ip` not displaying in the brackets


(as an aside, thankfully that second address is blacklisted.. wouldn't want my ISP thinking I was trying to resolve it!)

**Comment by fayetted** [comment]
Good catch and thanks for looking.  I think taking the static IP out will fix the issue. But you did bring up a new use case where the name does not resolve at all because your pointed at a non existant name server.  Which could also happen if the upstream name server was not accessible or returned an NXDOMAIN response.

I'll take a look and address these and then comment on the PR.  Should be fairly quick to fix and easy to test.

As for the "aside", I'm picking at random a name from the gravity.list.  Is this ok, or would it be better to pick at random then test for certain key words and if found pick again?

**Comment by fayetted** [comment]
I removed the test IP that was left in accidentally and also accounted for when a name does not resolve.

Ready for re-testing.

**Comment by PromoFaux** [comment]
OK, that is actually much quicker than it was, too.. I'm guessing that was to do with the test IP you left in?

The two random addresses is fine, I was just clad I wasn't having to actually resolve it :D

Looks good to me. Will need to have a conversation with @jacobsalmela about how we include/implement this.

**Comment by fayetted** [comment]
Great, I'm glad it worked this time.

**Comment by jacobsalmela** [comment]
I think this is a good start, and I like how it chooses random domains to test.  

One thing I noticed though is that if you run it directly from the Pi so it can't simulate a client connection.  For example, if you turn off `dnsmasq` and try go get out to the Internet, it won't work, but the script would still say that it succeeded (because the Pi can still make it out the the Internet).

**Comment by fayetted** [comment]
Would forcing the lookups to query localhost rather than relying on the resolv.conf address the problem?

**Comment by dschaper** [comment]
If the queries are executed on the pi, then you can query `127.0.0.1` and get the local `dnsmasq`. Try it while you're tailing logs in another terminal window... (Or try byobu and do it from a single terminal...)

**Comment by fayetted** [comment]
I'm not following your logic.  The script should be performing 4 sets of tests by querying the DNS configured on the system it is run from.  So on the RPI running Pi-Hole, mine is set to use 127.0.0.1 by default, I don't think I changed that.  So the test should perform as such.
1. Is the client able to resolve Good domains via the RPI, If an Internet IP (not the RPI, and not RFC1918) then success.
2. Is the client able to resolve white-listed hosts to an internet IP. if not, then fail
3. Is the client able to resolve adlist IP's to the RPI address. If the RPI address is returned then success, else fail.
4. Is the client able to resolve blacklisted IP's to the RIPI address. If the PI address is returned then success, else fail.

So the comment from @jacobsalmela about turning off dnsmasq is confusing.  Some of the tests would pass if you turn off dnsmasq and change your resolv.conf file to an internet DNS server but the blacklist and adlist queries would fail as they would resolve.

Maybe what is missing is a final status message that checks to make sure all 4 tests succeed and then report either success or failure based on the sum of all the tests.

**Comment by jacobsalmela** [comment]
I use my Pi-hole as my sole DNS server (relying on the upstream servers set in `01-pihole.conf`.  If `dnsmasq` isn't working, my client cannot reach the Internet.  But I turn off `dnsmasq` and ping a domain from the Pi itself, it works.  So even though some of the tests pass when the script runs on the Pi, it may not work for clients if they cannot resolve any hostnames.

I think my logic is right, but I could certainly be wrong.  It starts to get confusing with so many variables!

**Comment by fayetted** [comment]
@jacobsalmela I think we might be confusing each other, so I think it might be best to try to start fresh.

My understanding was that you wanted to be able to run the script from the PI to have it check and validate that the pi-hole service was functioning.  Functioning meaning that good domains resolve to their internet address and bad domains resolve to the PI's IP Address.

The way the script is currently written it relies on the /etc/resolv.conf file to be pointed only to 127.0.0.1 (Your could use the PI's real address too with the same results).  But if your resolv.conf file has your upstream DNS listed then the script will not give an accurate representation of the functioning state of Pi-Hole. (This is why I suggested that maybe hardcodeing 127.0.0.1 in the script might actually be better.  It would provide more accurate results when run from the PI, but would not work if you ran it from a client.)

If you run the script from the PI it will perform nslookups against the IP in the /etc/resolv.conf file (assumed to be 127.0.0.1).  If dnsmasq is truly turned off then all 4 tests will fail as the nslookup will not connect to any DNS service that can return a response (i.e. Every response will be a timeout.)  If you get anything except 4 sets of failures then 1 of 3 things is happening.  1. dnsmasq is not really disabled. 2. Your resolve.conf file is pointing to something other than 127.0.0.1.  3. You also have named/bind (or some other DNS service) also listening on UDP/53 and resolving addresses when DNSMASQ doesn't intercept the connection. This 3rd state would give you partially inaccurate test results as good domains will resolve correctly but bad domains will also resolve to their Internet address.  The script will say the first 2 tests passed and the 2nd 2 test failed.  Which is correct from the scripts perspective because it was able to resolve good domains but bad domains resolved in a way that we don't want and until that is fixed your pi-hole is not 100% functional (It's actually not functioning at all but the script can't differentiate that some other service responded to the DNS queries.)

When dnsmasq is turned on, then you can get any number of possible combinations.  Good address could resolve or not resolve depending on the upstream DNS server in your 01-pihole.conf file (This is independent of your resolv.conf file).  Bad domains could resolve to their actual IP or the RPI depending on if pi-hole is functioning or not ( I actually tested this by setting my umask to 007 and then running gravity before the fix I provided. You can test by changing the permission of /etc/pihole/gravity.list  to 400 and restarting the dnsmasq service. )

Pleas let me know if I'm completely misunderstanding you or the concept your trying to explain to me.  This is an awesome project and I'm glad I found it.  I wrote scripts to do this same functionality on corporate BIND servers years ago but this project gives home users some of the same benefits corporations benefit from and I think that is awesome.

**Comment by manuelgu** [comment]
Any updates? :-)

**Comment by Mcat12** [comment]
Does #411 do some of this?

**Comment by manuelgu** [comment]
Haven't had a detailed look at it but the `piholeDebug.sh` might provide some useful information as to where the Pi-hole works or not

**Comment by nate-ubiquisoft** [comment]
@Mcat12 Yes #411's piholeDebug.sh will give everything you will need, and if there is more information to be needed, I am working on an advanced debug version which will need to install additional network tools to use for advanced debugging. That will be in PiHoleController release, which can be cloned from my repo now if you want to try it out. I still havent finished testing, which after I will submit a PR.

**Comment by jacobsalmela** [comment]
Can this be closed since `pihole -d` is now available?

**Comment by PromoFaux** [comment]
I should say so. Unless there are any updates from @fayetted .

**Comment by Mcat12** [comment]
Closing unless @fayetted says otherwise.

**Pull request closed without merging**
