### PR TITLE
Simplify restarting code for "pihole restartdns"

### LINKED ISSUE #2869: pihole-FTL fails to restart on Debian 10 (Buster)
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`2`

---
**Expected behaviour:**

I am aware that Debian 10 (Buster) is not yet officially supported, but I expect pihole-FTL to support it in the future and found this issue.

**Actual behaviour:**

On Debian 10, `pihole-FTL` has a tendency to fail to restart (using `pihole restartdns` or `pihole -r`), logging that port 53 is already in use despite it not being so.

**Steps to reproduce:**

1. Clean installation of Debian 10 (x86_64).
2. Install Pi-hole
3. `pihole restartdns`

[Demo video](https://youtu.be/bfbHbJTvwQE)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`https://tricorder.pi-hole.net/3y7w56odsy`

**Troubleshooting undertaken, and/or other relevant information:**

By contrast, `systemctl restart pihole-FTL` (almost) always seems to work.

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**

Fixes #2869.

**How does this PR accomplish the above?:**

Simplify restarting code for `pihole restartdns`. The issue has been that we (needlessly) detected whether `pihole-FTL` has been running to decide if we want to run `sudo service pihole-FTL` wither with option `start` or `restart`.

We confirmed experimentally that Debian 10's `system` command refused to `start` `pihole-FTL` after it entered a failed state (even though the binary didn't run). However, `restart`ing always brings the resolver back into an operational state.

As it doesn't seem to be an issue to just always call `restart` (it will also work if `pihole-FTL` was not running!), we will do this now.

### CODE REVIEW

**Comment by dschaper** [comment]
Can you base this on `release/v4.3.2` branch and change the milestone? I'd like to get this in the bugfix release here in the next week instead of waiting for 5.0.

**Comment by DL6ER** [comment]
Rebased as requested.

**Comment by dschaper** [comment]
Pull in changes from `release/v4.3.2` that should pass CI issues with Fedora.

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-4-3-2-release-notes/23852/1

**Pull request merged**
