### PR TITLE
elevate permissions and execute this local script 

### PR DESCRIPTION
**Pull request by stevenharradine**
instead of downloading from the internet

**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

_1_

---
_sudo bash basic-install.sh "$@"_

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by Mcat12** [comment]
`basic_install.sh` is only there if you download the script first.

**Comment by dschaper** [comment]
Yeah, `curl |bash` doesn't leave anything to re-run. If you can find another solution, we'd be very glad to see it.

Declined

**Comment by dschaper** [comment]
Denied

**Comment by dschaper** [comment]
What's the PA NAck code??

**Comment by dschaper** [comment]
Rejected   ?

**Comment by stevenharradine** [comment]
I added a test if the file exists to run it locally.

it caught me off guard when it was redownloading the script from the internet after I had downloaded it and was editing it.  Just running with sudo is probably a good work around, but if someones intentionally downloaded it i don't think they expect the script to download itself again and run that with elevated permissions.

**Comment by dschaper** [comment]
What do you think about `curl -sSL https://install.pi-hole.net  -o basic-install.sh; sudo bash basic-install.sh` as the one-line installer method? That would be very explicit in what it's going to do. We do put a very large emphasis on asking the users to read through the code before executing, but that advice is sometimes at a level higher than our users are comfortable with. 

I'm going through the code right now with the assisstance of the rest of the development team to try to reduce or elmiminate the need for elevate priv's and only call for superuser if required. (Daemon install, any function that needs ports in the <1024 protected range, etc.)

We've been looking for ways to reduce our security footprint, and I really do like the idea, I'm just not sure the best way to implement the whole process. (And bash -x would just leave most users running in abject terror :) )

**Comment by stevenharradine** [comment]
just ran some tests it appears that will still overwrite the file and run it.  there does not appear to be flags to not overwrite with curl.  wget however has --no-clobber but im unsure of the reasoning for using curl here in the first place (but i see wget installed in the script elsewhere)

wget --no-clobber https://raw.githubusercontent.com/pi-hole/pi-hole/master/automated%20install/basic-install.sh; sudo bash basic-install.sh "$@"

**Comment by dschaper** [comment]
The script is `curl`ed to bash to start the install. If `main()` is called as an unprivileged user, then we have to restart the script as `sudo` since we install packages and affect changes to the networking stack. Due to the fact that the script does not exist anywhere as it is piped directly to bash, the only way to call the script a second time with `sudo` is to curl the script a second time as the code does now.

Options would be download the script and not pipe anymore, but my concerns are already in this thread about the issues with that. 

I'm not sure what the difference in `curl` or `wget` would be, and the `raw.githubusercontent.com` address is `install.pi-hole.net`, I just changed the address in the script on the secondary curl to be more specific that we aren't pulling in backdoor code.

I also think we can get rid of the `$@` trailer, as the install is called with no arguments, it doesn't have the code necessary to handle any passed arguments.

**Comment by dschaper** [comment]
Ah, I understand now the basis for the PR. As this would just be an edge case for Ansible I'll stay with my initial declined comment. This opens too many holes that we've spent time to make sure are closed.

**Comment by dschaper** [comment]
After some internal communication, some ideas. What is it that is being changed in the `basic-install.sh` file that needs customization? If we offered the ability to do something along the lines of a preseed file where you could answer the installer questions and set things like file installation paths and the installer would use the preseed declarations, would that help? So you could `curl` the file but still have customization of the process?

**Comment by dschaper** [comment]
Re-opening for further discussion on the issue, feel free to unfollow the issue if you'd like to not be notified of our conversations.

**Comment by dschaper** [comment]
No discussion ensued. Closing.

**Pull request closed without merging**
