### PR TITLE
[BugFix] A man has no name resolution

### PR DESCRIPTION
**Pull request by PromoFaux**
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**By submitting this pull request, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**
- [x] 10 (very familiar)

---

(should) fix an issue brought up here: https://github.com/pi-hole/pi-hole/pull/814#issuecomment-256037665

### CODE REVIEW

**Comment by PromoFaux** [comment]
Downside to this method is of course:
```
adam@adam-debian:/etc/.pihole$ ping pi.hole
PING pi.hole (192.168.216.236) 56(84) bytes of data.
64 bytes from 0000mps.webpreview.dsl.net (192.168.216.236): icmp_seq=1 ttl=64 time=0.016 ms
```

But I'm sure we can find another way around this.

**Comment by PromoFaux** [comment]
Hmm, this isn't working on my Pi at home. Yet it worked earlier at work....

**Comment by PromoFaux** [comment]
Last commit fixed the issue I was having above.

**Comment by dschaper** [comment]
Approved

**Comment by jcandresen** [comment]
is there a way to fix the pi showing up as 0000mps.webpreview.dsl.net ?

**Comment by PromoFaux** [comment]
Unfortunately, a side effect of this change was that locally the pi will show as whatever the top result in `/etc/pihole/gravity.list` is. 

However it made sense at the time to move the `pi.hole` and `<whateveryourhostnameis>` from `gravity.list` as they're not really blocking domains.

If we come up with a solution, I'll try and remember to update this thread!

**Comment by tl87** [comment]
I've noticed the problem as well.
pihole error
To make things clear, this means that everytime I see "0000mps.webpreview.dsl.net", it's just the Pi-Hole, that is using the first line in /etc/pihole/gravity.list as it's hostname?

**Comment by DL6ER** [comment]
Indeed, I can confirm this also as follows:

<pre>
me@local ~ $ host pi.hole
pi.hole has address 1.2.3.4
pi.hole has IPv6 address ....
me@local ~ $ host 1.2.3.4
1.2.3.4.in-addr.arpa domain name pointer <b>0.r.msn.com</b>.
me@local ~ $ 
</pre>

@PromoFaux Could we just add `ip.of.pi.hole pi.hole` (and the same for IPv6) in the first line of `gravity.list`?

**Comment by PromoFaux** [comment]
@DL6ER 
We used to have it at the top of `gravity.list`, but when in `pihole disable` mode, you would no longer be able to resolve `pi.hole`.

The work around to that was to remove it from `gravity.list` and add it into `01-pihole.conf`

@tl87 that's correct, it doesn't matter what the first line is, it will return that name.

@pi-hole/gravity, is it overkill to have two entries for `pi.hole` ? One at the top of `gravity.list` for reasons mentioned in the above two comments, and one in `01-pihole.conf` for the purpose of still being able to resolve it when `pihole disable` mode is on.

**Comment by Mcat12** [comment]
As long as it works, that sounds like a good idea. Only thing might be that pinging the Pi-hole while it's disabled would have a different hostname than when it's enabled. So maybe a better idea would be to create a small list with only hostname/`pi.hole` information and load that list before gravity.list? So basically instead of setting the information in the dnsmasq config we link to a small list with the same information. In that list we could optionally also implement the custom local domain names, if we want to do that.

**Comment by PromoFaux** [comment]
so `hostnames.list` and `gravity.list` and have two `addn-hosts` lines?

**Comment by Mcat12** [comment]
Ya, then the gravity count wouldn't be inflated by `pi.hole` and other unblocked hosts.

**Comment by PromoFaux** [comment]
OK, let's have a play and see what happens...

**Comment by PromoFaux** [comment]
Yep, that works. I'll stick in a pull request.

**Comment by PromoFaux** [comment]
@jcandresen @tl87 your concerns should be resolved in the next release

**Comment by tl87** [comment]
@PromoFaux much much appreciated :-)

**Pull request merged**
