### PR TITLE
Debug Updates

### PR DESCRIPTION
**Pull request by dschaper**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

- [x] 10 (very familiar)

---
Modify debug process for less vebosity. And fix the IPv6 gateway bug.

### CODE REVIEW

**Comment by brontide** [comment]
While you are in there, why not zap that systemctl.  

```
		( systemctl -l status "${i}" || system "${i}" status ) >> "${DEBUG_LOG}" 
```

**Comment by dschaper** [comment]
Thanks, I'll get to that...

**Comment by brontide** [comment]
I just tried it.. helps if I get the right commands.  Here is what I ended up with and the debug output.

```
                systemctl -l status "${i}" 2>/dev/null || service "${i}" status 2>/dev/null  >> "${DEBUG_LOG}"
```

snippit from debug

```
#######################################
########### Processes Check ###########
#######################################

lighttpd processes status:
lighttpd (pid  1571) is running...

dnsmasq processes status:
dnsmasq (pid  1658) is running...
```

**Comment by dschaper** [comment]
Thanks, the output is helpful for formatting purposes.

**Comment by dschaper** [comment]
Can I get some sanity checks before I get too deep down the rabbit hole on this now-rewrite?

**Comment by dschaper** [comment]
Approved for merge at this stage, please keep open for further development.

**Comment by dschaper** [comment]
Approved

**Comment by brontide** [comment]
Sorry for the late reply, I'm running it now against debian8-sysvinit and debian sid.  Will you get the uploads automatically?

**Comment by dschaper** [comment]
Yes, I'll check the Debug web and see the same thing you would see in `/var/log/pihole_debug.log`. It's a partial completion, but enough to get into the release and be further developed until the Array approach works or doesn't work.

**Comment by dschaper** [comment]
And no apologies needed.

**Comment by PromoFaux** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/pi-hole/pi-hole/pull-request/857/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=pi-hole/pi-hole)

**Pull request merged**
