### PR TITLE
Update webpage.sh to allow remove of DHCP-Lease

### PR DESCRIPTION
**Pull request by CBrosius**
Enable Backend to remove DHCP-Lease-Entry from /etc/pihole/dhcp.leases

**By submitting this pull request, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
The current GUI does not allow to remove DHCP-Leases from /etc/pihole/dhcp.leases
This is the first step to make such a feature possible. The core will be able to remove DHCP-Leases via an added commandline-parameter.
The next step is to expand the Admin-GUI to allow removing Leases from the Web-Management like already implemented for Static-DHCP-Entries.
This part will be a PR in AdminLTE-Repository

**How does this PR accomplish the above?:**
The existing function RemoveDHCPStaticAddress() is copied and rewritten to RemoveDHCPLeaseAddress()
The existing commandline parameter 'removestaticdhcp' is copied and rewritten to 'removedhcplease'

**What documentation changes (if any) are needed to support this PR?:**
Commandline-parameter can be added to https://docs.pi-hole.net/core/pihole-command/
Syntax is the same as for 'removestaticdhcp' but this one is missing at the moment, too.

### CODE REVIEW

**Comment by CBrosius** [comment]
Sorry for not integrating the Sign-Off in the first commit. It´s my first PR and I have a lot to learn :oP

**Comment by PromoFaux** [comment]
Oh... crap, just noticed (was on mobile before), you've based the changes on the `master` branch, where as we require them to be based on `development`. Especially important in this case because there is a lot more going on under the hood with `FTL` in development.

Either you can rebase this PR on the `development` branch, or just start again. Somtimes I find the latter easier.. still not got my head around rebasing!

**Comment by CBrosius** [comment]
It is a very small change, so I can start again without problems.
Sorry for the inconvenience.
Regards,
Christian...

**Comment by PromoFaux** [comment]
Look forward to seeing the next PR :)

**Pull request closed without merging**
