### PR TITLE
Update basic-install.sh

### LINKED ISSUE #602: CHIP computer PiHole install script not detecting / FS
##### Expected Behaviour:
`existingFreeBytes=$(df -k / 2>&1 | awk '{print $4}' | head -2 | tail -1)`
`3206688`
##### Actual Behaviour:
`existingFreeBytes=$(df -lk / 2>&1 | awk '{print $4}' | head -2 | tail -1)`
`systems`
##### Steps to reproduce this issue:
Install Pi-hole on CHIP computer

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/36499266-chip-computer-pihole-install-script-not-detecting-fs?utm_campaign=plugin&utm_content=tracker%2F3011939&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F3011939&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by CDeeRON**
Fixes #602 

Changes proposed in this pull request:

`existingFreeBytes=$(df -k / 2>&1 | awk '{print $4}' | head -2 | tail -1)`

@pi-hole/gravity

Fixes #602

### CODE REVIEW

**Comment by Mcat12** [comment]
O.o when did I put "in progress" on these?

**Comment by PromoFaux** [comment]
@CDeeRON can you rebase/update from the development branch, please? Thanks

**Comment by CDeeRON** [comment]
Can you give me a quick reminder on rebase? or would it be quicker for delete my fork and resubmit the PR?

**Comment by dschaper** [comment]
You should be able to go to your local branch and run git fetch, then push your branch again. There have been changes to the development branch since you made the initial PR and those need to be reflected in your PR now.

**Comment by CDeeRON** [comment]
will try this again...lol

**Pull request closed without merging**
