### PR TITLE
Add optional health check to Pi-hole databases in debug script

### PR DESCRIPTION
**Pull request by yubiuser**
- **What does this PR aim to accomplish?:**

1. Add permission info about `/etc/pihole/pihole-FTL.db` to debug script
2. Add an optional database health check to debug script (check for `integrity` and `foreign_keys`) - available via `pihole -d -c` or `pihole -d --check_database`
3. Fix health check in gravity script during "automatic repair" (added by https://github.com/pi-hole/pi-hole/pull/4288) to account for different output:
    `PRAGMA integrity_check` outputs `ok` in case of no errors or a table with the errors found (https://www.sqlite.org/pragma.html#pragma_integrity_check)
`PRAGMA foreign_key_check` does not output anything if no error are present or a table with the key errors (https://www.sqlite.org/pragma.html#pragma_foreign_key_check)
___

Bildschirmfoto zu 2022-05-29 09-37-05
Bildschirmfoto zu 2022-05-29 09-48-38

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
5. I have commented my proposed changes within the code and I have tested my changes.
6. I am willing to help maintain this change if there are issues with it later.
7. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
8. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
[x] I have read the above and my PR is ready for review. _Check this box to confirm_

### CODE REVIEW

**Comment by DL6ER** [comment]
Have you measured how much extra time the `PRAGMA integrity_check` needs on a full database (365 days) on a low-end device such as a Raspberry Pi 1B+ (which is still in use quite a bit according to the Github FTL download statistics)?

I know that this is a pretty time-consuming task as it has to read and analyze every byte of the database and basically recompute all indices in order to check the stored ones for correctness. I recall vaguely that we looked at adding this check to the debug process some time ago (think in terms of "some to several years ago") but refrained from doing this for some reason I don't recall (but which may have been runtime impact).

A quick test on my small `x86_64` Pi-hole (AMD Turion(tm) II Neo N54L Dual-Core - because compiling FTL on a Raspberry several times a day isn't fun) reveals that even here it takes quite some time to finish:
```
$ time sqlite3 /etc/pihole/pihole-FTL.db "PRAGMA integrity_check;"
ok

real    0m25,613s
user    0m14,202s
sys     0m4,459s
```
This database is worth 660 MB, resides on a fast SSD and stores only 3 months of data. All this suggests it may take much longer on Raspberry Pi devices. Extrapolating this to 12 months already suggests 2 minutes runtime on the comparably fast hardware.

**Comment by yubiuser** [comment]
No I haven't tested this - I don't have a Pi 1 nor a big long-term database (got deleted somehow while testing). I can add a note that checking this can take several minutes. As this is not something users should run regularly I think it is acceptable to wait a few minutes (when they know they need to wait) . 

Can you please check how much time `PRAGMA quick_check` takes for you?

**Comment by dschaper** [comment]
You can simulate a B+ on any Raspi hardware:

>Edit /boot/cmdline.txt and add maxcpus=N
>
>Where N is in range 1 to 4.

Max CPU of 1 will give you a single core.

**Comment by rdwebdesign** [comment]
I added these changes to my pi-hole almost a month ago and everything is working fine.

image

**Comment by rdwebdesign** [comment]
**Test results:**
Since I don't have a Raspberry Pi1, a Raspberry Pi2, or a Raspberry Pi Zero to test, I tested in a Raspberry Pi4B, using docker "[resource constraints](https://docs.docker.com/config/containers/resource_constraints/)" to simulate a slower machine.

I limited the memory to 512MB and limited cpu to 0.25 (out of 4). 
I'm not sure how a real Raspberry Pi Zero will work and I'm not sure if this config is equivalent to any real hardware, but I think it's good enough for a initial comparison.

**Note:** I just measure the time to complete the "integrity check" part, not the entire log run. The database file size is 273MB, on a SD card.

| # | Hardware | Mem | CPUs | Check | Time |
|---|---|---|---|---|---|
| 1 | Pi 4B - no restrictions | 8GB | 4 | PRAGMA integrity_check | around **10 seconds** |
| 2 | Pi 4B - restricted via docker | 512MB | 0.25 | PRAGMA integrity_check | around **64 seconds** |
| 3 | Pi 4B - restricted via docker | 512MB | 0.25 | PRAGMA **quick_check** | around **30 seconds** |

**Comment by PromoFaux** [comment]
```
pi@raspberrypi:~ $ cat /proc/device-tree/model
Raspberry Pi 2 Model B Rev 1.1

pi@raspberrypi:~ $ time sqlite3 /etc/pihole/pihole-FTL.db "PRAGMA integrity_check;"
ok

real    0m30.341s
user    0m28.741s
sys     0m1.590s

```

**Comment by yubiuser** [comment]
Force pushed after rebased on latest development.

**Comment by dschaper** [comment]
> Force pushed after rebased on latest development.

What pull strategy are you using for `git?

I have `pull.rebase true` to keep those merge commits out. Or you can use the Button here and select `rebase` instead of `merge` to bring in the changes from the target branch.

**Comment by yubiuser** [comment]
I changed to `PRAGMA quick_check` as it is 50% faster and should cover the majority of errors.
https://www.sqlite.org/pragma.html#pragma_quick_check

**Comment by MichaIng** [comment]
A single cored RPi 4 or even 2 is not RPi 1 😉. I have an RPi Zero (same SoC) which I can underclock to 700 MHz to test the worst case. But someone needs to send me a database (or a script to create a large dummy). Especially when stored in SD card, I guess it can take up to hours 🤔.

**Comment by yubiuser** [comment]
Thanks MichaIng.

This worked for me:
```
INSERT INTO query_storage
    WITH RECURSIVE
      cnt( id, timestamp, type, status, domain, client, forward, additional_info, reply_type, reply_time, dnssec) AS (
      VALUES(1 , random(), random(), random(), random(), random(), random(), random(), random(), random(), random()) UNION ALL 
      SELECT id+1,random(),random(), random(), random(), random(), random(), random(), random(), random(), random() FROM cnt WHERE ID<100000)
    select * from cnt;
```

From https://stackoverflow.com/a/28139886

**Comment by dschaper** [comment]
Better test



```bash
pi@raspberrypi:/etc/pihole $ ls -lah pihole-FTL.db
-rw-r--r-- 1 pi pi 795M Jul  6 14:05 pihole-FTL.db

pi@raspberrypi:/etc/pihole $ time pihole-FTL sqlite3 pihole-FTL.db "PRAGMA quick_check;"
*** in database main ***
On tree page 202986 cell 0: invalid page number 203321
Error: stepping, database disk image is malformed (11)
```
real    4m13.256s
user    1m0.000s
sys     0m43.561s

**Comment by yubiuser** [comment]
Because of the time it takes on low-end hardware to run even the `quick_check` I made the function optional to not run on every call. Users can use `pihole -d -c` or `pihole -d --check_database` to only run the (deep) database check.

**Review by rdwebdesign — DISMISSED** [review]
Approving (unless you think we need to send more info with the database check log).

**Comment by rdwebdesign** [comment]
Question (more like a  suggestion):

Why don't we just add:
```sh
# if users want to check database integrity
if [[ "${CHECK_DATABASE}" = true ]]; then
    check_database_integrity
fi
```
after [this line](https://github.com/pi-hole/pi-hole/pull/4745/files#diff-8e13fa9927aabae5439f4ae9d8736f56ab9220296dd931a69cab1e97830a63e3R1524) (and remove the `if` [here](https://github.com/pi-hole/pi-hole/pull/4745/files#diff-8e13fa9927aabae5439f4ae9d8736f56ab9220296dd931a69cab1e97830a63e3R1493-R1502))?

It will generate a complete debug log.
If we ask an user to run this option, we won't need to look into 2 different logs.

**Comment by yubiuser** [comment]
I've included the database check in the normal debug run, triggered when `CHECK_DATABASE=true`.

Squashed all commits.

**Comment by yubiuser** [comment]
```
pihole -d

*** [ DIAGNOSING ]: Pi-hole FTL Query Database
-rw-rw-r-- 1 pihole pihole 71M Jul 10 13:55 /etc/pihole/pihole-FTL.db

*** [ DIAGNOSING ]: Gravity Database
-rw-rw-r-- 1 pihole pihole 93M Jul 10 13:53 /etc/pihole/gravity.db

*** [ DIAGNOSING ]: Info table

```

```
pihole -d -c

*** [ DIAGNOSING ]: Pi-hole FTL Query Database
-rw-rw-r-- 1 pihole pihole 71M Jul 10 13:55 /etc/pihole/pihole-FTL.db
[i] Checking integrity of /etc/pihole/pihole-FTL.db ... (this can take several minutes)
[✓] Integrity of /etc/pihole/pihole-FTL.db intact
[i] Checking foreign key constraints of /etc/pihole/pihole-FTL.db ... (this can take several minutes)
[✓] No foreign key errors in /etc/pihole/pihole-FTL.db

*** [ DIAGNOSING ]: Gravity Database
-rw-rw-r-- 1 pihole pihole 93M Jul 10 13:53 /etc/pihole/gravity.db
[i] Checking integrity of /etc/pihole/pihole-FTL.db ... (this can take several minutes)
[✓] Integrity of /etc/pihole/pihole-FTL.db intact
[i] Checking foreign key constraints of /etc/pihole/pihole-FTL.db ... (this can take several minutes)
[✓] No foreign key errors in /etc/pihole/pihole-FTL.db

*** [ DIAGNOSING ]: Info table

```

**Comment by rdwebdesign** [comment]
I tested the new version and it's working nicely.

**Review by rdwebdesign — APPROVED** [review]

**Review by rdwebdesign — APPROVED** [review]

**Pull request merged**
