### PR TITLE
Fix colour tail for use with new blocking methods

### PR DESCRIPTION
**Pull request by WaLLy3K**
**By submitting this pull request, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Resolves issue #2330 by including `NXDOMAIN`, `0.0.0.0` and `::`.

### CODE REVIEW

**Comment by WaLLy3K** [comment]
Instead of `<unknown>`, I feel you should be seeing `/etc/pihole/black.list` as per the following:

untitled

**Comment by WaLLy3K** [comment]
Regex blacklisting probably shouldn't be replying as `<unknown>`, but rather `/etc/pihole/regex.list`. It's easy enough to account for either of these, but it does seem like a bug.

**Comment by Mcat12** [comment]
@DL6ER Is it possible to use the regex file path instead of `<unknown>` in the log?

**Comment by DL6ER** [comment]
I'm fully aware of this issues. It is caused because we don't mess around with `dnsmasq`'s own logging. Let me give some further details here:
The issue is here that we inject domains that are queried and do match a filter into `dnsmasq`'s cache as manually configured. However, as it is not tied to any `addn-hosts=<file>` option of `dnsmasq`, there is no name available for it. One solution is to leave it like it is now. The other solution would be to import an (empty) file just for establishing a filename we can use. I think the latter is overkill and that's why I haven't done it.

I will, nevertheless, look at this again in the next few days and maybe I can spark a new idea how to get this done without modifying `dnsmasq`'s logging routine.

**Comment by DL6ER** [comment]
@Mcat12 @WaLLy3K https://github.com/pi-hole/FTL/pull/350

**Pull request merged**
