### PR TITLE
Link to the admin panel on the splash page.

### PR DESCRIPTION
**Pull request by theLMGN**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*
Add a link to the admin page on the splash page

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*
Adding a <a> to the string

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*
None.

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

Signed-off-by: Leo Nesfield <youcanputanythingyouwanthere@thelmgn.com>

### CODE REVIEW

**Comment by theLMGN** [comment]
@Mcat12 This is on the splash page, 
image

**Comment by Mcat12** [comment]
Ok, then we may merge it after the next release is merged (#2055)

**Comment by Mcat12** [comment]
@theLMGN since you didn't sign off your commit, could you add a signed off by line to the PR?
https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project

**Comment by theLMGN** [comment]
@Mcat12 Would I just add that to the end of the PR description like I have done?

**Comment by jacobsalmela** [comment]
@dflamand please contact me directly for a special thank you for contributing to our repo.

**Pull request merged**
