### PR TITLE
Fedora 33 Support

### PR DESCRIPTION
**Pull request by bcambl**
**By submitting this pull request, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**
Installation script complete successfully on Fedora 33

**How does this PR accomplish the above?:**
Sysconfig network scripts are absent on pure NetworkManager configuration found with the release of Fedora 33.
The `setIFCFG` function performs a `grep` for a static IP address then generates a new configuration file if not found. Once generated, the configuration file is then loaded via `nmcli` to configure NetworkManager. 

**What documentation changes (if any) are needed to support this PR?:**
Supported operating systems list should be updated to have Fedora 33 added and Fedora 31 removed.

### CODE REVIEW

**Comment by bcambl** [comment]
The should be completed prior to these changes being released:
- [ ] supported os documentation requires updates (add fedora 33 and remove fedora 31)
- [ ] ci containers should be updated (add fedora 33 and remove fedora 31)
- [ ] supported os dns records require updates (add fedora 33 and remove fedora 31)

**Comment by bcambl** [comment]
expected failure due to dns txt.
```
[gw1] [ 77%] PASSED test_automated_install.py::test_os_check_fails[test_container] 
[gw1] [ 96%] FAILED test_automated_install.py::test_os_check_passes[test_container] 
```

**Comment by bcambl** [comment]
Fedora 31 is EOL as of 2020-11-24 and can be removed from versions DNS at any time.  
Fedora 33 should not be added until this these changes are in a release version.

**Comment by secret223** [comment]
The game was

**Review by secret223 — APPROVED** [review]

**Comment by secret223** [comment]
Hi there is your number for your

**Comment by bcambl** [comment]
Fedora 33 is test failing as expected as per checklist above (https://github.com/pi-hole/pi-hole/pull/4004#issuecomment-763349515)

```
[bcambl@fedora pi-hole]$ dig +short -t txt versions.pi-hole.net @ns1.pi-hole.net
"Raspbian=9,10 Ubuntu=16,18,20 Debian=9,10 Fedora=31,32 CentOS=7,8"
[bcambl@fedora pi-hole]$ 
```

We will need to remove `31` and add `33` along with release `v5.3`.

**Review by PromoFaux — APPROVED** [review]

**Pull request merged**
