### PR TITLE
Additional upstream DNS choices

### PR DESCRIPTION
**Pull request by PromoFaux**
To be reviewd by @dschaper @jacobsalmela and @Mcat12

### CODE REVIEW

**Comment by dschaper** [comment]
What needs to be tested on this branch?

**Comment by PromoFaux** [comment]
Just that it works. I've tested it myself, but as there are a lot of changes in there, it would be good to get a confirmation from someone else on the team that it's working!

**Comment by jacobsalmela** [comment]
I'll try it out tonight and let you know.

**Comment by PromoFaux** [comment]
#### To Test:
- [ ] Verify selecting any of the new DNS providers actually sets the upstream after install
- [ ] Custom selection: 
 - [ ] verify that you cannot pass an invalid IP address.
 - [ ] verify that you get an "are you sure?" and the option to change your input
 - [ ] verify you can pass just one IP address

**Comment by jacobsalmela** [comment]
# My testing (will update as I go):
- [ ] Verify selecting any of the new DNS providers actually sets the upstream after install
- [x] Custom selection: 
 - [x] verify that you cannot pass an invalid IP address.
 - [x] verify that you get an "are you sure?" and the option to change your input
 - [ ] verify you can pass just one IP address

The only error I got was on line 403:

```
./test: line 403: [: ==: unary operator expected
./test: line 403: [: ==: unary operator expected
./test: line 403: [: ==: unary operator expected
```
This can usually be solved by using the double bracket notation `[[ $piholeDNS1 == $strInvalid ]]`

**Comment by PromoFaux** [comment]
Error fixed, ready for merge.

**Pull request merged**
