### PR TITLE
Add conditional forwarding options to webpage.sh 

### PR DESCRIPTION
**Pull request by ryanknapper**
Updated webpage.sh to include conditional forwarding options.

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#git-commit---signoff))

---

**What does this PR aim to accomplish?:**

This update writes conditional forwarding settings gathered from settings.php to setupVars.conf and 01-pihole.conf to allow for Pi-hole to resolve internal DNS hostnames.

**How does this PR accomplish the above?:**

Relevant data is entered via settings.php and submitted through savesettings.php

**What documentation changes (if any) are needed to support this PR?:**

None.

Signed-off-by: Ryan Knapper <ryanknapper@gmail.com>

### CODE REVIEW

**Comment by dschaper** [comment]
https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project Does that help any with the DCO issues?

**Comment by ryanknapper** [comment]
I’m only using Github from the web-interface.  Does pasting it the text suffice?

**Comment by dschaper** [comment]
It can, but you checked all the boxes for the template so we can just let this one go.

**Comment by jacobsalmela** [comment]
@ryanknapper Please contact me via email for a special thank you for your contribution to our project.

**Pull request merged**
