### PR TITLE
Move contributer file

### PR DESCRIPTION
**Pull request by Mcat12**
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**By submitting this pull request, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

- [ ] 1 (very unfamiliar)
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [X] 10 (very familiar)

---

This will make the contributor's guide more visible to a user and fixes the link in the PR template.

### CODE REVIEW

**Comment by dschaper** [comment]
:+1:

**Comment by dschaper** [comment]
Although this should go through development, so we don't end up with out of sync branches....

**Comment by PromoFaux** [comment]
Approved

**Comment by PromoFaux** [comment]
Admin Crimes

**Comment by dschaper** [comment]
#AdamCrimes

**Pull request merged**
