### PR TITLE
Update pihole locahost probe for DNS status

### PR DESCRIPTION
**Pull request by Razvici**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
Some users are changing /etc/hosts to have 127.0.0.1 to translate into something else rather than localhost.

Because this piece of code looks for "localhost" in order to display the status of the DNS server, it will never find if it's changed in /etc/hosts
image

**How does this PR accomplish the above?:**
127.0.0.1 will always be the loopback and this change should prevent any errors when querying the status of the DNS server via the Web  Interface

**What documentation changes (if any) are needed to support this PR?:**
None

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by DL6ER** [comment]
Approved this, although I'm still highly suspicious if one should change `/etc/hosts` such that `localhost` cannot be found any longer. I'm not sure how other software will like not being able to resolve `localhost`.

**Comment by PromoFaux** [comment]
@Razvici, it's OK this time, but just for future reference, can you please ensure that all changes are based on the `development` branch. And not, as in this case, based on `master` to be merged into `development`

Cheers!

**Comment by Razvici** [comment]
@DL6ER I agree and totally understand this aspect (as I already statded on discourse) however this only does improve pihole. It prevents people that have that change in /etc/hosts from asking questions on the forum. As for the pihole functionality, i think of this as an improvement (for the tinkerers out there that might poke around with /etc/hosts). Thak you for approving. 

@PromoFaux I thought i cloned the dev folder and edited them there. And then merged my master (cloned Development folder) to pi-hole development.

**Comment by Mcat12** [comment]
You just need to checkout the development branch and make your changes (optimally making a branch off of development as well)

**Pull request merged**
