### PR TITLE
Update tests

### PR DESCRIPTION
**Pull request by PromoFaux**
**By submitting this pull request, I confirm the following (please check boxes, eg [X])Failure to fill the template will close your PR:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

- [x] 10 (very familiar)

---

PR to support : #1441

Addresses tests I broke in #1437 

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by PromoFaux** [comment]
@dschaper , what do you think? Too hack?

**Comment by dschaper** [comment]
It looks a little extreme. The one test will pass no matter what and the others are gone. I'm concerned that people won't see the announcements for the flag and will lose data. But I'm good with the flag, just need more tests to check with and without flags to make sure things are covered. Jacob mentioned some concerns too, I'll tag him @jacobsalmela too...

**Comment by PromoFaux** [comment]
>Hang on a minute lads, I have an idea.

image

**Comment by PromoFaux** [comment]
closed by #1440

**Comment by jacobsalmela** [comment]
Thanks for doing this.

**Pull request closed without merging**
