### PR TITLE
Enable support for /etc/pihole/setupVars.conf in gravity

### PR DESCRIPTION
**Pull request by PromoFaux**
@pi-hole/gravity

### CODE REVIEW

**Comment by PromoFaux** [comment]
bump

**Comment by jacobsalmela** [comment]
Approved

**Comment by PromoFaux** [comment]
Approved

**Comment by dschaper** [comment]
:+1:

**Comment by jacobsalmela** [comment]
Approved

**Comment by PromoFaux** [comment]
:shipit:

**Comment by PromoFaux** [comment]
👍 


(Let's review the pull approve yaml!)

**Comment by dschaper** [comment]
:+1:

**Comment by jacobsalmela** [comment]
Approved

**Pull request merged**
