### PR TITLE
Fix formatting, use consistent style, add comments

### PR DESCRIPTION
**Pull request by ChadBHowell**
Fix formatting, use consistent style, add comments.

### CODE REVIEW

**Comment by ChadBHowell** [comment]
If need be, I can go over the formatting and style after the next major commit.  Also, is this needed anymore?
```bash
# Is this if statement used anymore?
if [ -f "/etc/dnsmasq.d/01-pihole.conf" ]; then
	if [ -f "/etc/dnsmasq.d/01-pihole.conf" ]; then
		#Likely an existing install
  		upgrade=true
  	else
		upgrade=false
fi
```
I could not find $upgrade referenced anywhere in basic-install.sh

**Comment by PromoFaux** [comment]
It's not currently used, I put it in a placeholder for a future merge. It can be commented out for now, but it is not doing any harm!

**Comment by PromoFaux** [comment]
You'll also find there was a hotfix pushed for the install script, and checkForDependencies() has been altered... Other than that, looks OK!

**Comment by ChadBHowell** [comment]
Rebased after latest merge.

**Comment by dschaper** [comment]
I'm going to merge this to an alpha branch real quick just to test out, it doesn't look like things are functionally changed much, just some typographicals.

**Comment by dschaper** [comment]
Alpha Branch with PR #259 Please push any further changes to that branch. Thanks!

**Pull request closed without merging**
