### PR TITLE
Remove development branch from PullApprove

### PR DESCRIPTION
**Pull request by dschaper**
**By submitting this pull request, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [ ] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#git-commit---signoff))

---

**What does this PR aim to accomplish?:**

Remove PullApprove from development branch and update team name for master approval.

### CODE REVIEW

**Comment by dschaper** [comment]
Looks like PullApprove now has DCO ability, as well as integration in to GitHub code approvals. May want to add those in if wanted.

**Comment by Mcat12** [comment]
PullApprove doesn't seem to like this PR:
screenshot from 2018-01-16 21-32-19

**Comment by dschaper** [comment]
Yeah, I'll take a look at that, it's valid yaml so it's something in the DSL that's off. It's not a big pull anyways, we already disabled it on development.

**Comment by dschaper** [comment]
PA will be leaving us.

**Pull request closed without merging**
