### PR TITLE
Added check for universe repo on ubuntu bionic.

### PR DESCRIPTION
**Pull request by kefnab**
Added universe repo check for Ubuntu bionic.

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Commit signed.

---
**What does this PR aim to accomplish?:**
Closes pi-hole/pi-hole#2447

**How does this PR accomplish the above?:**
As noted in the issue documentation, Ubuntu Server 18.04.1 LTS Live installer no longer includes *universe* as an enabled repo.  Upgrades from 18.04 were unaffected, but with the newer installer for Ubuntu Bionic - pihole was unable to pull packages for *dialog* or *dhcpcd5*.

While there may be a better place to position my code, I grouped it in the area where __apt__ has already been identified as the package manager.  From there, I check to see if /etc/apt/sources.list contains *bionic* __without__ *universe*.  If so, I add universe to the repos.  If not, the code does nothing.

I attempted to mimic the code style already present for modifying `EPEL_PKG="epel-release"` in the yum repos.

__I tested my code__ by making this change AND updating the curl reflection to my own GitHub raw source code.  On a freshly installed 18.04.1 LTS Server, the test code was successful.

**What documentation changes (if any) are needed to support this PR?:**
It is not clear if documentation changes are needed.  A backup of the repo sources.list file is conducted for recovery if needed.

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by dschaper** [comment]
Thanks for the submission. One concern I have is in enabling Universe without user permission or consent. I agree that this is needed currently but I'd like to see something that asks/requires a yes to continue.

**Comment by kefnab** [comment]
>           Thanks for the submission. One concern I have is in enabling Universe without user permission or consent. I agree that this is needed currently but I'd like to see something that asks/requires a yes to continue.

@dschaper I had considered that, but I patterned my submission off of what is already happening for CentOS:
```bash
# on CentOS we need to add the EPEL repository to gain access to Fedora packages
EPEL_PKG="epel-release"
rpm -q ${EPEL_PKG} &> /dev/null || rc=$?
if [[ $rc -ne 0 ]]; then
    printf "  %b Enabling EPEL package repository (https://fedoraproject.org/wiki/EPEL)\\n" "${INFO}"
    "${PKG_INSTALL[@]}" ${EPEL_PKG} &> /dev/null
    printf "  %b Installed %s\\n" "${TICK}" "${EPEL_PKG}"
fi
```
Additionally, dependent packages are installed without prompting.  But if you are sure, I can prompt the user prior to enabling the Universe repo on Ubuntu Bionic - I just wanted to confirm because that doesn't seem to match script behavior elsewhere.

**Comment by dschaper** [comment]
The install script is in the process of being updated to not assume as much as it used to. Moving towards https://github.com/pi-hole/pi-hole/blob/release/v4.1/automated%20install/basic-install.sh#L297 with verification.

**Comment by kefnab** [comment]
Ok, will amend.  Thank you.

**Comment by kefnab** [comment]
Ok - amended and I used your v4.1 example as a template.

**Comment by jacobsalmela** [comment]
@kefnab please contact me directly for a special thank you for contributing to our repo!

**Pull request merged**
