### PR TITLE
Allow custom DNS servers to have a custom port.

### PR DESCRIPTION
**Pull request by ryt51V**
Changes proposed in this pull request:
- If the user chooses a custom DNS server, allow them to specify a custom port in dnsmasq conf file syntax (e.g. 192.168.2.0#5353).  This is particularly useful for forwarders running on localhost on a different port (e.g. 127.0.0.1#40).

@pihole/gravity

### CODE REVIEW

**Comment by PromoFaux** [comment]
@ryt51V Thanks for your submission! Do you have any examples of DNS servers that use an alternative port, to make this easier to test?

**Comment by ryt51V** [comment]
Personally I use this so that I can have dnsmasq forward to non-caching servers running on the same host, for example dnscrypt-proxy running on 127.0.0.1:\<someport\>

That said, it looks like OpenDNS (208.67.222.222 & 208.67.220.220) respond on ports 443 and 5353 and so can be used for testing.

```
> nslookup -port=5353 example.com 208.67.222.222
Server:         208.67.222.222
Address:        208.67.222.222#5353

Non-authoritative answer:
Name:   example.com
Address: 93.184.216.34

> nslookup -port=443 example.com 208.67.220.220
Server:         208.67.220.220
Address:        208.67.220.220#443

Non-authoritative answer:
Name:   example.com
Address: 93.184.216.34
```

**Comment by dschaper** [comment]
Thanks for the tip about the secondary port configuration for OpenDNS... And yes, this would make it easier to get DNScrypt proxy as the upstream... I'll see if I can remember how to bring this PR into a branch so we can test it... (I know it's in the Git Book, but I can't remember offhand which section, it's buried somewhere in our Slack logs, lol...)

**Comment by Mcat12** [comment]
Here you go: `git remote add -t <branch> <name> <url>`

**Comment by dschaper** [comment]
Thank you, thank you!

**Comment by Mcat12** [comment]
Is this ready for merge?

**Comment by PromoFaux** [comment]
Ping! @dschaper Did you test this?

**Comment by dschaper** [comment]
Just getting back to this now, as I'm battling with resolvconf and /etc/resolv.conf for port assignments. Shouldn't be a problem, with `dnsmasq` listening on 53, and forwarding to whatever stack you want as the resolver. @ryt51V I totally dropped the ball on this one, so this one's my fault.

**Comment by jacobsalmela** [comment]
@dschaper did you make any headway?  Just looking through some of these old PRs to see if there is anything worth keeping or closing.

**Comment by dschaper** [comment]
I let it go since `/etc/resolv.conf` won't do ports unless you're on BSD. I'll take another look at it if this is something that's wanted.

**Comment by jacobsalmela** [comment]
It might be a bit out of scope right now as we try to scale.  I'll close and we can revisit if needed.

**Pull request closed without merging**
