### PR TITLE
Free Disk Space check standardization

### PR DESCRIPTION
**Pull request by Fourdee**
Fixes #[issue number] .
Improvement to https://github.com/pi-hole/pi-hole/issues/602

Changes proposed in this pull request:

+ Improve available free disk space check.

+ Option to override if the free disk space check is not a valid
integer.

@pi-hole/gravity

### CODE REVIEW

**Comment by Mcat12** [comment]
Approved. Looks good. :+1:

**Comment by PromoFaux** [comment]
Approved!

**Comment by dschaper** [comment]
Approved and merged.

**Comment by dschaper** [comment]
Changelog updated.

**Pull request merged**
