### PR TITLE
Do not pass whole environment for PIHOLE_SKIP_OS_CHECK=true

### PR DESCRIPTION
**Pull request by MichaIng**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/contributing/).

---
**What does this PR aim to accomplish?:**
With `sudo -E`, the whole environment is passed to the root shell, which is a potential security and/or privacy issue when command overrides/functions, PATH or private user info are passed.

**How does this PR accomplish the above?:**
To pass `PIHOLE_SKIP_OS_CHECK=true`, it can be passed alone to the bash/script call within the sudo session, so the `-E` flag can be omitted.

**What documentation changes (if any) are needed to support this PR?:**
There is an image which should be updated accordingly: https://github.com/pi-hole/docs/blob/master/docs/images/OSWarning.png
Actually, it should be possible to replace it with HTML `<pre>`/Markdown code fences instead of using an image. HTML tags can be used within Markdown code fences to apply the colors, if I'm not mistaken.

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by yubiuser** [comment]
The `sudo -E` was added during one of the commits of this PR: https://github.com/pi-hole/pi-hole/pull/3596
Not sure if @PromoFaux remembers why it was added.

**Comment by PromoFaux** [comment]
Because I googled something along the lines of "How to pass an environment variable into sudo session" and went with what worked. 😏

**Comment by MichaIng** [comment]
For passing it from the unprivileged session through `sudo` this is true, but since the variable is assigned statically here, and we call a bash session from within the sudo session, `-E` can be omitted, and IMO for mentioned security and privacy reasons it should be omitted whenever possible.

Other reasons are e.g.: #3527
This was done to assure that users who run the installer via `su` (instead of `sudo`) do not pass an incomplete PATH, where `/sbin` and `/usr/sbin` are missing. For this exact reason, `sudo` is anyway recommended by anyone I know, as it does not pass the environment by default like `su`. But with the `-E` flag, one introduces the same issues for `sudo`.

**Review by yubiuser — APPROVED** [review]
Please do not merge before a PR for the documentation exists. (Going to do this later)

**Comment by yubiuser** [comment]
https://github.com/pi-hole/docs/pull/689

**Pull request merged**
