### PR TITLE
Consistent Style in Bash

### PR DESCRIPTION
**Pull request by airencracken**
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**By submitting this pull request, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

- [x] 1 (very unfamiliar)

---
So it seems the bash here had about four or five different styles co-existing. I've tried to clean that up and make it look similar everywhere. Even if someone doesn't like the particular style I've picked (I tried to go with whatever seemed most common in the files already) it's easier to change now that it's all relatively the same. I suspect this was the result of a lot of copy/paste. ~~Going to hopefully work on another commit that pulls out some of the more common functions (like the spinner function) and puts them into a library that the respective scripts can just source.~~

**Edit: I'll do that in a separate pull request.

### CODE REVIEW

**Comment by dschaper** [comment]
Thanks! Let us know when the PR is ready for review, you can label it and we'll start the process...

**Comment by airencracken** [comment]
Looking at the file structure I'd have to make some changes to how you guys handle PATH to make it easy to source, so I'll hold off on that for now, this should be atomic as it stands. I'll try to pull out common functions in another PR.

**Comment by dschaper** [comment]
Engage

**Comment by PromoFaux** [comment]
Approved!

(Allready done the hard work of merging it into #814 )

**Comment by jacobsalmela** [comment]
This looks really nice (and much appreciated).  Just doing some more testing here before approving.

**Comment by jacobsalmela** [comment]
Not sure if it's specific to your branch or not, but I get this when running the debug log from [line 141](https://github.com/pi-hole/pi-hole/pull/831/files#diff-499b751268b08d94233fe28bd8001e56R141) in `debug.sh`:
```
::: Pinging default IPv6 gateway...
connect: Invalid argument
::: Pinging Internet via IPv6..
```
Looks like it can be easily fixed by appending `%eth0` or the interface name, after the IP address.  
```
ping6 -q -w 3 -c 3 -n fe80::21c:42ff:fe00:18%eth0 | tail -n3
```

**Comment by PromoFaux** [comment]
>Not sure if it's specific to your branch or not

Looks like this may be a pre-existing bug in debug.sh line 141 of this pull is identical to line 145 of debug.sh in development

**Comment by jacobsalmela** [comment]
Engage

**Pull request merged**
