### PR TITLE
New Default BlockList

### PR DESCRIPTION
**Pull request by drego85**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [ ] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [ ] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
Offer new users a better experience with updated BlockLists.

**How does this PR accomplish the above?:**
I believe it is time to delete old lists that are no longer maintained in favor of new ones.

In detail:

- Cameleon: last Update 2018-03-17;
- ZeusTracker: has been discontinued on Jul 8th, 2019;
- DisconTrack: last Update 2015-07-31;
- DisconAd: last Update 2016-03-09;
- HostsFile: last Update 2019-06-12 and it often contains false positives and is very similar to the StevenBlack list.

Some lists have not been updated for at least a year, we risk giving new users a negative experience.

For the new lists I preferred:

- AdAway: Updated Weekly to contrast Ads;
- SquidBlackList: Updated Weekly to contrast Ads and Malicious domains;
- PhishingArmy: Updated Daily to contrast Phishing;
- Daniel White: Updated Weekly to contrast Ads.

I personally use these lists with great satisfaction!

I believe that after a period of testing by the community they can be chosen as predefined lists.

**What documentation changes (if any) are needed to support this PR?:**
not needed

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by PromoFaux** [comment]
It's certainly an interesting suggestion, although we have had _some_ discussion internally about knocking the "default" lists back to just be the stevenblack list.

Some time back, we updated the wording of the installer to imply that the lists we ship with are by no means necessary, and that the user has the option to deselect any that they choose. Ultimately we're tying to distance ourselves from being the arbiters of _what_ Pi-hole blocks, more providing users with tools to make their own considered choices.

Personally I am still running the "default" lists on my install, and have not added any extras, and find the blocking experience to be adequate. But that is just my personal opinion. I'm sure others will chime in with theirs!

Thanks for the submission.

**Comment by drego85** [comment]
Thanks Adam for the answer.

I personally believe that keeping the lists out of date is wrong. Better a few lists but updated.

In my list I have entered PhishingArmy and SquidBlackList Malicious because they can replace or even improve the work done by ZeusTracker.

AdAway, Daniel White and SquidBlackList ADS are very similar lists to Steven's.

Steven's list is undoubtedly excellent!

I understand you difficulty as "arbriti" and impose predefined lists!

Perhaps it is a good idea to start only with Steve's list and allow the user subsequent additions.

**Comment by lordraiden** [comment]
https://github.com/justdomains/blocklists

adguard lists are pretty clean of FP's

**Comment by dschaper** [comment]
I'm a veto on this. If you want, remove an existing list when it's no longer updated. I'm not of the mind to be changing everything for the sake of change or a new personal favorite list. 

The suggestion of just one list is fine by me, I have no preference as to which one. If that is the route then please open a new PR and follow the template instructions, base on `development` and open the PR against that branch. Thanks!

**Comment by drego85** [comment]
Thanks Dan, sorry but I hadn't seen the development channel. I close this PR.

**Pull request closed without merging**
