### PR TITLE
Quickfix for CNAME responses of dig

### PR DESCRIPTION
**Pull request by ryrun**
Always return only the last line, which should always be an ip.

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [ ] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
Fix for #2863 

**How does this PR accomplish the above?:**
It filters the output of the dig command, so only the last line will be set to the variable.

**What documentation changes (if any) are needed to support this PR?:**
-

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/update-gravity-doesnt-work-for-lists-when-domain-is-on-blocked-list/22121/31

**Comment by dschaper** [comment]
The DCO error can be fixed with the instructions at https://github.com/pi-hole/pi-hole/pull/2864/checks?check_run_id=184878253

In order to fix the Travis errors you will need to base your changes on the `development` branch instead of `master` and then  edit the PR and change the base branch of the PR to `development` as well.

**Comment by ryrun** [comment]
I'm a git noob, sorry :D The best would be to close this one and create a new one, right? I changed the base of both, but there are now 2 commits in this pull ...

**Comment by dschaper** [comment]
No problem, go ahead and do a new PR, remember to sign off the commits as shows here: https://docs.pi-hole.net/guides/github/how-to-signoff/ and make sure your local changes are based off of the development branch and not master. If you need more information on that let us know and we can help guide you.

**Pull request closed without merging**
