### PR TITLE
Add host-record option

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 10

---

Implementation of a feature request on [Discourse](https://discourse.pi-hole.net/t/domain-redirect/1826/) .

Curent behavior: The Android OpenVPN client is not able to connect to the VPN server when the Android device is within the internal network.

```plain
pi@raspberrypi:~# pihole -a hostrecord home.mydomain.de 192.168.1.10
Setting host record for home.mydomain.de -> 192.168.1.10

pi@raspberrypi:~# grep 'home' /etc/dnsmasq.d/01-pihole.conf
host-record=home.mydomain.de,192.168.1.10
```
Afterwards: The Android OpenVPN client is able to connect to the VPN server and shows its internal IP (`192.168.1.10`).

---

This command is IPv6-aware. Use:

```plain
pi@raspberrypi:~# pihole -a hostrecord home.mydomain.de 192.168.1.10,2003:89:xxxx:xxxx::xxx
Setting host record for home.mydomain.de -> 192.168.1.10,2003:89:xxxx:xxxx::xxx
```

`dig aaaa home.mydomain.de` will return the IPv6 address on the corresponding device in the internal network. Note that should not be necessary when using the proper global scope IPv6 address.

---

It is also possible to remove the configuration by not specifying any host/IP:
```plain
pi@raspberrypi:~# pihole -a hostrecord
Removing host record

pi@raspberrypi:~# grep 'home' /etc/dnsmasq.d/01-pihole.conf
```

Result: The configuration has been removed. The OpenVPN server is, again, not able to connect.

---

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by jacobsalmela** [comment]
Approved

**Comment by cusco** [comment]
Just a question: this allows only one custom dns entrie??

**Comment by autumnwalker** [comment]
Wondering the same thing - can this be used to add multiple host records?

**Comment by mikegleasonjr** [comment]
@cusco @autumnwalker only one, just tested it 😢

**Comment by mikegleasonjr** [comment]
For those wondering how to add multiple entries, add your entries to `/etc/hosts` then `$ pihole restartdns`

**Comment by cusco** [comment]
What I did, in /etc/dnsmasq.conf I added a line:

conf-file=/etc/dnsmasq.more.conf

and in this file I added lines such as:
host-record=hostname.com,192.168.1.1

**Comment by cby016** [comment]
This feature is not very useful if it only works for one host entry. I went through and added about 10 entries and then tested and only the last one was working. When I checked the config files only the last one had been saved.

**Comment by cusco** [comment]
Exactly!!

I found a workaround but this is for dnsmasq only. No pihole interaction.

Include a extra configuration file with several lines.

**Comment by cby016** [comment]
Yeah I ended up doing this https://discourse.pi-hole.net/t/howto-using-pi-hole-as-lan-dns-server/533

**Comment by joshbgosh10592** [comment]
I'd really, really like the ability to add multiple host records... One reason is that I frequently call my Windows server something else, depending on what I'm working on at that moment (Apollo/media/share) and often forget that it's name is actually Apollo. I used to have a host record on my router's DNS to make it all point to the same IP.

Second reason is that for some reason, Pi-hole doesn't always resolve my hostnames. My MacBook Pro, for example, shows as the IP address only, and no client on my network can resolve to it. I want to be able to manually assign it.

**Comment by Mcat12** [comment]
Add extra records to `/etc/hosts`. Make sure you only have one DNS server sent to your clients. If you have other questions, make a new issue.

**Comment by mikegleasonjr** [comment]
I would remove the feature then to avoid confusion.

**Comment by DL6ER** [comment]
Well, @mikegleasonjr you can read in the original PR description for what users are using this feature. I know of at least five people using it exactly for this purpose (including me). Everything else should be done as @Mcat12 suggested: In early times, all name resolution was done by having up-to-date `hosts` files on the servers. As the Internet grew, the DNS service was introduced, eventually. Our DNS resolver (the current and the new one) both hand out all knowledge you specify in this one single place (the `/etc/hosts`) file and this is the place where any non-trivial configuration should be installed.

**Comment by xenithorb** [comment]
This option makes zero sense if it's only for one record

**Comment by gmask** [comment]
Yeah I don't understand, does anybody who needs a custom DNS entry for local IPs only need one?

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/can-i-use-pi-hole-dns-as-a-online-hosts-manager/25504/1

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/request-dns-rewrites-planned/27350/11

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/request-dns-rewrites-planned/27350/14

**Comment by DL6ER** [comment]
We're sorry guys, this feature got down-voted very often and we missed it. We'll remove it to avoid further confusion.
For users of this feature:
- We will not remove existing host records.
- The Custom DNS page is an adequate replacement. It can be accessed from the dashboard.
- If you cannot use the dashboard, please add your records to `/etc/pihole/custom.list` or `/etc/hosts` and run `pihole restartdns reload` afterwards.

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/request-dns-rewrites-planned/27350/18

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/request-dns-rewrites-planned/27350/23

**Comment by cusco** [comment]
> * n be accessed from th

We understand removing a feature that is not serving its purpose. But how about adding a feature that does? Just a custom hosts entry like you mentioned, but manageable on the web gui (and pihole cli)

**Comment by dschaper** [comment]
>     * The Custom DNS page is an adequate replacement. It can be accessed from the dashboard.

Screenshot_2020-05-02 Pi-hole Admin Console

**Comment by DL6ER** [comment]
And to add what @dschaper quoted,

> If you cannot use the dashboard, please add your records to /etc/pihole/custom.list or /etc/hosts and run pihole restartdns reload afterwards.

This is likely even much easier than having to remember the Pi-hole syntax for the same task and will always give you an overview of what is already there.

You'll be asked for the `sudo` password, but you'll also be asked for it when using the `pihole` command (and don't have passwordless `sudo` such as the user `pi` on Raspbian).

Conclusion: Everything is still available. On the dashboard it is even much improved.

**Comment by Anuskuss** [comment]
Late to the party but while I agree that Local DNS Records / `/etc/hosts` / `/etc/pihole/custom.list` are fine for job, it would be great to have the same flexability as white/blacklists but for redirects, mainly regex and groups. I personally have a niche but valid use case for this: I have two identical devices in my network and I'd like to prevent the first one from auto-updating itself. So I'll setup my Pi-hole to redirect to a custom "You're on the latest firmware" page while at the same time allowing the second device to be on the actual latest firmware. That is just not possible to achieve with only one Pi-hole right now.

**Pull request merged**
