### PR TITLE
Pi-Hole Core release v2.10

### PR DESCRIPTION
**Pull request by PromoFaux**
Been a while! Must be merged before web UI is merged, as there are features there that depend on changes that have been made here.

### CODE REVIEW

**Comment by PromoFaux** [comment]
@jacobsalmela @bcambl @elpatron68 @brontide Please sign the CLA. Many thanks!

**Comment by brontide** [comment]
Sorry, no.  I have an aversion to legalese.

**Comment by dschaper** [comment]
Are you okay with us using your code?

**Comment by brontide** [comment]
I wouldn't have pulled if I did.

**Comment by bcambl** [comment]
I just signed my contribution of a single `>`.

**Comment by dschaper** [comment]
It's a one time thing, you don't have to sign every time or sign every commit. Once is good enough for everything.

**Comment by dschaper** [comment]
Approved

**Comment by jacobsalmela** [comment]
Approved

**Comment by Mcat12** [comment]
Approved

**Comment by DL6ER** [comment]
Approved

**Pull request merged**
