### PR TITLE
Alpine

### PR DESCRIPTION
**Pull request by deftdawg**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [ ] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [ ] I have made only one major change in my proposed changes.
- [X ] I have commented my proposed changes within the code.
- [ ] I have tested my proposed changes, and have included unit tests where possible.
- [ ] I am willing to help maintain this change if there are issues with it later.
- [X ] I give this submission freely and claim no ownership.
- [ ] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**

This pull contains modifications needed to basic-install.sh to get it to work on Alpine Linux.

It also contains a wrapper script (Alpine doesn't have bash out of the box) that was used to make sure basic-install.sh and some of the other dependencies (such as a working pihole-FTL) would be installed.

I give it freely to the pihole project, please do what you will with it (I don't have an expectation that you will merge it as is, but hopefully it will be helpful as a basis for supporting Alpine)

**How does this PR accomplish the above?:**

With a list of dependencies needed to run on alpine and with some hacks to basic-install.sh to support missing alpine commands/busybox features.

**What documentation changes (if any) are needed to support this PR?:**

None.

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by DL6ER** [comment]
@deftdawg What is the status of your PR? Both @stickler-ci and @DCO requested changes.

**Comment by deftdawg** [comment]
@DL6ER I'm not sure what to do about @stickler-ci flagging line 286 (https://github.com/pi-hole/pi-hole/blame/74a5d3e929287eb3a06c51d38190025c813ecce8/automated%20install/basic-install.sh#L286), it's saying to add quotes to avoid splitting, but we actually **want** splitting...  This is the same way it's being done line 191 (https://github.com/pi-hole/pi-hole/blame/74a5d3e929287eb3a06c51d38190025c813ecce8/automated%20install/basic-install.sh#L191) which is not my work.

I'll have to look into the DCO thing.

**Comment by deftdawg** [comment]
@DL6ER added a shellcheck suppress for SC2206, squashed, and signed off the branch...  😄

**Comment by eisengrau** [comment]
Hello,

Is this functional as of now? It is possible to download and run this script on the latest Alpine distro and it should set up pi-hole?

**Comment by deftdawg** [comment]
@eisengrau should work, though it's not really tested.   I just got everything running and went to the admin page, I never actually tried running traffic through it.

You'd need to run through the installation in ``/automated install/alpine-install-wrapper.sh`` in the branch as it sets up Alpine to install pihole and build pihole-ftl.

**Comment by dschaper** [comment]
Alpine support should be in a package. Busybox compatibility is too much to do  in a script.

**Pull request closed without merging**
