### PR TITLE
Remove the ZeusTracker blocklist from the defaults

### LINKED ISSUE #2843: Dead default blocklist link
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

3

---
**Expected behaviour:**

Blocklist showing a list of hosts to block

**Actual behaviour:**

URL Shows ?php
echo "# ZeuS Tracker has been discontinued on Jul 8th, 2019";
exit();
?

**Steps to reproduce:**

Go to https://zeustracker.abuse.ch/byebye.php?download=domainblocklist

`{Steps of what you have done to fix this}`

Saw reddit post https://old.reddit.com/r/pihole/comments/ccfxom/one_of_default_blocklists_is_dead_another_outdated/

Checked URL https://zeustracker.abuse.ch/byebye.php?download=domainblocklist
 Site shows
?php
echo "# ZeuS Tracker has been discontinued on Jul 8th, 2019";
exit();
?

### PR DESCRIPTION
**Pull request by Mcat12**
**By submitting this pull request, I confirm the following:** 
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
---
**What does this PR aim to accomplish?:**
Fix #2843

**How does this PR accomplish the above?:**
It is no longer served and contained less than 400 domains, so it has been removed.

**What documentation changes (if any) are needed to support this PR?:**
None

### CODE REVIEW

**Comment by dschaper** [comment]
@jfb-pihole Did you have any thoughts on this?

**Comment by jfb-pihole** [comment]
Perhaps Wally3K may have a recommendation for a replacement list.

**Comment by Mcat12** [comment]
Tagging @WaLLy3K so he gets a notification.

**Comment by pheiduck** [comment]
ZeusTracker.: Server Down

Error 503 Backend unavailable, connection failed
Backend unavailable, connection failed

Guru Mediation:
Details: cache-fra19128-FRA 1566323403 1387466377

**Comment by dschaper** [comment]
Thanks, shouldn't affect anything, updating gravity will just skip the list.

**Comment by dschaper** [comment]
Seems like it's taking a really long time to pass the list. I'll work on a fix release today.

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-4-3-2-release-notes/23852/1

**Pull request merged**
