### PR TITLE
Change installScripts to use install

### PR DESCRIPTION
**Pull request by dschaper**
Fixes #INTERNAL .

Changes proposed in this pull request:

-  Use `install` for copying and creating files on systems.

@pi-hole/gravity

Use the install program instead of copying files and directories in installScripts function.

### CODE REVIEW

**Comment by dschaper** [comment]
:+1:

**Comment by Mcat12** [comment]
:shipit:

**Comment by jacobsalmela** [comment]
Approved

**Comment by dschaper** [comment]
Leaving branch, for further optimizations.

**Pull request merged**
