### PR TITLE
Update basic-install.sh

### LINKED ISSUE #251: Lighttpd appears not to start
I installed pi-hole tonight (Jan 26) and it is reporting info the pihole log and ads I used to see on some sites are thankfully no longer there. I thought I read that the latest version comes with everything to use the web admin. However, that page never opens. 

pi@raspberrypi:/var/log/lighttpd $ more error.log
2016-01-26 23:44:44: (log.c.164) server started
2016-01-26 23:45:52: (server.c.1558) server stopped by UID = 0 PID = 1
2016-01-27 01:02:38: (log.c.164) server started
2016-01-27 01:02:38: (mod_fastcgi.c.1112) the fastcgi-backend /usr/bin/php-cgi failed to start:
2016-01-27 01:02:38: (mod_fastcgi.c.1116) child exited with status 2 /usr/bin/php-cgi
2016-01-27 01:02:38: (mod_fastcgi.c.1119) If you're trying to run your app as a FastCGI backend, make sure you're using the FastCGI-enabled version.
If this is PHP on Gentoo, add 'fastcgi' to the USE flags.
2016-01-27 01:02:38: (mod_fastcgi.c.1406) [ERROR]: spawning fcgi failed.
2016-01-27 01:02:38: (server.c.1022) Configuration of plugins failed. Going down.
2016-01-27 01:06:41: (log.c.164) server started
2016-01-27 01:06:41: (mod_fastcgi.c.1112) the fastcgi-backend /usr/bin/php-cgi failed to start:
2016-01-27 01:06:41: (mod_fastcgi.c.1116) child exited with status 2 /usr/bin/php-cgi
2016-01-27 01:06:41: (mod_fastcgi.c.1119) If you're trying to run your app as a FastCGI backend, make sure you're using the FastCGI-enabled version.
If this is PHP on Gentoo, add 'fastcgi' to the USE flags.
2016-01-27 01:06:41: (mod_fastcgi.c.1406) [ERROR]: spawning fcgi failed.
2016-01-27 01:06:41: (server.c.1022) Configuration of plugins failed. Going down.

Is there something else I'm missing in the install/configuration to get this to work? I suppose it's probably a Raspian issue, but it appears pi-hole has made changes to lightpd.conf so I thought I'd start asking here first.

### PR DESCRIPTION
**Pull request by PromoFaux**
This PR is for any updates to `basic-install.sh` whilst we look at the issue surrounding #251 

This will fix #251, and various reports of the same thing on reddit.

### CODE REVIEW

**Comment by PromoFaux** [comment]
@dschaper 
To test:
Requires a fresh flash of SD card.
copy this install script to the `/home/pi` directory
run `bash basic-install.sh`

report back on the results!

**Comment by DonLexos** [comment]
I am prepping 2 new SD cards so I could test this if you like. Would it install master or dev banch?

**Comment by PromoFaux** [comment]
He @DonLexos It will install master branch, as before... To test run this on a FRESH install. DO NOT run `apt-get update`

`curl -L https://raw.githubusercontent.com/pi-hole/pi-hole/b8f48d1bce621fa136af96f2ea765b85780b924e/automated%20install/basic-install.sh | bash`

**Comment by DonLexos** [comment]
oh really, well we need to wait for that second SD card, since I just did exactly that and am awaiting it to  finish ;-) .. .so clean clean Jessy Lite and nothing else?

**Comment by PromoFaux** [comment]
Clean clean! Just that one command please! Hopefully it will detect that `apt-get update` needs to be run...

**Comment by DonLexos** [comment]
Ok will do exactly that, just swapped cards, need to do some raspi-config but will report back as soon as I know anything...

**Comment by PromoFaux** [comment]
`raspi-config` is fine just as long as you don't update the package list we're all good!

**Comment by DonLexos** [comment]
Need to change the timezone/keyboard since that is all wrong, wont touch anything else

**Comment by PromoFaux** [comment]
Hold fire on the install command please @DonLexos

**Comment by DonLexos** [comment]
Oh really, am already running it :/

Am here:
`::: apt-get update has not been run today. Running now..\`

**Comment by PromoFaux** [comment]
ok carry on! , you got another ready to go? @DonLexos found a fault, need to tweak

**Comment by DonLexos** [comment]
It asks if it should be the DNS server ..  <ok>. . .than came to this:
```
::: There are 63 updates availible for your pi!
::: Please consider running 'sudo apt-get upgrade' before continuing with installation
:::
::: Would you like to continue with the pi-hole installation? (Y/n):::: Quitting install, please run 'curl -L install.pi-hole.net | bash' after updating packages!
Failed to start dnsmasq.service: Unit dnsmasq.service failed to load: No such file or directory.
Failed to start lighttpd.service: Unit lighttpd.service failed to load: No such file or directory.
```

**Comment by PromoFaux** [comment]
Yeah, same thing happened to @DonLexos , but not on my local machine...

**Comment by DonLexos** [comment]
Not sure if it prompted me for the Y/n or not, I did hit enter since the screen turned blue with 1 red <ok> button

**Comment by DonLexos** [comment]
Can try again if it needs tweaking first ..  .let me know.. this seems to have done nothing except check for updates, full output:
```
pi@pi-hole:~ $ curl -L https://raw.githubusercontent.com/pi-hole/pi-hole/b8f48d1bce621fa136af96f2ea765b85780b924e/automated%20install/basic-install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16575  100 16575    0     0   2892      0  0:00:05  0:00:05 --:--:--  5192
:::
::: sudo will be used for the install.
::: Using interface: eth0
Your static IPv4 address:    192.168.1.11/24
Your static IPv4 gateway:    192.168.1.1
:::
::: Setting IP to 192.168.1.11/24.  You may need to restart after the install is complete.
:::
::: Using IPv4 on 192.168.1.11/24
::: IPv6 will NOT be used.
:::
::: apt-get update has not been run today. Running now.. done!
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: There are 63 updates availible for your pi!
::: Please consider running 'sudo apt-get upgrade' before continuing with installation
:::
::: Would you like to continue with the pi-hole installation? (Y/n):::: Quitting install, please run 'curl -L install.pi-hole.net | bash' after updating packages!
Failed to start dnsmasq.service: Unit dnsmasq.service failed to load: No such file or directory.
Failed to start lighttpd.service: Unit lighttpd.service failed to load: No such file or directory.

```

**Comment by dschaper** [comment]
@DonLexos Did you get the Whiptail screen that has the backtitle "Make It So!"?

**Comment by DonLexos** [comment]
If that is a blue screen with a message along the lines of 'make this the DNS to make it all work blabla' (or similar) with 1 red Ok button then yes

**Comment by dschaper** [comment]
Yeah, That's the one... got the same on a fresh install here, just needs a quick tweak I believe...

**Comment by DonLexos** [comment]
Yes and not sure if this part did actually ask me anything or just ran through untill the error:
```
::: Would you like to continue with the pi-hole installation? (Y/n):::: Quitting install, please run 'curl -L install.pi-hole.net | bash' after updating packages!
Failed to start dnsmasq.service: Unit dnsmasq.service failed to load: No such file or directory.
Failed to start lighttpd.service: Unit lighttpd.service failed to load: No such file or directory.
```

**Comment by PromoFaux** [comment]
Yeah, it's doing that automatically. Which is really weird because I can't reproduce it if I save the script on my SD and run it locally.

**Comment by DonLexos** [comment]
Can try that if you like to see if that is the same on this end, but not sure if I should get the one you mentioned above or await a different one (not really that github pro to figure it out)

**Comment by PromoFaux** [comment]
Get the one I mentioned above and see what happens when you run locally `bash /path/to/script.sh`

**Comment by DonLexos** [comment]
Locally it does ask
```
pi@pi-hole:~ $ bash basic-install.sh
:::
::: sudo will be used for the install.
::: Using interface: eth0
::: Using IPv4 on 192.168.1.11/24
::: IPv6 will NOT be used.
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: There are 63 updates availible for your pi!
::: Please consider running 'sudo apt-get upgrade' before continuing with installation
:::
::: Would you like to continue with the pi-hole installation? (Y/n):N
::: Quitting install, please run 'curl -L install.pi-hole.net | bash' after updating packages!
Failed to start dnsmasq.service: Unit dnsmasq.service failed to load: No such file or directory.
Failed to start lighttpd.service: Unit lighttpd.service failed to load: No such file or directory.
```

However when you No the script to exit it you still get two service errors, and that Whiptail screen is still shown

**Comment by PromoFaux** [comment]
Yeah, I'm less concerned about that right now. I'm more concerned with why Curling the script stops user input

**Comment by PromoFaux** [comment]
AND here is the answer:
http://stackoverflow.com/a/26872969

**Comment by DonLexos** [comment]
Does anybody like me to test anything else? Otherwise I'll be updating the pi and install the 2.4, I see banners everywhere now ;-)

**Comment by Mcat12** [comment]
So, basically add -c to the end of the install? ```curl -L install.pi-hole.net | bash -c```

**Comment by DonLexos** [comment]
or like this?
`bash -c "$(curl -L https://raw.githubusercontent.com/pi-hole/pi-hole/b8f48d1bce621fa136af96f2ea765b85780b924e/automated%20install/basic-install.sh | bash)"`

**Comment by Mcat12** [comment]
That runs bash twice. The ```bash -c "$(curl -L ...)"``` stuff is equal to ```curl -L ... | bash -c```. I'm pretty sure of that at least...

**Comment by DonLexos** [comment]
so adding -c would trigger the Yes/no then . .wil try that and report back

**Comment by PromoFaux** [comment]
OK run `curl -L https://raw.githubusercontent.com/pi-hole/pi-hole/cc0997f1105f692835619991ec1e90635c6bbc25/automated%20install/basic-install.sh | bash`

I've switched it up to force the user to not be able to install if there are packages that need upgrading...

**Comment by Mcat12** [comment]
You mean ```bash -c```?

**Comment by DonLexos** [comment]
No not anymore,.. you cannot continue without the apt-get upgrade now.

```
pi@pi-hole:~ $ curl -L https://raw.githubusercontent.com/pi-hole/pi-hole/cc0997f1105f692835619991ec1e90635c6bbc25/automated%20install/basic-install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16669  100 16669    0     0  92112      0 --:--:-- --:--:-- --:--:-- 92605
:::
::: sudo will be used for the install.
::: Using interface: eth0
::: Using IPv4 on 192.168.1.11/24
::: IPv6 will NOT be used.
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: There are 63 updates availible for your pi!
::: Please run 'sudo apt-get upgrade' before continuing with installation
:::
::: Quitting install, please run 'curl -L install.pi-hole.net | bash' after updating packages!
Failed to start dnsmasq.service: Unit dnsmasq.service failed to load: No such file or directory.
Failed to start lighttpd.service: Unit lighttpd.service failed to load: No such file or directory.
pi@pi-hole:~ $
```

**Comment by PromoFaux** [comment]
nope, just bash

We can't go changing up the install command... so we have to work around it. Instead of giving the user a choice if they wish to continue, we just exit out, make them run apt-get upgrade, then they can continue


@DonLexos run apt-get upgrade then curl the install script again

**Comment by Mcat12** [comment]
Ok.

**Comment by DonLexos** [comment]
Will do, 2 notes though:
- I did get that whiptail screen regardless that nothing was installed
- if the service cannot be started remains there maybe add a blank line under
`::: Quitting install, please run 'curl -L install.pi-hole.net | bash' after updating packages!` 
so its more clear why the installation stopped.

**Comment by PromoFaux** [comment]
Try again with latest commit!

`curl -L https://raw.githubusercontent.com/pi-hole/pi-hole/dbf1308c67dafd8658ec5fae8aaa5a5c7b21edb9/automated%20install/basic-install.sh | bash`

**Comment by DonLexos** [comment]
Will do as soon as the update is done!

**Comment by PromoFaux** [comment]
This has got messy.. brb

**Pull request closed without merging**
