### PR TITLE
[RELEASE] Pi-Hole Core 2.10.2

### PR DESCRIPTION
**Pull request by DL6ER**

### CODE REVIEW

**Comment by Mcat12** [comment]
Approved

**Comment by dschaper** [comment]
Approved

**Comment by PromoFaux** [comment]
Approved.

On bloody Christmas day! You guys are machines....

**Comment by DL6ER** [comment]
We can truly blame @diginc for having to do this on Christmas ...

**Comment by jacobsalmela** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/pi-hole/pi-hole/pull-request/1041/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=pi-hole/pi-hole)

**Pull request merged**
