### PR TITLE
Allow to run test workflow manually

### PR DESCRIPTION
**Pull request by yubiuser**
**What does this PR aim to accomplish?:**

**PR MASTER BRANCH!**

Allows to run the test suite manually from the "Actions" menu. 
This would allow to run the test for branches that have no PR yet or PRs in draft mode. 

**How does this PR accomplish the above?:**

Add `workflow_dispatch:` to the `test.yml`

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by dschaper** [comment]
I'm not sure I like this idea. Why do we need it?

**Comment by yubiuser** [comment]
Actually for:

> This would allow to run the test for branches that have no PR yet or PRs in draft mode.
__

See this PR: https://github.com/pi-hole/pi-hole/pull/5044

I tested it locally and it worked fine. Now it takes forever for CentOS8 to complete the tests, so I set it to `draft` because this is its current state. If I push new commits, the workflows won't run, unless I mark it as "ready for review". With this PR, I could simply trigger the tests manually. 
Actually, I wouldn't have opened the PR in the first place if I could trigger the workflows from the branch - but I needed the PR to make the workflows run as creating branches also does not trigger the workflows.

**Comment by yubiuser** [comment]
Where do you see issues with allowing manual triggering?

**Comment by PromoFaux** [comment]
It's a semi-useful option to be able to trigger a workflow manually, but I think for the use-case really one should be pushing/experimenting with tests on their own fork/locally rather than using the organisation repo. Not least because of the potential for notification spam to many members of the org.

At least for now it is a no from me

**Pull request closed without merging**
