### PR TITLE
Allow optional parsing of blocklists into NXDOMAIN style lists, rather than HOSTS

### PR DESCRIPTION
**Pull request by PromoFaux**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**

As addressed in #2010, it would be nice to have the option to return `NXDOMAIN` instead of the address of the Pi-Hole host. With the PR, we can do just that. Obviously this renders the block page useless, but with the rise of HTTPS, that is becoming less and less relevant

**How does this PR accomplish the above?:**
`gravity.sh` now checks for a new value in `setupVars.conf` named `BLOCKSTYLE_NXDOMAIN` (boolean, name subject to change). If it is `true`, then `gravity` will empty out `gravity.list` and `black.list`, and then create three additional files:
- `/etc/dnsmasq.d/00-pihole-gravity.conf` - `server=/badDomain.com/`
- `/etc/dnsmasq.d/00-pihole-userBlacklist.conf` - `server=/badDomain.com/`
- `/etc/dnsmasq.d/99-pihole-whitelist.conf` - `server=/goodDomain.com/#`

**What documentation changes (if any) are needed to support this PR?:**
FTL will need a change to read number of blocked domains from this new source, as currently "number of blocked domains" shows as 0 (due to `gravity.list` being empty!)

image

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by DL6ER** [comment]
> FTL will need a change to read number of blocked domains from this new source, as currently "number of blocked domains" shows as 0 (due to gravity.list being empty!)

Actually, with *FTL*DNS is it different as we directly hook into the resolvers code to see how many host file entries it parsed. This avoids that we count domains that have not been imported by `dnsmasq` (maybe because they contain some invalid Unicode). There is no such information for config files.

So, I'll add code that will count the number of entries in lists mentioned in this PR. What do you think @PromoFaux ?

**Comment by PromoFaux** [comment]
Sounds good to me, as long as we are happy with the filenames!

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/implement-response-zone-policies-nxdomain-for-end-user-performance-increase/1342/17

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/add-the-ability-to-let-pi-hole-resolve-dns/2368/18

**Comment by PromoFaux** [comment]
Close as this functionality is now in `FTL`

**Pull request closed without merging**
