### PR TITLE
fixes #4196

### LINKED ISSUE #4196: Installation process fails when doing so on a system with multiple (read above 20) network adapters
### Versions
- Pi-hole version is v5.3.1 (Latest: v5.3.1)
-  AdminLTE version is v5.5 (Latest: v5.5)
-  FTL version is v5.8.1 (Latest: v5.8.1)

### Platform
- OS and version:  Linux rock64 4.4.167-1213-rockchip-ayufan-g34ae07687fce #1 SMP Tue Jun 18 20:44:
49 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
- Platform:  Pine Rock64
- Docker running with 25 active services, 16 docker networks, 47 network adapters (`ifconfig -a|grep flags|wc -l`)

### Expected behavior

It is possible to install PiHole while logged in via SSH

### Actual behavior / bug

It is (near) impossible to install PiHole because when the curses dialog shows where the user can select the network card, all docker (virtual) network cards, bridges, etc. show up - when this happens, the list can get so huge that the user is unable to get at the entries way up in the list. The list is not scrollable - so if the user needs to select an entry among  the first in the list - that is impossible

### Steps to reproduce

* Get a system with a fair amount of docker containers running and a fair amount of network cards  where `ifconfig -a|grep flags|wc -l` returns something above 30 maybe
* Try to start the installation process and look at the dialog for the selection of the network interface

## Debug Token

not applicable because Error happens during install

### Screenshots

image

### Additional context

none so far

### PR DESCRIPTION
**Pull request by elbosso**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [ X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [ X] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [ X] I have tested my proposed changes, and have included unit tests where possible.
- [ X] I am willing to help maintain this change if there are issues with it later.
- [ X] I give this submission freely and claim no ownership.
- [ X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
fixes #4196

**How does this PR accomplish the above?:**
At least the current version of whiptail in my install has issues when explicit row and column numbers are specified  - therefore i propose to let it figure them out by itself in (at least) the dialog for choosing the interface to act on

**What documentation changes (if any) are needed to support this PR?:**
none

### CODE REVIEW

**Comment by yubiuser** [comment]
All PR's should be made against `development`. 

Have you checked what `${r}` and  `${c}` are in your case and if the error is within their definition?

**Comment by elbosso** [comment]
> All PR's should be made against `development`.
> 
> Have you checked what `${r}` and `${c}` are in your case and if the error is within their definition?

I did indeed check and they had reasonable values - in fact, replacing `whiptail` with `dialog` worked as expected without changing `$r` or `$c`

**Comment by MichaIng** [comment]
https://github.com/pi-hole/pi-hole/blob/1994d11dbb8afc577acdcd1d5fce0acbd334a647/automated%20install/basic-install.sh#L98-L107
When calling the installer with `curl -sSL https://install.pi-hole.net | bash`, `[ -t 0 ]` returns false as STDIN is the output of the installer and no terminal. Hence `screen_size="24 80"` is applied. As of:
https://github.com/pi-hole/pi-hole/blob/1994d11dbb8afc577acdcd1d5fce0acbd334a647/automated%20install/basic-install.sh#L109-L114
those values halved are lower than the set minimal values and hence the result is always `r=20` and `c=70` 😄. For the text to be readable, the whiptail needs to be 7 rows higher than the amount of list rows.

It is possible via `tput` to get the correct terminal/screen size, despite STDIN is overridden, but I made this an issue once (or the other way round, suggested to call the installer via `bash -c "$(curl -sSL https://install.pi-hole.net)"` to preserve STDIN, but the quite large whiptail dialogues were seen more ugly then the 20/70 which everyone is used to already.

Using `0 0` makes whiptail use the required dimensions automatically, up to max possible (as of screen/terminal size), so that should work fine in most cases. `0 "${c}"` would be sufficient, as only the height is the problem here. Alternatively the list rows could be reduced to fit the whiptail nicely:
```sh
local lr=${interfaceCount}
if (( lr > r - 7 )); then
    lr=$(( r - 7 ))
fi
chooseInterfaceCmd=(whiptail --separate-output --radiolist "Choose An Interface (press space to toggle selection)" "${r}" "${c}" "${lr}")
```
So the whiptail dialogue size stays exactly as it is and the list won't exceed it, but if required, gets a scroll bar to scroll with arrow keys.

**Comment by dschaper** [comment]
I think the size calculations were done a long, long time ago with the initial creation of the installer script. 

I can't really remember why we changed the whiptail/dialog size for the displays to be honest. It's not any code I'm married to or have objections to changing. If there's something better that works and looks okay then why not? 

This is based on the master branch so that needs to change. Or if you want to pop up a new PR Micha?

**Comment by MichaIng** [comment]
> Or if you want to pop up a new PR Micha?

Jep, I can do that. Removing some old/obsolete code from the installer is always good. It's however two different things, so it probably makes sense to keep this PR here as well to only address the issue where long interface lists exceed the dialogue.

To keep changes in look&feel otherwise untouched here (and handle this in the separate PR), the last code suggestion I posted above would be a way to go:
- It leaves the width untouched, which is irrelevant for the issue.
- It leaves the height of the dialogue itself untouched, which is generally sufficient (with currently minimum 20 lines) for text and 13 list items.
- So when navigating through the installer, all whiptail dialogues keep having the same sizes, as it is now.
- Even with much more interfaces or on very small screens, the list is assured to not exceed the dialogue, and instead a scrollbar is shown. With `0 0 "${interfaceCount}"` it would still be possible that the list is larger than the dialogue on small screens.
    **EDIT: Just verified on a Debian Bullseye system `height=0` (auto-height) implies `list-height=0`, so `"${interfaceCount}"` becomes irrelevant. However, I wouldn't count on this on every `whiptail` version/build to be handled gracefully.**
- Downside: Four additional code lines 🤔.

**Comment by dschaper** [comment]
>     * Downside: Four additional code lines

That's not a worry for me. 

I'm not sure if this PR is going to go anywhere. It's based on master and that is a blocker, I don't know if @elbosso is getting notifications for comments here.

**Comment by elbosso** [comment]
Hi, I am sorry if you waited for a coment from me - of course i read all your exchanges here but I thought that i neednt do anything because judging  by their contents i sensed that the topic is with specialists that do not need my two dimes. Especially because i blundered even before putting up this pull request by making it not against the dev but against the master branch.

So please tell me where to go from here - should i close the pull request in this branch? If so - should i really open it against the dev branch and if so - with what content? because my initial proposal seems to have been sub-optimal (there are others - no doubt better suited ones - being discussed here) 

And another question .is there any possibility (other than referencing this pull request) to kind of carry over the discussion and comments here into the new one?

**Comment by dschaper** [comment]
We are always happy to hear what anyone has to say about the topic. I am far from being a specialist on this, 

I think Micha was going to expand on what you had here instead of replacing this PR but he would be able to confirm that. Depending on your level of comfort with `git` you can either rebase your commits on to the development branch and then force push those changes up to this PR. The other choice is to close this PR and open a new one, just make sure your commits are based on the development branch (so make sure you `git checkout development` first and then make your changes and commits).

There's no rush to get this done and there may be some other `git` tricks to help out that would not need this PR to be closed. I would like you and @MichaIng to coordinate if you could on this.

And please don't hesitate to comment, everyone has a unique view and approach and you may see something that we have missed.

**Comment by MichaIng** [comment]
Jep I think it's two tasks about those whiptail dialogues:
1. Assure that menu/checklists never exceed the dialogue and leaves enough room for the text above.
    - I just recognised that all other whiptail `--radiolist` calls use a fixed list height of `6`. Instead of doing calculations, this could be done here as well, so they all look the same and with the practically hardcoded or minimum `r=20` it fits well. As said, the list gets a scrollbar then, so it should look nice as well with many interfaces. Else see my suggestion above to calculate and in case apply the max possible light height.
    - The whiptail `--menu` calls as well use a hardcoded menu height of either `2` or `7` (upstream DNS selection).
2. Define dialogue dimensions themselves in a consistent way, regardless how the script is called, so that those are assured to look nice and everything fits inside, regardless how it is tested.
    - I'll open a PR for this now, using the hardcoded `r=20` and `c=70`, which is small enough to fit 99,9% of screens (no one complained yet), but obviously is able to hold all content (except for the rare cases this PR addresses).

**Comment by yubiuser** [comment]
Is this PR obsolet now, as https://github.com/pi-hole/pi-hole/pull/4229 has been merged? 
And is https://github.com/pi-hole/pi-hole/issues/4196 fixed by now?

**Comment by MichaIng** [comment]
@elbosso @yubiuser 
#4229 does not solve #4196! It's two different sizes: The whole dialogue size is now fixed, with an overall height of 20 rows, practically it was like that before when calling the installer via pipe. But the network interface list within the dialogue can still exceed it, so that it looks ugly, respectively the text above the list is covered. With a fixed dialogue size it makes sense to have a fixed list height as well. As mentioned, all other `--radiolist` calls have a fixed height of `6` with fits well, and the list itself then gets a scroll bar and can be scrolled via up/down and pageup/pagedown buttons. Compared to using `0 0`, this has the other benefit that it works on small screens/consoles as well, while `0 0` will never exceed the actual console dimensions, hence the list can still be too high.

**Comment by MichaIng** [comment]
Opened a related PR now: #4434

**Pull request closed without merging**
