### PR TITLE
basic-install.sh: fix "install: invalid user ''"

### LINKED ISSUE #1767: install: invalid user ''
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_2_

---
**[BUG REPORT | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

I deploy Pi-hole via Puppet by `--unattended` w/ `/etc/pihole/setupVars.conf` already being present and it just works.

**[BUG | ISSUE] Actual Behaviour:**

I deploy Pi-hole via Puppet by `--unattended` w/ `/etc/pihole/setupVars.conf` already being present and it fails w/ `install: invalid user ''`.

**[BUG | ISSUE] Steps to reproduce:**

People who are familiar w/ Puppet know how to deploy something, but they maybe don't have any module for pihole. Here you are (made for Ubuntu 16.04 LXD containers):

`modules/pihole/manifests/dns.pp`

```
class pihole::dns ($netif, $upstream) {
	file { '/etc/pihole/setupVars.conf':
		content => epp('pihole/etc/pihole/setupVars.conf.epp', {
			'netif'    => $netif,
			'upstream' => $upstream,
		}),
		require => File['/etc/pihole'],
	}

	file { '/etc/pihole':
		ensure => directory,
	}
	-> exec { '/usr/bin/wget -O /etc/pihole/basic-install.sh https://install.pi-hole.net':
		creates => '/etc/pihole/basic-install.sh',
	}
	-> exec { '/bin/bash /etc/pihole/basic-install.sh --unattended':
		user        => 'root',
		group       => 'root',
		creates     => '/opt/pihole',
		require     => File['/etc/pihole/setupVars.conf'],
	}
}
```

`modules/pihole/templates/etc/pihole/setupVars.conf.epp`

```
<%-| $netif, $upstream |-%>
PIHOLE_INTERFACE=<%= $netif %>
IPV4_ADDRESS=0.0.0.0
IPV6_ADDRESS=
PIHOLE_DNS_1=<%= $upstream %>
PIHOLE_DNS_2=
QUERY_LOGGING=false
INSTALL_WEB=false
```

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #1767

**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

_2_

---
_fixes #1767_

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by Al2Klimov** [comment]
@Fauxsys *Why* don't you agree with this pull request?

**Comment by Fauxsys** [comment]
This PR will make $USER=root for unattended installs. Since the updatePihole() function is called during an unattended install rather than the installPihole() function, a better suggestion would be to add the following to the updatePihole() function:
`  create_pihole_user

  if [[ ${INSTALL_WEB} == true ]]; then
    if [ ! -d "/var/www/html" ]; then
      mkdir -p /var/www/html
    fi
    chown ${LIGHTTPD_USER}:${LIGHTTPD_GROUP} /var/www/html
    chmod 775 /var/www/html
    usermod -a -G ${LIGHTTPD_GROUP} pihole
    if [ -x "$(command -v lighty-enable-mod)" ]; then
      lighty-enable-mod fastcgi fastcgi-php > /dev/null || true
    else
      printf "\n:::\tWarning: 'lighty-enable-mod' utility not found. Please ensure fastcgi is enabled if you experience issues.\n"
    fi
  fi
`

**Comment by Mcat12** [comment]
@Fauxsys If you want to propose a different fix, than open a new PR and perhaps link to this one to explain why the new PR should be chosen as the fix.

**Comment by Mcat12** [comment]
The issue this attempts to solve was fixed by #1835

**Comment by Al2Klimov** [comment]
@Mcat12 I'm afraid the problem I filed isn't (and has never been) fixed. The installer [still uses](https://github.com/pi-hole/pi-hole/blob/23a7feeb6e59be31cb8423b2aaeefb7e22476534/automated%20install/basic-install.sh#L1138) the USER variable which isn't set if run by Puppet. I've no idea what the other PR was for, but this one is definitively still needed.

**Comment by Al2Klimov** [comment]
Rebased against master.

**Comment by DL6ER** [comment]
Hmm, I think `whoami` is deprecated. I use `id -un` for these purpose.

**Comment by DL6ER** [comment]
See e.g., http://man.openbsd.org/whoami.1

**Comment by Al2Klimov** [comment]
Corrected.

**Comment by jacobsalmela** [comment]
@Al2Klimov please contact me directly for a special thank you.

**Pull request merged**
