### PR TITLE
Add force clear to gravity

### PR DESCRIPTION
**Pull request by PromoFaux**
Feature request [on reddit](https://www.reddit.com/r/pihole/comments/4xz8y6/only_70k_domains_blocked_down_from_100k_any_ideas/d6kcctq?context=3)

Changes proposed in this pull request:

- Adds `-f` switch to gravity, which clears out the list cache files (`list.*`) and downloads each list from scratch.

@pi-hole/gravity

### CODE REVIEW

**Comment by PromoFaux** [comment]
Approved. Naturally.

**Comment by dschaper** [comment]
Approved (Would like a -n for nuclear that wipes black/white and starts over for really buggered installs?)

**Comment by jacobsalmela** [comment]
Approved

**Comment by dschaper** [comment]
How did this branch go out of date in 7 minutes from creation???

**Pull request merged**
