### PR TITLE
Tidying up the uninstall script

### PR DESCRIPTION
**Pull request by PromoFaux**
TODO:
- [x] Update to reflect install script pulling from git
- [ ] replace `dnsmasq.conf` with `dnsmasq` default file if it is pi-hole flavoured.
- [ ] Tidy up output to match style of other scripts
- [x] Fix some formatting in the installer

(Should anyone wish to complete these tasks, please submit a Pull Request to the branch `UninstallFix`)

### CODE REVIEW

**Comment by Mcat12** [comment]
What kind of output were you thinking of?

**Comment by PromoFaux** [comment]
I mean for the format to match the same as `basic-install.sh` and `gravity.sh`

```
:::   Some message...
```

**Comment by dschaper** [comment]
Merge conflicts!! Woo Hoo!! :wink:

**Comment by PromoFaux** [comment]
Ah, yeah, this one kind of fell by the wayside. To be honest, it can probably be junked as it'll be fixed as part of the refactor.

**Pull request closed without merging**
