### PR TITLE
Make the output of pihole -q a bit clearer. Bye Bye nifty one-liner!

### PR DESCRIPTION
**Pull request by PromoFaux**
e.g:

``` bash
pi@raspberrypi:~ $ pihole -q doubleclick.com
::: /etc/pihole/list.0.raw.githubusercontent.com.domains (4 results)
0.0.0.0 doubleclick.com
0.0.0.0 www2.doubleclick.com
0.0.0.0 www3.doubleclick.com
0.0.0.0 www.doubleclick.com

::: /etc/pihole/list.2.sysctl.org.domains (4 results)
127.0.0.1        doubleclick.com
127.0.0.1        www.doubleclick.com
127.0.0.1        www2.doubleclick.com
127.0.0.1        www3.doubleclick.com

::: /etc/pihole/list.5.s3.amazonaws.com.domains (1 results)
doubleclick.com

::: /etc/pihole/list.6.hosts-file.net.domains (11 results)
127.0.0.1       doubleclick.com
127.0.0.1       ftp.doubleclick.com
127.0.0.1       m.doubleclick.com
127.0.0.1       mediavisor.doubleclick.com
127.0.0.1       reports.doubleclick.com
127.0.0.1       search.doubleclick.com
127.0.0.1       static.doubleclick.com
127.0.0.1       studio.doubleclick.com
127.0.0.1       www.doubleclick.com
127.0.0.1       www2.doubleclick.com
127.0.0.1       www3.doubleclick.com

```

@pi-hole/gravity

### CODE REVIEW

**Comment by PromoFaux** [comment]
Approved

**Comment by jacobsalmela** [comment]
What about an `else` message saying `domain not found`, or `(0 results)`?

**Comment by dschaper** [comment]
Sexy!

**Comment by PromoFaux** [comment]
I can add that if you like!

**Comment by PromoFaux** [comment]
This OK?

```
pi@raspberrypi:/etc/.pihole $ pihole -q doubleclick.com
::: /etc/pihole/list.0.raw.githubusercontent.com.domains (4 results)
0.0.0.0 doubleclick.com
0.0.0.0 www2.doubleclick.com
0.0.0.0 www3.doubleclick.com
0.0.0.0 www.doubleclick.com

::: /etc/pihole/list.1.mirror1.malwaredomains.com.domains (0 results)

::: /etc/pihole/list.2.sysctl.org.domains (4 results)
127.0.0.1        doubleclick.com
127.0.0.1        www.doubleclick.com
127.0.0.1        www2.doubleclick.com
127.0.0.1        www3.doubleclick.com

::: /etc/pihole/list.3.zeustracker.abuse.ch.domains (0 results)

::: /etc/pihole/list.4.s3.amazonaws.com.domains (0 results)

::: /etc/pihole/list.5.s3.amazonaws.com.domains (1 results)
doubleclick.com

::: /etc/pihole/list.6.hosts-file.net.domains (11 results)
127.0.0.1       doubleclick.com
127.0.0.1       ftp.doubleclick.com
127.0.0.1       m.doubleclick.com
127.0.0.1       mediavisor.doubleclick.com
127.0.0.1       reports.doubleclick.com
127.0.0.1       search.doubleclick.com
127.0.0.1       static.doubleclick.com
127.0.0.1       studio.doubleclick.com
127.0.0.1       www.doubleclick.com
127.0.0.1       www2.doubleclick.com
127.0.0.1       www3.doubleclick.com

::: /etc/pihole/list.7.raw.githubusercontent.com.domains (0 results)

::: /etc/pihole/list.8.ransomwaretracker.abuse.ch.domains (0 results)
```

**Comment by jacobsalmela** [comment]
Sexy!

**Comment by jacobsalmela** [comment]
Approved

**Comment by PromoFaux** [comment]
Approved (again!)

**Comment by dschaper** [comment]
Would "Not found in lists" be easier to understand, or better to have `0 results` for `grep` possibilities?

**Comment by PromoFaux** [comment]
I think `0 results` is quite self explanatory?

**Comment by jacobsalmela** [comment]
Yeah, I think it's good with `(0 results)`

**Comment by dschaper** [comment]
:+1:

**Pull request merged**
