### PR TITLE
Tweak lighttpd configs

### PR DESCRIPTION
**Pull request by XhmikosR**
* Compress more types
* Add charset=utf-8 in more text types
* Use proper media types
* Add default expire header
* Use consistent indentation

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [ ] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [ ] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---

Non-whitespace diff: https://github.com/pi-hole/pi-hole/pull/3425/files?w=1

Depends on #3403

### CODE REVIEW

**Comment by cqueern** [comment]
Thank you for submitting this one @XhmikosR . I was about to submit a request regarding how Pi-Hole's lighthttpd server doesn't serve static assets with an efficient cache policy but when I saw 

> Add default expire header

above, it looks like you're already working on that. 

1.  Are you planning on adding the `Cache-Control` header for all four of these?

- fonts
- css
- javascript
- images

2. How long are you thinking to make the caching directive? One year?

**Comment by XhmikosR** [comment]
Changing the default header to 1 year is moot because the files are not cache busted. That's what this patch tries to fix, because browsers cache the static files and when a new version is out, users need to clear their browser cache or hard refresh.

So, this patch aims to fix that problem. If we ever have cache busting in the dashboard, then we can change the cache headers. But keep in mind, not everyone is using lighttpd.

**Comment by PromoFaux** [comment]
#3403  has now been merged

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-5-1-released/35577/1

**Pull request merged**
