### PR TITLE
replace 'git -C' with long version

### LINKED ISSUE #1004: [ISSUE] Pi-Hole V2.10 installation Error
CentOS 7.3.1611

I ran the usual to update to the latest V2.10:
`curl -L https://install.pi-hole.net | bash`

During the upgrade, I receive an error.
Here is the full trace:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
:::
::: You are root.
100 39652  100 39652    0     0  24852      0  0:00:01  0:00:01 --:--:--  313k
::: Update option selected.
::: Verifying free disk space...
:::
::: yum update has not been run today. Running now... done!
:::
::: Checking yum for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with Pi-hole installation...
:::    Checking for git... installed!
:::    Checking for iproute... installed!
:::    Checking for net-tools... installed!
:::    Checking for newt... installed!
:::    Checking for procps-ng... installed!
:::
::: Checking for existing repository...
:::    Cloning https://github.com/pi-hole/pi-hole.git into /etc/.pihole... done!
:::
::: Checking for existing repository...
:::    Cloning https://github.com/pi-hole/AdminLTE.git into /var/www/html/admin... done!
:::    Checking for bc... installed!
:::    Checking for bind-utils... installed!
:::    Checking for cronie... installed!
:::    Checking for curl... installed!
:::    Checking for dnsmasq... installed!
:::    Checking for epel-release... installed!
:::    Checking for findutils... installed!
:::    Checking for lighttpd... installed!
:::    Checking for lighttpd-fastcgi... installed!
:::    Checking for nmap-ncat... installed!
:::    Checking for php... installed!
:::    Checking for php-common... installed!
:::    Checking for php-cli... installed!
:::    Checking for sudo... installed!
:::    Checking for unzip... installed!
:::    Checking for wget... installed!
:::
::: Installing scripts from /etc/.pihole... *** ERROR: Local repo  not found, exiting.
::: Control all PiHole specific functions!
:::
::: Usage: pihole [options]
:::		Add -h after -w (whitelist), -b (blacklist), or -c (chronometer)  for more information on usage
:::
::: Options:
:::  -w, whitelist            Whitelist domains
:::  -b, blacklist            Blacklist domains
:::  -d, debug                Start a debugging session if having trouble
:::  -f, flush                Flush the pihole.log file
:::  -up, updatePihole        Update Pi-hole
:::  -g, updateGravity        Update the list of ad-serving domains
:::  -s, setupLCD             Automatically configures the Pi to use the 2.8 LCD screen to display stats on it
:::  -c, chronometer          Calculates stats and displays to an LCD
:::  -h, help                 Show this help dialog
:::  -v, version              Show current versions
:::  -q, query                Query the adlists for a specific domain
:::  uninstall                Uninstall Pi-Hole from your system :(!
:::  status                   Is Pi-Hole Enabled or Disabled
:::  enable                   Enable Pi-Hole DNS Blocking
:::  disable                  Disable Pi-Hole DNS Blocking
:::  restartdns               Restart dnsmasq

```

I tried re-running several times, no go.
Any ideas?

Thanks!

### PR DESCRIPTION
**Pull request by bcambl**
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**
- [x] 8

---

The -C argument was introduced in git 1.8.4. CentOS 7.3 at the time of this commit provides v1.8.3.1.
see: https://git.kaarsemaker.net/git/commit/44e1e4d67d5148c245db362cc48c3cc6c2ec82ca/

Fixes #1004

### CODE REVIEW

**Comment by dschaper** [comment]
Okay, not a biggie to change. Can we to that in curly braces though so it doesn't spawn a subshell?

**Comment by bcambl** [comment]
np

**Comment by dschaper** [comment]
Merci, I've just been getting bit by the scopes and environment variables with subshells, so as much as we can keep things in the parent shell the easier to trace down some mysto bugs.

**Comment by dschaper** [comment]
Approved

**Pull request merged**
