### PR TITLE
Update Quad9 to correct resolver IPs, replacing legacy

### PR DESCRIPTION
**Pull request by debrunet**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
Quad9 is moving from primary and secondary IP `9.9.9.9` and `149.112.112.112` to `9.9.9.9` and `149.112.112.9` to be more in line with the other resolver options they have available (`9.9.9.10`, `149.112.112.10` and `9.9.9.11`, `149.112.112.11`) and reduce confusion.
This can also be seen when performing a reverse lookup on `9.9.9.9`:

    debrunet@mac ~ % host 9.9.9.9
    9.9.9.9.in-addr.arpa domain name pointer dns9.quad9.net.
    debrunet@mac ~ % dig +short a dns9.quad9.net
    9.9.9.9
    149.112.112.9
    debrunet@mac ~ % dig +short aaaa dns9.quad9.net
    2620:fe::9
    2620:fe::fe:9

`9.9.9.9` points to `dns9.quad9.net`, which points to `9.9.9.9` and `149.112.112.9` (and `2620:fe::9`, `2620:fe::fe:9`). I contacted Quad9 support about this matter and they confirmed that `9.9.9.9` and `149.112.112.9` are the correct and recommended IPs to use from now on. The response can be found below. Quad9's current website still contains the old IP addresses, but support also confirmed they will roll out a new website in "early 2020" (I suspect 2021) with clarifications and the correct IP addresses.   

> Hello,  
> Thank you for reaching out to Quad9 Support. All of these IP addresses point to the same service on our servers and there is essentially no difference in results. When the service was initially implemented which was before my time with Quad9 so this is all based on information passed along to me, there was the inconsistency that you pointed out such as our services primary address being 9.9.9.9 and the secondary being 149.112.112.112. To stay on brand and to stay consistent with our other offering, we realized it didn't make much sense to have the secondary address not end in .9 so the 149.112.112.9 was added later and is now what we recommend simply for consistency. For example or service with no blocklist is 9.9.9.10 and 149.112.112.10. Unfortunately though, once the address was advertised and being used by our users, we couldn't simply take it away so now they both serve as secondary addresses. The 149.112.149.112 address is even more legacy and was never promoted by us but does function as an alternate.
> The IP situation on our main service is a bit confusing because of the early decision not to have the secondary address of 149.112.112.9 but we have been slowly attempting to clear up this confusion and correct this without affecting users who may have certain addresses configured. We are currently focused on developing and rolling out a brand new website that should be coming out early 2020 where we will have a lot of that cleaned up. **<ins>That said, my recommendation would be to configure your device to use 9.9.9.9 and 149.112.112.9 as this will be our focus moving forward.</ins>**
> I apologize for the confusion, please let me know if you have any further questions.  
> Thanks,  
> Tony

**How does this PR accomplish the above?:**
The IP addresses in the file `automated install/basic-install.sh` on line 42 have been updated.

**What documentation changes (if any) are needed to support this PR?:**
The documentation on [this page](https://docs.pi-hole.net/guides/upstream-dns-providers/#quad9) will need to be updated with the correct IP addresses for IPv4 (`9.9.9.9`, `149.112.112.9`) and IPv6 (`2620:fe::9`, `2620:fe::fe:9`).

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by PromoFaux** [comment]
What is https://github.com/pi-hole/pi-hole/pull/3963/commits/ffa095e66fb824c5674b70cb2cc048b0c94e094a for? Not described anywhere in the OP - and unsure how it is related to changing the IP addresses....

**Comment by debrunet** [comment]
@PromoFaux Yes, that was an error and has nothing to do with this commit. DCO gave me an error and it got accidentally added. I think I resolved it now.

**Comment by jfb-pihole** [comment]
According to the Quad 9 web page FAQ at https://www.quad9.net/faq/, they are providing the following IP's.

Yes. Quad9 provides DNSSEC validation on our primary resolvers.

9.9.9.9, 149.112.112.112

2620:fe::fe, 2620:fe::9

In addition we validate DNSSEC on our EDNS enabled service.

9.9.9.11, 149.112.112.11

2620:fe::11,  2620:fe::fe:11

Our IP's should match what they specify on their own public documentation.

**Comment by debrunet** [comment]
Quad9 support said themselves the website is currently out of date and not completely correct anymore. The internal decision was made to consider `149.112.112.112` as deprecated, but it will still function as a lot of people had it previously configured. Furthermore, they linked me the following document for the most up-to-date overview of all the IP addresses [here](https://support.quad9.net/hc/en-us/articles/360041193212-Quad9-IPs-and-other-settings). There you can see `149.112.112.9` listed.

**Comment by jfb-pihole** [comment]
The new IP is listed, but it's not the recommended IP.  The first set of IP's on the link you provided is the recommended set, and that's what Pi-hole should provide until the Quad9 documentation changes to recommend something else.  If a user wants to use the alternate IP's, that's why we provide for custom entries for upstream DNS servers.

image

**Comment by debrunet** [comment]
I suppose then we wait until the new documentation is released and put this pull request on hold.

**Comment by DL6ER** [comment]
July 4th, 2021

Screenshot from 2021-07-04 12-26-14

I guess they withdraw from their change in recommendation they mentioned to you.

**Comment by debrunet** [comment]
Indeed, it seems like an internal miscommunication at Quad9. For now, let's close this PR.

**Pull request closed without merging**
