### PR TITLE
Support systemd-networkd in containers

### PR DESCRIPTION
**Pull request by pemensik**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [-] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**

When Pi-hole is installed to lxc Fedora container, network is managed via systemd-networkd. Installer complaints it cannot find interface static configuration file and quits. My change adds support for networkd, as is used on Fedora. I expect other distributions would work also. When systemd-networkd is used, it would be able to finish installation.

*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*
Installation can pass

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*
As addition to dhcpcd and Network Manager support, systemd-networkd would also work on installation.

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by pemensik** [comment]
I needed this, when created container on [Turris Mox](https://www.turris.cz/en/mox/overview/) router on  fedora 31 [lxc container](https://uk.images.linuxcontainers.org/). My Pi-hole installation always aborted on it.

**Comment by PromoFaux** [comment]
Placing on hold for now. There lies the possibility that we're removing automated setting of static IP addresses. (See https://github.com/pi-hole/pi-hole/pull/3715)

**Comment by bcambl** [comment]
I agree with @PromoFaux that this should not be merged all automated network configuration is removed.  
That said, installation documentation should be updated for systemd `networkd` and `resolved`.

**Comment by PromoFaux** [comment]
Closing as we have removed all automated static address setting from the installer (except in cases where dhcpcd5 is already installer a la Raspbian)

**Pull request closed without merging**
