### PR TITLE
Add pihole-admin.conf to debug log

### PR DESCRIPTION
**Pull request by yubiuser**
**What does this PR aim to accomplish?:**

Adds the "new" lighttpd `pihole-admin.conf` to the debug output.

Additionally, fixed a bug where we try to `list_files_in_dir` even if `dir_check` says there is no directory (we never checked the output of `dir_check()`.

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by rdwebdesign** [comment]
I like the idea, but I have questions:

- The `/etc/lighttpd/conf.d` directory only exist on Fedora/CentOS. 
  Do you think we should avoid this test on Debian derivatives to avoid confusing users? 
  ```
  *** [ DIAGNOSING ]: contents of /etc/lighttpd/conf.d
  /etc/lighttpd/conf.d does not exist.
  ```
  
  - The same applies to `15-pihole-admin.conf` on Fedora/CentOS (this file only exist on Debian).

**Comment by rdwebdesign** [comment]
> Isn't it the other way round `conf-enabled` is symliked to `conf-available`? And if I edit one of two symlinked files, the changes should be reflected in the other file as well?

The changes made to `/conf-available` will be reflected on `/conf-enabled`, but if the user decides to delete the symlink (for whatever reason) the debug log will show the original file, but the config will not really use it.

**Comment by yubiuser** [comment]
Added the output of `lighttpd -tt -f /etc/lighttpd/lighttpd.conf` to the debug log.

**Review by rdwebdesign — DISMISSED** [review]

**Comment by yubiuser** [comment]
Last commit will print all files (not their content) of the lighttpd config directories.

**Review by rdwebdesign — APPROVED** [review]

**Pull request merged**
