### PR TITLE
Sri786 : added the tested logic for the password validation for the issue 1781 

### PR DESCRIPTION
**Pull request by sri786**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [] I have considered, and confirmed that this submission will be valuable to others.
- [] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

8

Following is the link for detailed documentation of the issue and the changes with the test results:
[pihole-issue-1781-documentation.docx](https://github.com/pi-hole/pi-hole/files/1536793/pihole-issue-1781-documentation.docx)

Following is the pull request content (line 100 to 121):
image

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by dschaper** [comment]
Can you close out this PR and open a new one based off of Development branch, that should clean out the merge spam that got picked up when you based off of Master. Thanks for the submission!

**Comment by sri786** [comment]
changed the pi-hole base to development  for the following change : added the tested logic for the password validation for the issue 1781 and added -r for safe read operation (does not mangle the back slash)

**Comment by dschaper** [comment]
Thanks, looks like the base change fixed it. Can you also fill out the template with the check marks in the boxes, we need to have that so that we can merge in your commits under the license of the software.

**Comment by diginc** [comment]
I had left a comment about maybe using `cracklib-check` previously.  I really like it because then we don't have to write an opinionated re-implementation of how to make a strong password in our code base.  I was imagining a flow like:

> Do you want to set a web password? [ Y / N ]

Y

> User enters password once 

any cracklib warnings show up at this stage, similar to when changing a linux password

> User entered password again to confirm

> The password you entered is weak because of <cracklib-check output minus the password>
> Tips for a strong password:  ...
> 
> Press Y to confirm you want to use a weak password <if Y proceed>
> Press N to attempt a different, stronger, password <if N loop back to beginning>

Some example cracklib output:

```
$ echo "pass123" | cracklib-check
pass123: it is based on a dictionary word
$ echo "pass1234" | cracklib-check
pass1234: OK
$ echo "JDSjfdjjeJJEJE3332#" | cracklib-check
JDSjfdjjeJJEJE3332#: OK
```

**Comment by sri786** [comment]
@dschaper and @diginc  Sure, Thanks

**Comment by sri786** [comment]
@dschaper I have updated the terms and agreements (template), and signed the CLA agreement. sorry to miss that earlier.

**Pull request closed without merging**
