### PR TITLE
Remove `listen-address` directive

### PR DESCRIPTION
**Pull request by dschaper**
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**By submitting this pull request, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

- [x] 10 (very familiar)

---

Since we declare an `interface` `dnsmasq` should ignore the `listen-address` directive thus making redundant. Removed.

### CODE REVIEW

**Comment by PromoFaux** [comment]
Ah yeah, I forgot about this!

:shipit:

**Comment by PromoFaux** [comment]
Approved

**Comment by Fedora-Core** [comment]
Warning

Please read the manpages of DNSMasq first.
And the comments in the Original configuratie file.

Greetings,
Fedora-Core

**Comment by dschaper** [comment]
Should I ask Mr. Kelley directly?

**Comment by dschaper** [comment]
NM, message received...

**Comment by dschaper** [comment]
Reverting to further test if this is behavior we want or if there is another flow that would work.

**Comment by dschaper** [comment]
This shouldn't matter, if it's removed then the `dnsmasq` only listens on the interface, which is what we want. The localhost would use `/etc/resolv.conf` anyways, as we don't want the Pi to query itself, if the `dnsmasq` process stops, we still need the Pi to resolve in order to operate and download an update if needed. 

Testing process, just turn off the `dnsmasq` completely and see if Pi resolves, and it does, via `/etc/resolv.conf` given resolvers. If `/etc/resolv.conf` contains only `127.0.0.1` then that's a separate issue we need to address.

This means that all communication to the `dnsmasq` process needs to occur over the requested interface, the debugger can't poll 127.0.0.1 anymore, not a big deal. We have the addresses in `setupVars.conf` of IPv4 and IPv6 to poll.

F.C., any fault to this logic? Checking to see if we set a static 127.0.0.1 address and we set `static domain_name_servers=$IPv4gw` which will never be `127.0.0.1` from what I can see?

**Comment by dschaper** [comment]
```
root@ubuntu-512mb-nyc1-01:/etc/.pihole/automated install# cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.0.1
root@ubuntu-512mb-nyc1-01:/etc/.pihole/automated install# sudo systemctl stop dnsmasq
root@ubuntu-512mb-nyc1-01:/etc/.pihole/automated install# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=61 time=1.47 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=61 time=1.32 ms
^C
--- 8.8.8.8 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 1.323/1.399/1.476/0.085 ms
root@ubuntu-512mb-nyc1-01:/etc/.pihole/automated install# ping www.google.com
PING www.google.com (216.58.219.196) 56(84) bytes of data.
64 bytes from lga25s40-in-f196.1e100.net (216.58.219.196): icmp_seq=1 ttl=59 time=1.52 ms
64 bytes from lga25s40-in-f196.1e100.net (216.58.219.196): icmp_seq=2 ttl=59 time=1.65 ms
^C
--- www.google.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 1.525/1.588/1.652/0.074 ms
root@ubuntu-512mb-nyc1-01:/etc/.pihole/automated install# dig www.google.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> www.google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14233
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.google.com.                        IN      A

;; ANSWER SECTION:
www.google.com.         299     IN      A       216.58.219.196

;; Query time: 18 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Oct 27 19:32:10 UTC 2016
;; MSG SIZE  rcvd: 59
```

**Comment by dschaper** [comment]
```
root@ubuntu-512mb-nyc1-01:/etc/.pihole/automated install# cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.0.1
root@ubuntu-512mb-nyc1-01:/etc/.pihole/automated install# dig www.google.com

;; ANSWER SECTION:
www.google.com.         250     IN      A       216.58.219.196

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Oct 27 19:35:41 UTC 2016

root@ubuntu-512mb-nyc1-01:/etc/.pihole/automated install# cat /etc/dnsmasq.d/01-pihole.conf
address=/pi.hole/10.10.0.5
address=/pi.hole/fe80::c894:ebff:fee1:cbf2
address=/ubuntu-512mb-nyc1-01/10.10.0.5
address=/ubuntu-512mb-nyc1-01/fe80::c894:ebff:fee1:cbf2
addn-hosts=/etc/pihole/gravity.list
domain-needed
bogus-priv
no-resolv
server=8.8.8.8
server=8.8.4.4
interface=eth0
cache-size=10000
log-queries
log-facility=/var/log/pihole.log
local-ttl=300
log-async
```
No localhost listener directive included.

**Comment by J-Papa** [comment]
Hi guys, great work on the Pi-Hole so far!
Don't know if I have to post this here of create a new issue.

I'm having the following problem occurring since the listen-address has been removed.
The situation is this:
Both my VPN and PiHole are on the same device. PiHole wasn't working on the VPN so I changed the listen-address in 01-pihole.conf from 127.0.0.1 to 192.168.1.20
This resolved the issue and gave the benefit of the PiHole on both eth0 and tun0.

Now of course this has changed again :/

Do you perhaps have a (better) solution for me in this case without having to move the VPN to a different device?

**Comment by dschaper** [comment]
Since the `01-pihole.conf` is a file that is subject to change (often) I would suggest a new configuration file for you. `99-jpapa.conf` with just your `listen-address` directive will override anything, but since we removed the directive, you shouldn't have any problems with a new directive. Then run `service dnsmasq restart` or `systemctl restart dnsmasq` depending on your OS (may need sudo for those) and you should be back to business, without worrying about us changing configurations on you in the future.

**Comment by J-Papa** [comment]
Hi dschaper, thanks for your quick reply.
Can I just create this file next to 01-pihole.conf with only the listen-address in it?
So that it uses both files? Or should I remove the 01-pihole.conf so that I have only the 99-jpapa.conf in the directory?

**Comment by dschaper** [comment]
Both files in the same directory, it will load `01` first and then `99` last with the latest directives taking precedence. (Some commands will cause an error if duplicated, but you shouldn't be needing to configure any of those.)

**Comment by J-Papa** [comment]
Did as you suggested and it works like a charm! Thank you very much!

**Pull request merged**
