### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by roots84**
Adding DNS-Swapper Project back after it was accidently removed

**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'development' branch!}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [] I have made only one major change in my proposed changes.
- [] I have commented my proposed changes within the code.
- [] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#git-commit---signoff))

---

**What does this PR aim to accomplish?:**

`{A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues}`

**How does this PR accomplish the above?:**

`{A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix}`

**What documentation changes (if any) are needed to support this PR?:**

`{A detailed list of any necessary changes}`

> * `{Please delete this quoted section when opening your pull request}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand an issue quicker, but please ensure it's relevant.

### CODE REVIEW

**Comment by dschaper** [comment]
https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project

**Comment by roots84** [comment]
My apologies. I couldn't find a way to do the signoff via the GitHub webpage. Is that even possible?

**Comment by Mcat12** [comment]
You would have to manually enter it at the bottom. To fix this instance, you should force-push the fixed commit to the branch. See the link posted above for more information.

**Comment by roots84** [comment]
Well, I'm giving up. Can we just close this PR and I create a new one?
And you might want to add to the Sign Off Documentation that the name and GitHub-internal email is required for the signoff instead of the username and real email.

**Comment by Mcat12** [comment]
We've disabled the signoff bot from the required list of checks since it's been being a bit too strict. While we look into making it less strict, we can still accept your changes as they are.

**Pull request merged**
