### PR TITLE
New Core Help text

### PR DESCRIPTION
**Pull request by WaLLy3K**
**By submitting this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

10

---

I've [separated out the commits](https://github.com/WaLLy3K/pi-hole/commits/newCoreOutput/pihole) to try and make it easier to review, because there's a bunch of changes. Detailed changes can be found on each commit

* Remove `::: ` from text output
* Update help text wording
* Add `pihole --help` as another option for help text
* Double brace all conditionals for consistency
* Accept `pihole -q -exact <url>` as valid
* Silence potential `pihole -q` errors if something like `pihole -q -foo` is used
* Add help text option to `pihole enable`, `pihole logging` and `pihole checkout`
* Altered text output for `pihole tail`

### CODE REVIEW

**Comment by PromoFaux** [comment]
>Remove ::: from text output

I put these in originally to make the output of the install script stick out from normal CLI text. It then just became a thing throughout the entire project. What I would DEARLY love to have the time to figure out is coloured output.

**Comment by WaLLy3K** [comment]
I thought about coloured output (I can throw something like that in with ease), but I feel it's time we start making the project look more professional, and standardised with more "unix-like" output.

To be fair, it's something we probably need more of a discussion on :smile:

**Comment by dschaper** [comment]
Please go easy on the `tput` :)

**Comment by WaLLy3K** [comment]
I'm going to work on this more and separate the stuff I'd like to fix better.

**Pull request closed without merging**
