### PR TITLE
[Ready for check and merge] Centos6 install fixes

### PR DESCRIPTION
**Pull request by brontide**
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**By submitting this pull request, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

- [ ] 1 (very unfamiliar)
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [X] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10 (very familiar)

---

This allows the basic install to run to completion on centos6, it warns about the webui but does nothing to fix it right now.

Before

```
ewarnke@eric-cb:~$ lxc exec pihole-centos6 -- bash
[root@pihole-centos6 ~]# curl -L https://install.pi-hole.net | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0:::
::: You are root.
100 35295  100 35295    0     0  77150      0 --:--:-- --:--:-- --:--:-- 77150
::: Verifying free disk space...
df: `/sys/kernel/debug/tracing': Permission denied
:::
::: yum update has not been run today. Running now... done!
:::
::: Checking yum for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with Pi-hole installation...
:::    Checking for iproute... installed!
:::    Checking for net-tools... installed!
:::    Checking for procps-ng...[root@pihole-centos6 ~]# 
```

after

```
[root@pihole-centos6 ~]# more /etc/pihole/install.log 
::: Checking if user 'pihole' exists...
::: User 'pihole' doesn't exist. Creating...

:::	Warning: 'lighty-enable-mod' utility not found. Please ensure fastcgi is enabled if you experience issues.
:::
::: Installing scripts to /opt/pihole... done.
:::
::: Installing configs...
:::    Existing dnsmasq.conf found... it is not a pi-hole file, leaving alone!
:::    Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf... done.
:::
::: Creating log file and changing owner to dnsmasq... done!
:::
::: Installing pihole custom index page...
:::	No default index.lighttpd.html file found... not backing up done!
::: Installing sudoer file... done!
:::
::: Installing latest Cron script... done!
::: Configuring iptables for httpd and dnsmasq..
:::
::: Preparing to run gravity.sh to refresh hosts...
::: Running gravity.sh
:::
::: Neutrino emissions detected...
:::
::: No custom adlist file detected, reading from default file... done!
:::
::: Existing pihole directory found
:::
::: Getting raw.githubusercontent.com list... List updated, transport successful!
::: Getting mirror1.malwaredomains.com list... List updated, transport successful!
::: Getting sysctl.org list... List updated, transport successful!
::: Getting zeustracker.abuse.ch list... List updated, transport successful!
::: Getting s3.amazonaws.com list... List updated, transport successful!
::: Getting s3.amazonaws.com list... List updated, transport successful!
::: Getting hosts-file.net list... List updated, transport successful!
::: Getting raw.githubusercontent.com list... List updated, transport successful!
::: Getting ransomwaretracker.abuse.ch list... List updated, transport successful!
::: 
::: Aggregating list of domains... done!
::: Formatting list of domains to remove comments.... done!
::: 126184 domains being pulled in by gravity...
::: Removing duplicate domains.... done!
::: 102096 unique domains trapped in the event horizon.
::: Formatting domains into a HOSTS file...
:::
::: Adding 9 adlist sources to the whitelist... done!
::: Running whitelist script to update HOSTS file.... 7 domains whitelisted!
::: Running blacklist script to update HOSTS file.... 0 domains blacklisted!
:::
::: Cleaning up un-needed files... done!
:::
::: Refresh lists in dnsmasq...Starting dnsmasq:           [  OK  ]
```

Validated on

- debian 8 ( sysvinit not systemd )
- debian sid
- centos 6 ( non working web-ui )
- centos 7
- ubuntu 16.04
- ubuntu 16.10
- fedora 24

Tried but failed validation on

- debian 7 - fails install due to lack of iproute2 package ( should be iproute )
- ubuntu 14.04, fetching random js file does not return index.js

### CODE REVIEW

**Comment by dschaper** [comment]
Thank you. This may help us keep CentOS support going for a while longer. We'll take a look at the code, just Label it when you're ready for a review!

**Comment by brontide** [comment]
Sorry.. new to this... label?

**Comment by dschaper** [comment]
Yes, on the right hand side of the page there should be some items like "Labels" "Assignees" and the like. Under labels, there is one called "Ready for Check and Merge" and that signals us that code review is ready to start. Just helps us out with getting things when they are ready.

**Comment by brontide** [comment]
Yes, I see the are ... it says "None yet" and doesn't allow me to select it.  The code is ready for check-in or I would not have issued a pull.  I figure small incremental changes are better than a larger hit.

**Comment by dschaper** [comment]
My mistake if the users aren't allowed to label, I'll check on that. And yes smaller and more often is better than omnibus. I'll flag it for now, thanks.

**Comment by brontide** [comment]
Continuing development.  This allows the installer to complete on debian7 based hosts which do not have iproute2 but iproute.  This will install on everything I've tested but the webui/api is broken on C6 and lighttpd does not return the javascript payload on ubuntu 14.04 and debian 7 ( suspect lighttpd config, will investigate ).

**Comment by PromoFaux** [comment]
@brontide I've tagged your title as `[WIP]` based on the above comment. When you have done everything you need, then feel free to remove that part of the title!

**Comment by brontide** [comment]
Each pull is ready when you are to review and integrate.  If you don't want smaller patches it will get bigger.

**Comment by PromoFaux** [comment]
Happy for smaller patches, I was just going on your comment above where you said "Continuing Development"

**Comment by brontide** [comment]
Honestly I'll keep pulling and you should tell me when you are ready to review.  I was just hoping to keep the drift to a minimum since basic-installer.sh seems like a high-traffic area.  I've got cleanup currently working through a battery of tests against 9 distros.

**Comment by PromoFaux** [comment]
OK. Stop pushing to this PR for now, and I'll test it out. on Centos 6/7 and fedora. You haven't touched any of the debian-family stuff I don't think...?

**Comment by brontide** [comment]
There is a wheezy dependency fix to allow installation.

**Comment by PromoFaux** [comment]
OK, I'll check it out!

**Comment by PromoFaux** [comment]
### Centos 6 
No `nc`, cannot upload debug log, doesn't actually appear to be blocking, but that could be something to do with this DO droplet... Debug script looks up doubleclick OK and shows as blocked. Web does not work.. expected.

### Centos 7 [Debug log](http://termbin.com/3ka7). 
```
/opt/pihole/piholeDebug.sh: line 206: lsof: command not found
/opt/pihole/piholeDebug.sh: line 207: lsof: command not found
```

Web interface loads.

### Fedora 23 [Debug log](http://termbin.com/330a)
Lots of perl warnings about setting locale (I have NO fedora experience so... I'm lost here) Could be down to the DO droplet
interface loads.

### Fedora 24 [Debug log](http://termbin.com/nwc7)

Same as above

### Wheezy

Well, DO is just not playing ball at all here!

Someone else may wish to do some more thorough testing...

**Comment by brontide** [comment]
Do you have the log for wheezy?  I'll find out where nc and lsof are hiding and update deps.

What is DO/Droplets?

**Comment by brontide** [comment]
I see, Digial Ocean VM systems.  Start one up, run the script and then capture the debug log?

**Comment by brontide** [comment]
I added nc, lsof to my host to generate [debug log](http://termbin.com/3eh7)

**Comment by brontide** [comment]
Centos 7 [debug log](http://termbin.com/03es)

**Comment by brontide** [comment]
OK... going to do another pull once I run these changes through my testing.

**Comment by PromoFaux** [comment]
With wheezy, it got as far as `dhcpcd5` in the install script before bugging out. Though this is a known issue with debian DO droplets, so I wasn't holding out much hope

```
Could not resolve 'mirrors.digitalocean.com'
Err http://mirrors.digitalocean.com wheezy-updates Release.gpg
  Could not resolve 'mirrors.digitalocean.com'
Reading package lists... Done
W: Failed to fetch http://mirrors.digitalocean.com/debian/dists/wheezy/Release.gpg  Could not resolve 'mirrors.digitalocean.com'

W: Failed to fetch http://security.debian.org/dists/wheezy/updates/Release.gpg  Could not resolve 'security.debian.org'

W: Failed to fetch http://mirrors.digitalocean.com/debian/dists/wheezy-updates/Release.gpg  Could not resolve 'mirrors.digitalocean.com'

```

**Comment by brontide** [comment]
Here are the results from this most recent test ( and what is pushed )

- Centos 6 [debug log](http://termbin.com/rdbw) - no admin interface because php5.3
- Centos 7 [debug log](http://termbin.com/gk3l) - fully functional, needed to run twice because it stopped at php for no apparent reason
- Debian sid [debug log](http://termbin.com/k29x) - needed iputils-ping installed, added to deps
- Debian 8 [debug log](http://termbin.com/j0kp) - installed ping otherwise perfect
- Debian 7 [debug log](http://termbin.com/3xdy) - copied lighttpd.conf in place for full function
- Ubuntu 14.04 [debug log](http://termbin.com/v122) - copied lighttpd in place for full function
- Ubuntu 16.04 [debug log](http://termbin.com/0qxa) 
- Ubuntu 16.10 [debug log](http://termbin.com/p6wp)
- Fedora 24 [debug log](http://termbin.com/22xp)

So all passed my validation tests.  Only Centos6 can't view the web admin panel.

**Comment by brontide** [comment]
Please check and give feedback.  I will try to keep future updates to feature branches

**Comment by brontide** [comment]
Fixes 

- updated deps for wheezy and rpm based systems
- there is an updated lighttpd.conf for fedora and debian based systems to fix the known bug in lighttpd
- remove iptables configuration, but should identify iptables and warn if it appears as though firewall is setup
- skip selinux stuff if it's disables

Debian wheezy and ubuntu 14.04 are now fully functional and it should install on Centos 6.

**Comment by PromoFaux** [comment]
>copied lighttpd.conf in place for full function

Is this an additional action needed to be carried out manually?

**Comment by brontide** [comment]
> Is this an additional action needed to be carried out manually?

Because the install pulls from the official repo, yes.  If you want the fix for wheeze and ubuntu 14.04 you have to copy the file into place manually until the patch hits the main area.

**Comment by brontide** [comment]
@PromoFaux I've been running into the occasional blip on containers as well that seemed random at first but I'm sensing a pattern.  I think in some cases the install trigger for dnsmasq will kill networking.  It must be restarted to continue.  I'm thinking of trying some code changes to pre-download the packages if a flag is passed to the script.

**Comment by PromoFaux** [comment]
The framework for passing flags to the install script is already there, so see what you can come up with!

Yeah, I've seen SSH terminals on digital ocean stop responding on the install of `dhcpcd5` before...

**Comment by brontide** [comment]
I have added a single line that allows for better testing.  I have set development as my default branch and I can not use it as a target for the script.  It defaults to the primary if not set ( tested ).

```
piholeGitUrl=https://github.com/brontide/pi-hole.git ./basic-install.sh
``` 

````
:::
::: Checking for existing repository...
:::    Checking /etc/.pihole is a repo...:::    Cloning https://github.com/brontide/pi-hole.git into /etc/.pihole... done!
:::
````

**Comment by PromoFaux** [comment]
When I'm installing from a clean slate for testing I usually:

```
git clone https://github.com/pi-hole/pi-hole.git /etc/.pihole
cd /etc/.pihole
git checkout <branchIwantToTest>
./automated\ install/basic-install.sh
```

Otherwise, I have my IDE (InteliJ Idea), set up with directory mirroring on `/etc/.pihole` and then either run the script manually from there, or run `pihole -r` to install without updating repos from web....

**Comment by brontide** [comment]
You know, things that would be nice to add to the contributed guide.  :-)

**Comment by brontide** [comment]
I'm going to close this and break them down again.  I just get started and sometimes I don't know when to quit.

**Pull request closed without merging**
