### PR TITLE
[WIP] Add script for non-piholed links

### PR DESCRIPTION
**Pull request by shadiakiki1986**
Fixes https://github.com/pi-hole/pi-hole/issues/732

Changes proposed in this pull request:
- added php script that gets queries that were not pi-holed

@pi-hole/gravity

### CODE REVIEW

**Comment by shadiakiki1986** [comment]
This PR was not made to the `development` branch. I will close it and make a new PR

**Comment by shadiakiki1986** [comment]
So it turns out that I can change the base branch from github. Reopening PR

**Comment by PromoFaux** [comment]
This is a neat script! But I'm afraid that with [this pull request](https://github.com/pi-hole/pi-hole/pull/731) going through finer tests before merge.. it may be a little redundant....

To give you a head-start [take a look at my comment here](https://github.com/pi-hole/pi-hole/issues/732#issuecomment-250588191) . That's all that will be needed to produce the same output :)

**Comment by shadiakiki1986** [comment]
I tried to test your [https://github.com/pi-hole/pi-hole/pull/731](#731), but I couldn't find a file `/etc/pihole/pihole.db`. [https://github.com/shadiakiki1986/test-pihole-db](Here) is what I did

**Comment by PromoFaux** [comment]
what's the output of `cat /etc/pihole/intsall.log`?

**Comment by shadiakiki1986** [comment]
http://paste.debian.net/851373/

**Comment by PromoFaux** [comment]
OK, looks like that ran the correct update. A

`ls -l /etc/pihole`

**Comment by shadiakiki1986** [comment]
http://paste.debian.net/852089/

**Comment by shadiakiki1986** [comment]
btw, I noticed that
```
root@9599a68012d4:/etc/.pihole# pihole -g
/usr/local/bin/pihole: line 129: /opt/pihole/gravity.sh: No such file or directory
```
and
```
root@9599a68012d4:/etc/.pihole# ./pihole -g
./pihole: line 129: /opt/pihole/gravity.sh: No such file or directory
```
and
```
root@9599a68012d4:/etc/.pihole# pihole -q bla
grep: /etc/pihole/list.*: No such file or directory
::: /etc/pihole/list.* (0 results)
```
shows that `pihole` is trying to grep in the text files instead of the `pihole.db` file

**Comment by PromoFaux** [comment]
Hmm, I will also take a look at this!

**Comment by PromoFaux** [comment]
Something has messed up with your install there... for starters you're missing `gravity.sh`

What branch are you on currently?

Also yeah `pihole -q` is supposed to parse those list files as they are the master lists, and the command is to give an indication as to which list a given blocked domain came from.

The gravity domains stored in /etc/pihole/pihole.db are there as a lookup table purely for the web interface's `queries.php` https://github.com/pi-hole/AdminLTE/blob/dbIntegrate/server.php#L51

**Comment by shadiakiki1986** [comment]
I was on the db  branch, just like you mention in the first comment on the
pull request (marked "testing")

**Comment by PromoFaux** [comment]
Try killing it off and starting that again:
```
cd /etc/
sudo rm -rf .pihole
sudo git clone https://github.com/pi-hole/pi-hole.git .pihole
cd .pihole
sudo git checkout db
./automated\ install/basic-install.sh
```
Then you should see this screen
image

**Comment by Mcat12** [comment]
What's the situation on this PR?

**Comment by shadiakiki1986** [comment]
I got busy this past week. Will try PromoFaux's latest comment this evening

**Comment by shadiakiki1986** [comment]
So I managed to get the update (with a slightly different formatted screen), but I still don't have a `/etc/pihole/pihole.db`.  Now the `pihole -q` doesnt give a `grep: /etc/pihole/list.*: No such file or directory`. Here is some output, and [here](https://github.com/shadiakiki1986/test-pihole-db) is the repository where I'm trying to reproduce the `.db` file

```
root@6b3a0dc94019:/etc/.pihole# pihole -q blablabla  
::: /etc/pihole/list.0.raw.githubusercontent.com.domains (0 results)
::: /etc/pihole/list.1.mirror1.malwaredomains.com.domains (0 results)
::: /etc/pihole/list.2.sysctl.org.domains (0 results)
::: /etc/pihole/list.3.zeustracker.abuse.ch.domains (0 results)
::: /etc/pihole/list.4.s3.amazonaws.com.domains (0 results)
::: /etc/pihole/list.5.s3.amazonaws.com.domains (0 results)
::: /etc/pihole/list.6.hosts-file.net.domains (0 results)
::: /etc/pihole/list.7.raw.githubusercontent.com.domains (0 results)
::: /etc/pihole/list.8.ransomwaretracker.abuse.ch.domains (0 results)



root@6b3a0dc94019:/etc/.pihole# ls -l /etc/pihole
total 7916
-rw-rw-rw- 1 root root    3172 Oct 15 10:15 adlists.default
-rw-rw-rw- 1 root root       0 Oct 15 10:08 blacklist.txt
-rw-rw-rw- 1 root root 4001629 Oct 15 10:15 gravity.list
-rw-rw-rw- 1 root root      44 Oct 15 10:10 install.log
-rw-rw-rw- 1 root root  941178 Oct 15 10:15 list.0.raw.githubusercontent.com.domains
-rw-rw-rw- 1 root root  276522 Oct 15 10:07 list.1.mirror1.malwaredomains.com.domains
-rw-rw-rw- 1 root root  656158 Oct 15 10:08 list.2.sysctl.org.domains
-rw-rw-rw- 1 root root    8746 Oct 15 10:08 list.3.zeustracker.abuse.ch.domains
-rw-rw-rw- 1 root root     613 Oct 15 10:08 list.4.s3.amazonaws.com.domains
-rw-rw-rw- 1 root root   43642 Oct 15 10:08 list.5.s3.amazonaws.com.domains
-rw-rw-rw- 1 root root 1827029 Oct 15 10:08 list.6.hosts-file.net.domains
-rw-rw-rw- 1 root root  278255 Oct 15 10:15 list.7.raw.githubusercontent.com.domains
-rw-rw-rw- 1 root root   31934 Oct 15 10:15 list.8.ransomwaretracker.abuse.ch.domains
-rw-rw-rw- 1 root root      16 Oct 15 10:07 piholeIP
-rw-rw-rw- 1 root root      37 Oct 15 10:07 setupVars.conf
-rw-rw-rw- 1 root root     144 Oct 15 10:08 whitelist.txt


root@6b3a0dc94019:/etc/.pihole# ls /etc/pihole/pihole.db
ls: cannot access /etc/pihole/pihole.db: No such file or directory



root@6b3a0dc94019:/etc/.pihole# cat /etc/pihole/install.log
:::
::: Installing scripts to /opt/pihole...


root@6b3a0dc94019:/etc/.pihole# ls /opt/pihole
blacklist.sh  chronometer.sh  gravity.sh  pihole  piholeDebug.sh  piholeLogFlush.sh  setupLCD.sh  version.sh  whitelist.sh


root@6b3a0dc94019:/etc/.pihole# less /tmp/pihole-install.log
/tmp/pihole-install.log: No such file or directory
```

**Comment by PromoFaux** [comment]
Yeah, there has been a large focus on the base install script this past week, so a few things will have changed with the dialogs, which I've since pulled into the `db` branch so I can continue testing it!

It might be a safe bet to uninstall manually install the `db` branch.. something has gone wrong somewhere and is causing `pihole.db` to not be created. Starting from scratch is sometimes the best way forward...

`pihole uninstall` (choose no so you don't have to remove all the dependencies)
`sudo git clone https://github.com/pi-hole/pi-hole.git /etc/.pihole`
`cd /etc/.pihole`
`sudo git checkout db`
`./automated\ install/basic-install.sh`

**Comment by PromoFaux** [comment]
Oh hold on, Are you trying to do this with the docker image? I'm not sure how `db` fits into that... @diginc  will know!

**Comment by shadiakiki1986** [comment]
Yes I am using the docker image.
I tried to uninstall and re-install ... same thing.
In any case, I noticed the following during my installation
```
...
:::    Checking for netcat... installed!
:::    Checking for cron... installed!
:::    Checking for iproute2... installed!
install: invalid user ''       <<<<<<<<<<<<<<<<<<<<<<<<<<<<<
:::
::: Installing scripts to /opt/pihole...::: Restarting services...:::
::: Starting dnsmasq service... done.
...
```

**Comment by PromoFaux** [comment]
Might be best to wait for diginc, though I imagine he'll be a few hours as he's in the US.

**Comment by diginc** [comment]
Install/uninstall in the container us not really supported since I imitate the install during image creation.  The docker image can be developed with using my docker-pi-hole repo using docker image builds.  Simply clone recursively, go into the subrepo for pihole and make the changes you need (or goto the branch).  Then build the image you're working with: `docker build -f debian.docker diginc/pi-hole:debian`

After that destroy and up a new container based off the fee rebuilt IMG.

If you're specifically testing install or upgrade code I'd suggest just running a `debian:jessie` container then running the install.

**Comment by PromoFaux** [comment]
@shadiakiki1986 Closing for now, thanks for your submission.

**Pull request closed without merging**
