### PR TITLE
Adds OS and version to output if unsupported OS is detected

### PR DESCRIPTION
**Pull request by yubiuser**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**
Before: [✗] Unsupported OS detected
After: [✗] Unsupported OS detected: Linux Mint 19.3

**How does this PR accomplish the above?:**
Re-uses `$detected_os_pretty`

**What documentation changes (if any) are needed to support this PR?:**
No.

Rebase for https://github.com/pi-hole/pi-hole/pull/3567

### CODE REVIEW

**Comment by PromoFaux** [comment]
Rebase please, following #3596

**Comment by dschaper** [comment]
This now has a merge conflict. Let us know if you want some guidance on resolving it @yubiuser. This one is pretty basic but conflicts can be messy.

**Comment by yubiuser** [comment]
@dschaper Some guidance would be great. Don't want to mess it up again.

**Comment by dschaper** [comment]
Two options, you can rebase on to the updated `release/v5.1.2` branch or I can do the merge conflict for you. 

My suggestion is to try rebase and then if that goes wrong we can fix/do a new PR.

**Comment by yubiuser** [comment]
I think the conflict is resolved.

**Comment by dschaper** [comment]
Branch is outside the Pi-hole Org, Travis build will not fire. Overriding.

**Pull request merged**
