### PR TITLE
Change the word "folder" to "directory" since the pi-hole is intended…

### PR DESCRIPTION
**Pull request by borats**
Change the word "folder" to "directory" since the pi-hole is intended to run on rpi with Linux on it.

Signed-off-by: Borats Nolan <borats@i.dont.use.email>

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*

Change the word "folder" to "directory" since the pi-hole is intended to run on rpi with Linux on it.

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*

Change the word "folder" to "directory" since the pi-hole is intended to run on rpi with Linux on it.

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*

Change the word "folder" to "directory" since the pi-hole is intended to run on rpi with Linux on it.

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by borats** [comment]
@Mcat12 Are you new to Linux and/or any *NIX ? LMGTFY https://superuser.com/questions/169457/directory-vs-folder. This link clearly describes what a `directory` is.  When you run a software on *NIX, please use the terminologies that are *NIX native. Thanks!

**Comment by Mcat12** [comment]
Every other answer on that page does not note any real distinction between the two, besides that they are usually used in one place or the other.

It is a highly pedantic issue, but since it is just a change in comment wording it is fine.

I invite you to read over the contributor's guide again, noting especially:
> - Pi-hole is open source and [powered by donations](https://pi-hole.net/donate/), and as such, we give our **free time** to build, maintain, and **provide user support** for this project.  It would be extremely unfair for us to suffer abuse or anger for our hard work, so please take a moment to consider that.
> - Please be considerate towards the developers and other users when raising issues or presenting pull requests.

Pi-hole is made for Linux systems, and "LMGTFY" is not what I would call considerate.

**Comment by borats** [comment]
@Mcat12 I don't find `LMGTFY` as a derogatory term 👍 . It means *Let Me Google That For You*. You were probably unable to find documentation on why Linux uses the term `directory` as opposed to `folder` (a word that originates elsewhere e.g., NeXT/Apple/Windows) for reason unbeknownst to me or you probably didn't know the difference. That's fine, lot of other people still use the word interchangeably. But, I want to bring clarity to the shell script that runs on Linux and not sit on github arguing with someone about the reasons why Linux uses the term `directory` as opposed to `folder`. Again, if you feel a bit let down then be rest assured that it was not my intention. It was just a frank, light-hearted discussion aimed at bringing clarity and nothing more 😃

**Comment by borats** [comment]
> Every other answer on that page does not note any real distinction between the two, besides that they are usually used in one place or the other.

https://superuser.com/questions/187900/what-is-the-difference-between-a-directory-and-a-folder

**Pull request merged**
