### PR TITLE
chg: cmdline teleporter wrote tar.gz content to file suffixed .zip, w…

### PR DESCRIPTION
**Pull request by corbolais**
…rite as .tar.gz now.

Signed-off-by: corbolais <corbolais@gmail.com>

### CODE REVIEW

**Comment by dschaper** [comment]
Please review the template and instructions provided for you when you opened the Pull Request.

Thank you.

**Comment by corbolais** [comment]
@dschaper Please have at least a look at the PR. It is most minor. Please do not waste anyone's time having to fiddle with your extensive forms for most trivial PRs.
Thank you.

**Comment by dschaper** [comment]
There's a reason for our "extensive" forms. If you don't follow the instructions, it will not pass the CI build, and will not be merged. Master branch is also protected and this will not merge to master.

**Comment by corbolais** [comment]
Sorry, fix your CI build then.
Users contributing PRs shouldn't be forced to submit to such processes, this borders to harassment. And if it is a trivial one all the more so.
Why should CI fail after all, it's even signed-off.
If you want the source be improved, add this trivial PR yourself or let it continue to be faulty as it was.
This is nothing personal. It's about process enforcement where it is counter-productive.

**Comment by PromoFaux** [comment]
@corbolais Dan was being nice. He asked you nicely to follow the template.

You can't be bothered to read the template, we can't be bothered to read you proposal.

>this borders to harassment. 

Get a hold of yourself.

**Pull request closed without merging**
