### PR TITLE
Give user the choice to install web admin or not

### PR DESCRIPTION
**Pull request by PromoFaux**
**By submitting this pull request, I confirm the following (please check boxes, eg [X])Failure to fill the template will close your PR:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

- [x] 10 (very familiar)

---

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by DL6ER** [comment]
Ready for check, review, approve and merge?

**Comment by PromoFaux** [comment]
Certainly ready for scruity!

**Comment by Mcat12** [comment]
Approved

**Comment by PromoFaux** [comment]
just realised update.sh is going to need an overhaul here. :sigh:

**Comment by PromoFaux** [comment]
Only issue I'm facing now is that gravity does not download any of the lists on the first run after choosing not to install the web admin.

Subsequent runs of `pihole -g` work fine. 

This bug does not exist in current development branch, so it's clearly something I've introduced!

**Comment by PromoFaux** [comment]
^ that does the trick

**Comment by dschaper** [comment]
Will need to adjust #930 to no longer hard fail if web is missing. (Noted for Dan to track.)

**Comment by Mcat12** [comment]
Approved

**Comment by PromoFaux** [comment]
>Will need to adjust #930 to no longer hard fail if web is missing. (Noted for Dan to track.)

Do I need to make any changed to the debug script in this PR?

**Comment by dschaper** [comment]
Shouldn't need to, the current script will just report missing repo. The next iteration of the debug will have to be adjusted to not report a fatal error if the repo is missing, but not sure yet how to tell if the repo is intentionally missing or borked missing.

**Comment by DL6ER** [comment]
There will be
```
INSTALL_WEB=false
```
in `setupVars.conf`

**Comment by Mcat12** [comment]
Approved

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-2-13-core-2-5-web/2004/1

**Pull request merged**
