### PR TITLE
added whitelist wildcard

### PR DESCRIPTION
**Pull request by phynias**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?: 

2

---
Add wild card whitelist support_

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by WaLLy3K** [comment]
Hey @phynias, thanks for the PR! Couple of things:

* I've updated the base branch to be `development` and not `master`, as we only accept PR's into dev
* `gravity.sh` has undergone a major rewrite, so could you please [grab the latest version](https://github.com/pi-hole/pi-hole/blob/master/gravity.sh) and add your changes to that?
* Could you add some use case scenarios, and any testing you've performed on this?

Cheers

**Comment by Mcat12** [comment]
It might be easier to merge development into your branch instead of manually updating the file. Run:
```
git merge --no-ff development
```

You will probably have to deal with merge conflicts, but there's plenty of resources available online for that.

**Comment by phynias** [comment]
yeah putting into the new gravity.sh, the problem i am having now is when i run gravity.sh it never really runs. it gets to 
"Waiting up to ${secs} seconds before continuing..."

and never moves on. i think it has to do with my dev happens in a docker container and the new code isn't working in it for some reason.

**Comment by Mcat12** [comment]
@phynias Have you been able to get gravity working since your last comment?

**Comment by phynias** [comment]
i actually got it working in the newer version of gravity.sh. if you want i can make a new pull request based on the latest development branch. or update this. let me know what is better for you.

**Comment by Mcat12** [comment]
Making a new one based on development would be best, although you may also want to look at FTLDNS and/or talk to @DL6ER to see if this could be implemented in the resolver.

**Comment by DL6ER** [comment]
I'm not entirely sure what this PR tries to achieve, from looking at the code, I'd say that `se` in `whitelist_wild.txt`, all domains in `gravity.list` that contain this string would get removes, including things like
```
googleadservices.com
sendmail.com
somethingse.com
gosego.com
...
```
while this has no influence on the wildcard blocked domains which I find a bit confusing given the title "added whitelist wildcard".

**Comment by dschaper** [comment]
Closing, no activity.

**Pull request closed without merging**
