### PR TITLE
[WIP] Add option to update to development version

### LINKED ISSUE #948: Feature request: Add option to update to development version
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).

**How familiar are you with the codebase?:**

- [X] 9

---
**[FEATURE REQUEST]:**

There are often quite some changes in the `development` branch which mostly fix a lot of open issues for several users. However, many of the users who are rather inexperienced with `git` are not able to benefit immediately. Also, they cannot test themselves if the change we merge into `development` actually suits their needs.

I propose to add an option to be able to easily update pi-hole and the dashboard to the latest `development` / `devel` version for those who are willing to test this.

Example:
`pihole -development`

I'm working on this additional feature right now.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your PR:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

- [X] 9 (quite familiar)

---
Fixes #948

I works fine on my Raspberry Pi B+

<pre>
pi@raspberrypi:/etc/.pihole# sudo pihole development
::: Checking for updates...
<b>::: Updating Everything to development version</b>
:::
::: Be aware:
::: Running the development version is not recommended
::: for end-users. Do this only if you know what you are
::: doing. Note that this route is not officially supported
::: and you may end up with a system that is not fully
::: functional! If something breaks, you cannot expect
::: support from the developers. Furthermore, you may not
::: be able to switch back to the master branch easily.
::: If you switch and there are changes which prevent you
::: from chaning back to master, you will have to perform a
::: full installation again.   
::: Note that, though this is possible, it is not recommended!
:::
::: Are you sure you want to continue? [yes/N] yes
:::
::: Checking for existing repository...
:::     Updating repository in /etc/.pihole... done!
<b>:::     Checking out repository in /etc/.pihole to branch development... done!</b>
:::
::: Checking for existing repository...
:::     Updating repository in /var/www/html/admin... done!
<b>:::     Checking out repository in /var/www/html/admin to branch devel... done!</b>
:::
::: You are root.
::: --unattended passed to install script, no whiptail dialogs will be displayed
::: Verifying free disk space...
:::
::: apt-get update has not been run today. Running now... done!
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: There are 9 updates available for your system!
::: We recommend you run 'apt-get upgrade' after installing Pi-Hole!
:::
:::    Checking for apt-utils... installed!
:::    Checking for whiptail... installed!
:::    Checking for git... installed!
:::    Checking for dhcpcd5... installed!
::: --reconfigure passed to install script. Not downloading/updating local repos
:::    Checking for iputils-ping... installed!
:::    Checking for lsof... installed!
:::    Checking for dnsutils... installed!
:::    Checking for bc... installed!
:::    Checking for dnsmasq... installed!
:::    Checking for lighttpd... installed!
:::    Checking for php5-common... installed!
:::    Checking for php5-cgi... installed!
:::    Checking for curl... installed!
:::    Checking for unzip... installed!
:::    Checking for wget... installed!
:::    Checking for sudo... installed!
:::    Checking for netcat... installed!
:::    Checking for cron... installed!
:::    Checking for iproute2... installed!
:::
::: Installing scripts from /etc/.pihole... done.
:::
::: Installing configs...
:::    Existing dnsmasq.conf found... it is not a pi-hole file, leaving alone!
:::    Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf... done.
:::
::: Creating log file and changing owner to dnsmasq... already exists!
:::
::: Installing pihole custom index page...
:::     Existing index.html detected, not overwriting
:::     Existing index.js detected, not overwriting
:::
::: Installing sudoer file... done!
:::
::: Installing latest Cron script... done!
::: Configuring iptables for httpd and dnsmasq..
:::
::: Preparing to run gravity.sh to refresh hosts...
::: Cleaning up previous install (preserving whitelist/blacklist)
::: Running gravity.sh
:::
::: Neutrino emissions detected...
:::
::: No custom adlist file detected, reading from default file... done!
:::
::: Getting raw.githubusercontent.com list... List updated, transport successful!
::: Getting mirror1.malwaredomains.com list... List updated, transport successful!
::: Getting sysctl.org list... List updated, transport successful!
::: Getting zeustracker.abuse.ch list... List updated, transport successful!
::: Getting s3.amazonaws.com list... List updated, transport successful!
::: Getting s3.amazonaws.com list... List updated, transport successful!
::: Getting hosts-file.net list... List updated, transport successful!
::: Getting raw.githubusercontent.com list... List updated, transport successful!
:::
::: Aggregating list of domains... done!
::: Formatting list of domains to remove comments.... done!
::: 129468 domains being pulled in by gravity...
::: Removing duplicate domains.... done!
::: 105358 unique domains trapped in the event horizon.
:::
::: Adding adlist sources to the whitelist... done!
::: Whitelisting 7 domains... done!
::: Blacklisting 0 domains... done!
::: Formatting domains into a HOSTS file... done!
:::
::: Cleaning up un-needed files... done!
:::
::: Refresh lists in dnsmasq... done!
::: Pi-hole blocking is Enabled
::: Restarting services...
:::
::: Starting dnsmasq service... done.
:::
::: Enabling dnsmasq service to start on reboot... done.
:::
::: Starting lighttpd service... done.
:::
::: Enabling lighttpd service to start on reboot... done.
::: done.
:::
::: Update complete!
:::
::: The install log is located at: /etc/pihole/install.log

pi@raspberrypi:/etc/.pihole# git branch
<b>* development</b>
  master

pi@raspberrypi:/etc/.pihole# cd /var/www/html/admin
pi@raspberrypi:/var/www/html/admin# git branch
<b>* devel</b>
  master

</pre>

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by DL6ER** [comment]
Need to make sure that it also works on an installation which has never pulled the `development` branches before!

**Comment by dschaper** [comment]
Development branch can, does and will break and may even borrow money without paying it back. There needs to be very strong wording with multiple warnings that this action is not supported and you're playing in your own sandbox if anything breaks. This will also need an update to the debugger to test for which branch you are on, as well as the warning that if you switch to development, you can not switch back to master, you will need to do a full install again. (Case in point, the setupVars.conf is formatted differently between branches and will continue to be updated and the two branches are not interchangeable with the formatting.)

**Comment by DL6ER** [comment]
@dschaper Whoops, you are right. I just copy-and-pasted it...

**Comment by dschaper** [comment]
If Phillip J Fry has been involved, and it's hasn't been through a ShellCheck, then there are possibly bugs that exist. I don't think the `retVal` is checked anywhere, or at least it hasn't been tested fully to catch a bad return. I haven't gotten to that script yet to run it through.

**Comment by dschaper** [comment]
How about a new branch for beta releases for users to test on. Things that are pretty reliable and will function, just need a few more installs and eyes to check the code before it goes out to Master. I'm not too eager to let out the development branch, that's meant now to be code that is mostly tested, but not fully checked so it will likely break. (It's the testing branch for us to use in development, and will be part of the CI when we get that up and running, so it's going to be red/green a lot.)

**Comment by DL6ER** [comment]
@dschaper I like the idea of having a separate `beta` branch where we could 'pre-release' things for those who want to contribute in testing things out!

And I also like leaving the `development` to the developers.

**Comment by PromoFaux** [comment]
Yeah I like this idea. +1 for the beta branch. We've got lots of new stuff that could do with being tested by a wider audience!

**Comment by DL6ER** [comment]
I looked through it again and conclude that this is quite dangerous and will most likely force some users to do a complete re-install if they are inexperienced with `git`. Will close this for now. We might come back to this in the future, though. This code has no merge conflicts at the point I close this PR.

**Pull request closed without merging**
