### PR TITLE
Change OS Detection in debug script

### PR DESCRIPTION
**Pull request by PromoFaux**
**By submitting this pull request, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**

Currently the supported/unsupported OS detection is based on the distro name being one of 5 set values, this is fine, but then we also need to check further. For example Raspbian <9 is not supported.

This PR adds that check.  I'd like to get a similar output into the installer if it fails, however I am starting to think that maybe the installer should prompt user to run and _read_ the debug log if an update fails.  Though obviously that won't necessarily work on a fresh install.

Examples using a Debian 10 (Buster) system:
`supportedos.txt` contains:
```
Raspbian=9,10
Ubuntu=16,18
Debian=9,10
Fedora=31,32
CentOS=7,8
```
Debug output:
image

`supportedos.txt` contains:
```
Raspbian=9,10
Ubuntu=16,18
Debian=9
Fedora=31,32
CentOS=7,8
```
Debug Output:
image

`supportedos.txt` contains:
```
Raspbian=9,10
Ubuntu=16,18
Fedora=31,32
CentOS=7,8
```
Debug Output:
image

### CODE REVIEW

**Comment by yubiuser** [comment]
From you example
> Debian=9
Distro is supported but version is not - please upgrade

Wording doesn't make sense if version > supported version

**Comment by PromoFaux** [comment]
`Debian=9`

The intention of this is not to say "Version 9 and up are supported", but rather "_only_ version 9 is supported", hence it fails the check when the detected version is `10`

Obviously in real life we support Debian 10, but this is just an demonstration of what the output would look like if the detected version is not listed.

**Comment by yubiuser** [comment]
Better but not perfect ;-)
You could check if ${os_version} is bigger or smaller than the biggest/smallest supported version and change the error accordingly (not yet supported/not supported - please upgrade)

**Comment by PromoFaux** [comment]
That's not too bad an idea. I'll have a think on it later

**Comment by PromoFaux** [comment]
I may change up some of the logic in this PR, actually, based on #3441

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-5-1-released/35577/1

**Pull request merged**
