### PR TITLE
User-friendly queryFunc() output

### PR DESCRIPTION
**Pull request by WaLLy3K**
**By submitting this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

10

---

Features:
 * User friendly query output, similar to master branch behaviour
 * Speedy query results (1.35s to perform `pihole -q doubleclick.net -exact` on 38MB of block lists compared to 1.33s on current dev branch and 7.59s on master)
 * `-adlist` option, to return the URL's of the block lists that contain the query
 * Positions of -exact and -adlist can be placed before or after the query
 * If a general query has over 10 matches in one file, the rest of the file is skipped
 * `-all` option, to remove match limit
 * `pihole -q --help` text
 * Grep errors are silenced

Tests:
 * `pihole -q -h`
 * `pihole -q doubleclick.com`
 * `pihole -q -exact doubleclick.com`
 * `pihole -q doubleclick.com -exact`
 * `pihole -q doubleclick.com -adlist -exact`
 * `pihole -q <whitelisted domain>`
 * `pihole -q <blacklisted domain>`
 * `pihole -q <wildcard domain>`
 
Output:
 
`pihole -q -h`
```
Usage: pihole -q [option] <domain>
Example: 'pihole -q -exact domain.com'
Query the adlists for a specified domain

Options:
  -adlist             Print the name of the block list URL
  -exact              Search the block lists for exact domain matches
  -all                Return all query matches within a block list
  -h, --help          Show this help dialog
```

`pihole -q doubleclick.com`
```
Result from list.5.v.firebog.net.domains
  doubleclick.com
  www.doubleclick.com
Result from list.14.v.firebog.net.domains
  ad-apac.doubleclick.com
  ad-emea.doubleclick.com
  ad.doubleclick.com
  ads.doubleclick.com
  advertisers.doubleclick.com
  advertisersapitest.doubleclick.com
  amazon.doubleclick.com
  betareportcentral.doubleclick.com
  click.comms.doubleclick.com
  doubleclick.com
  Over 10 results found, skipping rest of file
Result from list.52.v.firebog.net.domains
  doubleclick.com
```

`pihole -q -exact doubleclick.com` (and `pihole -q doubleclick.com -exact`)
```
Exact result in list.5.v.firebog.net.domains
Exact result in list.14.v.firebog.net.domains
Exact result in list.52.v.firebog.net.domains
```

`pihole -q doubleclick.com -adlist -exact`
```
Exact result in https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Exact result in http://sysctl.org/cameleon/hosts
Exact result in https://hosts-file.net/ad_servers.txt
```

`pihole -q <whitelist>`
```
Result from whitelist.txt
  www.dshield.org
::: No results found for www.dshield.org found within block lists
```

`pihole -q <blacklist>`
```
Result from blacklist.txt
  fullstory.com
Result from list.3.v.firebog.net.domains
  fullstory.com
Result from list.15.v.firebog.net.domains
  fullstory.com
```

`pihole -q <wildcard>`
```
Result from whitelist.txt
  3879194.fls.doubleclick.net
Result from 03-pihole-wildcard.conf
  *.doubleclick.net
::: Over 1000 results found for doubleclick.net found within block lists
```

`pihole -q <wildcard> -exact`
```
Wildcard result in 03-pihole-wildcard.conf *.doubleclick.net
Exact result in list.1.v.firebog.net.domains
Exact result in list.5.v.firebog.net.domains
```

`pihole -q -foo`
```
::: No results found for -foo found within block lists
```

### CODE REVIEW

**Comment by DL6ER** [comment]
Is this PR ready for reviewing?

**Comment by WaLLy3K** [comment]
Yeah, it's good to go.

**Comment by DL6ER** [comment]
?

```
pi@raspberrypi:~ $ pihole -q abc
Result from list.0.raw.githubusercontent.com.domains
  0.0.0.0
Result from static.contentabc.com
  static.contentabc.com
Result from list.0.raw.githubusercontent.com.domains
  0.0.0.0
Result from abclauncher.com
  abclauncher.com
Result from list.0.raw.githubusercontent.com.domains
  0.0.0.0
Result from abctoppictures.net
  abctoppictures.net
Result from list.0.raw.githubusercontent.com.domains
  0.0.0.0

[...]

Result from [Disney
  [Disney
Result from Company][ABC
  Company][ABC
Result from News][INFOSEEK]
  News][INFOSEEK]

[...]

Result from vod.mobile-abc.com
  vod.mobile-abc.com
Result from list.6.hosts-file.net.domains
  127.0.0.1
Result from www.abcjmp.com
  www.abcjmp.com
Result from list.6.hosts-file.net.domains
  127.0.0.1
Result from www.mobile-abc.com
  www.mobile-abc.com
```

`[ ... ]` = I removed similar stuff for the sake of convenience

**Comment by WaLLy3K** [comment]
Latest commit should fix all known issues with content found in public block lists

```
pihole -q abc
Result from blacklist.txt
  collector.abc-host.net.au
Result from list.0.raw.githubusercontent.com.domains
  static.contentabc.com
  abclauncher.com
  abctoppictures.net
  abc.xyz
  www.abc7.pl
  abcdg.pro
  abcdespanol.com
  abcstats.com
  abc.doublegear.com
  adsatt.abcnews.starwave.com
  Over 10 results found, skipping rest of file
Result from list.1.mirror1.malwaredomains.com.domains
  prod-abc.ro
  abc.yuedea.com
  abcmlm.com
  abcommunication.it
  bb01abc4net.com
  labconnectlc.com
  abc-check.com
  abconstructions.us
  abcosecurity.ca
  cn.abcibankcard.com
  Over 10 results found, skipping rest of file
```

**Comment by DL6ER** [comment]
Setting this on hold for now (marking as `[WIP]`)

**Comment by PromoFaux** [comment]
@WaLLy3K I just looked at fixing the conflicts on this, but I think it may be best if you do it, as you know your changes better!

**Comment by DL6ER** [comment]
@WaLLy3K What is the status of this PR?

**Comment by PromoFaux** [comment]
Approved

**Pull request merged**
