### PR TITLE
Adds FamilyShield DNS server address to the "Choose DNS" screen in installer.

### PR DESCRIPTION
**Pull request by justinamcafee**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x ] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [ x] I have made only one major change in my proposed changes.
- [x ] I have commented my proposed changes within the code.
- [x ] I have tested my proposed changes, and have included unit tests where possible.
- [x ] I am willing to help maintain this change if there are issues with it later.
- [x ] I give this submission freely and claim no ownership.
- [x ] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*
Added support for FamilyShield DNS from OpenDNS/CISCO.
With a very minor code change, individuals can now implement restrictions on dangers, disturbing, or otherwise adult oriented content without the need for managed restrictions.
This is a fairly non-invasive change and will benefit users who intend to use pi-hole for home or small business uses where access to such material may be undesirable.

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*
Adds FamilyShield DNS server address to the "Choose DNS Whiptail installer" 

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*
No changes. 

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

Signed-off-by: Justin McAfee <me@justinmcafee.com>

### CODE REVIEW

**Comment by justinamcafee** [comment]
Reviewers: Not sure how I failed DCO? I used the github website to make my changes. Should the sign-off be IN my code, instead of in my PR? Guidance and I'll fix whatever is' necessary.

**Comment by justinamcafee** [comment]
I don't have git installed anywhere and even after reading through and understanding that my signoff should be in the commits, I have no idea how to go back and change them. 
I clicked "Fork" 
Made my changes. Committed then. 
Then created a PR, all from the website. I also can't find a way to edit my commits on the website?

**Comment by dschaper** [comment]
Since you're doing it all from the GitHub web interface, the place to enter the sign-off-by line would be in the commit message. But since you've added it to the PR message we can accept that if the PR is approved for merge.

**Comment by dschaper** [comment]
Also, please base you changes against the development branch, and not master. I've updated the PR to base development for you on this PR.

**Comment by justinamcafee** [comment]
@dschaper thanks Dan! You're a real sport, I appreciate you helping me out. If I could get git to git git right LOL I could do the CLI stuff. But my dev box doesn't play well with it for some reason.

**Comment by justinamcafee** [comment]
@dschaper  Can we get a DCO override? and merge this?

**Pull request merged**
