### PR TITLE
Gh0stshell/bugfix/log flush

### PR DESCRIPTION
**Pull request by dschaper**
Alpha branch of #258.

### CODE REVIEW

**Comment by Mcat12** [comment]
Is this ready to go?

**Comment by dschaper** [comment]
I don't currently have a screen to test it out on, so I can't say for sure yet.

**Comment by Mcat12** [comment]
Neither do I. D:

**Comment by jacobsalmela** [comment]
I have a screen.  I'll test it out. 

@gh0stshell does this happen only on the LCD?  Or does it happen over ssh as well?

**Comment by jacobsalmela** [comment]
The runtime error still appears, but this does solve the LCD issue of going over 100%.  As a side effect, the [advanced stats](https://github.com/pi-hole/AdminLTE/pull/25) doesn't display properly (although it's not a finished PR yet).

**Comment by dschaper** [comment]
Okay, so what is the current status on this one? @gh0stshell has graciously donated a LCD that should be here next week for me to help test out some more...

**Comment by jacobsalmela** [comment]
I feel like this was fixed by @PromoFaux somewhere else already...

**Comment by PromoFaux** [comment]
What I fixed was the divide by 0 error. I'm yet to get a confirmation that it also fixes the queries showing as 0 when the day rolls over..

**Comment by jacobsalmela** [comment]
OK.  Where is that fix exactly?  I can test it out tonight.

**Comment by PromoFaux** [comment]
[2.5.2](https://github.com/pi-hole/pi-hole/wiki/Changelog) ;)

**Comment by jacobsalmela** [comment]
Well easy enough then!  I just need to install my screen again to test it out.

**Comment by jacobsalmela** [comment]
2.5.2 has indeed fixed the issue.  I'm closing this since it is not needed.

**Pull request closed without merging**
