### PR TITLE
Updated port 53 check

### PR DESCRIPTION
**Pull request by RamSet**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
Upon install/repair, port 53 is checked for availability.

**How does this PR accomplish the above?:**
If port 53 is in available or used by pihole-FTL, the installer proceed and allows install:
image

image

If port 53 is occupied by dnsmasq or systemd-resolver, a similar message is displayed:
image

`--forceFTLDNS` parameter/function will be (can be) renamed into something more meaningful 

the use of `--forceFTLDNS` by the user, at initial install implies consent for daemon handling by the installer.
image

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by dschaper** [comment]
Does this work with the `sudo` refire or is this dependent upon that being updated?

**Comment by dschaper** [comment]
Holding for #2271

**Comment by dschaper** [comment]
Hold released. Merge conflict needs resolution.

**Comment by RamSet** [comment]
Re-submitted under https://github.com/pi-hole/pi-hole/pull/2282

**Pull request closed without merging**
