### PR TITLE
README.md: fix typo

### PR DESCRIPTION
**Pull request by stangri**
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Simple typo fix.

### CODE REVIEW

**Comment by PromoFaux** [comment]
Please make any changes based on, and against the `development` branch, thanks! I tried to change the target branch, but that brings across a couple of merge commits with it.

**Comment by stangri** [comment]
@PromoFaux well, by default the README from master shows up when people visit your repo. I figured you may want to fix that too.

**Comment by dschaper** [comment]
@stangri It will, after it goes through the process we've used for 5 years now.

**Comment by dschaper** [comment]
And honestly, it's fine as it is, no need for the change.

**Comment by PromoFaux** [comment]
https://github.com/pi-hole/pi-hole/pull/3581/files

already done, in any case :)

**Pull request closed without merging**
