### PR TITLE
set X-XSS-Protection headers to 0 in lighttpd.conf

### PR DESCRIPTION
**Pull request by leftydrummer**
Signed-off-by: Neill Wolf <neillawolf@gmail.com>

## Thank you for your contribution to the Pi-hole Community!

Please read the comments below to help us consider your Pull Request.

We are all volunteers and completing the process outlined will help us review your commits quicker.

**Please make sure you**

 1. Base your code and PRs against the repositories developmental branch.
 2. [Sign Off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits as we enforce the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
 3. [Sign](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all your commits as they must have verified signatures
 4. File a pull request for any change that requires changes to [our documentation](https://docs.pi-hole.net/) at our [documentation repo](https://github.com/pi-hole/docs) 

---

**What does this PR aim to accomplish?:**

Align with other open source projects and disable X-XSS-Protection headers. This is due to dwindling browser support and a history of security issues.

**How does this PR accomplish the above?:**

Sets X-XSS-Protection header values to "0" in advanced/lighttpd.conf.fedora and advanced/lighttpd.conf.debian

**Link documentation PRs if any are needed to support this PR:**

See this [issue](https://github.com/pi-hole/pi-hole/issues/4983)

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [X] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Review by dschaper — APPROVED** [review]

**Comment by dschaper** [comment]
Wait for DL.

**Comment by PromoFaux** [comment]
We should also keep #5065 and #5066 in mind

**Comment by rdwebdesign** [comment]
> We should also keep `#5065` and `#5066` in mind

We just need to replicate this change on other PRs.

**Comment by gstrauss** [comment]
Updated references recommending `X-XSS-Protection: 0` or omitting the X-XSS-Protection response header:
https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html#x-xss-protection
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection

**Comment by dschaper** [comment]
> We just need to replicate this change on other PRs.

No need to do that. `git` is capable of merging the commits/PRs as long as no one else tries to modify that exact same line.

**Comment by MichaIng** [comment]
Since Pi-hole explicitly allows inline scripts, I'd actually leave it at `1; mode=block`. In modern browsers it has no effect, in old browsers (and Safari still supports the header) it completely prevents page loading in case of an XSS attack. This sounds safer than not filtering the page at all, and without secure CSP. MDN does recommend both equally, OWASP recommends to disable it, given that CSP denies `unsafe-line`, which Pi-hole explicitly allows.

And instead of disabling it, if `1; mode=block` despite `unsafe-line` is not seen as needed, isn't it then better to just omit the header, leaving the choice to the browser and saving the little bandwidth? 🙂

**Comment by iasdeoupxe** [comment]
> See this [issue](https://github.com/pi-hole/pi-hole/issues/4983)

Just a note on this so that people are not wondering why this is leading to a 404 / Page not found:

A friend of mine had created #4983 in the past but got his account flagged and content hidden with a wrong accusation by GitHub that he violated the terms of them. They insisted to keep the account flagged and it's content hidden which lead now to such broken links / missing content :frowning: :facepalm: like seen now.

We tried to get the content restored since many months but all tries are leading to a dead end without any response / action by GitHub.

Ref: https://github.com/orgs/community/discussions/27294

**Pull request merged**
