### PR TITLE
add gateway to interface configuration

### LINKED ISSUE #586: Installing on Centos-7
Fresh install from CentOS-Userland-7-armv7hl-Minimal-1603-RaspberryPi3.img

Did some minor tweaking on the Pi, just installed a few utilities I find useful for myself.

##### Expected Behaviour:
Run install script, end up with an operational pi-hole setup.

##### Actual Behaviour:
Downloaded the install script to a local file.  Ran it as root via a ssh login.  Received numerous errors, most of all seemed to be related to packages not found.

##### Steps to reproduce this issue:
Install to new sd card from CentOS-Userland-7-armv7hl-Minimal-1603-RaspberryPi3.img
Run "curl -L https://install.pi-hole.net | bash" (or download it first and run manually)

Full output from the shell at http://pastebin.com/VwhcFMiV

Is this expected?  I was under the impression that CentOS on the Pi was ready to go, or is it just CentOS support that's been added?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/36204895-installing-on-centos-7?utm_campaign=plugin&utm_content=tracker%2F3011939&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F3011939&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by bcambl**
Fixes #586 .

Changes proposed in this pull request:

- Add missing gateway mentioned in issue #586.

Ensure gateway is specified when configuring static IP via pi-hole installer on Fedora/CentOS. 

@pi-hole/gravity

### CODE REVIEW

**Comment by bcambl** [comment]
I have more commits to add here.

**Comment by dschaper** [comment]
Thanks, still on site, will review and try with Pi based tests. Let us know when to poll for pullapprove.

**Comment by bcambl** [comment]
As per @BiloxiGeek [wiki document](https://github.com/pi-hole/pi-hole/wiki/CentOS-and-RPi3), I think I will keep this PR as-is. 
The additional commits I wanted to add should be separate.

This PR addresses:

> Network config (/etc/sysconfig/network-scripts/ifcfg-eth0) could be missing a GATEWAY= directive. This will cause the install to fail.

There is also mention in the wiki document of the netcat dependency:

> netcat is named differently in CentOS, should be nmap-ncat

This has already been merged into development via #573

**Comment by dschaper** [comment]
Approved

**Comment by Mcat12** [comment]
Approved

**Comment by PromoFaux** [comment]
Approved pending merge with latest changes from development branch

**Comment by dschaper** [comment]
@bcambl Can you pull in the latest changes from pi-hole/development so that PullApprove will process this? Thanks!

**Pull request merged**
