### PR TITLE
Add commands to add/remove custom DNS records

### PR DESCRIPTION
**Pull request by Mograine**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
Those command will be used by the AdminLTE custom DNS entries interface, pull requested here : https://github.com/pi-hole/AdminLTE/pull/1035

It will correctly answer the feature request of issue #975

**How does this PR accomplish the above?:**
By adding a custom.list file in dnsmasq conf folder, we allow the users to properly handle their custom DNS entries using the two new webpage.sh commands.

**What documentation changes (if any) are needed to support this PR?:**
We would need to add those two new commands in the webscript commands list in https://docs.pi-hole.net/core/pihole-command/#pi-hole-web

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by PromoFaux** [comment]
Hi @Mograine , thanks for the submission.

I would recommend you take a look at some of the changes we've been making in the `development` branches of the various repos, as we will be moving to storing the blacklists/whitelists etc in an sqlite database (`gravity.db`)

**Comment by Mograine** [comment]
Hello,
I may be wrong but i don't think we have to store thoses data in the sqlite database. We need the custom.list file anyway for the DNS support, and imho it's better to have them only there rather that trying to keep this file and the DB in sync

**Comment by PromoFaux** [comment]
@pi-hole/core-approvers Any thoughts on this?

**Comment by DL6ER** [comment]
I agree that this should not go into the database and should be solved in a file. However, should we validate the IP/name? I think they could not cause a lot of harm, just something worth thinking about.

**Comment by Mograine** [comment]
FYI they are validated on the AdminLTE side of this PR, meaning that only "advanced users" will have to use this command and risk to add wrong ip/name

That's why i stood with the "no check here" rule seeming to rule webpage.sh :p

**Comment by DL6ER** [comment]
@Mograine Check out https://www.codefactor.io/repository/github/pi-hole/pi-hole/pull/2978

**Comment by Mograine** [comment]
> 
> 
> @Mograine Check out https://www.codefactor.io/repository/github/pi-hole/pi-hole/pull/2978

That wasn't related to this PR, but i merged development and it should be fine now :)

**Comment by PromoFaux** [comment]
As it stands, in order for `FTL` to know about the custom entries, one must manually restart it to pick it up. (see below screenshot) It would be nice if it kicked `FTL` after adding/removing an entry to `custom.list`

image

Similarly, it would be nice to add some output to the command, so that the command line user has some form of feedback, For example, the whitelist command: 

image

**Comment by Mograine** [comment]
This command is in the "webpage.sh" because it's mostly intended to be used throught the AdminLTE panel not thought the console. That's why i used the "AddDHCPStaticAddress" command, in the same file, as an example.

FYI the AdminLTE panel handle the "reload" part when you add a customDNS using it.

**Comment by PromoFaux** [comment]
Hmm, we could probably do with some consistency in that file, that's for sure. Just overviewing it now I see we have parts that say "restart dnsmasq" despite now using `pihole-FTL` as the resolver.

That said, it would be a good idea to add a call to RestartDNS at the end of your function(s), then it is handled whether the command is called from the interface or the CLI

This is a similar function to yours:

https://github.com/pi-hole/pi-hole/blob/b93628acb3d8d77775dae9778d07262c93c0aca1/advanced/Scripts/webpage.sh#L464-L488

**Comment by PromoFaux** [comment]
Much smoother :) Great work, thanks very much for the submission!

image

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/support-for-cname-besides-host-record/25707/1

**Comment by mwoolweaver** [comment]
So would this make things like enforcing google safe search and such possible with pihole?

**Comment by PromoFaux** [comment]
It's already possible, though not through Pi-hole's commands/tools

See here for an explanation: https://discourse.pi-hole.net/t/use-dns-to-force-youtube-into-restricted-mode-and-pi-hole/1996/15

**Comment by mwoolweaver** [comment]
But this would allow me to do from cli w/o edit config files even it’s a bit tedious?

**Comment by PromoFaux** [comment]
There is no support for adding a CNAME with the functionality included in this PR (although there now an open feature request for this in discourse... see comment from @pralor)

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/enforce-safe-search-via-etc-pihole-custom-list/25714/5

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/support-for-cname-next-to-host-record/25707/7

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/import-etc-pihole-custom-list-for-easier-safe-search-enforcement/25724/1

**Pull request merged**
