### PR TITLE
Use github cli to sync master back to development

### PR DESCRIPTION
**Pull request by yubiuser**
**What does this PR aim to accomplish?:**

After we merged PRs to `master` we use a workflow to sync back to `development`. Currently we use https://github.com/TreTuna/sync-branches , but it looks a bit abandoned and triggers warnings (https://github.com/pi-hole/pi-hole/actions/runs/3560063832/jobs/5979845151)

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

While looking for a replacement, I stumbled across https://stackoverflow.com/a/73340290 which suggest to use Githubs CLI to create pull requests (https://cli.github.com/manual/gh_pr_create). This looks like an elegant solution as it does not depend on outside actions to maintain this workflow. 

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by PromoFaux** [comment]
Can you test a couple of situations on a fork please? Namely:

 - PR from master to dev already exists ( I have seen this in the case where we had an open PR from a contributor's master branch)
 - master and dev are already equal (I don't remember how I have got into this situation before, but I've definitely seen it happen)

Mostly I'm curious as to what the command will output / if it will error

**Comment by yubiuser** [comment]
After merging the new workflow into master it created this PR: https://github.com/yubiuser/pi-hole/pull/8.
___

> PR from master to dev already exists ( I have seen this in the case where we had an open PR from a contributor's master branch)

I'm not sure how to test this. I would need to sneak in a commit to master without this workflow to trigger. But I can't create an "empty" master -> dev PR, because it always tells me

> There are no new commits between base branch 'development' and head branch 'master' 

Which basically is equal to

> master and dev are already equal (I don't remember how I have got into this situation before, but I've definitely seen it happen)

___

I'm not sure why you want these test. My changes do not change the "trigger" of the workflow, but only how the PR is created. It still triggers on

```
on:
  push:
    branches:
      - master
```

**Comment by PromoFaux** [comment]
> I'm not sure why you want these test. 

Mostly I just want to see how the CLI handles the situations compared to the existing action. Whether it throws errors or.. whatever happens. 

So I have created https://github.com/yubiuser/pi-hole/pull/11 - keep that open and then add a new commit directly to master. That should create the same situation I have seen in the past

**Comment by yubiuser** [comment]
The action failed (https://github.com/yubiuser/pi-hole/actions/runs/3707589616/jobs/6284185721) with 

> a pull request for branch "master" into branch "development" already exists:

**But** the PR was updated: https://github.com/yubiuser/pi-hole/pull/13

**Comment by PromoFaux** [comment]
Cool, that's good enough for me. Let's shipit

**Review by PromoFaux — APPROVED** [review]

**Review by PromoFaux — APPROVED** [review]

**Comment by PromoFaux** [comment]
Huh, it let me approve twice.

**Pull request merged**
