### PR TITLE
Added end line in printf

### PR DESCRIPTION
**Pull request by yael-tramier**
**What does this PR aim to accomplish?:**

There was a missing end line in the basic-install script. 

**How does this PR accomplish the above?:**

I added it. 

**Link documentation PRs if any are needed to support this PR:**

---
By submitting this pull request, I confirm the following:

1. I have read and understood the contributors guide, as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the EUPL 1.2 license
5. I have squashed any insignificant commits. (git rebase)
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---

- [X] I have read the above and my PR is ready for review.

### CODE REVIEW

**Comment by DL6ER** [comment]
Why do you think there should be a `\n` here?

**Comment by yael-tramier** [comment]
Hello, at the end of the installation, there is : `[i] Restarting pihole-FTL service...admin@pihole:/tmp#`

**Comment by yubiuser** [comment]
When this is the last line printed, something is wrong with the installation. It likely fails to restart `FTL`

**Comment by DL6ER** [comment]
The solution should rather be to capture this error and show something useful (like systemctl status)

**Comment by dfelton** [comment]
> The solution should rather be to capture this error and show something useful (like systemctl status)

First comment in this repo else I'd offer to do this for you @DL6ER.

Might I suggest applying this statement as a comment on the one file changed. This would then cause it to be a "Conversation" recognized by the pull request's auto checks that must be resolved, and it would no longer appear as though this PR has met all checks and is merely awaiting an approved review.

**Comment by yubiuser** [comment]
Closing due to no response >9 months. Feel free to re-open.

**Pull request closed without merging**
