### PR TITLE
Upsteam DNS enhancement v2

### PR DESCRIPTION
**Pull request by ChadBHowell**
The purpose of these commits is to do the following:

1) Bring the dnsmasq.conf changes to be inline with how config files are modified on current Debian type systems by using the "*.d" directory. This allows for a cleaner distro upgrade path and avoids stomping our config changes during dnsmasq upgrades.

2) Allow the user to choose between Google and DynDNS upstream servers during the install. This will later be extended to allow the user to enter custom upstream DNS servers as well.

3) Add unzip to the dependencies to avoid errors on some systems.

Change Log:
1) Fixed Typo pointed out by Mcat12
2) Pull Request against Dev Branch

### CODE REVIEW

**Comment by dschaper** [comment]
Thanks for moving the PR to development. It really does help us keep stability on Master while trying out all these awesome patches that you all are submitting. We'll test them out and see what shakes loose. (I need to go pick up another PiB+ so I have a test unit for that flavor of RaspberryPi.)

**Comment by dschaper** [comment]
Merging to branch https://github.com/jacobsalmela/pi-hole/tree/feature/UpstreamResolver 

I like this, the only thing we need to take into account is that on existing installs that have `/etc/dnsmasq.conf` populated there will be `illegal repeated keywords` conflicts. So can you modify this to check for an existing `dnsmasq.conf` and replace that file with the `dnsmasq.conf.orig` file, then go ahead and drop the new config in the subdirectory?

Thanks again for the submit, looks great!

**Comment by ChadBHowell** [comment]
Sure thing.  Will work on it tomorrow night.

**Comment by dschaper** [comment]
@ChadBHowell You may have to pull down a new copy of the development branch, there were some changes to the `basic-install.sh` and it looks like there's a merge conflict now.

**Comment by PromoFaux** [comment]
bump

**Comment by extremeshok** [comment]
Rather install bind9 as per https://github.com/pi-hole/pi-hole/issues/170

Which will give you dnssec for upstream servers, bind9 is also more efficient for upsteams.

**Comment by ChadBHowell** [comment]
I was just learning how to use github when I submitted this PR. I have sense done a bunch of reading and figured out branches... I think. :) I am going to resubmit this PR rebased off the latest dev branch.

**Pull request closed without merging**
