### PR TITLE
Avoid reactivating a deactivated lighttpd service

### LINKED ISSUE #1362: Pi-hole updater doesn't check used webserver type
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

2

---
**[BUG | ISSUE] Expected Behaviour:**

Pi-hole updater should check the used webserver (lightppd, nginx) and not assume lighttpd and just enable that service without warning

**[BUG | ISSUE] Actual Behaviour:**

Pi-hole updater activates a disabled lighttpd without warning, causing failure of an already running nginx instance

**[BUG | ISSUE] Steps to reproduce:**

- Install Pi-hole and run it on nginx, disabling lighttpd
- Upgrade Pi-hole
- Lighttpd is now running again

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### PR DESCRIPTION
**Pull request by WaLLy3K**
**By submitting this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

3

---

* Fixes #1362

### CODE REVIEW

**Comment by dschaper** [comment]
Should we add in a `systemctl` call to this to check and see if the status is `disabled` or will the `service` call cover this situation as well?

**Comment by dschaper** [comment]
```
[danschaper@Horizon ~]$ systemctl is-enabled sshd
enabled
```

**Comment by WaLLy3K** [comment]
Getting the exit code from the service command will let us know if `lighttpd` was active when it was called, so it should cover it.

I have noticed in some cases such as restarting the DNS server, service OR systemctl could be used, so it may be appropriate to check both?

**Comment by dschaper** [comment]
`systemctl` is preferred if they are running `systemd` as we can pull more information from it, but if they are on `Upstart` or `sysv` then service is the choice. We also have some users running in a jailed environment that `systemctl` exists but may return false information. https://github.com/pi-hole/pi-hole/issues/1218

**Comment by dschaper** [comment]
Also, on a fresh install where we are installing `lighttpd` will this still fire? (Haven't had a chance to test on a live system to check it, so just a general question.)

**Comment by WaLLy3K** [comment]
`$useUpdateVars` should not be `true` on a fresh install, meaning the `[[ -z "${LIGHTTPD_ENABLED}" ]]` conditional should start the service.

**Comment by PromoFaux** [comment]
Is this supposed to happen?

image

image

**Comment by PromoFaux** [comment]
for the `service` call, I ended up going with:
`LIGHTTPD_ENABLED=$(service lighttpd status | sed -n 2p | grep -c 'enabled')`

Can either of you see any issues with that?

**Comment by PromoFaux** [comment]
Tested extensively

Approved.

**Pull request merged**
