### PR TITLE
Fix v5 -> v6 update

### PR DESCRIPTION
**Pull request by yubiuser**
**What does this PR aim to accomplish?:**

Should fix v5 -> v6 updated where `pihole.toml` is not present yet.
Background: https://github.com/pi-hole/pi-hole/pull/5790 fixed fresh v6 installations, but forgot about v5->v6 updates.

**How does this PR accomplish the above?:**

Re-add `setupVars.conf` at the right place. If present, this is an update.

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Review by PromoFaux — COMMENTED** [review]
So this basically puts the logic back to how it was (or is, in the current `master` branch) so that the update dialogs run (or not) when we detect an existing install of v5, with the addition of checking for the v6 file. Right? 

I think I've understood that correctly!

**Comment by yubiuser** [comment]
Yes this is how I meant it. We can't get rid of `setupVars.conf` completely until everyone is on v6 and above. We *could* add a step where we delete this file once we did create the toml file. Or move it out of the way

**Comment by yubiuser** [comment]
I would do such a migration step after this: https://github.com/pi-hole/pi-hole/pull/5830

**Comment by yubiuser** [comment]
pinging  @DL6ER where FTL would expect `setupVars.conf` during the update? Still in `/etc/pihole` or already in `/etc/pihole/migration_backup_v6`

**Comment by DL6ER** [comment]
> Or move it out of the way

FTL moves it away for us:

grafik

**Comment by PromoFaux** [comment]
This seems to work as intended, I don't get the dialogs when migrating from v5->v6 with this branch.

However this bring up something else... In the test environment I did not first uninstall `lighttpd`, so when FTL starts up it has failed over to using port 8080 - but there is nothing in the output to suggest this. Open to discussion elsewhere, but should we add a check here, or just document this occurrence very well in any release notes?

**Comment by yubiuser** [comment]
>  just document this occurrence very well in any release notes?

I think this is the way to go. No more migration code please.

**Review by PromoFaux — APPROVED** [review]

**Review by DL6ER — APPROVED** [review]
Approving this after testing this in both a Ubuntu and a Debian VMs

**Comment by DL6ER** [comment]
I'm afraid I have two more PRs, at least one directly related to migration (but you already know it: #5830 )

**Pull request merged**
