### PR TITLE
Fix AdminLTE issue 2094

### PR DESCRIPTION
**Pull request by rdwebdesign**
**By submitting this pull request, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**

Fixes pi-hole/AdminLTE#2094

**How does this PR accomplish the above?:**

Validate domains using case insensitive check.

**What documentation changes (if any) are needed to support this PR?:**
 none

### CODE REVIEW

**Comment by rdwebdesign** [comment]
I found the same problem on the Custom CNAME page.
If the user enters CNAME records manually and the records contains uppercase letters, the deletion will fail.

**Comment by yubiuser** [comment]
We did include the check for hostname on removal to prevent

>  attack where users can insert arbitrary `sed` commands via the deletion path (`pihole -a removecustomcname` ...).

See resolved conversation with @DL6ER here https://github.com/pi-hole/pi-hole/pull/4384

**Comment by rdwebdesign** [comment]
OK.
So `checkDomain` needs to allow uppercase/mixedcase for the `host` string.

**Comment by yubiuser** [comment]
Something went when after latest push `stale.yml` should not be touched by this PR.

**Comment by yubiuser** [comment]
Superseded by https://github.com/pi-hole/pi-hole/pull/4597

**Pull request closed without merging**
