### PR TITLE
Prep for Release 2.5

### PR DESCRIPTION
**Pull request by PromoFaux**

### CODE REVIEW

**Comment by PromoFaux** [comment]
Or should it be 2.4.1?

**Comment by dschaper** [comment]
It contains a change of location for config files, I'd be inclined to give it a full 2.5 and not a point release.

**Comment by PromoFaux** [comment]
Sure thing

**Comment by PromoFaux** [comment]
Oh, The file can go?

**Comment by Mcat12** [comment]
I'd say 2.5

**Comment by PromoFaux** [comment]
Is everyone happy for this lot to go live?

**Comment by Mcat12** [comment]
Ya

**Comment by PromoFaux** [comment]
Me too. Just waiting on @dschaper and @jacobsalmela to sign off, then we're good!

**Comment by Mcat12** [comment]
Also remember after merging to make a ```v2.5``` tag so that the web interface can grab the version.

**Comment by dschaper** [comment]
Minor changes in #277 but other than that it looks okay to me...

**Pull request merged**
