### PR TITLE
feature/debug_timeout

### PR DESCRIPTION
**Pull request by dschaper**
**By submitting this pull request, I confirm the following _Failure to fill the template will close your PR_:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

- [x] 10 (very familiar)

---
Add timeout to debug log dumper.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by PromoFaux** [comment]
How easy would it be to display a countdown?

**Comment by PromoFaux** [comment]
Also, this is my debug log after timeout:
https://tricorder.pi-hole.net/f0z8ttkw4a/

**Comment by PromoFaux** [comment]
Seeing the same thing when using `ctrl+c` to terminate, too.

**Comment by dschaper** [comment]
That's on the fiche side, the log is too big, I'll push the upload limit on fiche to account for bigger logs...
And a countdown I'll look at, or at least a notice that the event will auto timeout.

**Comment by dschaper** [comment]
Okay, should have a countdown now, it's in 5 second increments.

**Comment by Mcat12** [comment]
Approved

**Comment by PromoFaux** [comment]
Approved

**Comment by PromoFaux** [comment]
Oh wait. I didn't need to. hahaha

**Pull request merged**
