### PR TITLE
Remove obsolete iproute APT package check

### PR DESCRIPTION
**Pull request by PromoFaux**
[Internal]

Redo of https://github.com/pi-hole/pi-hole/pull/4114

`development-v6` branch is broken following rebase - a lot of changes have been lost between it and `development`, and I think I would rather start it again at some point than try to sort it on the existing branch.

This is the only PR that's been merged into `development-v6`, so I have tweaked it slightly and targeted `development`.

@MichaIng , please can I borrow your eyes to ensure I've cherry picked this correctly? Else feel free to just redo the changes based on `development` and submit a fresh PR, thanks!

`development-v6` is closed to pull requests until further notice

### CODE REVIEW

**Review by MichaIng — APPROVED** [review]

**Comment by MichaIng** [comment]
What do you think about reopening #4106 instead? It removes the other package checks as well, which are all obsolete, and reduces the difference between v5 and v6 code a little.

Looks like there is some consequent PR backporting required, e.g. after a fresh v6 branch has been created, force all PRs against v6 and backport each relevant one to v5 (e.g. using a backports bot addon). Or stop developing on v5 and focus on v6, if the FTL+PH7 binary and concept is ready enough?

**Comment by PromoFaux** [comment]
In all honesty I can't see v6 happening until much later in the year at the absolute earliest. We're currently beta testing some more 5.x stuff (https://discourse.pi-hole.net/t/join-us-beta-testing-pi-hole-ftl-v5-9-web-v5-6-and-core-v5-4/48021) so I don't want to hard freeze `development` just yet (Speaking for myself here, but I think @dschaper and @DL6ER) would agree with me)

So, at the moment I'd just like to forget that the v6 branch even exists and get some of these improvements into the main development branch.

When you mention backports bot addon, is that a GHA thing? Do you have any links I can read up on?


And, OK, let's revisit #4106 in the meantime

**Comment by PromoFaux** [comment]
It was @lightswitch05's PR (https://github.com/pi-hole/pi-hole/pull/4218) that made me look at the v6 branch in detail and realise how messed up it is!

(I would also like to get https://github.com/pi-hole/pi-hole/pull/4218 merged in so that we can hit the ground running with Bullseye)

**Comment by DL6ER** [comment]
I do agree. The majority is done but there is a certain number of breaking changes ahead. This will require some intense coding sessions and I'll take some vacation for it but who knows when this will happen (maybe October).

**Comment by MichaIng** [comment]
> When you mention backports bot addon, is that a GHA thing? Do you have any links I can read up on?

Yes there are a bunch of GHAs which do backports (respectively open a new PR rebased on another branch) based on labels when a PR is merged: https://github.com/marketplace?query=backport

I know from Nextcloud their backports bot, which is not an action but an app, which listens on post commands, like `/backport to <banch>/` to backport a PR: https://github.com/nextcloud/backportbot
But I think an action is finally easier and more transparent to implement.

> I would also like to get #4218 merged in so that we can hit the ground running with Bullseye

Makes sense as it is released already end of the month. As it hits some same code lines, it should be merged before #4106, so I can resolve the conflicts (there is already one anyway).

**Pull request closed without merging**
