### PR TITLE
fix centos nc dependency

### PR DESCRIPTION
**Pull request by bcambl**
Fixe for commit e106ff0

Changes proposed in this pull request:

- Correction for `nc` dependency on CentOS/Fedora

@pi-hole/gravity

### CODE REVIEW

**Comment by dschaper** [comment]
Hmm rpm.pbone was showing the package as `netcat` but I'll take your word for it. Ran a `yum provides` and got `netcat`? We were wondering if that's a stock package or an add on. I had it already installed, but I wasn't sure if it was a dependent that got installed on the side.

Thanks!

**Comment by bcambl** [comment]
Here is some output for your review:

Fedora 24:
```
[bcambl@redacted pi-hole]$ grep -r -E '\bnc\b' *
advanced/Scripts/piholeDebug.sh:	TERMBIN=$(cat /var/log/pihole_debug.log | nc termbin.com 9999)
[bcambl@redacted pi-hole]$ grep -r 'netcat' *
automated install/basic-install.sh:	PIHOLE_DEPS=( dnsutils bc dnsmasq lighttpd php5-common php5-cgi php5 git curl unzip wget sudo netcat )
[bcambl@redacted pi-hole]$ yum provides */nc
Yum command has been deprecated, redirecting to '/usr/bin/dnf provides */nc'.
See 'man dnf' and 'man yum2dnf' for more information.
To transfer transaction metadata from yum to DNF, run:
'dnf install python-dnf-plugins-extras-migrate && dnf-2 migrate'

Last metadata expiration check: 2:24:23 ago on Fri Jul 15 19:58:50 2016.
nmap-ncat-2:7.12-1.fc24.x86_64 : Nmap's Netcat replacement
Repo        : @System

nmap-ncat-2:7.12-1.fc24.x86_64 : Nmap's Netcat replacement
Repo        : fedora

[bcambl@redacted pi-hole]$ dnf provides */nc
Last metadata expiration check: 2:24:42 ago on Fri Jul 15 19:58:50 2016.
nmap-ncat-2:7.12-1.fc24.x86_64 : Nmap's Netcat replacement
Repo        : @System

nmap-ncat-2:7.12-1.fc24.x86_64 : Nmap's Netcat replacement
Repo        : fedora

[bcambl@redacted pi-hole]$ 
```

Also confirmed on CentOS 6.. so CentOS 7 should also comply.

**Comment by dschaper** [comment]
Got ya, appreciate the caps. Better grabbing off System than SF if it's a drop in replacement. Can I get you to cap the output from the new `pihole -d` and post up the link? You can take the link down or email it to me if you don't want it in the clear. Redact whatever you feel necessary.

**Comment by dschaper** [comment]
@PromoFaux Ubuntu now complains about `nc` -> 
```
1 dan@singularity:~⟫ cat /dev/nulll | nc termbin.com 9999
cat: /dev/nulll: No such file or directory
Use netcat.
```
May want to just use `netcat` straight out, 
```
pi@raspberrypi:~ $ netcat
usage: nc [-46bCDdhjklnrStUuvZz] [-I length] [-i interval] [-O length]
          [-P proxy_username] [-p source_port] [-q seconds] [-s source]
          [-T toskeyword] [-V rtable] [-w timeout] [-X proxy_protocol]
          [-x proxy_address[:port]] [destination] [port]
```

**Comment by bcambl** [comment]
you have a typo there.

**Comment by dschaper** [comment]
This isn't my day... The correct file does the same `Use netcat.` nag. The process completes successfully, but it still nags at you. Just have that on Ubuntu `netcat-openbsd` package so far but that means it's going to find its way down to the other Distros eventually.

**Comment by diginc** [comment]
Not 100% related to this but I was looking at the code around the changeset and saw you're using `if [ -x "$(command -v rpm)" ];then` followed by an else if for the something against apt-get.

I'd say it's much more likely for RPM to be installed on a debian system for packaging RPMs or just rpm2cpio than apt-get to be installed on a redhat system leading to a potential bug.  

I'd reverse the order if that if or just bite the bullet and start using some config management tools to help keep things more OS agnostic: https://docs.puppet.com/facter/3.0/core_facts.html#osfamily

**Comment by dschaper** [comment]
Can we move that to a new issue? I think that is going to lead to a larger discussion and I don't want to get these two tied in together and mix things up. (I had to do the changelog updates today and what ever I can do to keep that job nice with really clean, individual and separate issues and PR's the better it is for everybody! :smile: )

**Comment by bcambl** [comment]
I actually completely agree @diginc.

**Comment by bcambl** [comment]
This is a DO CentOS 7.2 droplet
Install: http://termbin.com/olvd
debug: http://termbin.com/8z35

**Comment by dschaper** [comment]
Thanks, shows exactly what I needed to see. Forgot about DO, left a few droplets on, so thanks also for that.

**Comment by dschaper** [comment]
Approved - DO Spinup Check

**Comment by PromoFaux** [comment]
Approved!

**Pull request merged**
