### PR TITLE
Add Clean Tail Function

### PR DESCRIPTION
**Pull request by LordFlashmeow**
**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'development' branch!}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [X] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#git-commit---signoff))

---

**What does this PR aim to accomplish?:**
Add a way to watch what domains are being blocked in real time. 
`pihole -t` felt like it had too much information, and I just wanted to see the domains being blocked.
Inspired by [this video](https://www.reddit.com/r/pihole/comments/43cecp/viewing_in_realtime_what_ads_are_being_blocked/czh9vcw/)

**How does this PR accomplish the above?:**

This creates a new function using `grep` (and maybe `sed`) to filter out other information in the log

**What documentation changes (if any) are needed to support this PR?:**

* Add a note in the list of commands for the new function

**Note:** I've put in two ways to do it: with `grep -E` and `sed -E`, or with `grep -P`. I'm not sure if `grep -P` is supposed to be supported (the `man` page says it's experimental), but it is much cleaner to do it that way.

### CODE REVIEW

**Comment by LordFlashmeow** [comment]
About using `grep -P`: See #1177 discussion on it. Currently it's used in the codebase, but I'm not sure if you want to use it more.

**Comment by dschaper** [comment]
Thanks for the submission, we'll take a look at it and add any concerns to the discussion.

**Comment by Mcat12** [comment]
Maybe a better name would be `-td` for `taildomains`. Other than that it looks like it's working.

**Comment by jacobsalmela** [comment]
This works well as-is on the servers I've tested on

**Comment by Mcat12** [comment]
It looks like we forgot to merge this PR, and now it is incompatible with the dev version. I tested regex-blocked domains, and they didn't show up.

Also, we will likely turn off the log file by default on new installs because FLTNDS does not need a log file to generate stats, so tailing the log will not work.

**Comment by dschaper** [comment]
@LordFlashmeow Is this still an active PR?

**Comment by dschaper** [comment]
Closing, no activity.

**Pull request closed without merging**
