### PR TITLE
3 New DNS Choices

### PR DESCRIPTION
**Pull request by slamanna212**
Added 3 new DNS Choices and modified the Whiptail dialog for the DNS choice to fit all now 5 available choices

Screenshot of modified code running on my install:
New DNS Choices

### CODE REVIEW

**Comment by slamanna212** [comment]
Sorry for the multiple pull requests, wanted to make sure i got it perfect

**Comment by Mcat12** [comment]
You don't have to resubmit a PR when you want to add commits. You can just continue working on your branch and the PR will update automatically.

**Comment by slamanna212** [comment]
Wow, i was unaware of that! Its finished now but il keep that in mind for the future! Thanks a ton!

**Comment by Mcat12** [comment]
Yep. PRs are pretty neat. You can reference other issues and comment on lines in changed files too!

**Comment by slamanna212** [comment]
Oh wow, Im still learning github thanks! This is the first project if contributed to

**Comment by fayetted** [comment]
You beat me to it.  I have the code written to allow the user to specify 1 or 2 of their own DNS servers but had not finished testing.

I think it's ready now, but it will conflict with this PR.  Would you rather I wait until this is merged into Development to submit the PR?

**Comment by slamanna212** [comment]
That would be handy! i keep having to go back in and put my 2 dns servers
back in since im using weird ones. I have no idea about the PR, probably
will need one of the project admins to decide

**Comment by PromoFaux** [comment]
@fayetted How easily will it merge with this PR? I'll branch this off so you can base your pull of of it.. One moment please.

**Comment by PromoFaux** [comment]
OK, I've branched this off to the branch [slamanna212-development](https://github.com/pi-hole/pi-hole/tree/slamanna212-development)

@fayetted can you rebase your changes on that branch and then create a PR to that branch please?

**Comment by fayetted** [comment]
Piece of ~~cake~~ pi

**Comment by slamanna212** [comment]
@fayetted Nailed it

**Comment by DonLexos** [comment]
Would it be smart to provide some information in the wiki on to what kind of differences the DNS providers have? I believe Comodo does some filtering on their end, and I know openDNS will resolve (or at least did, stopped using them) wrong domains to a default search page (in a browser that is).

**Comment by PromoFaux** [comment]
Excellent Idea. Do you think you could gather all the information you can about each of the DNS providers and put it together on the wik for us? :+1:

**Comment by DonLexos** [comment]
Sure, I am not familiar with all of them but can give it a try. I can always set the resolver to that dns and check if something fancy happens. Will take me a bit to gather all the info though.

**Comment by DonLexos** [comment]
Started researching, while you are at it, maybe add one more from OpenDNS?

`OpenDNS also offers DNS servers that block adult content, called OpenDNS FamilyShield. Those DNS servers are 208.67.222.123 and 208.67.220.123..`
source: http://pcsupport.about.com/od/tipstricks/a/free-public-dns-servers.htm

So maybe also add option `OpenDNS FamilyShield` with `208.67.222.123` and `208.67.220.123` ?

Source provides even more, don't think that adding many more would make things more clear, and if someone really would like to use a different DNS that's quite easy to change. Will add the link to the wiki page when I finish collecting the info up.

**Comment by DonLexos** [comment]
And while reading the page I just mentioned maybe it would be wise to only add completely open DNS servers and provide some info on the wiki on content-filtering (public) DNS server options and a link to more information. 

Adding DNS servers that block content could lead to headaches when troubleshooting items in the future. That would mean that in the current commit (from what I can tell) at least Comodo Sucure and Norton ConnectSafe need to be removed. Ideas?

**Comment by DonLexos** [comment]
Ok page is there!

**Comment by PromoFaux** [comment]
Super, thanks @DonLexos ! The changes are not live yet, but that page looks great for when they go live!

**Comment by PromoFaux** [comment]
Also, if you notice in #327, the ability to define your own DNS servers has been put in. too.

**Comment by DonLexos** [comment]
Oh will check that later and if I can figure out how that would work I will add it to the wiki, thanks for pointing that out!

**Pull request closed without merging**
