### PR TITLE
Improve comments in basic-install.sh

### PR DESCRIPTION
**Pull request by jbzdarkid**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
- Improve / clean up various comments in a critical script
- Be more consistent about do/while/for/then syntax
- Be explicit about returns and exits, fix a couple of cases where the script would "exit 0" despite failing
- Fix a couple of whitespace issues

**How does this PR accomplish the above?:**
I read the script carefully. Big thanks to whoever added comments the last time, they were mostly great.

**What documentation changes (if any) are needed to support this PR?:**
I feel like this change is self-documenting.

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by dschaper** [comment]
Please see the first bullet point of https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md#technical-requirements

**Comment by dschaper** [comment]
I'm not inclined to merge PRs that address multiple aspects at once. Please break this up in to atomic PRs, (following the Contributor's Guide and making sure you are using the proper branches) and we can work through them.

**Comment by jbzdarkid** [comment]
Changed base to development, isolated just the comments.

**Review by PromoFaux — APPROVED** [review]
Thanks for the work on this. I think a lot of the changes make things clearer. It is very easy, sometimes, when writing the comments in the first place to forget that not everyone reading it knows exactly what you mean. 

Note to self: This will cause some merge conflicts into `development-v6` - do this asap after merging to `development`

**Pull request merged**
