### PR TITLE
Hotfix 2.6.1

### PR DESCRIPTION
**Pull request by PromoFaux**
Bring hotfix for Pi-hole not blocking ads to master branch.

### CODE REVIEW

**Comment by VDRrulez** [comment]
And furthermore you maybe want to update pihole.cron?

**Comment by Mcat12** [comment]
Update it with what?

**Comment by VDRrulez** [comment]
@Mcat12 
If you take a quick look at pihole.cron then you will recognize that it references scripts in /usr/local/bin that do not exist anymore since rel 2.6. So I do not know what the intentions of the devs are. Either /usr/local/bin/pihole has to be started or the corresponding scripts in /opt/pihole.
And this is so obvious that I really wonder why I have to explain it to you.

**Comment by PromoFaux** [comment]
Ah yeah, good catch.  We'll get that updated.. 

No need to be rude @VDRrulez,  we work on this in our spare time, and we're only human after all!

**Pull request merged**
