### PR TITLE
Start pihole-FTL after network

### LINKED ISSUE #2924: dnsmasq fails to identify LAN requests when started before network
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:** `9`

---
**Expected behaviour:**

When using `pihole -a -i local`, after reboot, Pi-hole is expected to allow DNS requests from local network clients.

**Actual behaviour:**

Local network requests are denied by the underlying `dnsmasq`, producing the log entry:
```
Sep 14 16:36:16 dnsmasq[301]: Ignoring query from non-local network
```

**Steps to reproduce:**

1. `pihole -a -i local`
2. `reboot`
3. E.g. `wget --spider pi-hole.net` from a client, located in the same local network.

**Troubleshooting undertaken, and/or other relevant information:**

Bug report, investigation and identifying the underlying issue in dnsmasq has been done here: https://github.com/MichaIng/DietPi/issues/3007#issuecomment-522942038
- `pihole -a -i local` adds the dnsmasq setting: [`local-service`](https://manpages.debian.org/buster/dnsmasq-base-lua/dnsmasq.8.en.html)
- When `dnsmasq` starts with this setting before any network interfaces has been configured, it does not have any network or IP info where it could derive the information from, which client IPs are from within the local network and which not, which is logically understandable. Obviously a DNS request does not force `dnsmasq` to update this info.

The following can be done to fix the issue:
- Manually restart `pihole-FTL`.
- Add startup dependencies to service to have it started after network interfaces being configured: `# Required-Start: $network` => `After=network-online.target`
- Access the Pi-hole admin panel (web UI), even without login, although I did not yet identify the exact trigger from e.g. the php script.

**Suggested solution:**
- Add network to the start requirement of the pihole-FTL service.
```
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
```
- If systemd is used, this leads to [`After=network-online.target`](https://www.freedesktop.org/software/systemd/man/systemd.special.html#network-online.target) being added to the generated systemd unit.
- It generally makes sense, not only to prevent this issue, but also since no DNS resolution can be done without network access anyway.
- Additionally this can be taken as initiator to create a proper `pihole-FTL.service` systemd unit instead of relying on the sysvinit => systemd generator on very most modern distros, which is not assured to translate everything very well. E.g. `$syslog` seems to be not translated at all on Debian, even with `rsyslog` installed additionally to `systemd-journald`:
```
root@VM-Buster:~# systemctl cat pihole-FTL.service
# /run/systemd/generator.late/pihole-FTL.service
# Automatically generated by systemd-sysv-generator

[Unit]
Documentation=man:systemd-sysv-generator(8)
SourcePath=/etc/init.d/pihole-FTL
Description=LSB: pihole-FTL daemon
Before=multi-user.target
Before=multi-user.target
Before=multi-user.target
Before=graphical.target
After=remote-fs.target

[Service]
Type=forking
Restart=no
TimeoutSec=5min
IgnoreSIGPIPE=no
KillMode=process
GuessMainPID=no
RemainAfterExit=yes
SuccessExitStatus=5 6
ExecStart=/etc/init.d/pihole-FTL start
ExecStop=/etc/init.d/pihole-FTL stop
ExecReload=/etc/init.d/pihole-FTL reload
```

### PR DESCRIPTION
**Pull request by MichaIng**
**By submitting this pull request, I confirm the following:** 
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [ ] I have made only one major change in my proposed changes.
  - Sorry, I recognised the `/var/run` inconsistency and couldn't let it like this 😉.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

**Signed-off-by: MichaIng <micha@dietpi.com>**

---
**What does this PR aim to accomplish?:**
"$network" on a systemd-driven OS leads to "After=network-online.target" in the generated systemd unit.
This target is no guarantee that all network interfaces have been fully configured, as it depends on the related network services types, but at least it reduces the risk that those have not fully finished their job when pihole-FTL starts. If this is the case, certain issues can occur:
- https://github.com/pi-hole/pi-hole/issues/2924
- https://discourse.pi-hole.net/t/have-to-pihole-restartdns-after-reboot/28772

Runtime files are now consistently created in "/run" instead of "/var/run". The second is a symlink to the first for backwards compatibility but on none-ancient distro versions one should use "/run", systemd even prints a warnings if service files use "/var/run". The service file used "/run" and "/var/run" both, in cases for the same files/directories before, which does not directly cause issues currently, due to the symlink, but is inconsistent at best.

**How does this PR accomplish the above?:**
- Add `$network` to sysvinit service Required-Start/Stop lines
- Raplace `/var/run` with `/run`

Fixes #2924

### CODE REVIEW

**Comment by MichaIng** [comment]
On non-systemd systemd btw the result should be similar: http://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/facilname.html
But I couldn't find more details about how exactly it is resolved there, i.e. for what exactly the service will wait.

**Comment by DL6ER** [comment]
Rationale for moving `/var/run -> /run` for Debian:

> The compatibility symlinks will automatically make any files created in /var/run and /var/lock available under /run and /run/lock, respectively. Therefore the only change needed is to switch to using the new paths in any code creating or referencing files in these directories. Before wheezy, a versioned depends upon initscripts (>= 2.88dsf-13.3) will be required to ensure the presence of a functional /run. After wheezy, /run will always be present, and no dependency will be needed. 
> [Source](https://wiki.debian.org/ReleaseGoals/RunDirectory#Packages_using_.2Fvar.2Frun_and_.2Fvar.2Flock)

and
> Files are automatically transitioned to the new location, and are available via both the old and new paths. As a result, packages do not need to move their files, they just need to start using the new paths by doing the following:
>  -  Depend on initscripts (>= 2.88dsf-13.3)
>  -  Replace all usage of /var/run with /run, and /var/lock with /run/lock. 
>
> Note that the initscripts dependency is only required up to the release of wheezy. If you transition after wheezy, /run will be guaranteed to be present, and the initscripts dependency may be omitted. 
> [Source](https://wiki.debian.org/ReleaseGoals/RunDirectory#How_to_transition_from_.2Fvar.2Frun_to_.2Frun_and_.2Fvar.2Flock_to_.2Frun.2Flock.3F)

and for Fedora:
> In the past weeks key people from the Debian, Suse, Ubuntu and Fedora
camps (and others, too) discussed the whole issue forth and back, to
find a solution to stop the misuse of /dev before it becomes even more
widespread. Various solutions have been suggested, but in the end it all
boiled down to the fact that /var/run does not belong beneath /var and
what we really want is a top-level directory /run, and that that is the
only really clean solution. The only reason why nobody dared to actually
implement such a directory was unwillingness to deal with the political
backlash, especially messy discussions on mailing lists like this one.
>
> Understanding this, we came to the conclusion that we should rather
implement what everybody thinks is the right technical solution, instead
of evading the political backlash for it. And so we implemented this.
>
> With this upload Fedora and Suse have already adopted /run now. Debian
folks will suggest this for their coming release. Ubuntu has agreed with
introducing /run as well.
[Source](https://lists.fedoraproject.org/pipermail/devel/2011-March/150031.html)

**Comment by dschaper** [comment]
Ignore the Branch build, I need to set Travis up to only build our branches. Or if you want to set up a free Travis-CI.com account so the CI can access your branch Micha.

**Comment by MichaIng** [comment]
@dschaper 
> I need to set Travis up to only build our branches.

Makes sense as this affects all contributions from outside the team.

> Or if you want to set up a free Travis-CI.com account so the CI can access your branch Micha.

I can do that, if this helps you to verify my PRs. Will not be my last contribution, and I guess this allows Travis CI to check my PRs on other projects as well, right?

**Comment by MichaIng** [comment]
@dschaper 
Okay I registered with Travis CI and added my Pi-hole repo. I can trigger (and did) "custom" builds for all my branches and I just tested that it automatically queries builds for branch and PR when I open one against my own repo. But how can I trigger or submit the status of the branch test to be shown here?

**Comment by dschaper** [comment]
Force push the latest commit.

**Comment by MichaIng** [comment]
Okay found it now, I missed to update the commit (without change):
```
git commit --amend --no-edit
git push -f origin HEAD
```
This updated the PR and forced a Travis CI PR rebuild, but it still does not force a Travis CI Branch rebuild 😞. Probably this is simply not possible for a PR from foreign repo? I can simply open a new PR, just for verifying this, so you know for sure that branch build needs to be disabled or ignored for foreign PRs?

**Comment by DL6ER** [comment]
This change will need to be accompanied by a change to FTL. This has to be coordinated or it may result in an issue (when `/var/run` and `/run` are not the same location).

https://github.com/pi-hole/FTL/blob/5ad55e82b60d6e6f80127e3ad514c09bb9a12dad/src/config.c#L306

https://github.com/pi-hole/FTL/blob/5ad55e82b60d6e6f80127e3ad514c09bb9a12dad/src/config.c#L312

**Comment by MichaIng** [comment]
@DL6ER 
Yes, you are right the paths should be fixed in FTL then as well and probably the whole source code should be searched for `/var/run`, just to be failsafe. However if both are not the same location, things are already broken now since the service file currently contains both paths mixed for at least the PID file.

I could open a PR for FTL. Two PRs are required anyway since it's about two repos?

**Comment by DL6ER** [comment]
> I could open a PR for FTL. Two PRs are required anyway since it's about two repos?

Yes. Go ahead if you like. Otherwise, I will address this tomorrow. I don't think we will merge this into `v5.0` as we seem to be frozen now. After some more testing, we will eventually release Pi-hole v5.0.

However, we plan to ship v5.1 relatively fast afterwards, maybe one month later, only.

**Comment by MichaIng** [comment]
PR up to change /var/run to /run in FTL: https://github.com/pi-hole/FTL/pull/739
Both PRs should hence be merged together to be failsafe.

**Comment by MichaIng** [comment]
Next companion PR to update docs accordingly: https://github.com/pi-hole/docs/pull/313

**Comment by p1r473** [comment]
Will this fix errors about adapter eth0 not available at startup? I'm using a workaround with DELAY_STARTUP in pihole-FTL.conf

**Comment by MichaIng** [comment]
At least it reduces the risk for such errors.

#### Background
With systemd, the converted `network-online.target` sadly is not a failsafe target to assure network adapters have been fully set up. When using e.g. `allow-hotplug eth0` in `/etc/network/interfaces`, the `ifupdown` package on Ubuntu/Debian creates udev rules which create `ifup@eth0.service` as fast as the adapter is "physically" recognised. But this service is `Type=simple`, which means it only needs to start (not to finish) to allow follow-up targets/units to proceed, like `network-online.target`. Especially when you have a DHCP client in place, bringing up the network can take a little while, however not sure if with dhcpcd (Raspbian default) there is a similar issue AND with Pi-hole you have a static IP assigned anyway.
#### => Should solve the issue in ~95% of Pi-hole cases.
I suggest you test it, would be good to have some feedback if/where it helps and where probably not:
```
sed -i '/^# Required-Start:/c\# Required-Start:    $remote_fs $syslog $network' /etc/init.d/pihole-FTL
sed -i '/^# Required-Stop:/c\# Required-Stop:     $remote_fs $syslog $network' /etc/init.d/pihole-FTL
systemctl daemon-reload
sed -i '/^DELAY_STARTUP=/c\DELAY_STARTUP=0' /etc/pihole/pihole-FTL.conf'
# reboot
```

**Comment by p1r473** [comment]
Thanks, nifty script!!!

**Comment by MichaIng** [comment]
> Think you forgot a ' though

Or added one too much, how you see it 😄.

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-5-1-released/35577/1

**Pull request merged**
