### PR TITLE
Use pushd/popd and create random temporary directory

### PR DESCRIPTION
**Pull request by dschaper**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**

Utilize pushd/popd instead of storing directories and using `cd`. Also create random temp directory to prevent a user from injecting a rogue binary in to the `/tmp` directory to be copied in to priv'd directory.

**How does this PR accomplish the above?:**
See code for comments.

**What documentation changes (if any) are needed to support this PR?:**
None, internal function adjustment.

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by jacobsalmela** [comment]
Pull request #2000.  Congrats!

**Comment by PromoFaux** [comment]
~~mktmp~~ mktemp

Shall I open a new PR for it, or do you want to?

**Comment by dschaper** [comment]
#2016

**Comment by PromoFaux** [comment]
2fast4me

**Pull request merged**
