### PR TITLE
Allow configuration of dnsmasq log path.

### PR DESCRIPTION
**Pull request by Smarre**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
In some setups, dnsmasq may be needed to log out somewhere else than hardcoded /var/log/pihole.log. 

**How does this PR accomplish the above?:**
This commit parses the path from dnsmasq’s configuration file, or defaults to /var/log/pihole.log if no path has been set.

**What documentation changes (if any) are needed to support this PR?:**
- None.

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by DL6ER** [comment]
There are some more locations where the file is hard-coded, especially the service script is critical as starting `pihole-FTL` may fail if it cannot write to the log file:

https://github.com/pi-hole/pi-hole/blob/6b536b7428a1f57ff34ddc444ded6d3a62b00a38/advanced/Templates/pihole-FTL.service#L38

Note that there is also https://github.com/pi-hole/pi-hole/pull/3732 which is currently under review. It is directly related to your suggested change.

**Comment by PromoFaux** [comment]
Just out of curiosity, what would be the use case for having the log file be somewhere else?

**Comment by Smarre** [comment]
My rationale was probably same as in the linked PR, that is, to make some sense in the log paths. I’ve had this change (along with other supporting changes it seems) locally for some time now, and finally got around to upstream it.

Pi-hole probably shouldn’t be used so, but there is a faint possibility that there is some managemental baggage why a log should be saved to some specific location. I don’t really see that justifying this change though, so if you think there is no need for this configurability, I’m completely fine with closing this one in favor of #3732.

**Comment by PromoFaux** [comment]
I think I would be more comfortable (for now) fixing the paths so that they're defaulted to `/var/log/pihole/*.log`. 

I'm not 100% opposed to making the log location configurable in future, but it would need to be reflected across the three repos (this one, adminLTE, and FTL) - see linked PRs in #3732, there are quite a few places where the log file is referred to outside of the core repo.

**Comment by DL6ER** [comment]
When they are all inside `/var/log/pihole`, you are free to `mount` this directory from anywhere

**Pull request closed without merging**
