### PR TITLE
Add link to Windows DNS Swapper

### PR DESCRIPTION
**Pull request by Mcat12**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/pi-hole/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

10

---

See #1400

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by DL6ER** [comment]
Approved

**Comment by roots84** [comment]
The link to my project was removed in https://github.com/pi-hole/pi-hole/commit/7fddce4a1f6b4fc8d9e4181a4c1ad18c0ba23098#diff-04c6e90faac2675aa89e2176d2eec7d8 
Any specific reason why this happened?

**Comment by Mcat12** [comment]
@roots84 Sorry, it must have been by mistake! Please make a PR to add it back.

**Comment by roots84** [comment]
No worries. Thought there might be an issue with my code or something. https://github.com/pi-hole/pi-hole/pull/1900

**Pull request merged**
