### PR TITLE
Do not require DCO for Pi-hole Org members with GPG signed commits.

### PR DESCRIPTION
**Pull request by dschaper**
**By submitting this pull request, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [] I have commented my proposed changes within the code.
- [] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#git-commit---signoff))

---

**What does this PR aim to accomplish?:**

New feature for DCO, do not require signoff for Pi-hole Organization members that have GPG signed commits.

### CODE REVIEW

**Comment by PromoFaux** [comment]
Is the GPG signing enforced by the bot? Documentation suggests it's only the signoff aspect of things..

**Comment by dschaper** [comment]
Checking on that, reading through the code now to see where the GPG is checked, will update when I find out.

**Comment by dschaper** [comment]
The only thing I could find is https://github.com/probot/dco/blob/master/index.js#L9 but that just checks the API for Org membership. So I'm not sure where the sign is validated. Good question.

**Comment by PromoFaux** [comment]
It looks like it just disables the DCO requirement for members, but still allows them to commit without GPG-signing. To be totally fair, is there any real requirement to drop the signoff requirement for members? It's not much of a hardship to sign off commits..

**Comment by dschaper** [comment]
There's the ability to enforce GPG sign on commits at the branch level, but with new committers already having trouble with DCO signing, I'm not sure if we should enforce GPG sign across the board? I think all the developers are already signing everything and even GitHub web based commits carry the GPG signature of the logged in user. 

I'd prefer everything be GPG signed and DCO signed, so any suggestions on that are great.

**Comment by dschaper** [comment]
Or do you mean no need to drop off the DCO signoff requirement? Sorry, I got confused there with the GPG issue. This is just primarily until the DCOBot is updated to not be so stringent with regards to case-sensitivity and name changes.

**Comment by PromoFaux** [comment]
> I'm not sure if we should enforce GPG sign across the board? 

Dear god no.. can you imagine? Not to disparage our users, but it is something that is on the advanced side of things! So maybe not...

And yeah, as per your second comment, but you make a fair point.

**Comment by dschaper** [comment]
Eventually when I can get NodeJS playing nice in a container with our infra we can self-host our own DCOBot and I can cherry pick the couple of PR's on the upstream repo and relax the regulations. But that's a little down on the priority list at the moment.

**Comment by dschaper** [comment]
Thanks, not a huge fan of extra metadata, but hopefully we can pull it back out when better things are merged upstream or we do our own. I've forked the repo, and I'll cherrypick a few PR's off upstream, but I still need to get this in a container.

**Pull request merged**
